bugfix/13768-gantt-using-keys
highcharts/highcharts pull request #14026
Opened 2020-08-11 10:44 UTC by Basts

Fixed #13768, using the keys in the Gantt chart.

2020-08-11 10:56 UTC, circleci-mu commented
## Visual test results - No difference found

2020-08-11 10:56 UTC, circleci-mu commented
### File size comparison
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts-gantt | 356.4 kB | 356.4 kB | 89 B |
| highcharts-gantt, gzipped | 121.9 kB | 121.9 kB | 15 B|

2020-08-18 07:12 UTC, TorsteinHonsi commented on ts/Core/Axis/TreeGridAxis.ts
> +
Where did returning `merge(d)` go? The original function made sure to return a copy of `d` if `d` was an object...

2020-08-20 09:25 UTC, pawelfus requested changes

2020-08-20 09:25 UTC, pawelfus commented on ts/Core/Axis/TreeGridAxis.ts
> +                                    if ((d as any).includes(point.x) && (d as any).includes(point.x2)) {
Two things here:
- `includes` is not supported by IE at all
- what if `d: PointOptionsType` is object type? Or in general, not an array?

2020-08-25 09:43 UTC, pawelfus requested changes

2020-08-25 09:43 UTC, pawelfus commented on ts/Core/Axis/TreeGridAxis.ts
> +                            if (H.isArray(d) && series.options.keys && series.options.keys.length) {
Don't use `H.isArray`, but instead import `isArray` from utils.

2020-08-25 09:43 UTC, pawelfus commented on ts/Core/Axis/GridAxis.ts
> +                if (point && series.is('gantt') && !(point as any).initialData) {
I might be missing it, but what's this `initialData` property?

2020-08-25 09:43 UTC, pawelfus commented on ts/Series/GanttSeries.ts
> +                retVal = options;
This seems to be an unnecessary assignment?

2020-08-25 09:43 UTC, pawelfus commented on ts/Gantt/Pathfinder.ts
> +                        (point.options as any).connect = (point.options as Highcharts.GanttPointOptions).dependency;
Quite a lot castings here (to `any` and `GanttPointOptions`). Can we somehow improve this?

2020-08-26 07:59 UTC, pawelfus approved these changes
Nothing more from me, thanks! :)

2020-08-26 08:09 UTC, bre1470 requested changes
The `any` cast has to be removed.

2020-08-26 08:09 UTC, bre1470 commented on ts/Series/GanttSeries.ts
> +            (options as any) = parent.prototype.pointClass.prototype.applyOptions
`options` needs to be of type `DeepPartial<Highcharts.GanttPointOptions>`

2020-08-26 08:11 UTC, bre1470 commented on ts/Series/GanttSeries.ts
> +            (options as any) = parent.prototype.pointClass.prototype.applyOptions
Maybe use a new property instead of trying to replace the input argument.

2020-08-26 12:22 UTC, bre1470 approved these changes
Thanks! In type sense it is now okay.

It would be nice, if `setGanttPointAliases(ganttPoint as Highcharts.GanttPointOptions) ` can be written as `setGanttPointAliases(ganttPoint.options)`, but I guess some property changes get not reflected in the options property.

2020-09-01 07:40 UTC, TorsteinHonsi approved these changes

2020-09-01 07:40 UTC, merged