ts/series-base
highcharts/highcharts pull request #14126
Opened 2020-08-25 18:55 UTC by bre1470

- Introduced base class for series migration.

2020-08-25 19:07 UTC, circleci-mu commented
## Visual test results - No difference found

2020-08-25 19:08 UTC, circleci-mu commented
### File size comparison
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts | 264.7 kB | 266.2 kB | 1511 B |
| highcharts, gzipped | 91.6 kB | 92.0 kB | 397 B|
| highstock | 343.8 kB | 345.3 kB | 1529 B |
| highstock, gzipped | 117.9 kB | 118.2 kB | 277 B|
| highmaps | 313.3 kB | 302.6 kB | -10966 B |
| highmaps, gzipped | 107.2 kB | 103.7 kB | -3544 B|
| highcharts-gantt | 358.3 kB | 359.8 kB | 1564 B |
| highcharts-gantt, gzipped | 122.4 kB | 122.9 kB | 501 B|

2020-08-26 16:54 UTC, bre1470 commented
At the moment CatesianSeries is identical with LineSeries. In the next migration step I will break this up, so that a real Series => CatesianSeries => LineSeries class inheritance gets established.

2020-08-28 08:12 UTC, TorsteinHonsi requested changes
All good except
- CatesianSeries should be CartesianSeries
- Data labels should extend CartesianSeries
- Resolve conflicts

2020-08-30 06:04 UTC, TorsteinHonsi approved these changes

2020-08-30 06:04 UTC, merged