bugfix/13591-grid-axis-label-format
highcharts/highcharts pull request #14155
Opened 2020-09-01 13:24 UTC by karolkolodziej

Fixed #13591, time zone declared per chart was not respected for calculating axis labels.

2020-09-01 13:29 UTC, pawelfus commented on ts/Core/Axis/GridAxis.ts
> +    return time.dateFormat('%a', timestamp, true).charAt(0);
Why can't we use `this.dateFormat()` but we need to create another `Time` instance? Is that a problem with TS or something else? :)

2020-09-01 13:39 UTC, circleci-mu commented
## Visual test results - No difference found

2020-09-01 13:39 UTC, circleci-mu commented
### File size comparison
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts-gantt | 360.4 kB | 360.4 kB | 29 B |
| highcharts-gantt, gzipped | 123.1 kB | 123.0 kB | -130 B|

2020-09-02 08:02 UTC, TorsteinHonsi requested changes
Pending change to `return this.dateFormat`

2020-09-07 08:40 UTC, TorsteinHonsi approved these changes
Thanks!

2020-09-07 08:40 UTC, merged