Fixed #13749, ticks exceeded axis extremes when tickAmount was set
highcharts/highcharts pull request #14185
Opened 2020-09-07 10:54 UTC by TorsteinHonsi

Fixed #13749, when `tickAmount` was set, the tick positions would sometimes violate settings of `min`, `max` or `softThreshold`.

Replaces PR #14077

2020-09-07 11:07 UTC, circleci-mu commented
## Visual test results - Differences found
Found **1** diffing sample(s). [Please review the differences.](https://vrevs.highsoft.com/pr/14185/review)

2020-09-07 11:08 UTC, circleci-mu commented
### File size comparison
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts | 266.5 kB | 266.6 kB | 152 B |
| highcharts, gzipped | 92.1 kB | 92.1 kB | 24 B|
| highstock | 345.6 kB | 345.8 kB | 152 B |
| highstock, gzipped | 118.3 kB | 118.4 kB | 73 B|
| highmaps | 302.9 kB | 303.0 kB | 152 B |
| highmaps, gzipped | 103.8 kB | 103.9 kB | 66 B|
| highcharts-gantt | 362.1 kB | 362.2 kB | 152 B |
| highcharts-gantt, gzipped | 123.3 kB | 123.4 kB | 19 B|

2020-09-14 09:29 UTC, pawelfus requested changes
Just a minor thing (doclet).

Solution is not perfect: `min`+`max`+`tickAmount` still fails for xAxis: https://jsfiddle.net/BlackLabel/3pu6axed/5/ but I think it's good for now - the config in my demo is rather uncommon.

2020-09-14 09:29 UTC, pawelfus commented on ts/Core/Axis/Axis.ts
> +     */
Unnecessary (duplicated) doclet

2020-09-18 07:53 UTC, TorsteinHonsi commented on ts/Core/Axis/Axis.ts
> +     */
Thanks!

2022-04-27 16:02 UTC, closed without merging