ts/shadow-options-object-type
highcharts/highcharts pull request #14229
Opened 2020-09-15 13:19 UTC by marvin19

Put ShadowOptionsObject in its own type definition file.

2020-09-15 13:35 UTC, circleci-mu commented
## Visual test results - No difference found

2020-09-15 13:35 UTC, circleci-mu commented
### File size comparison
No differences found

2020-09-15 16:45 UTC, bre1470 requested changes
So far it looks good. `SVGRenderer.ts` also defines `Highcharts.ShadowOptionsObject`, so it should be removed there, too.
https://github.com/highcharts/highcharts/blob/ts/shadow-options-object-type/ts/Core/Renderer/SVG/SVGRenderer.ts#L73-L79

2020-09-16 10:31 UTC, bre1470 approved these changes
Looks good! 👍

2020-09-18 09:05 UTC, TorsteinHonsi approved these changes

2020-09-18 09:05 UTC, merged