ts/animations
highcharts/highcharts pull request #14245
Opened 2020-09-18 12:07 UTC by marvin19

Created animation folder and extracted animation functions and Fx class into their own files. Added type definition files.

2020-09-18 12:29 UTC, circleci-mu commented
## Visual test results - No difference found

2020-09-18 12:29 UTC, circleci-mu commented
### File size comparison
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts | 267.0 kB | 267.9 kB | 913 B |
| highcharts, gzipped | 92.3 kB | 92.3 kB | 2 B|
| highstock | 346.2 kB | 347.1 kB | 912 B |
| highstock, gzipped | 118.4 kB | 118.7 kB | 288 B|
| highmaps | 303.4 kB | 304.3 kB | 927 B |
| highmaps, gzipped | 103.8 kB | 104.2 kB | 360 B|
| highcharts-gantt | 362.7 kB | 363.6 kB | 912 B |
| highcharts-gantt, gzipped | 123.6 kB | 123.8 kB | 163 B|

2020-09-21 07:11 UTC, TorsteinHonsi approved these changes
Thanks!

2020-09-21 07:11 UTC, TorsteinHonsi commented
Pending @bre1470 's approval

2020-09-21 07:58 UTC, bre1470 requested changes
Looks good. 👍

Though `FxLike` needs some explanation for others to understand the purpose.

2020-09-21 07:58 UTC, bre1470 commented on ts/Core/Animation/FxLike.d.ts
> +}
```ts
/**
 * Optional properties for the Fx class. Should be defined outside of this file by `declare module` pattern.
 */
export interface FxLike {
    // nothing here yet
}
```

2020-09-22 12:16 UTC, bre1470 approved these changes

2020-09-23 13:47 UTC, merged