docs/fix-point-options
highcharts/highcharts pull request #14252
Opened 2020-09-22 12:27 UTC by bre1470

Fixed options types of data point.

2020-09-22 12:44 UTC, circleci-mu commented
## Visual test results - No difference found

2020-09-22 12:44 UTC, circleci-mu commented
### File size comparison
No differences found

2020-09-24 08:51 UTC, TorsteinHonsi requested changes
Do we want to expose `undefined` as a valid point value and thereby clutter up the API? It does not work in plain number config: https://jsfiddle.net/highcharts/06euoc5n/. It probably works just by accident in array configs.

2020-09-24 08:58 UTC, bre1470 commented
Probably not, because it is not part of the JSON specifications. Will fix.

2020-09-24 11:24 UTC, TorsteinHonsi approved these changes

2020-09-24 11:25 UTC, merged