bugfix/14298-cancelable-touch-events
highcharts/highcharts pull request #14318
Opened 2020-10-08 08:57 UTC by khlieng

Fixed #14298.

2020-10-08 09:12 UTC, circleci-mu commented
## Visual test results - No difference found

2020-10-08 09:12 UTC, circleci-mu commented
### File size comparison
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts | 268.2 kB | 268.2 kB | 27 B |
| highcharts, gzipped | 92.4 kB | 92.4 kB | 5 B|
| highstock | 347.3 kB | 347.4 kB | 27 B |
| highstock, gzipped | 118.6 kB | 118.6 kB | 6 B|
| highmaps | 304.6 kB | 304.6 kB | 27 B |
| highmaps, gzipped | 104.1 kB | 104.1 kB | 3 B|
| highcharts-gantt | 363.8 kB | 363.8 kB | 27 B |
| highcharts-gantt, gzipped | 123.7 kB | 123.8 kB | 12 B|

2020-10-12 08:20 UTC, oysteinmoseng requested changes
Just two concerns:
1. What happens in browsers that do not support `event.cancelable`?
2. In AccessibilityComponent we should always run `preventDefault` as the event is moved to a different element. See inline comment.

2020-10-12 08:20 UTC, oysteinmoseng commented on ts/Accessibility/AccessibilityComponent.ts
> +                    e.preventDefault();
This should always run `preventDefault` - regardless of `cancelable`.

2020-10-12 08:55 UTC, oysteinmoseng requested changes
Looks good, just a minor comment

2020-10-12 08:55 UTC, oysteinmoseng commented on ts/Core/Pointer.ts
> +            (typeof e.cancelable !== 'boolean' || e.cancelable)) {
Just nitpicking, but you might be able to get away with `e.cancelable !== false` and save a few bytes of filesize.

2020-10-12 10:18 UTC, oysteinmoseng approved these changes
Looks good to me, thanks!

2020-10-12 10:30 UTC, TorsteinHonsi approved these changes

2020-10-16 08:07 UTC, merged