bugfix/14289-infinite-loop-histogram
highcharts/highcharts pull request #14378
Opened 2020-10-20 06:28 UTC by khlieng

Fixed #14289, histogram series entered an infinite loop when passed certain data values.

2020-10-20 06:46 UTC, circleci-mu commented
## Visual test results - No difference found

2020-10-20 06:46 UTC, circleci-mu commented
### File size comparison
No differences found

2020-10-29 10:38 UTC, Denyllon approved these changes
Looks correct to me. Thank you!

2020-10-29 11:38 UTC, TorsteinHonsi requested changes
Thanks! Please add a test too.

2020-10-29 11:47 UTC, khlieng commented
Would the tests hanging forever be an acceptable way of failing?

2020-11-02 10:39 UTC, Denyllon approved these changes

2020-11-02 12:05 UTC, TorsteinHonsi approved these changes

2020-11-02 12:05 UTC, merged