ts/line-column-series
highcharts/highcharts pull request #14377
Opened 2020-10-19 21:34 UTC by bre1470

Migrated LineSeries and ColumnSeries to class pattern.

The migration techniques differs in some important aspects of the previous approaches.
1. There is no class split of the LineSeries, so for now it is still the base class.
2. The series class have only the default constructor without arguments.
3. Non-optional properties are part of the prototype interface, not of the class.

The following technique pattern helps with the series migration. You can move every series function one by one and test in between, if something breaks:
```ts
class SomeSeries extends ParentSeries {
  const defaultOptions = merge(ParentSeries.defaultOptions, {
    // some options
  });
  // here are the functions after movement
  // you can use super instead of seriesTypes.parent like
  public init(): void {
    super.init.apply(this, arguments as any);
  }
}
interface SomeSeries extends ParentSeries {
  // here are the definitions taken from Highcharts.namespace
}
extend(
  SomeSeries.prototype,
  {
    // here are the functions before movement (like in the seriesType factory)
    // properties from the factory will stay here and not be moved,
    // because they need to be on the prototype (not instance)
  }
);
Series.addSeries('some', SomeSeries);
```

2020-10-19 21:48 UTC, circleci-mu commented
## Visual test results - No difference found

2020-10-19 21:48 UTC, circleci-mu commented
### File size comparison
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts | 268.2 kB | 269.1 kB | 841 B |
| highcharts, gzipped | 92.5 kB | 92.4 kB | -128 B|
| highstock | 347.5 kB | 348.3 kB | 831 B |
| highstock, gzipped | 118.8 kB | 118.8 kB | 12 B|
| highmaps | 304.7 kB | 305.5 kB | 841 B |
| highmaps, gzipped | 104.2 kB | 104.1 kB | -172 B|
| highcharts-gantt | 364.0 kB | 364.8 kB | 841 B |
| highcharts-gantt, gzipped | 123.9 kB | 123.9 kB | 13 B|

2020-10-30 09:29 UTC, TorsteinHonsi approved these changes
Thanks, looks good!

Logically it looks a bit quirky that the LineSeries now is the base series (for example in Legend, where a legend item can either be a `Point|LineSeries`... in reality it is a point or any type of series), but I assume this is temporary.

2020-11-02 09:02 UTC, bre1470 commented
> Thanks, looks good!
> 
> Logically it looks a bit quirky that the LineSeries now is the base series (for example in Legend, where a legend item can either be a `Point|LineSeries`... in reality it is a point or any type of series), but I assume this is temporary.

Yes, it is temporary and just represents the situation on runtime right now.

2020-11-02 10:22 UTC, TorsteinHonsi requested changes
Pending conflict resolution

2020-11-02 12:26 UTC, TorsteinHonsi approved these changes

2020-11-02 12:27 UTC, merged