bugfix/14372-patternfill-opacity
highcharts/highcharts pull request #14456
Opened 2020-10-29 11:58 UTC by karolkolodziej

Fixed #14372, unable to set opacity in the pattern.

2020-10-29 12:11 UTC, circleci-mu commented
## Visual test results - No difference found

2020-10-29 12:12 UTC, circleci-mu commented
### File size comparison
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts | 268.5 kB | 268.6 kB | 69 B |
| highcharts, gzipped | 92.5 kB | 92.5 kB | 30 B|
| highstock | 347.8 kB | 347.8 kB | 69 B |
| highstock, gzipped | 118.8 kB | 118.8 kB | -16 B|
| highmaps | 317.3 kB | 317.4 kB | 69 B |
| highmaps, gzipped | 108.1 kB | 108.2 kB | 85 B|
| highcharts-gantt | 364.2 kB | 364.3 kB | 66 B |
| highcharts-gantt, gzipped | 123.9 kB | 123.8 kB | -93 B|

2020-10-30 08:05 UTC, khlieng commented on ts/Extensions/PatternFill.ts
> +    addEvent(Highcharts.Color, 'setPatternOpacity', function (e): void {
This is going to leak event handlers.

2020-11-02 13:42 UTC, TorsteinHonsi requested changes
I'm wondering if we're looking at this the wrong way. Instead of adding a hack to allow opacity in patterns, let's look at the pie series, where opacity works:
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/series/pattern-fill-pie/

This is because the pie series sets the `opacity` attribute directly on the point graphic, which works like so: https://jsfiddle.net/Lb9qoehc/1/

In the pie series' `pointAttribs` function (borrowed from , the `opacity`) attribute is returned. But in the venn series, the `opacity` is applied to the `fill` color (using `setOpacity`) before returned, which is why it fails with patterns.

So I think we should start by looking at why the Venn series does it this way and not like other series.

Edit: Here's the proposed fix applied to the OP: https://jsfiddle.net/highcharts/zuf0sncq/1/

Next, _if we find out Venn has a good reason for doing it differently_, we should find a way to integrate opacity in pattern fills, preferably without tailored event hooks in the Color.ts function.

2020-11-02 14:17 UTC, pawelfus commented
> So I think we should start by looking at why the Venn series does it this way and not like other series.

Just to be on the same page: setting `opacity` attribute sets opacity also to border, while setting opacity in `fill` sets opacity only in `fill`. Apart from that, I don't see any other good reason.

2020-11-09 11:38 UTC, TorsteinHonsi requested changes
I like the cleanness of 47fd255 better - apply a global opacity regardless of pattern. Three visual samples were diffing because the other series' data labels were no semi-transparent, but that is in accordance with [how other series work](https://jsfiddle.net/highcharts/tef0k4s9/), and should be accepted.

2020-11-09 12:55 UTC, karolkolodziej commented
I went back to the previous commit and accepted visual changes with a comment about that change.

2020-11-10 11:14 UTC, TorsteinHonsi approved these changes
Thanks!

2020-11-10 11:14 UTC, merged