ts/bar-series
highcharts/highcharts pull request #14501
Opened 2020-11-06 12:36 UTC by marvin19

Migration of bar series.

2020-11-06 12:50 UTC, circleci-mu commented
## Visual test results - No difference found

2020-11-06 12:50 UTC, circleci-mu commented
### File size comparison
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts | 272.1 kB | 272.7 kB | 657 B |
| highcharts, gzipped | 93.2 kB | 93.3 kB | 136 B|
| highstock | 351.5 kB | 352.1 kB | 655 B |
| highstock, gzipped | 119.7 kB | 120.0 kB | 235 B|
| highmaps | 321.0 kB | 321.6 kB | 655 B |
| highmaps, gzipped | 109.1 kB | 109.2 kB | 149 B|
| highcharts-gantt | 367.8 kB | 368.4 kB | 655 B |
| highcharts-gantt, gzipped | 124.7 kB | 124.9 kB | 216 B|

2020-11-06 13:55 UTC, bre1470 approved these changes
Looks good. 👍

2020-11-09 10:27 UTC, TorsteinHonsi requested changes
Thanks, please fix conflict before we can merge.

2020-11-10 12:14 UTC, TorsteinHonsi approved these changes

2020-11-10 12:15 UTC, merged