Fixed #14495, correct label color.
highcharts/highcharts pull request #14523
Opened 2020-11-09 14:50 UTC by DJTechnoo

Fixed background color not overwritten by lastVisiblePrice label background color.

2020-11-09 15:06 UTC, circleci-mu commented
## Visual test results - No difference found

2020-11-09 15:07 UTC, circleci-mu commented
### File size comparison
No differences found

2020-11-09 16:36 UTC, pawelfus requested changes
Can we fix all other options too? For example padding: https://jsfiddle.net/BlackLabel/13qmwfkr/2/

Just a guess, but it seems `yAxis.options.crosshair` is overwritten, but never restored, maybe that's it? I see below comment: `// Restore crosshair:` that some props are restored.

2020-11-10 12:05 UTC, pawelfus approved these changes
Thanks!
I thought we use single quotes, even in tests, not double quotes, but it seems eslint is fine with that, so am I! 👍

2020-11-10 12:11 UTC, DJTechnoo commented
> I thought we use single quotes, even in tests

Whoops, wasn't aware of that! I'll keep it in mind for next time, thanks Pawel 👍

2020-11-10 12:36 UTC, TorsteinHonsi commented
> I thought we use single quotes, even in tests, not double quotes, but it seems eslint is fine with that, so am I!

@pawelfus We prefer single quotes, but we have some tests with large chunks of copy-pasted JSON. Maybe we should add a warning rather than an error.

2020-11-10 12:37 UTC, TorsteinHonsi approved these changes
Thanks!

2020-11-10 12:39 UTC, TorsteinHonsi commented
PS @DJTechnoo See https://github.com/highcharts/highcharts/tree/master/changelog#writing-content-for-the-changelog
* Start with "Fixed #14382..."
* Wrap code in backticks: `lastVisiblePrice`

2020-11-10 12:40 UTC, merged