ts/bullet-series
highcharts/highcharts pull request #14531
Opened 2020-11-10 13:50 UTC by marvin19

Migration of bullet series.

2020-11-10 14:09 UTC, bre1470 requested changes
Thank you. One thing with the point class can be improved.

2020-11-10 14:09 UTC, bre1470 commented on ts/Series/Bullet/BulletSeries.ts
> +}
This should go into a `BulletPoint.ts` (instead of the `BulletPoint.d.ts`).

2020-11-10 14:26 UTC, circleci-mu commented
## Visual test results - Differences found
Found **1** diffing sample(s). [Please review the differences.](https://vrevs.highsoft.com/pr/14531/review)

2020-11-10 14:26 UTC, circleci-mu commented
### File size comparison
No differences found

2020-11-10 14:37 UTC, bre1470 approved these changes
Thank you! Looks great. 👍

2020-11-10 14:38 UTC, bre1470 commented
There is a visual test differing.

2020-11-11 08:35 UTC, TorsteinHonsi requested changes
Pending a fix for the visual diff. Apparently the `target` value is no longer considered.

2020-11-12 10:46 UTC, bre1470 commented
We unable to reproduce it locally. Additionally the graph looks completely different in the browser.

2020-11-12 12:46 UTC, TorsteinHonsi approved these changes

2020-11-12 12:46 UTC, merged