ts/bb-indicator
highcharts/highcharts pull request #14600
Opened 2020-11-18 11:13 UTC by karolkolodziej

2020-11-18 11:25 UTC, circleci-mu commented
## Visual test results - Differences found
Found **4** diffing sample(s). [Please review the differences.](https://vrevs.highsoft.com/pr/14600/review)

2020-11-18 11:26 UTC, circleci-mu commented
### File size comparison
No differences found

2020-11-19 14:15 UTC, bre1470 requested changes
Thank you! Please note the review comment.

2020-11-19 14:15 UTC, bre1470 commented on ts/Stock/Indicators/BB/BBIndicator.ts
> +    public init(this: BBIndicator): void {
The generic comment is incorrect. You have two options to solve this. Remove this generic comment, or replace it with "Properties" and add "Functions". In a class pattern property assignments go on the instance and only functions go on the prototype.

2020-11-19 15:18 UTC, bre1470 approved these changes
Looks good. 👍

2020-11-20 09:31 UTC, TorsteinHonsi commented
Pending tests after conflict resolving, otherwise ready to merge.

2020-11-20 11:12 UTC, merged