enhancement/series-area-3d
highcharts/highcharts pull request #14608
Opened 2020-11-19 12:13 UTC by Izothep

Enhancement, added support for area series in 3d charts.

2020-11-19 12:59 UTC, circleci-mu commented
## Visual test results - No difference found

---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  Added | samples/highcharts/3d/area/demo.js |

</p>
</details>

2020-11-19 13:00 UTC, circleci-mu commented
### File size comparison
No differences found

2020-11-19 15:55 UTC, pawelfus commented on ts/Series/Area3DSeries.ts
> +    if (series.chart.is3d() && series.chart.options && series.chart.options.chart) {
You checked `is3d()` already above

2020-11-19 15:58 UTC, pawelfus requested changes
Apart from that one minor thing, amazing work!

2020-11-19 19:45 UTC, Izothep commented on ts/Series/Area3DSeries.ts
> +    if (series.chart.is3d() && series.chart.options && series.chart.options.chart) {
I have removed this check. Thanks!

2020-11-20 09:49 UTC, TorsteinHonsi requested changes
Thanks, it looks great!

It seems the Z index is not 100% though: https://jsfiddle.net/highcharts/dk486t5m/

In addition I think we need some more visual samples both for user education and for regression testing:
* Multiple series non-stacked
* Multiple series with stacking
* Perhaps a combination of stacking and not

2020-11-24 15:05 UTC, Izothep commented
All corrected, thanks @TorsteinHonsi! I will add the demo to the related docs article in a separate PR.

2020-11-30 14:27 UTC, TorsteinHonsi requested changes
Thanks!

There is still a Z index issue with the markers: https://jsfiddle.net/highcharts/dkqe7m5y/. Note how _Series 2_'s markers are hidden behind _Series 1_'s fill area.

> I will add the demo to the related docs article in a separate PR.

Can we have the docs and the nice demo in the same PR please? So that we don't lose track of this new feature.

2020-12-04 16:59 UTC, Izothep commented
Thanks for the review. `zIndex` problem is solved in the newest version of the code. I have added a demo and prepared docs explanation (I am not sure if they are written correctly though).

2020-12-08 10:54 UTC, TorsteinHonsi approved these changes
Perfect, thanks!

2020-12-08 10:54 UTC, merged