ts/dpo-indicator
highcharts/highcharts pull request #14605
Opened 2020-11-19 11:07 UTC by madepiet

Added initial class pattern to dpo indicator.

2020-11-19 11:21 UTC, circleci-mu commented
## Visual test results - No difference found

2020-11-19 11:21 UTC, circleci-mu commented
### File size comparison
No differences found

2020-11-20 13:01 UTC, bre1470 requested changes
Thank you! One small change needed, otherwise it is good.

2020-11-20 13:01 UTC, bre1470 commented on ts/Stock/Indicators/DPO/DPOIndicator.ts
> +    options: DPOOptions;
The options property should go into the class pattern.

2020-11-20 17:27 UTC, bre1470 requested changes
Thank you so far. I found an other issue. Please see the comment.

Note that you also have to fix the auto merge conflict caused by changes of other indicators.

2020-11-20 17:27 UTC, bre1470 commented on ts/Stock/Indicators/DPOIndicator.ts
> -        nameBase: 'DPO',
I believe that the value of nameBase somehow got removed. This part needs to be restored with the `extend` call right under the interface of the prototype properties.
```ts
extend(DPOIndicator.prototype, {
    nameBase: 'DPO'
});
```

2020-11-23 08:40 UTC, bre1470 approved these changes
Thank you! Looks good. 👍

2020-11-23 08:45 UTC, sebastianbochan approved these changes

2020-11-23 08:58 UTC, merged