ts/ao-indicator
highcharts/highcharts pull request #14614
Opened 2020-11-20 07:02 UTC by K009

2020-11-20 07:15 UTC, circleci-mu commented
## Visual test results - No difference found

2020-11-20 07:15 UTC, circleci-mu commented
### File size comparison
No differences found

2020-11-20 08:14 UTC, sebastianbochan commented
- missed splitting indicator into files
- missing `.d.ts` definitions of AOOptions and AOPoint

2020-11-23 08:32 UTC, TorsteinHonsi requested changes
Please resolve conflicts. Then pending @bre1470 's review.

2020-11-23 11:43 UTC, closed without merging