ts/DEMA-indicator
highcharts/highcharts pull request #14633
Opened 2020-11-23 12:37 UTC by karolkolodziej

2020-11-23 13:16 UTC, circleci-mu commented
## Visual test results - No difference found

2020-11-23 13:16 UTC, circleci-mu commented
### File size comparison
No differences found

2020-11-24 13:55 UTC, bre1470 requested changes
Thank you! See the comments for requested changes.

2020-11-24 13:55 UTC, bre1470 commented on ts/Stock/Indicators/DEMA/DEMAIndicator.ts
> +}
This should be deleted. Replace the DEMAIndicatorLinkedParentSeries type with `LineSeries` and add in this place:
```ts
/* *
 *
 *  Declarations
 *
 * */

declare module '../../../Core/Series/SeriesLike' {
    interface SeriesLike {
        EMApercent?: number;
    }
}
```

2020-11-24 13:55 UTC, bre1470 commented on ts/Stock/Indicators/DEMA/DEMAIndicator.ts
> +    } as DEMAOptions)
If there were not default options, you can just assign `merge(EMAIndicator.defaultOptions);`

2020-11-25 10:01 UTC, bre1470 approved these changes
Thank you! Looks good. 👍

2020-11-25 10:08 UTC, TorsteinHonsi approved these changes

2020-11-25 10:08 UTC, TorsteinHonsi commented
Is it ready to merge? If so, please mark it "Ready for review".

2020-11-26 08:53 UTC, merged