ts/aoindicator
highcharts/highcharts pull request #14632
Opened 2020-11-23 10:56 UTC by K009

2020-11-23 11:40 UTC, sebastianbochan commented
Looks good 👍

2020-11-23 11:44 UTC, K009 commented
This is the fixed version of [ts/ao-indicator #14614](https://github.com/highcharts/highcharts/pull/14614).

2020-11-23 13:20 UTC, sebastianbochan requested changes
It looks like edit of `js/masters/indicators` import file is missing.

2020-11-23 13:46 UTC, circleci-mu commented
## Visual test results - No difference found

2020-11-23 13:47 UTC, circleci-mu commented
### File size comparison
No differences found

2020-11-23 14:05 UTC, sebastianbochan commented
Looks good!

2020-11-23 14:05 UTC, sebastianbochan approved these changes

2020-11-24 09:41 UTC, bre1470 commented
All the space lines in the sources are missing now. It makes it harder to understand the code than before. Comes this from some editor clean up?

2020-11-24 14:19 UTC, bre1470 requested changes
Please restore the spaces between lines like in the original code.

2020-11-26 15:06 UTC, bre1470 requested changes
Thanks. Please see comments for requested changes.

2020-11-26 15:06 UTC, bre1470 commented on ts/Stock/Indicators/AO/AOIndicator.ts
> +    drawGraph: function (this: AOIndicator): void {
drawGraph should go into the class pattern.

2020-11-26 15:06 UTC, bre1470 commented on ts/Stock/Indicators/AO/AOIndicator.ts
> +    getValues: function<TLinkedSeries extends LineSeries> (
getValues should go into the class pattern

2020-11-26 15:06 UTC, bre1470 commented on ts/Stock/Indicators/AO/AOIndicator.ts
> +    points: Array<AOPoint>;
data, options, points go into the class pattern.

2020-11-27 10:01 UTC, bre1470 requested changes
Thank you! Please see comments for additional changes.

2020-11-27 10:01 UTC, bre1470 commented on ts/Stock/Indicators/AO/AOIndicator.ts
> +import BaseSeries from '../../../Core/Series/Series.js';
In addition deconstruct column series (`column: ColumnSeries`) for code change below.

2020-11-27 10:01 UTC, bre1470 commented on ts/Stock/Indicators/AO/AOIndicator.ts
> +    drawPoints: H.seriesTypes.column.prototype.drawPoints
Instead of using the namespace with `H.seriesTypes.column.prototype` here, you should replace it with the series type `ColumnSeries.prototype`.

2020-11-27 14:12 UTC, bre1470 approved these changes
Thank you! Looks good. 👍

2020-11-30 09:37 UTC, merged