ts/areasplinerange-series
highcharts/highcharts pull request #14636
Opened 2020-11-23 14:41 UTC by goransle

Migrated `areasplinerange` series to class pattern.

2020-11-23 15:11 UTC, circleci-mu commented
## Visual test results - No difference found

2020-11-23 15:11 UTC, circleci-mu commented
### File size comparison
No differences found

2020-11-24 14:25 UTC, bre1470 requested changes
Thank you! Please see comments for requested changes.

2020-11-24 14:25 UTC, bre1470 commented on ts/Series/AreaSplineRange/AreaSplineRangeSeries.ts
> +import '../../Core/Options.js';
The anonymous import can be removed, because it is done by BaseSeries.

2020-11-24 14:25 UTC, bre1470 commented on ts/Series/AreaSplineRange/AreaSplineRangeSeries.ts
> +    );
The API generator supports a reduced `merge` call. So you can simplify it to:
```ts
       public static defaultOptions: AreaSplineRangeSeriesOptions = merge(AreaRangeSeries.defaultOptions);
```

2020-11-25 09:16 UTC, bre1470 approved these changes
Thank you! Looks good. 👍 

Though it has now a merge conflict with master that needs to be solved. 🙈

2020-11-25 10:05 UTC, TorsteinHonsi approved these changes

2020-11-25 10:06 UTC, merged