bugfix/14549-clip-path-added-axis
highcharts/highcharts pull request #14776
Opened 2020-12-08 12:30 UTC by karolkolodziej

Fixed #14549, incorrect clip-path for added axis.

2020-12-08 13:01 UTC, circleci-mu commented
## Visual test results - Differences found
Found **246** diffing sample(s). [Please review the differences.](https://vrevs.highsoft.com/pr/14776/review)

2020-12-08 13:02 UTC, circleci-mu commented
### File size comparison
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highstock | 362.2 kB | 362.2 kB | -14 B |
| highstock, gzipped | 121.8 kB | 121.8 kB | 0 B|

2020-12-09 10:30 UTC, pawelfus requested changes
Visual diff in Highcharts Stock: ✅   - previously line was overflowing in this demo, now it's clipped. Only this one demo shows the diff, because probably only this one adds series in `chart.load` event.
Visual diffs in Highcharts Maps: 🔴   - this 1px looks strange, could you please check it?

2020-12-09 12:35 UTC, karolkolodziej commented
As it comes to the visual differences in maps, it is strange indeed.
When you compare (see the difference in northern Greenland):
- v8.2.2 https://jsfiddle.net/BlackLabel/9407pvyn/
- master http://jsfiddle.net/BlackLabel/ucvmwexp/

You can observe that the differences were introduced to the master in some earlier commit.
Why this change is first caught in this PR?

2020-12-14 09:49 UTC, TorsteinHonsi approved these changes
Looks good, thanks!

2020-12-14 09:49 UTC, merged