docs/accessibility-module
highcharts/highcharts pull request #14781
Opened 2020-12-09 09:22 UTC by marvin19

Added more more content and headings to the docs.

2020-12-09 09:37 UTC, circleci-mu commented
## Visual test results - No difference found

2020-12-09 09:37 UTC, circleci-mu commented
### File size comparison
No differences found

2020-12-10 14:19 UTC, oysteinmoseng requested changes
Great work! Only minor comments.

2020-12-10 14:19 UTC, oysteinmoseng commented on docs/accessibility/accessibility-module.md
> +The accessibility of Highcharts is critical to us. Accessibility should be fundamental to any software project, not an additional add on. Every Highcharts license includes our Accessibility module, w
Maybe replace "not an additional add on" with e.g. "not an afterthought". Also looks like an extra space before "We use the WCAG 2.1 standard...".

2020-12-10 14:19 UTC, oysteinmoseng commented on docs/accessibility/accessibility-module.md
> +You can read more about [installation of Highcharts](https://www.highcharts.com/docs/getting-started/installation) and [setting up your first chart](https://www.highcharts.com/docs/getting-started/yo
Maybe instead of "You can read more about" just do "Read more about", and put it in _italics_?

2020-12-10 14:19 UTC, oysteinmoseng commented on docs/accessibility/accessibility-module.md
> +It is possible to add the text description directly on the chart SVG as well, using the [`caption`](https://api.highcharts.com/highcharts/caption) option. If this option is used, the caption will aut
We might want to replace "The caption renders in the bottom" with "The caption renders at the bottom of the chart, and is included if the chart is exported" or something similar

2020-12-10 14:19 UTC, oysteinmoseng commented on docs/accessibility/accessibility-module.md
> +        text: '<b>The caption renders in the bottom, and is part of the exported chart.</b>'
Same comment here as above

2020-12-10 14:42 UTC, oysteinmoseng approved these changes
Nice!

2020-12-14 09:46 UTC, TorsteinHonsi approved these changes

2020-12-14 09:46 UTC, merged