bugfix/14868-gantt-drilldown-labels-postion
highcharts/highcharts pull request #14889
Opened 2021-01-07 11:46 UTC by karolkolodziej

Fixed #14868, labels were positioned incorrectly when Gantt was imported.

2021-01-07 12:04 UTC, circleci-mu commented
## Visual test results - Differences found
Found **192** diffing sample(s). [Please review the differences.](https://vrevs.highsoft.com/pr/14889/review)

2021-01-07 12:05 UTC, circleci-mu commented
### File size comparison
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts-gantt | 382.2 kB | 382.3 kB | 56 B |
| highcharts-gantt, gzipped | 127.9 kB | 127.9 kB | 26 B|

2021-01-08 13:20 UTC, TorsteinHonsi requested changes
Nice, thanks! I've been wondering why the labels were sometimes slightly off center.

Change requests:
* Is there a specific reason for checking `userOptions.grid.enabled` rather than the usual `options`? Unless looking for things that are set explicitly, we should use the processed `options`.
* Can you also go over the 192 differing visual samples and verify them? Most or all seem to correctly adjust the axis label back to center. But we must also make sure there is not a real regression hiding in between the valid diffs.

2021-01-12 08:08 UTC, karolkolodziej commented
You are right, there is no need to use the `userOptions` the `options` works fine in this case. 
I went through all visual differences and each one looked as correct adjustment of label positioning.

2021-01-13 08:37 UTC, TorsteinHonsi requested changes
Thanks! There seems to be room for some more micro-optimization.

2021-01-13 08:37 UTC, TorsteinHonsi commented on ts/Core/Axis/GridAxis.ts
> +        if (axis.options.grid && axis.options.grid.enabled) {
On line 910, we already have `gridOptions = options.grid || {}`. That means line 914 can probably be optimized to `if (gridOptions.enabled) {`

2021-01-13 08:37 UTC, TorsteinHonsi commented on ts/Core/Axis/GridAxis.ts
> +                if (gridOptions.enabled === true) {
Now since we're already checking for `gridOptions.enabled` on line 914, we should be able to safely remove the check on line 916.

2021-01-13 15:01 UTC, TorsteinHonsi approved these changes

2021-01-13 15:02 UTC, merged