bugfix/8095-reset-zoom-drilldown
highcharts/highcharts pull request #14881
Opened 2021-01-06 12:27 UTC by karolkolodziej

Fixed #8095, reset zoom button was not visible after drilldown.

2021-01-06 12:31 UTC, sebastianbochan requested changes

2021-01-06 12:31 UTC, sebastianbochan commented on ts/Extensions/Drilldown.ts
> +    }
Lines 1668-1681 are exactly the same as 1649-1661. I suggest to extract it and avoid code rendudant.

2021-01-06 12:41 UTC, circleci-mu commented
## Visual test results - No difference found

2021-01-06 12:42 UTC, circleci-mu commented
### File size comparison
No differences found

2021-01-07 10:46 UTC, sebastianbochan approved these changes

2021-01-08 09:47 UTC, TorsteinHonsi requested changes
We already have an event handler for `beforeShowResetZoom` on line 1057. Instead of creating a complicated workaround for our own code, we should modify the existing code to do what we want. The current event handler disables the `resetZoomButton` if the `drillUpButton` is present. That's obviously not what we want with this fix, we want to align them side by side instead.

2021-01-13 09:35 UTC, TorsteinHonsi requested changes
In addition to the inline comments, there is a fail case. With the [OP demo](http://jsfiddle.net/502k9msp/):

1. Perform drilldown by clicking first column
2. Zoom in
3. Click "Back to"
4. Click first column => Crash

2021-01-13 09:35 UTC, TorsteinHonsi commented on ts/Extensions/Drilldown.ts
> +        temporaryDrillUpButton?: SVGElement;
This line is obsolete

2021-01-13 09:37 UTC, TorsteinHonsi requested changes

2021-01-13 09:37 UTC, TorsteinHonsi commented on samples/unit-tests/drilldown/resetzoom/demo.js
In addition to checking for the button's existence, it would probably be a good idea to check that it does not overlap with the drillUp button.

2021-01-13 12:38 UTC, karolkolodziej commented
Thanks for pointing that case! I added a piece of code (together with a proper test) covering that example.

2021-01-18 08:47 UTC, TorsteinHonsi approved these changes

2021-01-18 08:48 UTC, merged