bugfix/14448-scrollablePlotArea-drillUpButton
highcharts/highcharts pull request #14935
Opened 2021-01-14 11:43 UTC by khlieng

Fixed #14448, drillup button disappeared when combined with `scrollablePlotArea`.

2021-01-14 11:52 UTC, circleci-mu commented
## Visual test results - No difference found

2021-01-20 11:23 UTC, circleci-mu commented
### File size comparison
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts | 281.9 kB | 281.8 kB | -58 B |
| highcharts, gzipped | 95.2 kB | 95.2 kB | 1 B|
| highstock | 372.1 kB | 372.0 kB | -58 B |
| highstock, gzipped | 124.6 kB | 124.6 kB | 22 B|
| highmaps | 339.4 kB | 339.4 kB | -58 B |
| highmaps, gzipped | 112.0 kB | 112.0 kB | 44 B|
| highcharts-gantt | 387.5 kB | 387.5 kB | -57 B |
| highcharts-gantt, gzipped | 129.5 kB | 129.5 kB | 20 B|

2021-02-09 14:31 UTC, TorsteinHonsi approved these changes
Thanks!

2021-02-09 14:32 UTC, TorsteinHonsi requested changes
Pleas fix the conflicts, the we're good to go.

2021-02-09 14:33 UTC, khlieng commented
#11687: Should i do a separate PR for the fixed position?

2021-02-16 11:16 UTC, TorsteinHonsi approved these changes

2021-02-16 11:16 UTC, merged