bugfix/14980-toggle-stacking-centerInCategory
highcharts/highcharts pull request #14986
Opened 2021-01-25 10:01 UTC by khlieng

Fixed #14980, toggling stacking with `centerInCategory` enabled did not work.

2021-01-25 10:19 UTC, circleci-mu commented
## Visual test results - No difference found

2021-01-25 15:16 UTC, circleci-mu commented
### File size comparison
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts | 281.9 kB | 281.9 kB | 33 B |
| highcharts, gzipped | 95.2 kB | 95.2 kB | 8 B|
| highstock | 372.1 kB | 372.1 kB | 33 B |
| highstock, gzipped | 124.6 kB | 124.6 kB | -54 B|
| highmaps | 339.4 kB | 339.5 kB | 33 B |
| highmaps, gzipped | 112.0 kB | 112.0 kB | -14 B|
| highcharts-gantt | 387.5 kB | 387.5 kB | 33 B |
| highcharts-gantt, gzipped | 129.5 kB | 129.5 kB | 9 B|

2021-02-04 13:59 UTC, TorsteinHonsi requested changes
There's still a bug if we start out with `isStacked = false` : https://jsfiddle.net/highcharts/8cvk9q4x/

Everything is good until we click "Toggle" the second time, then the columns fly off to the left only to return on the third click.

Also, instead of doing the `skip` inside that loop, I think we should dig deeper. In the [OP demo](https://jsfiddle.net/nulle/x7pLeatr/), why is it that there is no `column,group` stack initially, but it is there when we're updating? It seems like there is something that should be destroyed when we toggle stacking.

2021-02-09 12:21 UTC, khlieng commented
Its not there initially because it doesnt get created if real stacking is enabled, but all the stacks should probably be destroyed somehow when `stacking` or `centerInCategory` changes.

2021-02-16 10:24 UTC, TorsteinHonsi commented
> all the stacks should probably be destroyed somehow when stacking or centerInCategory changes.

Yes, can you look into that? So that when we reach `adjustForMissingColumns` the state is the same regardless of what it was before the update.

2021-02-19 07:58 UTC, TorsteinHonsi approved these changes

2021-02-19 07:59 UTC, merged