bugfix/13876-currentPriceIndicator-stockTools-error
highcharts/highcharts pull request #15041
Opened 2021-02-03 09:52 UTC by karolkolodziej

Fixed #13876, toggling `currentPriceIndicator` button threw error.

2021-02-03 10:08 UTC, circleci-mu commented
## Visual test results - No difference found

2021-02-03 10:09 UTC, circleci-mu commented
### File size comparison
No differences found

2021-02-05 16:01 UTC, raf18seb requested changes

2021-02-08 10:01 UTC, pawelfus commented on samples/unit-tests/indicator-price-indicator/recalculations/demo.js
> +        chart.series[0].crossLabel.visibility,
In source code, yes, please. In tests, it's not that important, but we may as well practice this :)

2021-02-08 15:02 UTC, karolkolodziej commented on samples/unit-tests/indicator-price-indicator/recalculations/demo.js
> +                    color: 'blue',
I changed most of them, the only one left is the `red` for the `lastPrice` where it looks like a separate issue  #15074

2021-02-09 09:54 UTC, raf18seb commented on samples/unit-tests/indicator-price-indicator/recalculations/demo.js
> +                    enabled: true,
Sure, in that case you can leave it as it is!

2021-02-09 10:17 UTC, raf18seb approved these changes
Thanks!

2021-02-09 15:24 UTC, pawelfus approved these changes
Looks good!

2021-02-09 15:54 UTC, pawellysy approved these changes
Looks Good!

2021-02-09 17:02 UTC, raf18seb commented on samples/unit-tests/indicator-price-indicator/recalculations/demo.js
> +    have their own properties, no errors in console after toggle, #13876.`,
@pawellysy yes, we were talking about descriptions in **asserts**:
```js
assert.strictEqual(
    1 + 2,
    3,
    '1 + 2 should equal 3.'
);
```

In the above comment, I was talking about the **main title**. In the main title, you should shortly describe what you are testing or what was the main issue.

Please, have a look at this test for a reference: https://github.com/highcharts/highcharts/blob/master/samples/unit-tests/series-dumbbell/markers/demo.js
You will find 2 separate main tests with titles describing what the tests are about. Then, in every test, you will find many asserts testing a specific case with a "should" keyword indicating how the result should look like.

2021-02-16 10:28 UTC, merged