bugfix/15074-lastPrice-color
highcharts/highcharts pull request #15137
Opened 2021-02-15 13:26 UTC by karolkolodziej

Fixed #15074, `lastPrice` color was not applied properly.

2021-02-15 13:39 UTC, circleci-mu commented
### File size comparison
No differences found

2021-02-15 13:41 UTC, circleci-mu commented
## Visual test results - No difference found

2021-02-15 15:07 UTC, pawellysy approved these changes
Looks Good!

2021-02-15 16:25 UTC, pawelfus requested changes

2021-02-15 16:25 UTC, pawelfus commented on ts/Stock/StockToolsBindings.ts
> +                    color: (options.lastPrice && options.lastPrice.color) || '#ff0000'
Is this necessary to define `color` here? It should be enough to toggle the `enabled` option from the button perspective, right?

2021-02-18 10:33 UTC, raf18seb approved these changes
Look good 👍

2021-02-18 14:21 UTC, pawelfus approved these changes
Sweet! :)

2021-02-19 07:57 UTC, merged