bugfix/stock-default-axis-options
highcharts/highcharts pull request #15164
Opened 2021-02-17 15:01 UTC by khlieng

Fixed dynamically added axis defaults in stock, axes dynamically added to stock charts got different defaults than the ones added through the chart constructor.

2021-02-17 15:16 UTC, circleci-mu commented
### File size comparison
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highstock | 373.5 kB | 374.2 kB | 630 B |
| highstock, gzipped | 125.1 kB | 125.3 kB | 220 B|

2021-02-17 15:18 UTC, circleci-mu commented
## Visual test results - No difference found

2021-03-01 09:47 UTC, TorsteinHonsi requested changes
Thanks for the PR!

We need some tests too. Does the `StockChart.createAxis` function actually run at all? As far as I can see, the `StockChart` class isn't used. The `stockChart` factory returns an instance of `Chart`. And `Highcharts.StockChart` is a reference to the `stockChart` factory.

@bre1470 FYI

2021-03-01 11:51 UTC, khlieng commented
So I guess most of the factory function should be moved into an init function now that theres a real class, and then change `Highcharts.StockChart` to the class?

2021-03-02 08:28 UTC, bre1470 commented on ts/Core/Chart/StockChart.ts
> +H.StockChart = StockChart;
This should be moved to the master file for stock (modules/stock). All files except masters have to work without Highcharts namespace and automatic modifications to become compatible with ES6 tree shaking (async). And it is okay to have any casts in the master file. No need to define the namespace there.

2021-03-02 10:02 UTC, bre1470 commented on ts/masters/modules/stock.src.ts
> +import Highcharts from '../highcharts.src.js';
That needs to be taken from `'../../Core/Globals.js'` otherwise it bloats the product size.

2021-03-03 14:34 UTC, TorsteinHonsi approved these changes

2021-03-03 14:34 UTC, merged

2021-03-10 14:48 UTC, pawelfus commented
`xAxis.type` still fails: https://jsfiddle.net/BlackLabel/g7cfja6q/
Related ticket: https://github.com/highcharts/highcharts/issues/8603 

@khlieng