bugfix/15029-LastPrice-stockTools-functionality
highcharts/highcharts pull request #15208
Opened 2021-02-23 14:41 UTC by karolkolodziej

Fixed #15029, improved `currentPriceIndicator` button functionality.

2021-02-23 14:58 UTC, circleci-mu commented
### File size comparison
No differences found

2021-02-23 15:02 UTC, circleci-mu commented
## Visual test results - No difference found

2021-02-25 11:00 UTC, raf18seb requested changes

2021-02-25 12:06 UTC, pawellysy requested changes
Overall good, see comments :)

2021-02-25 12:06 UTC, pawellysy commented on ts/Stock/StockToolsGui.ts
> +                priceIndicatorEnabled = 'bothDisabled';
Having the boolean variable stored as a string seems a bit strange for me. A better way would be creating some kind of enum, where all options are available, which would prevent us from making some typos. If there are only 2 possibilities, the obvious choice seems `boolean`.

2021-02-25 14:50 UTC, pawellysy approved these changes
Looks Good!

2021-03-01 14:26 UTC, pawelfus requested changes
See comments below

2021-03-01 14:26 UTC, pawelfus commented on ts/Stock/StockToolsGui.ts
> +        });
This `forEach` in fact is testing only the last series. No matter what we decide for the first series, the last one can define `priceIndicatorEnabled` according to its own internal options.

For example, the first series has `lastPrice` enabled and it's setting `priceIndicatorEnabled` to true. Then the last series has both options disabled, resulting in `priceIndicatorEnabled = false`. If we reverse the series order, then we will always receive `priceIndicatorEnabled=true`, no matter what was set in the first series.

2021-03-01 14:26 UTC, pawelfus commented on ts/Stock/StockToolsBindings.ts
> +                priceIndicatorEnabled = chart.stockTools && chart.stockTools.priceIndicatorEnabled,
Question: Is it safe to store this as a property? Can something change the button state, so we should check it on demand (`isPriceIndicatorEnabled(..)`)? For example on series add/remove?

2021-03-02 15:12 UTC, pawelfus requested changes

2021-03-02 15:12 UTC, pawelfus commented on ts/Stock/StockToolsBindings.ts
> +                priceIndicatorEnabled = chart.stockTools && chart.stockTools.priceIndicatorEnabled,
I still have a small problem with storing `priceIndicatorEnabled` variable in `stockTools`. It is a bit bloating the properties, that are related to the tools in general (HTML references, options, chart references etc.). A property specific to just one button.

Can we go for now with the function call in both places? Upon `chart.render` event and here, when clicking on a button. So below would be changed from:

```js
if (priceIndicatorEnabled) {
  ...
}
```
to:
```js
if (chart.stockTools.isPriceIndicatorEnabled(series)) {
 ...
}
```

Or even better, store `isPriceIndicatorEnabled` in `bindingsUtils`, and use it:
```js
if (bindingsUtils.isPriceIndicatorEnabled(series)) {
 ...
}
```

What do you think?

2021-03-03 13:01 UTC, pawelfus requested changes
Just a minor clean up :)

2021-03-03 13:01 UTC, pawelfus commented on ts/Stock/StockToolsBindings.ts
> +                        }, false);
Q: Would that make sense to store `bindingsUtils.isPriceIndicatorEnabled(chart.series)` in a local variable? Then we could simplify this long if-else to:

```js
const priceIndicatorEnabled = bindingsUtils.isPriceIndicatorEnabled(chart.series);

if (gui && gui.guiEnabled && chart.stockTools) {
  series.forEach(function (series): void {
    series.update({
      lastPrice: { enabled: !priceIndicatorEnabled },
      lastVisiblePrice: { enabled: !priceIndicatorEnabled, label: { enabled: true } }
    }, false);
  });
}
```

2021-03-03 13:34 UTC, raf18seb requested changes

2021-03-03 13:34 UTC, raf18seb commented on ts/Extensions/Annotations/NavigationBindings.ts
> +            chart.stockTools.toolbar.querySelector('.highcharts-current-price-indicator');
You can use only `stockTools` variable instead of `chart.stockTools`

2021-03-03 13:34 UTC, raf18seb commented on ts/Extensions/Annotations/NavigationBindings.ts
> +addEvent(H.Chart, 'render', function (): void {
It would be nice to comment why this event is added or at least add a comment with a related ticket number only. Might be useful in the future

2021-03-03 13:34 UTC, raf18seb commented on ts/Extensions/Annotations/NavigationBindings.ts
> +            (button as any).firstChild.style['background-image'] =
Nothing big, but you could declare the variable like this
```js
button = chart.stockTools &&
            chart.stockTools.toolbar &&
            (chart.stockTools.toolbar.querySelector('.highcharts-current-price-indicator') as any).firstChild;
```
and use a shorter version
```js
button.style['background-image'] = ...
```

2021-03-03 13:34 UTC, raf18seb commented on ts/Stock/StockToolsBindings.ts
> +                gui: Highcharts.Toolbar = chart.stockTools as any;
Hmm, I'm not a TypeScript ninja, but is everything ok with this line?

2021-03-03 13:34 UTC, raf18seb commented on ts/Stock/StockToolsBindings.ts
> +                if (bindingsUtils.isPriceIndicatorEnabled(chart.series)) {
You have already declared `var series = chart.series` so use a variable instead

2021-03-05 11:31 UTC, raf18seb approved these changes
Thanks 👍

2021-03-08 11:48 UTC, pawelfus approved these changes
Approved! 👍

2021-03-09 11:33 UTC, TorsteinHonsi approved these changes
Thanks!

2021-03-09 11:33 UTC, merged