Fixed #15245 Added documentation & sample for xAxis.labels.allowOverlap
highcharts/highcharts pull request #15262
Opened 2021-03-04 12:40 UTC by melanki

https://github.com/highcharts/highcharts/issues/15245

Added API documentation for `xAxis.labels.allowOverlap`
Added sample _samples/highcharts/xaxis/labels-allowoverlap-true/_

2021-03-04 13:10 UTC, circleci-mu commented
### File size comparison
No differences found

2021-03-04 13:13 UTC, circleci-mu commented
## Visual test results - No difference found

---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  Added | samples/highcharts/xaxis/labels-allowoverlap-true/demo.js |

</p>
</details>

2021-03-04 13:15 UTC, khlieng commented
I think thats the first forward tick in the codebase, should probably be `'` :)

2021-03-04 13:25 UTC, melanki commented
@khlieng All good things are three? Got the right tick this time

2021-03-04 13:29 UTC, khlieng commented
Yes, nice!

2021-03-05 10:42 UTC, TorsteinHonsi requested changes
Thanks for the PR! Please see the inline comments.

2021-03-05 10:42 UTC, TorsteinHonsi commented on samples/highcharts/xaxis/labels-allowoverlap-true/demo.details
> +   - Torstein Hønsi
No

2021-03-05 10:42 UTC, TorsteinHonsi commented on samples/highcharts/xaxis/labels-allowoverlap-true/demo.html
> +<div id="container" style="height: 400px"></div>
Better add `demo.css` and do styling there.

2021-03-05 10:42 UTC, TorsteinHonsi commented on ts/Core/Axis/Axis.ts
> +             * Whether to allow the axis's labels to overlap
... the axis labels to ...

2021-03-05 10:42 UTC, TorsteinHonsi commented on ts/Core/Axis/Axis.ts
> +             * Whether to allow the axis's labels to overlap
And maybe elaborate: "When `false`, overlapping labels are hidden."

2021-03-08 14:48 UTC, TorsteinHonsi requested changes
Seems one of my comments from last time wasn't posted. The `demo.js` file doesn't lint because of inconsistent indentation and line max-len. It should have been caught in the pre-commit validation, did you commit with `--no-verify`?

2021-03-11 09:56 UTC, TorsteinHonsi approved these changes
Thanks!

2021-03-11 09:56 UTC, merged