bugfix/10464-boost-halo-axis-pos
highcharts/highcharts pull request #15376
Opened 2021-03-23 08:37 UTC by khlieng

Fixed #10464, halo position was wrong when using boost with multiple axes.

2021-03-23 08:54 UTC, circleci-mu commented
### File size comparison
No differences found

2021-03-23 08:57 UTC, circleci-mu commented
## Visual test results - No difference found

2021-03-23 10:35 UTC, TorsteinHonsi commented
What is the root cause of the problem? Is it that the marker group wasn't translated properly in the first place? Or is it that we have only one chart-level marker group versus the normal series-level marker group?

Can we fix the root cause so we don't have to do the translation twice?

If not, please add a verbose comment to explain the situation.

2021-03-23 10:36 UTC, TorsteinHonsi requested changes
What is the root cause of the problem? Is it that the marker group wasn't translated properly in the first place? Or is it that we have only one chart-level marker group versus the normal series-level marker group?

Can we fix the root cause so we don't have to do the translation twice?

If not, please add a verbose comment to explain the situation.

2021-03-23 10:52 UTC, khlieng commented
Its because of only one chart-level group.

2021-03-23 12:14 UTC, TorsteinHonsi requested changes
> If not, please add a verbose comment to explain the situation.

... and add a reference to the issue number, so future us can understand what this peculiar code does.

2021-03-25 10:08 UTC, TorsteinHonsi approved these changes

2021-03-25 10:08 UTC, merged