Demo/blog landing page
highcharts/highcharts pull request #15402
Opened 2021-03-25 11:37 UTC by nasin

Hi, Marketing requested that I remove the grayscale filter from the graphs.

2021-03-25 11:53 UTC, circleci-mu commented
### File size comparison
No differences found

2021-03-25 11:55 UTC, circleci-mu commented
## Visual test results - No difference found

---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  Modified | samples/highcharts/blog/blog-update-options/demo.js |
|  Modified | samples/highcharts/blog/blog-update-options/demo.js |
|  Modified | samples/highcharts/blog/blog-update-options/demo.js |
|  Added | samples/highcharts/blog/blog-update-options/demo.js |
|  Modified | samples/highcharts/blog/blog-landing-page/demo.js |
|  Deleted | samples/highcharts/blog/nw-landing-page/demo.js |
|  Added | samples/highcharts/blog/blog-landing-page/demo.js |
|  Modified | samples/highcharts/blog/nw-landing-page/demo.js |
|  Modified | samples/highcharts/blog/nw-landing-page/demo.js |
|  Added | samples/highcharts/blog/nw-landing-page/demo.js |

</p>
</details>

2021-03-26 11:56 UTC, TorsteinHonsi requested changes
It seems that #15365 and #15402 both contain (more or less) the same changes for the same files. Please make sure that the PRs don't interfere with each other. New PRs should be forked from the master branch, not a PR branch.

For this PR, I think only the removal of the grayscale filter really belongs here. Since this is a minor change, the fastest solution may be just to delete this PR and continue with #15365 that already contains the removal of the grayscale.

2021-03-26 13:00 UTC, nasin commented
Ok, thanks. I'll do that.

2021-03-26 23:28 UTC, nasin commented
Closing this because changes are already included in an existing PR.

2021-03-26 23:28 UTC, closed without merging