Bugfix/15157-stocktools-replace-colors-with-hex
highcharts/highcharts pull request #15425
Opened 2021-03-30 13:48 UTC by pawellysy

Fixed #15157, Replaced the hex, and string colors in the stock tools with the colors defined in the palette.

2021-03-30 14:02 UTC, circleci-mu commented
### File size comparison
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts | 283.6 kB | 283.5 kB | -16 B |
| highcharts, gzipped | 95.9 kB | 95.9 kB | -9 B|
| highstock | 375.8 kB | 375.8 kB | -16 B |
| highstock, gzipped | 125.7 kB | 125.7 kB | -11 B|
| highmaps | 341.5 kB | 341.4 kB | -16 B |
| highmaps, gzipped | 112.6 kB | 112.6 kB | -9 B|
| highcharts-gantt | 390.2 kB | 390.2 kB | -16 B |
| highcharts-gantt, gzipped | 130.0 kB | 130.0 kB | -12 B|

2021-04-01 08:57 UTC, karolkolodziej approved these changes

2021-04-01 12:24 UTC, pawelfus approved these changes
I'm not sure about the changes in gulptasks (I assume it was broken for a while?), but all others look good, thanks! 👍

2021-04-02 14:54 UTC, pawellysy commented
> I'm not sure about the changes in gulptasks (I assume it was broken for a while?), but all others look good, thanks! 👍

@bre1470 asked me to fix it right away, so I decided to add it in here as well.

2021-04-03 13:35 UTC, bre1470 approved these changes

2021-04-06 09:19 UTC, TorsteinHonsi reviewed
Awesome! Pending @raf18seb 's approval.

2021-04-06 09:35 UTC, raf18seb approved these changes
I am good with the above changes, good job 👍 
Only one thing comes to my mind - should it be a part of this ticket? Positive and negative indicators' lines color
https://github.com/highcharts/highcharts/blob/master/ts/Stock/Indicators/DMI/DMIIndicator.ts#L99-L135

2021-04-06 10:00 UTC, pawellysy commented
> I am good with the above changes, good job 👍
> Only one thing comes to my mind - should it be a part of this ticket? Positive and negative indicators' lines color
> https://github.com/highcharts/highcharts/blob/master/ts/Stock/Indicators/DMI/DMIIndicator.ts#L99-L135

I didn't notice this part doing this minor refactoring, but I guess I can replace it right away 👍

2021-04-06 10:19 UTC, raf18seb requested changes
See above comments

2021-04-06 11:09 UTC, raf18seb approved these changes

2021-04-08 07:57 UTC, TorsteinHonsi requested changes
Thanks! Two things remaining:
- Someone approve of the visual diff
- Fix the failure in CI tests for Safari

2021-04-09 08:44 UTC, TorsteinHonsi approved these changes

2021-04-09 08:44 UTC, merged