Fixed #15416, #15413, heatmap kbd nav issues.
highcharts/highcharts pull request #15482
Opened 2021-04-09 13:00 UTC by oysteinmoseng

Fixed #15416, #15413, heatmap kbd nav issues.
___
Two issues at play here, one being that `setState` in colorMap-series alters the z-index of the point, causing elements to lose focus. This is solved now by adding an event listener in the a11y module that reapplies focus after `setState` when relevant. This required some refactoring of how `setState` is handled in colorMap-series.

The other issue was related to the first one, but dealt with the auto-init of the first keyboard nav module when the container receives focus. This should not happen when exiting the chart, but is only an issue in combination with the z-index problem, since the focus is lost when the module inits.

2021-04-09 13:15 UTC, circleci-mu commented
### File size comparison
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts | 284.0 kB | 284.0 kB | 10 B |
| highcharts, gzipped | 96.1 kB | 96.1 kB | 1 B|
| highstock | 376.2 kB | 376.2 kB | 10 B |
| highstock, gzipped | 125.8 kB | 125.9 kB | 45 B|
| highmaps | 341.9 kB | 342.0 kB | 94 B |
| highmaps, gzipped | 112.8 kB | 112.8 kB | 27 B|
| highcharts-gantt | 390.6 kB | 390.6 kB | 10 B |
| highcharts-gantt, gzipped | 130.2 kB | 130.2 kB | -89 B|

2021-04-09 13:17 UTC, circleci-mu commented
## Visual test results - Differences found
Found **1** diffing sample(s). [Please review the differences.](https://vrevs.highsoft.com/pr/15482/review)

2021-04-12 09:54 UTC, TorsteinHonsi requested changes
Thanks! We just need a little more verbose description for the changelog, otherwise approved.

2021-04-12 09:57 UTC, oysteinmoseng commented
Edited - should ideally be two entries in the changelog perhaps?

2021-04-12 10:00 UTC, TorsteinHonsi approved these changes
Nah, that's fine!

2021-04-12 10:00 UTC, merged