Bugfix/13847-datalabels-in-navigator
highcharts/highcharts pull request #15564
Opened 2021-04-22 15:33 UTC by pawellysy

Fixed #13847, DataLabels in navigator should be disabled in the default configuration.

2021-04-22 15:53 UTC, circleci-mu commented
### File size comparison
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highstock | 377.3 kB | 377.3 kB | 29 B |
| highstock, gzipped | 126.3 kB | 126.4 kB | 23 B|
| highcharts-gantt | 391.6 kB | 391.7 kB | 29 B |
| highcharts-gantt, gzipped | 130.4 kB | 130.4 kB | 10 B|

2021-04-22 15:55 UTC, circleci-mu commented
## Visual test results - No difference found

2021-04-23 07:50 UTC, karolkolodziej requested changes

2021-04-23 07:50 UTC, karolkolodziej commented on ts/Core/Navigator.ts
> +                userNavOptions.dataLabels = splat(userNavOptions.dataLabels);
Please add a comment with the issue number here.

2021-04-23 07:50 UTC, karolkolodziej commented on samples/unit-tests/navigator/navigator/demo.js
> +        plotOptions: {
If you have only one series there is no need to declare the `plotOptions`. Simply add that config in the `series`.

2021-04-23 07:50 UTC, karolkolodziej commented on samples/unit-tests/navigator/navigator/demo.js
> +                    enabled: true
I would change here to `false`.
Now it doesn't change anything in the chart config, so it's hard to test if this update is performed properly.

2021-04-23 07:50 UTC, karolkolodziej commented on samples/unit-tests/navigator/navigator/demo.js
> +        true,
`false` as a consequence of the comment above

2021-04-23 11:22 UTC, karolkolodziej approved these changes
Greate!

2021-04-23 11:30 UTC, raf18seb approved these changes
One small typo. Except that everything looks great!

2021-04-23 11:30 UTC, raf18seb commented on ts/Core/Navigator.ts
> +                // if the settings are and array, #13847.
Typo "and" here. Maybe
```The dataLabels config is not merged correctly when provided in an array, #13847.```

2021-04-23 11:48 UTC, pawelfus approved these changes
Nice!

2021-04-26 13:24 UTC, TorsteinHonsi approved these changes

2021-04-26 13:25 UTC, merged