ts/migration-time
highcharts/highcharts pull request #15584
Opened 2021-04-27 10:05 UTC by marvin19

Migration: Removed internal namespace from time.ts

2021-04-27 10:20 UTC, circleci-mu commented
### File size comparison
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts | 285.4 kB | 285.4 kB | 3 B |
| highcharts, gzipped | 96.5 kB | 96.4 kB | -60 B|
| highstock | 378.9 kB | 378.9 kB | 3 B |
| highstock, gzipped | 126.9 kB | 126.9 kB | -4 B|
| highmaps | 343.5 kB | 343.5 kB | 3 B |
| highmaps, gzipped | 113.0 kB | 113.0 kB | 0 B|
| highcharts-gantt | 392.1 kB | 392.1 kB | 3 B |
| highcharts-gantt, gzipped | 130.8 kB | 130.8 kB | 4 B|

2021-04-27 10:23 UTC, circleci-mu commented
## Visual test results - No difference found

2021-04-27 13:21 UTC, bre1470 requested changes
Looks good! Some smaller things need to be addressed.

2021-04-27 13:21 UTC, bre1470 commented on ts/Core/Axis/DateTimeAxis.ts
> +}
This should be part of the TickPositionsArray file, because it is the essential definition of the type.

2021-04-27 13:21 UTC, bre1470 commented on ts/Core/Globals.ts
> +    }
No more `any` types in Globals (only `AnyRecord`). Delete this interface definition and cast the `win`/`window` object to `AnyRecord`, if the code access the `moment` or `Date` properties in an unsafe way.

2021-05-03 13:05 UTC, bre1470 approved these changes
Thank you! Looks good. 👍

2021-05-05 07:13 UTC, TorsteinHonsi approved these changes

2021-05-05 07:13 UTC, merged