ts/utilities-migration
highcharts/highcharts pull request #15597
Opened 2021-04-28 10:56 UTC by marvin19

Removed Highcharts namespace from Utilities.

2021-04-28 11:11 UTC, circleci-mu commented
### File size comparison
No differences found

2021-04-28 11:13 UTC, circleci-mu commented
## Visual test results - No difference found

2021-04-28 12:06 UTC, bre1470 requested changes

2021-04-28 12:06 UTC, bre1470 commented on ts/Core/FormatUtilities.ts
> +    }
This name can be simplified to `FormatCallback`.

2021-04-28 12:06 UTC, bre1470 commented on ts/Core/Utilities.ts
> +    }
This name can be simplified to `ObjectEachCallback`.

2021-04-30 12:05 UTC, bre1470 approved these changes
Thank you! Looks good. 👍

2021-05-04 13:21 UTC, TorsteinHonsi approved these changes

2021-05-04 13:21 UTC, merged