docs/15583-useohlcdata-demo-issues
highcharts/highcharts pull request #15703
Opened 2021-05-11 15:22 UTC by pawellysy

Fixed #15583, improved series.useOhlcData demo.

2021-05-11 15:38 UTC, circleci-mu commented
### File size comparison
No differences found

2021-05-12 07:27 UTC, TorsteinHonsi requested changes

2021-05-12 07:27 UTC, TorsteinHonsi commented on samples/stock/indicators/use-ohlc-data/demo.js
> +            text: 'Plot line on Y axis'
Why the text change? This sample actually doesn't have a plot line on the Y axis, and judging from the sample name and the docs, the purpose of the sample seems to be to demonstrate how to use OHLC data in a line  🤔  

https://github.com/highcharts/highcharts/blob/e2c54070667b7ce3427fb0155e23a8d293bcb79f/ts/Stock/Indicators/SMA/SMAIndicator.ts#L91-L92

2021-05-12 08:43 UTC, pawelfus requested changes
See Torstein's comment. The demo has a right name, but the name in docs is incorrect :)

2021-05-17 10:19 UTC, pawelfus approved these changes
Approved 👍

2021-05-19 12:22 UTC, karolkolodziej approved these changes

2021-05-21 07:41 UTC, raf18seb approved these changes

2021-05-21 08:50 UTC, TorsteinHonsi approved these changes

2021-05-21 08:50 UTC, merged