bugfix/15639-plotlinesAndBands-console-error
highcharts/highcharts pull request #15705
Opened 2021-05-12 08:07 UTC by DJTechnoo

Fixed #15639, error when calling `removePlotBand` after destroying `Axis`.

2021-05-12 08:24 UTC, circleci-mu commented
### File size comparison
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts | 288.8 kB | 288.8 kB | 9 B |
| highcharts, gzipped | 97.2 kB | 97.2 kB | -6 B|
| highstock | 382.7 kB | 382.7 kB | 9 B |
| highstock, gzipped | 127.6 kB | 127.6 kB | -1 B|
| highmaps | 346.9 kB | 346.9 kB | 9 B |
| highmaps, gzipped | 114.0 kB | 114.0 kB | -2 B|
| highcharts-gantt | 395.9 kB | 395.9 kB | 9 B |
| highcharts-gantt, gzipped | 131.7 kB | 131.8 kB | 51 B|

2021-05-12 08:26 UTC, circleci-mu commented
## Visual test results - No difference found

2021-05-12 10:38 UTC, TorsteinHonsi requested changes
Nice, thanks!

Can you also add a unit test? Should be sufficient to add `axis.destroy` then `removePlotBand` at the end of an existing test.

Also, while working on this part of the code, it's a nice opportunity to resolve `const` vs `let` inside the `removePlotBandOrLine` function.

2021-05-18 07:27 UTC, DJTechnoo commented
Unit test is still pending

2021-05-28 12:18 UTC, TorsteinHonsi approved these changes

2021-05-28 12:18 UTC, merged