bugfix/15729-annotation-drag-selected
highcharts/highcharts pull request #15748
Opened 2021-05-19 11:05 UTC by khlieng

Fixed #15729, annotation did not stay selected after dragging.

2021-05-19 11:20 UTC, circleci-mu commented
### File size comparison
No differences found

2021-05-19 11:22 UTC, circleci-mu commented
## Visual test results - No difference found

2021-05-19 12:57 UTC, pawelfus requested changes
See: https://github.com/highcharts/highcharts/pull/15738#pullrequestreview-662251718

2021-05-21 09:00 UTC, khlieng commented
@pawelfus should it also stay selected after dragging a control point?

2021-05-26 08:53 UTC, pawelfus commented
> @pawelfus should it also stay selected after dragging a control point?

Yes, it should, nice catch!

2021-07-05 15:56 UTC, pawelfus requested changes

2021-07-05 15:56 UTC, pawelfus commented on ts/Extensions/Annotations/NavigationBindings.ts
> +                }, 0);
Could you add an explanation (a comment) why we need to use `setTimeout()` here? The idea of this block was to simply close popup and deselect the annotation. Then, if any button is selected, start drawing a new annotation.

2021-07-12 09:31 UTC, pawelfus approved these changes

2021-08-13 07:15 UTC, TorsteinHonsi approved these changes

2021-08-13 07:16 UTC, merged