bugfix/15726-annotation-rect-clip
highcharts/highcharts pull request #15750
Opened 2021-05-19 11:33 UTC by khlieng

Fixed #15726, rectangle annotations were not clipped.

2021-05-19 12:08 UTC, circleci-mu commented
### File size comparison
No differences found

2021-05-19 12:10 UTC, circleci-mu commented
## Visual test results - No difference found

2021-05-19 13:03 UTC, pawelfus requested changes
Looks good, but the test is missing

2021-06-18 07:20 UTC, TorsteinHonsi approved these changes
Looks good to me, pending approval by @pawelfus

2021-06-30 13:11 UTC, pawelfus approved these changes

2021-07-05 12:31 UTC, merged