Expose Point.doDrilldown
highcharts/highcharts pull request #15856
Opened 2021-06-08 09:29 UTC by TorsteinHonsi

Exposed a simplified version of `doDrilldown`, and renamed the internal function to `runDrilldown`.

2021-06-08 09:45 UTC, pawelfus requested changes
It would be nice to have a demo like other API functions have (`sth.update()`, `Axis.addPlotLine()` etc)

Extra question:
I don't see support for multi-drilldown, for example drilling down two points at the same time (like drilldown to a category). I would expect something like this:
```js
series_1.points[0].doDrilldown(false);
series_2.points[0].doDrilldown(true); // redraw=true ?
```

2021-06-08 09:45 UTC, circleci-mu commented
## Visual test results - No difference found

2021-06-08 12:17 UTC, TorsteinHonsi commented
Thanks for the review! Will add a sample. 

> I don't see support for multi-drilldown, for example drilling down two points at the same time (like drilldown to a category)

The `redraw` parameter of `doDrilldown` doesn't quite work that way. Instead, there's a separate `Axis.prototype.drilldownCategory` function that does what you say. I will expose that too, and tie them together with `@see` tags.

2021-06-09 10:45 UTC, pawelfus approved these changes
Thanks!

2021-06-09 10:55 UTC, merged