Migration: Point
highcharts/highcharts pull request #15888
Opened 2021-06-11 08:51 UTC by marvin19

Removed Highcharts namespaces from Point.

2021-06-11 09:08 UTC, circleci-mu commented
### File size comparison
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts | 290.2 kB | 290.2 kB | -12 B |
| highcharts, gzipped | 97.5 kB | 97.6 kB | 85 B|
| highstock | 385.7 kB | 385.7 kB | -4 B |
| highstock, gzipped | 128.4 kB | 128.3 kB | -88 B|
| highmaps | 348.5 kB | 348.5 kB | -5 B |
| highmaps, gzipped | 114.1 kB | 114.3 kB | 141 B|
| highcharts-gantt | 397.6 kB | 397.6 kB | -4 B |
| highcharts-gantt, gzipped | 132.2 kB | 132.1 kB | -52 B|

2021-06-11 09:11 UTC, circleci-mu commented
## Visual test results - No difference found

2021-06-11 12:33 UTC, bre1470 approved these changes
Thanks! Looks good. 👍

2021-06-11 12:35 UTC, bre1470 requested changes
API declarations (doclets) should be moved under the default export.

2021-06-14 10:55 UTC, bre1470 approved these changes

2021-06-17 08:39 UTC, TorsteinHonsi approved these changes

2021-06-17 08:39 UTC, merged