Migration: Tooltip
highcharts/highcharts pull request #15887
Opened 2021-06-11 07:28 UTC by marvin19

Removed Highcharts namespace from Tooltip.

2021-06-11 07:45 UTC, circleci-mu commented
### File size comparison
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts | 290.2 kB | 290.2 kB | -5 B |
| highcharts, gzipped | 97.5 kB | 97.5 kB | 43 B|
| highstock | 385.7 kB | 385.7 kB | -5 B |
| highstock, gzipped | 128.4 kB | 128.3 kB | -42 B|
| highmaps | 348.5 kB | 348.5 kB | -3 B |
| highmaps, gzipped | 114.1 kB | 114.3 kB | 191 B|
| highcharts-gantt | 397.6 kB | 397.6 kB | 3 B |
| highcharts-gantt, gzipped | 132.2 kB | 132.1 kB | -91 B|

2021-06-11 07:47 UTC, circleci-mu commented
## Visual test results - No difference found

2021-06-11 12:30 UTC, bre1470 commented on ts/Core/Tooltip.ts
>   *
The API Declarations should be moved below the default export, followed by an `('');`, to reduce distraction.

2021-06-14 10:51 UTC, bre1470 approved these changes
Thank you! Looks good. 👍

2021-06-17 08:41 UTC, TorsteinHonsi requested changes
Thank you! Please resolve conflict, otherwise approved.

2021-06-21 07:02 UTC, TorsteinHonsi approved these changes

2021-06-21 07:02 UTC, merged