bugfix/15896-gantt-scrollbar
highcharts/highcharts pull request #15898
Opened 2021-06-14 08:09 UTC by khlieng

Fixed #15896, scrollbar did not work with gantt.

2021-06-14 08:27 UTC, circleci-mu commented
### File size comparison
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highstock | 385.7 kB | 385.7 kB | 13 B |
| highstock, gzipped | 128.4 kB | 128.5 kB | 70 B|
| highcharts-gantt | 397.6 kB | 397.7 kB | 70 B |
| highcharts-gantt, gzipped | 132.2 kB | 132.2 kB | 20 B|

2021-06-14 08:29 UTC, circleci-mu commented
## Visual test results - No difference found

2021-06-14 10:58 UTC, bre1470 commented on ts/masters/modules/stock.src.ts
> -Scrollbar.compose(G.Axis);
The order should not be important for the composition here. (= compositions usually come last, after all namespace assignments) Was something failing?

2021-06-14 10:59 UTC, bre1470 approved these changes

2021-06-14 11:01 UTC, bre1470 requested changes
Wait a second. The change means, that composition has no detection agains running twice. This should be fixed with a private array in the compose function, taking all modified axis class and then next time check, if the array already contains the axis class to modify.

2021-06-14 11:50 UTC, khlieng commented
> Wait a second. The change means, that the composition has no detection agains running twice. This should be fixed with a private array in the compose function, taking all modified axis class and then next time check, if the array already contains the axis class to modify.

Doesnt the `if (!G.Scrollbar)` handle that?

2021-06-15 10:57 UTC, TorsteinHonsi approved these changes
Thanks!

2021-06-15 10:58 UTC, TorsteinHonsi requested changes
Pending bre1420's comment

2021-06-15 11:17 UTC, bre1470 commented
Without fixing the composition only the master is compatible to tree shaking. If a user calls the composition in a ES6 module it has not protection agains double modification. (which triggers the bug)

2021-06-15 12:03 UTC, bre1470 approved these changes
Thank you! Looks good. 👍

2021-06-17 09:20 UTC, TorsteinHonsi approved these changes

2021-06-17 09:20 UTC, merged