Migration: Series
highcharts/highcharts pull request #15908
Opened 2021-06-15 17:32 UTC by marvin19

Removed Highcharts namespace.

2021-06-15 17:46 UTC, circleci-mu commented
### File size comparison
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts | 290.2 kB | 290.2 kB | -22 B |
| highcharts, gzipped | 97.5 kB | 97.5 kB | 6 B|
| highstock | 385.7 kB | 385.6 kB | -20 B |
| highstock, gzipped | 128.4 kB | 128.3 kB | -38 B|
| highmaps | 348.5 kB | 348.5 kB | -19 B |
| highmaps, gzipped | 114.1 kB | 114.2 kB | 29 B|
| highcharts-gantt | 397.6 kB | 397.6 kB | -22 B |
| highcharts-gantt, gzipped | 132.2 kB | 132.1 kB | -45 B|

2021-06-15 20:27 UTC, bre1470 requested changes

2021-06-15 20:27 UTC, bre1470 commented on ts/Core/Axis/DateTimeAxis.ts
>      }
Please move type `PointIntervalUnitValue` to the class namespace of `DateTimeAxis`. It was a mistake to have it declared in the series file.

2021-06-16 10:09 UTC, bre1470 approved these changes
Thank you! Looks good. 👍

2021-06-17 08:38 UTC, TorsteinHonsi approved these changes
Thanks!

2021-06-17 08:38 UTC, merged