Migration: PieSeries
highcharts/highcharts pull request #15932
Opened 2021-06-18 09:12 UTC by marvin19

Improved let and const.

2021-06-18 09:29 UTC, circleci-mu commented
### File size comparison
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highstock | 386.5 kB | 386.5 kB | -3 B |
| highstock, gzipped | 128.7 kB | 128.7 kB | -31 B|

2021-06-18 09:32 UTC, circleci-mu commented
## Visual test results - No difference found

2021-06-18 12:20 UTC, bre1470 approved these changes
Thank you! Looks good. 👍

2021-06-21 07:03 UTC, TorsteinHonsi requested changes
Please resolve conflict, otherwise good 👍

2021-06-22 10:05 UTC, TorsteinHonsi approved these changes

2021-06-22 10:05 UTC, merged