bugfix/16004-shared-tooltip-multiple-axes
highcharts/highcharts pull request #16005
Opened 2021-07-07 11:14 UTC by khlieng

Fixed #16004, shared tooltip did not show for some axes with multiple differently positioned axes.

2021-07-07 11:29 UTC, circleci-mu commented
### File size comparison
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts | 291.2 kB | 291.3 kB | 81 B |
| highcharts, gzipped | 97.8 kB | 97.8 kB | 21 B|
| highstock | 387.4 kB | 387.5 kB | 81 B |
| highstock, gzipped | 129.1 kB | 129.1 kB | -3 B|
| highmaps | 349.7 kB | 349.8 kB | 81 B |
| highmaps, gzipped | 114.8 kB | 114.8 kB | 48 B|
| highcharts-gantt | 398.8 kB | 398.8 kB | 82 B |
| highcharts-gantt, gzipped | 132.4 kB | 132.5 kB | 88 B|

2021-07-07 11:31 UTC, circleci-mu commented
## Visual test results - No difference found

2021-08-31 13:39 UTC, raf18seb commented
@TorsteinHonsi the users are reporting this issue on different support channels, so it would be great to push it if possible

2021-09-01 07:26 UTC, TorsteinHonsi requested changes
In addition to the inline comment, please set up a test.

2021-09-01 07:26 UTC, TorsteinHonsi commented on ts/Core/Tooltip.ts
> +                            currentSeries.shouldShowTooltip(checkX, checkY) :
Can we optimize this by always going the `points.some` route? In other words, are there any cases where `points.length === 1` and `currentSeries` is not the same as `points[0].series`?

2021-09-01 09:07 UTC, TorsteinHonsi approved these changes

2021-09-01 09:07 UTC, merged