Migration: OfflineExporting
highcharts/highcharts pull request #16034
Opened 2021-07-13 08:36 UTC by marvin19

Improved OfflineExporting.

2021-07-13 08:55 UTC, circleci-mu commented
### File size comparison
No differences found

2021-07-13 08:57 UTC, circleci-mu commented
## Visual test results - No difference found

2021-07-13 11:13 UTC, bre1470 requested changes

2021-07-13 11:13 UTC, bre1470 commented on ts/Core/Globals.ts
> +    }
This should go into the Vendor declarations too.

2021-07-13 11:13 UTC, bre1470 commented on ts/Core/Globals.ts
> +
Double space.

2021-07-13 11:13 UTC, bre1470 commented on ts/Extensions/OfflineExporting/OfflineExporting.ts
> +
`'use strict';` missing

2021-07-13 11:13 UTC, bre1470 commented on ts/Extensions/OfflineExporting/OfflineExporting.ts
> +    export function compose<T extends typeof Chart>(
Doclets without space. Section comments with space.

2021-07-13 11:13 UTC, bre1470 commented on ts/masters/modules/exporting.src.ts
> +OfflineExporting.compose(G.Chart);
Offline exporting is not part of exporting.

2021-07-14 12:06 UTC, bre1470 approved these changes
Thank you! Looks good. 👍

2021-08-13 07:41 UTC, TorsteinHonsi approved these changes

2021-08-13 07:41 UTC, merged