enhancement/15892-idicator-order-in-series
highcharts/highcharts pull request #16077
Opened 2021-07-19 15:01 UTC by karolkolodziej

Enhancement #15892, declaring the indicator before the main series was not possible.

2021-07-19 15:17 UTC, circleci-mu commented
### File size comparison
No differences found

2021-07-19 15:20 UTC, circleci-mu commented
## Visual test results - Differences found
Found **2** diffing sample(s). [Please review the differences.](https://vrevs.highsoft.com/pr/16077/review)

2021-07-20 11:20 UTC, pawelfus requested changes

2021-07-20 11:20 UTC, pawelfus commented on ts/Stock/Indicators/SMA/SMAIndicator.ts
> +import Chart from '../../../Core/Chart/Chart.js';
Could you move this away from type imports? Simply move them to the other imports

2021-07-20 11:20 UTC, pawelfus commented on ts/Stock/Indicators/VBP/VBPIndicator.ts
> +        addEvent(StockChart, 'afterLinkSeries', function (): void {
Missing unbinder

2021-07-20 11:20 UTC, pawelfus commented on ts/Stock/Indicators/Supertrend/SupertrendIndicator.ts
> +        addEvent(StockChart, 'afterLinkSeries', function (): void {
Unbind missing

2021-07-21 11:32 UTC, pawelfus approved these changes
Looks good, thanks!

2021-07-22 10:57 UTC, raf18seb approved these changes

2021-07-23 09:44 UTC, pawellysy approved these changes
nothing to add 👍

2021-08-13 08:19 UTC, merged