bugfix/15867-multiline-indicator-compare
highcharts/highcharts pull request #16075
Opened 2021-07-19 13:32 UTC by karolkolodziej

Fixed #15867, comparing the indicator with multiple lines (eg Bollinger Bands) was not possible.

2021-07-19 13:58 UTC, circleci-mu commented
### File size comparison
No differences found

2021-07-19 14:44 UTC, pawelfus requested changes
Nice! Just the test is missing

2021-07-20 07:59 UTC, pawellysy approved these changes

2021-07-20 08:16 UTC, raf18seb approved these changes

2021-07-20 11:16 UTC, pawelfus approved these changes
Thanks!

2021-08-13 08:58 UTC, TorsteinHonsi approved these changes

2021-08-13 08:58 UTC, merged