docs/15851-multiple-lines-indicator-docs
highcharts/highcharts pull request #16127
Opened 2021-08-02 10:39 UTC by raf18seb

Docs #15851, added an additional section about custom multiple lines indicator to the general documentation article.

https://www.highcharts.com/docs/stock/custom-technical-indicators

2021-08-02 10:48 UTC, karolkolodziej requested changes

2021-08-02 10:48 UTC, karolkolodziej commented on docs/stock/custom-technical-indicators.md
> +A live demo of the above multiline indicator can be found [here](https://jsfiddle.net/BlackLabel/6ueky3x2).
Change the URL for the demo you've created :)

2021-08-02 10:56 UTC, circleci-mu commented
### File size comparison
No differences found

2021-08-02 10:58 UTC, circleci-mu commented
## Visual test results - No difference found

---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  Added | samples/stock/indicators/custom-regression-multiple-lines/demo.js |

</p>
</details>

2021-08-02 12:07 UTC, pawellysy approved these changes
Looks good!

2021-08-03 12:52 UTC, pawelfus approved these changes
Looks great (just replace the demo), thanks!

2021-08-13 09:19 UTC, merged