enhancement/15696-indicator-on-indicator
highcharts/highcharts pull request #16156
Opened 2021-08-06 08:41 UTC by karolkolodziej

Enhancement #15696, added the possibility to calculate indicators on the indicator.

2021-08-06 08:52 UTC, pawelfus requested changes
Looks good, just one thing: http://jsfiddle.net/BlackLabel/q5hreoLj/1/ - add SMA, then edit SMA -> now you can choose SMA as a base for itself

2021-08-06 08:57 UTC, circleci-mu commented
### File size comparison
No differences found

2021-08-06 09:00 UTC, circleci-mu commented
## Visual test results - No difference found

2021-08-06 11:26 UTC, raf18seb requested changes

2021-08-06 11:26 UTC, raf18seb commented on ts/Extensions/Annotations/Popup.ts
> +                seriesOptions = series.options as any;
You are casting the whole `seriesOptions` variable to `any`, but only `seriesOptions.params` is throwing an error (other `seriesOptions.name` or `seriesOptions.id` are fine.

I would think about how we can get rid of `as any` totally or at least cast to `any` only `options.params` , not the whole variable (like previously, before your changes).

2021-08-06 11:26 UTC, raf18seb commented on ts/Extensions/Annotations/Popup.ts
> +                        seriesOptions.name || seriesOptions.id || '';
Duplicated `seriesOptions.name`.

Isn't it better?:
```js
const seriesName = seriesOptions.name ||
    (seriesOptions as any).params ? series.name : seriesOptions.id || '';
```

2021-08-06 11:30 UTC, pawellysy approved these changes

2021-08-10 09:29 UTC, pawelfus approved these changes
Looks good, one question though ;)

2021-08-10 09:29 UTC, pawelfus commented on test/cypress/integration/Highcharts/stock-tools.spec.js
> +        });
Can we use `cy.chart().then(chart => chart.xAxis[0].setExtremes(...)`?

2021-08-10 09:32 UTC, pawelfus commented
Edit: http://jsfiddle.net/BlackLabel/q5hreoLj/1/ - is is something with my build or is it still broken @karolkolodziej

2021-08-10 10:56 UTC, karolkolodziej commented
I guess it might be something on your end...
Add:
![Screenshot 2021-08-10 at 11 59 13](https://user-images.githubusercontent.com/57004120/128855086-4541c7ee-dc10-4857-9e5b-011ad501bbc9.png)
Edit: 
![Screenshot 2021-08-10 at 11 59 22](https://user-images.githubusercontent.com/57004120/128855100-1d288a3f-781b-431e-9f3c-d6cf1dd61b36.png)

2021-08-11 16:29 UTC, raf18seb approved these changes
Thanks!

2021-08-13 09:17 UTC, TorsteinHonsi requested changes
All good, except please resolve the conflicts.

2021-09-06 11:03 UTC, TorsteinHonsi approved these changes

2021-09-06 11:04 UTC, merged