Migration: Announcer
highcharts/highcharts pull request #16178
Opened 2021-08-11 06:32 UTC by marvin19

Removed global namespace from Announcer.

2021-08-11 06:43 UTC, circleci-mu commented
## Visual test results - No difference found

2021-08-11 12:15 UTC, bre1470 requested changes

2021-08-11 12:15 UTC, bre1470 commented on ts/Accessibility/Utils/Announcer.ts
> +/* *
It got removed, but not set in masters.

2021-08-11 12:16 UTC, bre1470 commented on ts/Accessibility/Utils/Announcer.ts
> +/* *
Sorry, it is okay. Not a public class.

2021-08-11 12:16 UTC, bre1470 approved these changes

2021-08-11 12:58 UTC, circleci-mu commented
### File size comparison
No differences found

2021-08-13 09:16 UTC, TorsteinHonsi approved these changes

2021-08-13 09:16 UTC, merged