ts/bubblelegend-composition
highcharts/highcharts pull request #16212
Opened 2021-08-17 10:12 UTC by marvin19

Improved BubbleLegendComposition.

2021-08-17 10:27 UTC, circleci-mu commented
## Visual test results - No difference found

2021-08-17 14:35 UTC, bre1470 commented
`$(...).datepicker is not a function` error in visual sample `Point.mouseOver (samples/**********/blog/stock-calendar/demo.js.preprocessed.js`. Det ser ut lik noko jQuery feil. 🤔

2021-08-17 14:38 UTC, bre1470 requested changes

2021-08-17 14:38 UTC, bre1470 commented on ts/Series/MapBubble/MapBubbleSeries.ts
> +    public static compose = BubbleLegendComposition.compose;
This should use `BubbleSeries.compose`.

2021-08-17 14:43 UTC, TorsteinHonsi commented
> This looks like some jQuery failure

Yes, it's from a different PR. I've fixed it now I believe.

2021-08-17 15:10 UTC, marvin19 commented on ts/Series/MapBubble/MapBubbleSeries.ts
> +    public static compose = BubbleLegendComposition.compose;
On it!

2021-08-18 06:57 UTC, circleci-mu commented
### File size comparison
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highmaps | 352.8 kB | 353.0 kB | 208 B |
| highmaps, gzipped | 115.2 kB | 114.9 kB | -282 B|

2021-08-18 07:46 UTC, bre1470 approved these changes

2021-08-18 07:47 UTC, merged