Feature/15826-new-annotation-time-cycles
highcharts/highcharts pull request #16262
Opened 2021-08-26 14:29 UTC by pawellysy

Added new annotation, Time Cycles. See #15826.

2021-09-29 08:33 UTC, karolkolodziej requested changes
To do:

- [ ] requested changes

2021-09-29 08:33 UTC, karolkolodziej commented on ts/Stock/StockToolsBindings.ts
> +            const position = annotation.anchor(annotation.points[1]).absolutePosition;
Instead of that, can't you use:
```
 steps: [
            bindingsUtils.updateNthPoint(1)        ]
```

2021-09-29 08:33 UTC, karolkolodziej commented on ts/Stock/StockToolsBindings.ts
> +import TimeCycles from '../Extensions/Annotations/Types/TimeCycles';
I would move that to 34th line

2021-09-29 08:33 UTC, karolkolodziej commented on test/cypress/integration/Highcharts/annotations/time-cycles/time-cycles.spec.js
> +        cy.get('.highcharts-fibonacci').children().eq(1).click();
Can you please add a utils method to select and add an annotation?

2021-09-29 08:33 UTC, karolkolodziej commented on test/cypress/integration/Highcharts/annotations/time-cycles/time-cycles.spec.js
> +            });
<<

2021-09-29 08:33 UTC, karolkolodziej commented on test/cypress/integration/Highcharts/annotations/time-cycles/time-cycles.spec.js
> +    it(`Dragging control Points should change annotation's properties`, () => {
End with a period.

2021-09-29 08:33 UTC, karolkolodziej commented on test/cypress/integration/Highcharts/annotations/time-cycles/time-cycles.spec.js
> +                'first point should be close to the place, where the mouse clicked'
Make it a sentance.

2021-09-29 08:33 UTC, karolkolodziej commented on test/cypress/integration/Highcharts/annotations/time-cycles/time-cycles.spec.js
> +                'first point should be close to the place, where the mouse clicked'
Second point?

2021-09-29 08:33 UTC, karolkolodziej commented on test/cypress/integration/Highcharts/annotations/time-cycles/time-cycles.spec.js
> +                'first point should be close to the place, where the mouse clicked'
This description doesn't make sense in that test.

2021-09-29 08:33 UTC, karolkolodziej commented on test/cypress/integration/Highcharts/annotations/time-cycles/time-cycles.spec.js
> +            assert.closeTo(xAxis.toPixels(point1.x), 75, 4, 'The point1 should change its place');
Can you please split it into separate lines as you did above?

2021-09-29 08:33 UTC, karolkolodziej commented on ts/Extensions/Annotations/Types/TimeCycles.ts
> + * function to create circle paths
Make it a sentence.

2021-09-29 08:33 UTC, karolkolodziej commented on ts/Extensions/Annotations/Types/TimeCycles.ts
> +        const options = this.options,
Please decide and unify the spaces at the begging of the method/if.
I prefer no extra line here but it's up to you ;)

2021-09-30 09:00 UTC, pawelfus requested changes
Issues:
- [x] - I'm not able to draw the annotation on the secondary yAxis

Questions:
- [x] - other annotations, when zooming in/out via RangeSelector are nicely animated. Could you check why it doesn't work for Time Cycles?
- [x] - how about setting the cursor for control points to horizontal resize (and vertical for inverted) instead of pointer?

2021-09-30 09:00 UTC, pawelfus commented on ts/Extensions/Annotations/Types/TimeCycles.ts
> + * @apioption annotations.timeCycles
Missing `exclude`: `labelOptions`

2021-09-30 09:00 UTC, pawelfus commented on ts/Extensions/Annotations/Types/TimeCycles.ts
> + *         Fibonacci Timezones
Wrong demo and the description

2021-09-30 09:00 UTC, pawelfus commented on ts/Stock/StockToolsBindings.ts
> +import TimeCycles from '../Extensions/Annotations/Types/TimeCycles';
Stock Tools Bindings shouldn't import full modules

PS: Just realized StockTools imports ALL annotations. It seems to be caused by importing NavigationBindings, which imports Annotations.. I will create a separate ticket, but still, please import types only

2021-10-01 08:45 UTC, karolkolodziej approved these changes
Seems fine, thanks!

2021-10-01 08:45 UTC, karolkolodziej commented on samples/highcharts/annotations-advanced/time-cycles/demo.js
> +        data: [
I think that this array may be in one line
Here you go: `data: [1, 2, 3, 5, 2, 3, 4, 5, 6, 7, 8, 3, 2, 4, 4, 4, 4, 3]`

2021-10-01 08:45 UTC, karolkolodziej commented on test/cypress/integration/Highcharts/annotations/time-cycles/time-cycles.spec.js
> +            });
<<

2021-10-01 08:45 UTC, karolkolodziej commented on test/cypress/support/index.js
> +Cypress.Commands.add('selectAnnotation', (annotationClassName, parentClassName) => {
I was wondering if there should be some sort of comment/documentation explaining each parameter?
On the other hand, the names are pretty self-explanatory...
But it's just a thought, so it's up to you ;)

2021-10-01 08:45 UTC, karolkolodziej commented on ts/Extensions/Annotations/Types/TimeCycles.ts
> +        const options = this.options,
Still visible

2021-10-06 11:11 UTC, raf18seb requested changes
Good job, just some polishing required

2021-10-06 11:11 UTC, raf18seb commented on ts/Extensions/Annotations/Types/TimeCycles.ts
> +        const point1 = points[0],
Missing line break (like in 169)

2021-10-06 11:11 UTC, raf18seb commented on ts/Extensions/Annotations/Types/TimeCycles.ts
> +        const y = isNumber(yValue) && !isNaN(yValue) ? yAxis.toPixels(yValue) : yAxis.top + yAxis.height,
If I'm not missing anything:
- When `yValue === NaN`, then `isNumber(yValue)` is `false` and the `!isNaN(yValue) ?` check is unnecessary.

- When `yValue !== NaN`, then `!isNaN(yValue) ?` check is also unnecessary.

2021-10-06 11:11 UTC, raf18seb commented on ts/Extensions/Annotations/Types/TimeCycles.ts
> +            x2 = isNumber(xValue2) && !isNaN(xValue2) ? xAxis.toPixels(xValue2) : xAxis.left + 30,
Same as above?

2021-10-06 11:11 UTC, raf18seb commented on ts/Extensions/Annotations/Types/TimeCycles.ts
> +            pixelShift = (Math.floor((x - xAxis.left) / pixelInterval) + 1) * pixelInterval;
Could you add some comments here explaining these variables and `+ 2` and `+ 1` operations?

2021-10-06 11:11 UTC, raf18seb commented on ts/Extensions/Annotations/Types/TimeCycles.ts
> +        this.startX = x - pixelShift;
Missing line break above

2021-10-06 11:11 UTC, raf18seb commented on ts/Extensions/Annotations/Types/TimeCycles.ts
> +TimeCycles.prototype.defaultOptions = merge(
Missing line break

2021-10-18 06:50 UTC, merged