Fixed CSP and style props issues with a11y module in styled mode.
highcharts/highcharts pull request #16268
Opened 2021-08-30 08:56 UTC by oysteinmoseng

2021-08-30 09:12 UTC, circleci-mu commented
### File size comparison
No differences found

2021-08-30 09:14 UTC, circleci-mu commented
## Visual test results - No difference found

2021-08-31 07:22 UTC, TorsteinHonsi requested changes
Thanks! In the [css/a11y](http://utils.highcharts.local/samples/#view/highcharts/css/a11y) demo, there's still one `<li style="visibility: visible;">...</li>` that probably could be set in CSS.

2021-08-31 11:25 UTC, oysteinmoseng commented
`Utils.attr` in this branch or master does not support removing attributes by setting them to `null` or `undefined`. Was this added in a different PR that is under review @TorsteinHonsi? Or does it have to be added?

2021-09-02 13:09 UTC, TorsteinHonsi approved these changes

2021-09-02 13:12 UTC, merged