bugfix/16041-flag-distribute-maxDistance
highcharts/highcharts pull request #16359
Opened 2021-09-17 09:22 UTC by karolkolodziej

Fixed #16041, long flag labels were not distributed properly which resulted in removing them.

2021-09-17 09:40 UTC, circleci-mu commented
### File size comparison
No differences found

2021-09-17 09:42 UTC, circleci-mu commented
## Visual test results - No difference found

2021-09-17 09:52 UTC, raf18seb requested changes

2021-09-17 09:52 UTC, raf18seb commented on samples/unit-tests/series-flags/general/demo.js
> +            type: 'line'
This is the default, not needed

2021-09-17 09:52 UTC, raf18seb commented on samples/unit-tests/series-flags/general/demo.js
> +    chart.setSize(400, undefined);
The second argument `undefined` is the default one, not needed here, but it can stay of course.

2021-09-17 09:52 UTC, raf18seb commented on samples/unit-tests/series-flags/general/demo.js
> +            type: "flags"
Double quote

2021-09-17 09:52 UTC, raf18seb commented on samples/unit-tests/series-flags/general/demo.js
> +                title: "Very long long text very long long text"
Double quote

2021-09-17 09:58 UTC, pawelfus approved these changes
Please resolve Rafal's comments, the rest looks good, thanks!

2021-09-17 15:37 UTC, raf18seb approved these changes
Thanks!

2021-09-20 09:37 UTC, pawellysy approved these changes

2021-09-21 08:39 UTC, TorsteinHonsi requested changes
I think 300px is too distant in most situations. See https://jsfiddle.net/highcharts/xLyzbt16/1/ and test it with the PR.

What if we analyze the boxes and look for the widest box? Then we could set the `maxDistance` to something like `Math.min(greatestBoxWidth, 100)`?

2021-09-21 09:23 UTC, karolkolodziej commented
Setting `Math.min(greatestBoxWidth, 100)` won't work in this case. 
For smaller flags, numbers are so small that they disappear.

I decided to use `Math.max..` to preserve the previous behaviour and for the longer labels distribute them properly 😄

2021-09-21 10:07 UTC, TorsteinHonsi commented
> won't work in this case

Yes of course, `Math.max` was what I meant 🙃

2021-09-21 12:48 UTC, merged