Allow removing a11y info sections by setting format to null.
highcharts/highcharts pull request #16352
Opened 2021-09-16 08:54 UTC by oysteinmoseng

Allow removing accessibility information sections by setting section formats to `null`.
___
This allows for a cleaner DOM in cases where one or more of these sections are not needed.

See [accessibility.screenReaderSection.beforeChartFormat](https://api.highcharts.com/highcharts/accessibility.screenReaderSection.beforeChartFormat).

2021-09-16 09:11 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| modules/accessibility.js | **32.5 kB**<br>117.2 kB | **32.5 kB**<br>117.3 kB | **5 B**<br>116 B |

2021-09-16 09:13 UTC, circleci-mu commented
## Visual test results - No difference found

2021-09-17 07:08 UTC, TorsteinHonsi requested changes
Instead of `null`, can we make an empty string remove the info sections? The typing would be simpler as it would always be a string rather than `string|null`.

2021-09-17 09:32 UTC, oysteinmoseng commented
Nice, changed. Also found a semi-related unreleased bug, so fixed that too

2021-09-17 10:42 UTC, TorsteinHonsi approved these changes

2021-09-17 10:42 UTC, merged