Migration: Sonification
highcharts/highcharts pull request #16362
Opened 2021-09-17 13:55 UTC by marvin19

2021-09-17 14:13 UTC, circleci-mu commented
### File size comparison
No differences found

2021-09-17 14:15 UTC, circleci-mu commented
## Visual test results - No difference found

2021-09-19 12:20 UTC, bre1470 requested changes
Nice job! There is one issue with the point typing.

2021-09-19 12:20 UTC, bre1470 commented on ts/Extensions/Sonification/ChartSonify.ts
> +        currentlyPlayingPoint?: Sonification.SonifyablePoint;
`Sonification.SonifyablePoint` should be integrated into `PointSonify.Composition`. Then you can delete the custom `this` scope of the `PointSonify.Composition` functions.

2021-09-19 12:20 UTC, bre1470 commented on ts/Extensions/Sonification/PointSonify.ts
>      }
That the spot, were it should get integrated.

2021-09-21 09:09 UTC, bre1470 approved these changes
Thank you! Looks good. 👍

2021-09-22 07:52 UTC, TorsteinHonsi approved these changes

2021-09-22 07:52 UTC, merged