Migration: Global win to window
highcharts/highcharts pull request #16360
Opened 2021-09-17 11:31 UTC by bre1470

Migrated global win to window. This will mask the global window object in every Highcharts bundle, so that always `Highcharts.win === window`.

2021-09-17 11:33 UTC, bre1470 commented
[ ] Release assembler v1.4.0 with changed UMD variable
[ ] Switch dependency in this branch to v1.4.0 (package.json & package-lock.json)

2021-09-17 12:21 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts.js | **98.0 kB**<br>292.2 kB | **98.0 kB**<br>292.1 kB | **16 B**<br>-39 B |
| highstock.js | **129.5 kB**<br>390.8 kB | **129.5 kB**<br>390.8 kB | **8 B**<br>-44 B |
| highmaps.js | **114.9 kB**<br>351.4 kB | **114.8 kB**<br>351.3 kB | **-95 B**<br>-39 B |
| highcharts-gantt.js | **132.6 kB**<br>399.6 kB | **132.6 kB**<br>399.6 kB | **34 B**<br>-44 B |

2021-09-17 12:24 UTC, circleci-mu commented
## Visual test results - No difference found

2021-09-21 09:11 UTC, pawelfus approved these changes
It's ok, I guess?

2021-12-01 14:05 UTC, TorsteinHonsi requested changes
1.5 kB increase in compiled+gzipped bundle size, just over this small refactoring? We need to find out where that comes from.

2022-01-04 09:48 UTC, TorsteinHonsi approved these changes

2022-01-04 09:48 UTC, merged