bugfix/16390-fixed-multiple-line-indicator-demo
highcharts/highcharts pull request #16391
Opened 2021-09-22 12:50 UTC by raf18seb

Fixed #16390, docs article: multiple lines indicator didn't work after changes related to migrating MultipleLines mixin to composition.

2021-09-22 13:28 UTC, karolkolodziej requested changes

2021-09-22 13:28 UTC, karolkolodziej commented on docs/stock/custom-technical-indicators.md
> +/* eslint-disable no-underscore-dangle */
I guess in the `.md` files we don't need to worry about `eslint`

2021-09-22 13:32 UTC, circleci-mu commented
## Visual test results - No difference found

2021-09-22 13:59 UTC, pawelfus approved these changes
Thanks!

2021-09-23 06:00 UTC, karolkolodziej approved these changes

2021-09-23 07:38 UTC, bre1470 approved these changes
Looks good! 👍

2021-09-23 08:26 UTC, circleci-mu commented
### File size comparison
No differences found

2021-09-27 12:44 UTC, TorsteinHonsi approved these changes
Thanks!

2021-09-27 12:44 UTC, merged