enhancement/15579-custom-indicator-on-event
highcharts/highcharts pull request #16409
Opened 2021-09-27 08:18 UTC by karolkolodziej

Enhancement #15579, added documentation with an example on how to calculate custom indicators on events.

2021-09-27 08:57 UTC, pawelfus requested changes
We need to put this on hold, because of https://github.com/highcharts/highcharts/issues/16397 - it seems a minor refactoring is necessary: indicator should be bound to both `updatedData` and `afterSetExtremes` events, not only one of them

2021-09-27 13:09 UTC, circleci-mu commented
### File size comparison
No differences found

2021-09-27 13:11 UTC, circleci-mu commented
## Visual test results - No difference found

---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  Added | samples/stock/indicators/custom-indicator-on-event/demo.js |

</p>
</details>

2021-09-27 13:42 UTC, pawellysy requested changes
Looks good! Some minor polishing :)

2021-09-27 13:42 UTC, pawellysy commented on docs/stock/custom-technical-indicators.md
> +The idea behind creating a custom indicator that is calculated after some chart evet (for example `afterSetExtremes`) is similar to the ones previously mentioned with a few additions.
`evet` -> `event`

2021-09-27 13:42 UTC, pawellysy commented on docs/stock/custom-technical-indicators.md
> +The indicator code should look like:
`Example configuration should look like this`

2021-10-06 11:16 UTC, raf18seb approved these changes
Thanks!

2021-11-02 12:24 UTC, pawelfus requested changes
Just a minor request.

Note: This PR should not be merged until the new version release (because docs are more often updated, and we don't want to have docs that describe something that will be possible in the next version). Should we somehow label this PR, @TorsteinHonsi ?

2021-11-02 12:24 UTC, pawelfus commented on docs/stock/custom-technical-indicators.md
> +*   `xAxis` - on which xAxis' event the indicator should be recalculated,
Could you add an example? Something like this: 
> on which xAxis' event the indicator should be recalculated (e.g. `afterSetExtremes`)

2021-11-03 08:52 UTC, pawellysy approved these changes
I like what you got. Good job!

2021-11-08 09:45 UTC, pawelfus approved these changes
#16397 merged and released, we can do the same with this docs-related PR.
Thanks!
PS: Awaiting CI

2021-11-08 11:02 UTC, TorsteinHonsi commented
So the _on hold_ comment in the first comment is no longer valid?
Also, merging in the master will probably fix the CI failures.

2021-11-09 08:55 UTC, pawelfus commented
> So the on hold comment in the first comment is no longer valid?

Yes, that's right.

2021-11-16 09:30 UTC, TorsteinHonsi approved these changes

2021-11-16 13:08 UTC, merged