Website/product icons
highcharts/highcharts pull request #16564
Opened 2021-10-31 13:03 UTC by nasin

Hi, I updated some more CSS to fix a gap on the new product page.

2021-10-31 13:23 UTC, circleci-mu commented
### File size comparison
No differences found

2021-10-31 13:25 UTC, circleci-mu commented
## Visual test results - No difference found

2021-11-01 09:39 UTC, TorsteinHonsi requested changes

2021-11-01 09:39 UTC, TorsteinHonsi commented on samples/highcharts/website/icon-chart/demo.css
> +	margin:opx;
Is that the letter o? 🤔

2021-11-01 12:47 UTC, nasin commented on samples/highcharts/website/icon-chart/demo.css
> +	margin:opx;
I'm sorry. I'll fix it.

2021-11-01 13:14 UTC, nasin commented
I'm not sure what failing 'test_cypress' means, and when I click on the details link, I get a 404 error.

2021-11-02 08:58 UTC, TorsteinHonsi approved these changes

2021-11-02 08:58 UTC, merged