Created static chart versions
highcharts/highcharts pull request #16623
Opened 2021-11-09 22:03 UTC by nasin

Hi, 

The web team asked me to create stand-alone static versions of the final charts for the product pages. I put them in their own directories.

I also fixed a bunch of accessibility issues and linted the CSS.

2021-11-09 22:26 UTC, circleci-mu commented
### File size comparison
No differences found

2021-11-09 22:28 UTC, circleci-mu commented
## Visual test results - No difference found

---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  Modified | samples/highcharts/website/icon-chart/demo.js |
|  Modified | samples/highcharts/website/icon-gantt/demo.js |
|  Modified | samples/highcharts/website/icon-map/demo.js |
|  Modified | samples/highcharts/website/icon-stock/demo.js |
|  Added | samples/highcharts/website/static-chart/demo.js |
|  Added | samples/highcharts/website/static-gantt/demo.js |
|  Added | samples/highcharts/website/static-map/demo.js |
|  Added | samples/highcharts/website/static-stock/demo.js |

</p>
</details>

2021-11-11 10:21 UTC, TorsteinHonsi requested changes

2021-11-11 10:21 UTC, TorsteinHonsi commented on samples/highcharts/website/static-chart/demo.details
> + skipTest: true
Unless there's a good reason, remove `skipTest: true` so that the static charts become part of the visual test routine.

2021-11-11 11:34 UTC, nasin commented
I updated the static versions demo.details files and removed the skipTest

2021-11-11 12:12 UTC, oysteinmoseng commented
A11y review ongoing

- [ ] Highcharts demo
- [ ] Stock demo
- [ ] Map demo
- [ ] Gantt demo

2021-11-11 14:37 UTC, oysteinmoseng requested changes
Some additional points that I did not fix @nasin :

- Icon-chart does not seem to be animating?
- I assume with reduced motion we would only show the static charts, so probably don't need much logic in the demos for this?
- Would recommend all the animating charts (icon-...) to have `enableMouseTracking: false` or `pointer-events: none` or similar, and remove the a11y module, then we'll give a description in the page where it is used.

**static-chart:**
- Is there any way to make the tooltip not move when hovered over? Thinking of low vision magnifier users.
- The green tabular point and brown wedge point both have too low contrast against the background. Could we add a dark border, or would this mess with the design too much?

**static-stock:**
- Tempted to add sonification to this, but perhaps wait until after the upcoming sonification revamp.

**static-map:**
- The darker points, such as the British isles, have low contrast against the background. Could we fix this somehow, either by changing colors or by adding a thin lighter border?
- Should the map title be "Population density" and not "Zoom to point"? Does it need a visible title at all?
- The subtitle text is invisible, but also not sure if it makes sense?
- Hovering over the color axis makes the text disappear
- Somehow it seems when zooming all the way out, you are zoomed back in automatically

**static-gantt:**
- The selected state for points needs to be obvious, since the user can remove the selected point. Currently you can only tell points are selected if you added them yourself.
- Could we reduce the contrast (!) on the vertical grid lines a bit? Or add a background color to the data labels for readability? Or both for that matter..
- Recommend not showing the "Remove selected" button unless something is selected.
- If possible, could we make the tooltip stick when hovered over? `stickOnContact: true` for some reason made the background color change for me..

2021-11-14 10:58 UTC, nasin commented
Hi,

I fixed all of the issues except the iceberg chart tooltip. I don't see how it's moving when I mouse over it.

2021-11-15 13:11 UTC, oysteinmoseng commented
Sorry, I meant change, not move. When moving the mouse over the text it changes to different points.

2021-11-15 20:04 UTC, nasin commented
Hi, I think I resolved the issue with the tooltip on the icon-chart chart (the icebergs.)

2021-11-16 08:59 UTC, oysteinmoseng commented
Hm, I think the tooltip might have been better before the fix actually.. It now moves whenever the mouse is moving, which makes it even harder. `stickOnContact: true` makes it tricky to use as well, so perhaps just revert to how it was for now.

One more question: Is there a static version of the home page stock chart somewhere? And is the stock chart after the animation supposed to be different from the one that happens if you click "Stop Animation"?

2021-11-16 09:26 UTC, TorsteinHonsi requested changes
The gantt chart tooltip now looks a bit bad. There are borders on top and left but not right and bottom.

2021-11-16 12:17 UTC, nasin commented
I fixed the tooltip issues.

The static homepage chart is called static-candlestick.

2021-11-16 12:32 UTC, oysteinmoseng commented
I will make some a11y tweaks to the candlestick

2021-11-16 12:49 UTC, oysteinmoseng commented
Did my changes to static-map somehow get removed @nasin?

2021-11-16 13:00 UTC, nasin commented
I guess it's possible when I fixed the zoom issue on the map @oysteinmoseng

2021-11-16 14:23 UTC, oysteinmoseng approved these changes
All good from my side now I think!

2021-11-17 10:24 UTC, TorsteinHonsi approved these changes

2021-11-17 10:24 UTC, merged