Fixed accessibility, created static version
highcharts/highcharts pull request #16632
Opened 2021-11-10 17:40 UTC by nasin

Hi,

I created a static version of the editor page chart for accessibility purposes, and fixed the accessibility on both the animated and static charts.

2021-11-10 17:59 UTC, circleci-mu commented
### File size comparison
No differences found

2021-11-10 18:01 UTC, circleci-mu commented
## Visual test results - No difference found

---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  Modified | samples/highcharts/website/icon-editor/demo.js |
|  Added | samples/highcharts/website/static-editor/demo.js |

</p>
</details>

2021-11-11 10:20 UTC, TorsteinHonsi requested changes

2021-11-11 10:20 UTC, TorsteinHonsi commented on samples/highcharts/website/static-editor/demo.details
> + skipTest: true
When `skiptTest: true`, these charts are not considered when doing visual regression tests. But if there's not a specific reason for leaving them out (like custom animation, timeouts etc.), all the static charts should be part of the regression tests.

2021-11-11 11:36 UTC, nasin commented
I removed the skipTest from demo.details

2021-11-11 13:02 UTC, TorsteinHonsi approved these changes

2021-11-11 13:02 UTC, merged