bugfix/14267-tilemap-square-error
highcharts/highcharts pull request #16646
Opened 2021-11-15 08:36 UTC by raf18seb

Fixed #14267, tilemap [tileShape](https://api.highcharts.com/highmaps/series.tilemap.tileShape) `square` was throwing an error into the console.

2021-11-15 08:56 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highmaps.js | **118.8 kB**<br>364.1 kB | **118.8 kB**<br>364.1 kB | **1 B**<br>3 B |
| modules/heatmap.js | **6.6 kB**<br>18.9 kB | **6.6 kB**<br>19.0 kB | **0 B**<br>3 B |

2021-11-15 08:56 UTC, DJTechnoo reviewed
Looks good to me!

2021-11-15 08:58 UTC, circleci-mu commented
## Visual test results - No difference found

2021-11-15 12:13 UTC, madepiet approved these changes

2021-11-15 16:16 UTC, KacperMadej approved these changes

2021-11-16 08:57 UTC, TorsteinHonsi requested changes
Thanks! I think now that we have guarded `markerOptions` we should also take the opportunity and get rid of the `any` cast. When typing the function input, we can resolve the rest of the anys:

```ts
        [['width', 'x'], ['height', 'y']].forEach(function (
            dimension: ['width'|'height', 'x'|'y']
        ): void {
```

2021-11-18 07:50 UTC, TorsteinHonsi approved these changes
Thanks!

2021-11-18 07:51 UTC, merged