docs/maps-series-link
highcharts/highcharts pull request #16654
Opened 2021-11-15 20:13 UTC by madepiet

Fixed link demo.

2021-11-15 20:35 UTC, circleci-mu commented
### File size comparison
No differences found

2021-11-15 20:37 UTC, circleci-mu commented
## Visual test results - No difference found

2021-11-17 09:13 UTC, raf18seb requested changes
Just a small question

2021-11-17 09:13 UTC, raf18seb commented on docs/maps/map-series.md
> +<iframe style="width: 100%; height: 520px; border: none;" src="https://www.highcharts.com/samples/embed/maps/demo/category-map" allow="fullscreen"></iframe>
Why `www.` is added here but not in the demo above? Not sure which one is correct (probably both), but we can choose one and be consistent from now

2021-11-18 10:01 UTC, KacperMadej approved these changes
I agree with Rafał. Other than that looks good 👍

2021-11-22 08:24 UTC, TorsteinHonsi approved these changes
Thanks!

2021-11-22 08:24 UTC, merged