Tools: Doclet readme
highcharts/highcharts pull request #16696
Opened 2021-11-23 15:25 UTC by bre1470

2021-11-23 15:45 UTC, circleci-mu commented
### File size comparison
No differences found

2021-11-23 15:47 UTC, circleci-mu commented
## Visual test results - No difference found

2021-11-26 09:56 UTC, karolkolodziej requested changes
Maybe it is worth mentioning how the `@productdesc` works and when it should be used?

2021-11-29 09:42 UTC, karolkolodziej approved these changes

2021-11-29 10:14 UTC, raf18seb approved these changes
Thanks! ;)

2021-12-13 15:00 UTC, TorsteinHonsi approved these changes
Thanks!

2021-12-13 15:00 UTC, merged