bugfix/10525-axis-cleared-undefined
highcharts/highcharts pull request #16721
Opened 2021-11-30 13:27 UTC by mfilipiec

Fixed #10525, setting tickPositions on undefined didn't clear options.

2021-11-30 13:35 UTC, raf18seb requested changes
Thanks for the PR!
Few improvement suggestions below:

- [ ] can you reuse an existing test and update the chart instead of creating a new one from scratch? With thousands of tests, it decreases the time needed to all tests pass
- [x] you can use ES6 when writing tests

2021-11-30 13:47 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts.js | **98.2 kB**<br>293.3 kB | **98.2 kB**<br>293.3 kB | **4 B**<br>19 B |
| highstock.js | **130.4 kB**<br>394.0 kB | **130.4 kB**<br>394.0 kB | **8 B**<br>19 B |
| highmaps.js | **119.1 kB**<br>364.2 kB | **119.1 kB**<br>364.2 kB | **12 B**<br>19 B |
| highcharts-gantt.js | **132.5 kB**<br>400.7 kB | **132.6 kB**<br>400.7 kB | **12 B**<br>19 B |

2021-11-30 13:49 UTC, circleci-mu commented
## Visual test results - No difference found

2021-11-30 23:39 UTC, raf18seb approved these changes
Good job, thanks!

2021-12-01 14:18 UTC, TorsteinHonsi approved these changes

2021-12-01 14:19 UTC, merged