api/15594-mappoint-missing-stickytracking
highcharts/highcharts pull request #16734
Opened 2021-12-01 13:47 UTC by raf18seb

Fixed #15594, the `mappoint.stickyTracking` property was missing in the API.

2021-12-01 14:06 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highmaps.js | **119.1 kB**<br>364.2 kB | **119.1 kB**<br>364.2 kB | **12 B**<br>18 B |

2021-12-01 14:09 UTC, circleci-mu commented
## Visual test results - No difference found

2021-12-01 16:34 UTC, madepiet approved these changes

2021-12-02 10:54 UTC, DJTechnoo approved these changes

2021-12-03 09:56 UTC, TorsteinHonsi requested changes
Thanks!

The API is set up so that objects extends each other. The `mappoint.plotOptions` extend the `scatter.plotOptions` here: 

https://github.com/highcharts/highcharts/blob/e7983c78b905f52cc6d400b23ea3eb780e723767/ts/Series/MapPoint/MapPointSeries.ts#L227

So we should expect that the `stickyTracking` option was also inherited, without us having to redefine it. The reason why it doesn't do so, I think is this line, where `highmaps` is missing:

https://github.com/highcharts/highcharts/blob/e7983c78b905f52cc6d400b23ea3eb780e723767/ts/Series/Scatter/ScatterSeries.ts#L126

2021-12-03 12:29 UTC, raf18seb commented
I saw this, but if we go this way, all maps series will be extended (including e.g. `map` series). That's why I decided to extend only the `mappoint` series.
I think `stickyTracking` shouldn't be listed in https://api.highcharts.com/highmaps/series.map

Knowing that, do you still want me to change it to use inheritance, or leave redefined `stickyTracking` only on the `mappoint` series as it is now in this PR?

2021-12-06 08:44 UTC, TorsteinHonsi commented
Okay, I see. In that case I think it would be better to exclude this option from the other map series types:

https://github.com/highcharts/highcharts/blob/f0b3c8e8951bf04f29ad78ff4ad246fee2267777/ts/Series/Map/MapSeries.ts#L160

It is better to exclude than to maintain two copies of the identical description. But before excluding you should check it agains the other map series. It may be that the feature actually works there too.

2021-12-08 11:01 UTC, KacperMadej approved these changes
No additional comments.

2021-12-09 13:46 UTC, raf18seb commented
@TorsteinHonsi, sorry, I was wrong in the first place. `stickyTracking` works for all current Maps series so it should be inherited.

2021-12-13 08:29 UTC, TorsteinHonsi approved these changes

2021-12-13 08:29 UTC, merged