bugfix/16759-rangeSelector-overwrite-dataGrouping
highcharts/highcharts pull request #16786
Opened 2021-12-14 15:26 UTC by mfilipiec

Fixed #16759, properly merging dataGrouping settings.

2021-12-14 15:45 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highstock.js | **130.4 kB**<br>394.1 kB | **130.4 kB**<br>394.1 kB | **25 B**<br>41 B |

2021-12-14 15:47 UTC, circleci-mu commented
## Visual test results - No difference found

2021-12-14 16:01 UTC, raf18seb requested changes
Thanks! Please see comments below.

- [ ] Also, is it necessary to create the whole QUnit.test? Maybe we could reuse an existing test instead.

2021-12-14 16:01 UTC, raf18seb commented on samples/unit-tests/series/datagrouping/demo.js
> +QUnit.test('The dataGrouping with selected range.', function (assert) {
Not really a big deal, but you can use ES6 arrow function here

2021-12-15 16:41 UTC, raf18seb commented on samples/unit-tests/series/datagrouping/demo.js
> +QUnit.test('The dataGrouping with selected range.', function (assert) {
Not really a big deal again, but if there's only one argument, you don't need parentheses. But you can leave it as it is not :)

2021-12-15 16:59 UTC, mfilipiec commented
> * [x]  Also, is it necessary to create the whole QUnit.test (and create the whole chart)? Maybe we could reuse an existing test instead.

@raf18seb I was trying to use one of the existing tests but neither of them matched in this case.

2021-12-15 17:03 UTC, raf18seb requested changes
(edit)
I see, it needs to be checked on first chart load (when xAxis is not created yet).

I found that you can reuse this test:
```js
QUnit.test('DataGrouping and update', function (assert) {
    const chart = Highcharts.stockChart('container', {
        rangeSelector: {
            selected: 0,
            buttons: [{
                type: 'all',
                text: 'All',
                dataGrouping: {
                    forced: true,
                    units: [
                        ['millisecond', [3]]
                    ]
                }
            }]
        },
        series: [
            {
                id: 'usdeur',
                dataGrouping: {
                    forced: true,
                    approximation: () => 3
                },
                data: [1, 2, 3]
            }
        ]
    });

    assert.strictEqual(
        chart.series[0].points[0].y,
        3,
        `When the scope is set in the dataGrouping options
        it should workas well as without it (#16759)`
    );

    chart.update(
        {
            series: [
                {
                    id: 'usdeur',
                    data: [3, 2, 1]
                },
                {
                    id: 'eurusd',
                    data: [1, 2, 3]
                }
            ]
        },
        true,
        true
    );

    assert.ok(
        true,
        `Should be no errors when:
            - updating one-to-one with IDs
            - DG enabled
        (#11471)`
    );
});
```

- [ ] Please, change the test name accordingly.

2021-12-17 10:14 UTC, TorsteinHonsi approved these changes
Thanks!

2021-12-17 10:53 UTC, raf18seb approved these changes
Good job, thanks!

2021-12-17 12:48 UTC, merged