Boost and devicePixelRatio (Retina)
highcharts/highcharts pull request #16797
Opened 2021-12-16 12:36 UTC by TorsteinHonsi

2021-12-16 12:59 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| modules/boost.js | **14.8 kB**<br>42.4 kB | **14.8 kB**<br>42.7 kB | **85 B**<br>259 B |

2021-12-16 13:02 UTC, circleci-mu commented
## Visual test results - No difference found

---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  Added | samples/highcharts/boost/line-devicepixelratio/demo.js |
|  Added | samples/highcharts/boost/line-export-pixelratio/demo.js |

</p>
</details>

2021-12-17 10:40 UTC, pawelfus requested changes
Just a minor thing, the rest looks good 👍

2021-12-17 10:40 UTC, pawelfus commented on ts/Extensions/Boost/BoostAttach.ts
> +const { doc, win } = H;
Unused variable

2021-12-17 10:52 UTC, raf18seb approved these changes
👍

2021-12-17 10:52 UTC, merged