bugfix/16568-data-options-merging
highcharts/highcharts pull request #16832
Opened 2021-12-28 12:31 UTC by mfilipiec

Fixed #16568, merging global data options with the chart options.

2021-12-28 12:50 UTC, raf18seb approved these changes
Good job!

2021-12-28 12:55 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| modules/data.js | **6.1 kB**<br>15.9 kB | **6.1 kB**<br>15.9 kB | **25 B**<br>70 B |

2021-12-28 12:58 UTC, circleci-mu commented
## Visual test results - No difference found

2021-12-28 14:32 UTC, raf18seb requested changes
Tests are not passing, could you check this out?

2021-12-28 15:37 UTC, raf18seb requested changes

2021-12-28 15:37 UTC, raf18seb commented on samples/unit-tests/data/general/demo.js
> +const defaultOptions = { ...Highcharts.defaultOptions };
Unused variable, do we need this?

2021-12-28 15:37 UTC, raf18seb commented on samples/unit-tests/data/general/demo.js
> +    });
It's good enough, but you can simply clear the `defaultOptions` this way:
```js
// Clear the default options for other tests
delete Highcharts.defaultOptions.data;
```

2021-12-29 14:00 UTC, raf18seb approved these changes
Thanks!

2022-01-03 15:12 UTC, KacperMadej approved these changes

2022-01-04 09:44 UTC, TorsteinHonsi approved these changes
Looks good, thanks!

2022-01-04 09:44 UTC, merged