bugfix/16820-drilldown-tooltip-mouseover
highcharts/highcharts pull request #16843
Opened 2021-12-30 14:31 UTC by karolkolodziej

Fixed #16820, adding drilldown series on point mouseover threw an error.

2021-12-30 14:51 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts.js | **98.7 kB**<br>294.5 kB | **98.7 kB**<br>294.5 kB | **20 B**<br>26 B |
| highstock.js | **130.8 kB**<br>395.2 kB | **130.8 kB**<br>395.2 kB | **7 B**<br>26 B |
| highmaps.js | **122.9 kB**<br>374.0 kB | **122.9 kB**<br>374.1 kB | **3 B**<br>26 B |
| highcharts-gantt.js | **133.1 kB**<br>402.0 kB | **133.1 kB**<br>402.1 kB | **9 B**<br>26 B |

2021-12-30 14:53 UTC, circleci-mu commented
## Visual test results - No difference found

2021-12-30 15:09 UTC, raf18seb reviewed
@TorsteinHonsi this solution is OK, but I'm wondering whether the `tooltip.refresh()` (or even `point.onMouseOver()`) method should be fired in the first place. In this case, we hover over the point to add series as drilldown, but not because we want to display the tooltip. Maybe we could stop mouseOver event from firing further actions by adding something similar to `e.preventDefault` or `return false` or something else in the `point.events.mouseOver` callback function?

Also, small info in the comment below.

2021-12-30 15:09 UTC, raf18seb commented on samples/unit-tests/drilldown/drilldown-general/demo.js
> +    Highcharts.fireEvent(chart.series[0].points[0].graphic.element, 'mouseover');
Just a note: you can fire `onMouseOver` instead
```js
chart.series[0].points[0].onMouseOver();
```

2022-01-04 10:17 UTC, TorsteinHonsi requested changes
Looks good to me except a small optimization.

2022-01-04 10:17 UTC, TorsteinHonsi commented on ts/Core/Tooltip.ts
> +        if (!options.enabled || !splat(pointOrPoints)[0].series) { // #16820
We already do `splat(pointOrPoints)` on line 1037, and refer to item 0 on line 1038, so we can simplify this line to `if (!options.enabled || !point.series) { // #16820`

2022-01-07 09:24 UTC, raf18seb approved these changes
Perfect 👍

2022-01-07 09:35 UTC, TorsteinHonsi approved these changes

2022-01-07 09:35 UTC, merged