bugfix/11115-dependency-wheel-labels
highcharts/highcharts pull request #16853
Opened 2022-01-05 12:52 UTC by karolkolodziej

Fixed #11115, `textPath` for dependency wheel.

2022-01-05 13:15 UTC, circleci-mu commented
### File size comparison
No differences found

2022-01-05 13:17 UTC, circleci-mu commented
## Visual test results - No difference found

2022-01-05 13:45 UTC, raf18seb approved these changes
👍

2022-02-15 10:29 UTC, raf18seb requested changes

2022-02-15 10:29 UTC, raf18seb commented on ts/Series/DependencyWheel/DependencyWheelSeries.ts
> +                    radius: r
`r` is already there

2022-02-15 10:29 UTC, raf18seb commented on ts/Series/DependencyWheel/DependencyWheelSeries.ts
> +                node.dlOptions = (dependecyWheel).getDlOptions({
Unnecessary bracket

2022-02-15 10:29 UTC, raf18seb commented on ts/Series/DependencyWheel/DependencyWheelSeries.ts
> +                    level: void 0,
Is it necessary to pass a property with `undefined` value?

2022-02-15 10:29 UTC, raf18seb commented on ts/Series/CircularDataLabels.ts
> +                isObject(params.shapeArgs) ? params.shapeArgs : {},
Is it possible that `shapeArgs` is not an object? There's probably something wrong with TS

2022-03-17 13:45 UTC, TorsteinHonsi requested changes
Thanks, nice work on the composition. This really makes sense the way it is implemented, and will make it easier to adapt to PieSeries in the future.

One thing we may be missing now is the kind of logic that automatically aligns the labels. Currently this is implemented in pie series, so labels on the left side are right aligned and vice versa. X axis labels in a polar chart also has this feature. In the visual demo with rotation mode perpendicular, the labels are centered aligned. This may be out of scope though, but I do feel it is the last missing piece.

I also took the liberty to move the sample, we've been cramming too much stuff into the `plotoptions` folder in the past.

2022-03-17 13:45 UTC, TorsteinHonsi commented on ts/Series/DependencyWheel/DependencyWheelSeries.ts
> +                node.linksFrom.forEach(function (point: any): void {
Why a new `any`? Perhaps some types need updating?

2022-03-17 13:45 UTC, TorsteinHonsi commented on ts/Series/DependencyWheel/DependencyWheelSeries.ts
> +                } as any;
Why a new `any`?

2022-03-17 13:45 UTC, TorsteinHonsi commented on ts/Series/DependencyWheel/DependencyWheelSeries.ts
> +        const dependecyWheel = this,
Why do we need a local reference? And if we really need one, the convention is to use `series` in this case.

2022-03-23 10:06 UTC, TorsteinHonsi commented
@raf18seb Do you want to have a go with auto-alignment? I imagine that we set the default `align` to `undefined`, which results in the left-side labels being right-aligned and the right-side labels being left-aligned.

For inspiration, similar logic can be found for polar charts. Though that logic actually writes the alignment back to `options.align`, which I think is unfortunate. The options should not be mutated.

https://github.com/highcharts/highcharts/blob/5f27de015659dc2f5ac32911e1e1b05d2962906c/ts/Extensions/Polar.ts#L966-L975

2022-05-30 10:42 UTC, karolkolodziej commented
@TorsteinHonsi could you please take a look?☝️

2022-06-01 09:27 UTC, TorsteinHonsi commented
@karolkolodziej We need more samples and docs. For example, the latest commit apparently should apply automatic label alignment when `rotationMode` and `align` are falsy, but there's no demo and I can't get it to work.

Also, the `rotationMode: 'auto'` setting in sunburst applies the best fit. It prefers a parallel layout, but falls back to perpendicular if there is no space. This doesn't seem to work with the dependency wheel?

2022-07-04 10:42 UTC, karolkolodziej commented
@TorsteinHonsi 
I fixed the auto alignment issue, but I'm not sure if I should add a separate demo for each alignment option?

2022-07-07 08:02 UTC, TorsteinHonsi requested changes
@karolkolodziej We need at least enough visual samples that we can demonstrate how this works. Right now there's only a sample for `rotationMode: 'perpendicular' `, but:
* The labels are centered, not auto-aligned. I would expect, at least if I set `align: 'auto'`, that the labels be aligned like in a pie chart. And then we need a sample for that. 
* When I change the `rotationMode` to `circular`, it still renders perpendicular.
* When I change the `rotationMode` to `auto`, all labels are still perpendicular. I would expect a mix between parallel and perpendicular labels.

2022-07-07 08:02 UTC, TorsteinHonsi commented on ts/Series/DependencyWheel/DependencyWheelSeries.ts
> + * @validvalue ["auto", "perpendicular", "parallel"]
Shouldn't we support 'circular' like the sunburst?

2022-07-07 08:02 UTC, TorsteinHonsi commented on ts/Series/DependencyWheel/DependencyWheelSeries.ts
> + * @sample {highcharts} highcharts/plotoptions/dependencywheel-datalabels-rotationmode-perpendicular/
This sample reference is wrong, the sample has moved.

2022-08-08 12:58 UTC, TorsteinHonsi commented
Thanks! Remaining issues:
* In [datalabels-rotationmode-auto](https://highcharts.github.io/highcharts-utils/samples/#gh/b4d352c4b5/sample/highcharts/series-dependencywheel/datalabels-rotationmode-auto), the Mexico label is hidden until hovered. (The South Africa label has an issue with text shadow, I'll deal with that).
* Re-iteration of the first point above: in the [perpendicular demo](https://highcharts.github.io/highcharts-utils/samples/#gh/b4d352c4b5/sample/highcharts/series-dependencywheel/datalabels-rotationmode-perpendicular), we need to show how to make the labels radiate out from the nodes. I expect `align: 'auto'` to do that. Instead, all labels are left-aligned: https://jsfiddle.net/highcharts/spcqvua5/. I would expect that labels on the left side of the wheel are right-aligned. We also need to implement [distance](https://api.highcharts.com/highcharts/series.sunburst.dataLabels.distance) for these labels. Distance currently works when `rotationMode` is circular, but not for perpendicular.

2023-01-23 09:09 UTC, TorsteinHonsi commented
@karolkolodziej Pending continued work. Maybe we should put this back in draft and add the remaining tasks as check boxes?

2024-08-03 01:52 UTC, closed without merging