demo/tooltip-extra-information
highcharts/highcharts pull request #16876
Opened 2022-01-12 12:16 UTC by karolkolodziej

Added API demo showing how to display extra information in the tooltip.

2022-01-12 12:40 UTC, circleci-mu commented
### File size comparison
No differences found

2022-01-12 12:42 UTC, circleci-mu commented
## Visual test results - No difference found

---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  Added | samples/highcharts/tooltip/formatter-extra-information/demo.js |

</p>
</details>

2022-01-12 12:50 UTC, raf18seb requested changes
Please see comments below

2022-01-12 12:50 UTC, raf18seb commented on samples/highcharts/tooltip/formatter-extra-information/demo.js
> +                extraInfrmation: 'First month when XYZ introduced.'
I think we should push the users to add additional info in a `data.custom` that was added specifically for cases like this
https://api.highcharts.com/highcharts/series.line.data.custom

2022-01-12 12:50 UTC, raf18seb commented on samples/highcharts/tooltip/formatter-extra-information/demo.details
> +   - Torstein Hønsi
Don't you want to change the author?

2022-01-13 08:35 UTC, TorsteinHonsi requested changes
Thanks for this useful demo!

I think we should encourage our users to use `pointFormat` instead of `formatter`. That's because it is JSON-compatible and thus more secure, avoiding callbacks in the options structure, and more compliant to wrappers and other languages. 

Arguably, formatters are more flexible, but in this case the implementer has control over `extraInformation`, so any logic can be added where this property is generated.

This is the equivalent setup with `pointFormat` instead of `formatter`: https://jsfiddle.net/highcharts/68pmut32/. As a consequence, the name of the sample must change too.

2022-01-13 08:35 UTC, TorsteinHonsi commented on samples/highcharts/tooltip/formatter-extra-information/demo.html
> +<div id="container" style="height: 400px"></div>
Avoid style attributes, use a `demo.css` file instead.

2022-01-14 08:13 UTC, TorsteinHonsi approved these changes

2022-01-14 08:14 UTC, merged