docs/custom-column-indicator
highcharts/highcharts pull request #16880
Opened 2022-01-13 11:58 UTC by karolkolodziej

Added documentation on how to create a custom column indicator.

2022-01-13 12:19 UTC, circleci-mu commented
## Visual test results - No difference found

---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  Added | samples/stock/indicators/custom-column-indicator/demo.js |

</p>
</details>

2022-01-14 12:50 UTC, raf18seb requested changes

2022-01-14 12:50 UTC, raf18seb commented on docs/stock/custom-technical-indicators.md
> +some other methods like `markerAttribs`,  `drawGraph`, `crispCol`, `drawPoints`, `getColumnMetrics`, `translate` needs to be inherited from the column series prototype as shown in the code snippet be
Type: "need" instead of "needs"

2022-01-14 12:50 UTC, raf18seb commented on docs/stock/custom-technical-indicators.md
> +some other methods like `markerAttribs`,  `drawGraph`, `crispCol`, `drawPoints`, `getColumnMetrics`, `translate` needs to be inherited from the column series prototype as shown in the code snippet be
It's not true, because e.g. `markerAttribs` method is overwritten with empty function

2022-01-14 12:50 UTC, raf18seb commented on docs/stock/custom-technical-indicators.md
> +        pointPadding: 0.2,
Unnecessary comma

2022-01-14 12:50 UTC, raf18seb commented on docs/stock/custom-technical-indicators.md
> +Along with that, in order to render the column,
Strange line break (?)

2022-01-14 12:50 UTC, raf18seb commented on samples/stock/indicators/custom-column-indicator/demo.html
> +<div id="container" style="height: 400px; min-width: 310px"></div>
Inline styles (use demo.css if you need to set styles)

2022-01-17 12:03 UTC, pawelfus approved these changes
Thanks, looks good! Just fix Rafal's comments :)

2022-01-17 13:04 UTC, raf18seb requested changes
Thanks!

One thing more - it's a very tiny typo, however, as it's an article for users to read, I think typos like this still should be corrected

2022-01-17 13:04 UTC, raf18seb commented on docs/stock/custom-technical-indicators.md
> +need to be inherited from the column series prototype and the `markerAttribs`,  `drawGraph` need to be overwritten with empty function
Double space before `drawGraph`

2022-01-17 13:06 UTC, raf18seb commented on docs/stock/custom-technical-indicators.md
> +need to be inherited from the column series prototype and the `markerAttribs`,  `drawGraph` need to be overwritten with empty function
I'm not good with that, but should it be `need to be overwritten with empty function` or `need to be overwritten with an empty function`?

2022-01-17 14:21 UTC, raf18seb approved these changes
Perfect, thanks once again

2022-01-18 08:46 UTC, TorsteinHonsi approved these changes
Thanks!

2022-01-18 08:47 UTC, merged