bugfix/16750-mapbubble-joinBy
highcharts/highcharts pull request #16950
Opened 2022-02-02 17:44 UTC by madepiet

Default joinBy added for mapbubble.

2022-02-02 18:06 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highmaps.js | **124.0 kB**<br>377.4 kB | **124.0 kB**<br>377.5 kB | **2 B**<br>16 B |

2022-02-02 18:08 UTC, circleci-mu commented
## Visual test results - No difference found

2022-02-03 07:39 UTC, TorsteinHonsi commented
Regarding the Safari fails: I have fixed the first one in another PR. The second one I don't recognize.

2022-02-03 09:54 UTC, raf18seb requested changes

2022-02-03 09:54 UTC, raf18seb commented on samples/unit-tests/maps/mapbubble-linewidth/demo.js
> +    assert.ok(
Could you use `assert.strictEqual` for consistency?

2022-02-03 09:54 UTC, raf18seb commented on samples/unit-tests/maps/mapbubble-linewidth/demo.js
> +        chart.series[1].joinBy[0] === "hc-key",
Please use single quotes when writing a JavaScript code

2022-02-03 09:54 UTC, raf18seb commented on samples/unit-tests/maps/mapbubble-linewidth/demo.js
> +        `Checking default options for joinBy: 'hc-key'.`
One of our internal rules, when writing unit tests, is that description of a test should have a "should" keyword.

For example:
```
The value of joinBy in the mapbubble series should be 'hc-key' by default.
```

2022-02-03 13:16 UTC, raf18seb approved these changes
Thanks!
(Now only failed tests left to resolve) - it's actually done, so all good!

2022-02-09 10:11 UTC, DJTechnoo approved these changes

2022-02-09 11:59 UTC, TorsteinHonsi approved these changes

2022-02-09 11:59 UTC, merged