bugfix/15863-remove-hide-by-translation
highcharts/highcharts pull request #17126
Opened 2022-03-24 13:17 UTC by pawellysy

Fixed #15863, elements are no longer hidden by setting `yPosition` to -9999.

2022-03-24 13:36 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highstock.js | **131.1 kB**<br>396.1 kB | **131.1 kB**<br>396.0 kB | **-20 B**<br>-18 B |
| highcharts-gantt.js | **134.1 kB**<br>402.9 kB | **134.1 kB**<br>402.9 kB | **-9 B**<br>-18 B |

2022-03-24 13:39 UTC, circleci-mu commented
## Visual test results - Differences found
Found **2** diffing sample(s). [Please review the differences.](https://vrevs.highsoft.com/pr/17126/review)

2022-03-28 19:26 UTC, TorsteinHonsi requested changes
Thanks! Remarks regarding the `show` and `hide` shorthand functions.

2022-03-28 19:26 UTC, TorsteinHonsi commented on ts/Core/Scrollbar.ts
> +            visibility: 'visible'
Use the shorter `.show()` function.

2022-03-28 19:26 UTC, TorsteinHonsi commented on ts/Core/Scrollbar.ts
> +                visibility: 'hidden',
In this case too it will probably be better to use the shorthand `.hide()` function. It is chainable.

2022-03-29 11:14 UTC, pawelfus approved these changes
Thanks!

2022-03-30 08:37 UTC, TorsteinHonsi requested changes

2022-03-30 08:37 UTC, TorsteinHonsi commented on ts/Core/Scrollbar.ts
> +                .hide(); // initially hide the scrollbar #15863
If possible, I think it is better to hide it before add. That would prevent rendering and a potential flash of visible content.

2022-03-30 09:17 UTC, TorsteinHonsi approved these changes

2022-03-30 09:17 UTC, merged