Fixed: #16810, inverted images.
highcharts/highcharts pull request #17158
Opened 2022-04-05 13:18 UTC by DJTechnoo

Fixed: #16810, inverted image pattern on maps.

2022-04-05 13:41 UTC, circleci-mu commented
### File size comparison
No differences found

2022-04-05 13:43 UTC, circleci-mu commented
## Visual test results - Differences found
Found **15** diffing sample(s). [Please review the differences.](https://vrevs.highsoft.com/pr/17158/review)

2022-04-21 10:00 UTC, TorsteinHonsi commented
@DJTechnoo It looks like in the current state of the PR, the scaling is done on the pattern in general. But we already have a hook, `Point.calculatePatternDimensions`, for adapting the pattern to individual points. Maybe we should adapt that to not only work with width and height, but also the scale transform?

At least in theory, that would be more correct because it won't flip the pattern unless it is _actually_ applied to a flipped point. With the current approach it flips the pattern regardless of where it is used.

2022-04-22 08:09 UTC, DJTechnoo commented
Thank you, I'll dive into it right away!

2022-05-06 14:43 UTC, raf18seb requested changes
Just a few small things, see the comments below

2022-05-06 14:43 UTC, raf18seb commented on samples/unit-tests/accessibility/accessible-highmaps/demo.js
> +    const polishFlagURL =
The variable name without indicating a value would be better, e.g.
```js
const url = ...
```

2022-05-06 14:43 UTC, raf18seb commented on samples/unit-tests/accessibility/accessible-highmaps/demo.js
> +                    keys: ['hc-key', 'color.pattern.image'],
You have 2 keys defined, but your data point has 3 values: `['pl', polishFlagURL, 2],`

2022-05-06 14:43 UTC, raf18seb commented on ts/Extensions/PatternFill.ts
> +            // Check if map image pattern is flipped (#16810)
This comment here is repeated in 2 different places but both parts of code are different so I think one of the comments should be changed or should be more descriptive

2022-05-06 14:43 UTC, raf18seb commented on ts/Extensions/PatternFill.ts
> +
Unnecessary line break methinks🤔

2022-05-06 15:02 UTC, KacperMadej approved these changes
What Rafał wrote. Other than that, looks good to me 👍

2022-05-09 12:51 UTC, DJTechnoo commented on samples/unit-tests/accessibility/accessible-highmaps/demo.js
> +        chart.series[0].points[1].options.color.pattern._inverted,
After trying this, ESLint wanted me to use the dotted notation again  ಥ_ಥ

2022-05-09 14:32 UTC, raf18seb approved these changes
Thanks!

2022-05-10 11:09 UTC, TorsteinHonsi approved these changes
Awesome, thanks!

2022-05-10 11:10 UTC, TorsteinHonsi commented
Now pending CI run after merging master in.

2022-05-11 08:14 UTC, merged