feature/16968-fullscren-events
highcharts/highcharts pull request #17175
Opened 2022-04-11 15:08 UTC by mfilipiec

Added fullscreen events with API declarations and sample demo. Feature #16968

2022-04-11 15:25 UTC, mfilipiec commented
I have not prepared unit tests for this feature because it is not possible to recreate the opening of the fullscreen in these conditions.

And I have two questions, or rather advice:
- [ ] Are the names of these callback functions appropriate? 
- [ ] This arrangement in the API is ok?

![image](https://user-images.githubusercontent.com/35931601/162770234-df0d8b4e-aaf5-4427-b1a3-bdd6d30b02ba.png)

2022-04-11 15:28 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| modules/exporting.js | **7.1 kB**<br>19.0 kB | **7.2 kB**<br>19.2 kB | **44 B**<br>130 B |

2022-04-11 15:30 UTC, circleci-mu commented
## Visual test results - No difference found

---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  Added | samples/highcharts/chart/events-fullscreenopen-fullscreenclose/demo.js |

</p>
</details>

2022-04-12 12:00 UTC, raf18seb requested changes
Thanks!

I have a few comments, see below.

ps. The events names are fine imho

2022-04-12 12:00 UTC, raf18seb commented on samples/highcharts/chart/events-fullscreenopen-fullscreenclose/demo.details
> +   - Michał Filipiec
I suggest not to use polish letters (they don't display correctly in some cases)

2022-04-12 12:00 UTC, raf18seb commented on samples/highcharts/chart/events-fullscreenopen-fullscreenclose/demo.js
> +        text: 'Fullscreen'
Maybe `text: 'Fullscreen events'`?

2022-04-12 12:00 UTC, raf18seb commented on samples/highcharts/chart/events-fullscreenopen-fullscreenclose/demo.js
> +        text: 'Click the context menu and choose "Fullscreen".<br> The title size will be larger'
The button's text is "View in full screen", not "Fullscreen".

Also, there's unnecessary space after `<br>`.

Also, a dot is missing at the end of the sentence

2022-04-12 12:00 UTC, raf18seb commented on ts/Extensions/FullScreen.ts
> +                        fireEvent(chart, 'afterFullscreenOpen');
Close events are not working when pressing the exporting menu button (they work only on `escape` button).

I suggest firing events at the beginning and end of the `open` and `close` methods.

2022-04-12 13:29 UTC, raf18seb requested changes

2022-04-12 13:29 UTC, raf18seb commented on samples/highcharts/chart/events-fullscreenopen-fullscreenclose/demo.css
> +#container {
I think you should use shorter folder names. What about
```samples/highcharts/chart/fullscreen-events/...```
?

Also, do we have a folder for fullscreen demos? (does it have to be in the `/chart/` folder?)

2022-04-12 13:29 UTC, raf18seb commented on ts/Extensions/FullScreen.ts
> + *         Fullscreen title size change
Could the description be more descriptive? See e.g. API of `chart.events.afterPrint` for a reference

2022-04-12 13:50 UTC, raf18seb commented on samples/highcharts/chart/events-fullscreenopen-fullscreenclose/demo.css
> +#container {
Ok

2022-04-13 07:17 UTC, raf18seb commented on ts/Extensions/FullScreen.ts
> + *         Fullscreen title size change
@mfilipiec sorry, maybe I missclicked or maybe GitHub is showing it incorrectly.

I meant that the `Fires after fullscreen close` sentence could be more descriptive, not the sample's name.

2022-04-13 07:24 UTC, raf18seb commented
Please see my comment above.

Also, please add appropriate PR labels and edit the PR description (see similar descriptions in changelog) ("feature" -> "see", and dot at the end of the sentence).

2022-04-19 09:56 UTC, TorsteinHonsi requested changes
Thanks! 

* Regarding the naming of the events, the convention in Highcharts is to name the `before` part the same as (or similar to) the function name, then add an `after...` event if we need it. So in this case it would be `fullscreenOpen`/`afterFullscreenOpen` and `fullscreenClose`/`afterFullscreenClose`.
* Another thing we commonly do, is that the `before` event holds the main function body as its default event handler. This pattern allows implementers to `return false` in order to cancel the default behaviour. I don't know if it makes sense in this case, but it is something we can consider.
* The last thing we need to consider is whether we now need the _after_ events at all? In what scenario would we need to run logic after open or close as opposed to before?

All these things can be seen in the [Series.bindAxes](https://github.com/highcharts/highcharts/blob/2ecc2c0f909197aa4fcb59fe04cf9da27ccd9f9d/ts/Core/Series/Series.ts#L558-L627) function.

2022-04-20 13:53 UTC, mfilipiec commented
When doing this feature, I was based on the printing events as Kacper suggested in the ticket, so I split it into `before` and `after` callback functions. It seems to me that it is quite useful. For example, it is better to set the chart options just before open fullscreen and run some animation after it. 

If it is unnecessary I can remove `after` callback functions, but then also include the approach from the second point?

As for the first point, I will include it in the changes.

2022-04-22 06:41 UTC, TorsteinHonsi commented
> I was based on the printing events

I see. But the printing logic actually has functions called `beforePrint` and `afterPrint`, so the event names reflect the function names. 

I think we should skip the `after*` events for now, we can always add them later if we find it is needed.

2022-04-25 11:35 UTC, TorsteinHonsi requested changes
Thanks! Was it intentional to put the events at the end of the respective functions? In that case they need the `after*` prefix. The convention is:

* Events in the beginning of a function is named the same as the function, and are cancellable by `return false` or `e.preventDefault()`. 
* Events at the end of a function are named  `after*`.

Also, there is an issue with the TS declarations that need to be adressed.

2022-04-27 06:52 UTC, TorsteinHonsi approved these changes

2022-04-27 06:52 UTC, merged