Themes/high contrast
highcharts/highcharts pull request #17206
Opened 2022-04-21 18:03 UTC by nasin

I updated the theme colors for high contrast light and high contrast dark to show more hue variance.

2022-04-22 07:00 UTC, TorsteinHonsi requested changes
Thanks! 

Please fix the lint error (it should be caught on pre-commit, have you done `npm install` correctly?

As for the colors themselves, it works much better now. More variance. Though I think it would be a good idea to keep the same total amount of colors as we do with the default palette. When we picked the current default colors, the idea was to maximize the variance between the first few colors at the expense of the ones at the end of the array. The assumption is that we are more likely to see a line or column chart with two series than three series, which is more likely than four series etcetera. So the first few colors are prioritized in terms of contrast. Following this, the last two colors could be for example variation in brightness of any of the preceding colors.

2022-04-22 12:23 UTC, circleci-mu commented
### File size comparison
No differences found

2022-04-22 12:26 UTC, circleci-mu commented
## Visual test results - No difference found

2022-04-22 12:58 UTC, nasin commented
Hi, I updated the colors to 10 and fixed the lint issue.

2022-04-25 07:34 UTC, TorsteinHonsi approved these changes

2022-04-25 07:34 UTC, merged