Enhancement/a11y warning
highcharts/highcharts pull request #17218
Opened 2022-04-26 20:21 UTC by oysteinmoseng

Added warning by default when `accessibility.js` module is not loaded.
___
Also added the module to all remaining demos, with basic configuration.

2022-04-26 20:42 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts.js | **99.4 kB**<br>295.5 kB | **99.6 kB**<br>296.0 kB | **213 B**<br>492 B |
| highstock.js | **131.3 kB**<br>396.2 kB | **131.6 kB**<br>396.7 kB | **222 B**<br>492 B |
| highmaps.js | **124.5 kB**<br>378.9 kB | **124.7 kB**<br>379.4 kB | **214 B**<br>492 B |
| highcharts-gantt.js | **134.4 kB**<br>403.2 kB | **134.6 kB**<br>403.7 kB | **193 B**<br>492 B |
| modules/accessibility.js | **34.6 kB**<br>125.1 kB | **35.0 kB**<br>126.8 kB | **462 B**<br>1749 B |

2022-04-26 20:43 UTC, oysteinmoseng commented
@TorsteinHonsi Just occurred to me that we do have `H.error` that could be used with the `stop=false` parameter and a direct string input. Do you think there is a point in adding that overhead for consistency, or should keep as is with a simple `console.warn`?

2022-04-26 20:45 UTC, circleci-mu commented
## Visual test results - Differences found
Found **4** diffing sample(s). [Please review the differences.](https://vrevs.highsoft.com/pr/17218/review)


---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  Modified | samples/maps/demo/all-maps/demo.js |
|  Modified | samples/maps/demo/category-map/demo.js |
|  Modified | samples/maps/demo/circlemap-africa/demo.js |
|  Modified | samples/maps/demo/color-axis/demo.js |
|  Modified | samples/maps/demo/data-class-two-ranges/demo.js |
|  Modified | samples/maps/demo/diamondmap/demo.js |
|  Modified | samples/maps/demo/distribution/demo.js |
|  Modified | samples/maps/demo/eu-capitals-temp/demo.js |
|  Modified | samples/maps/demo/flight-routes/demo.js |
|  Modified | samples/maps/demo/geojson/demo.js |
|  Modified | samples/maps/demo/heatmap/demo.js |
|  Modified | samples/maps/demo/honeycomb-usa/demo.js |
|  Modified | samples/maps/demo/latlon-advanced/demo.js |
|  Modified | samples/maps/demo/map-bubble/demo.js |
|  Modified | samples/maps/demo/map-pies/demo.js |
|  Modified | samples/maps/demo/mapline-mappoint/demo.js |
|  Modified | samples/maps/demo/mappoint-latlon/demo.js |
|  Modified | samples/maps/demo/marker-clusters/demo.js |
|  Modified | samples/maps/demo/pattern-fill-map/demo.js |
|  Modified | samples/maps/demo/spider-map/demo.js |
|  Modified | samples/maps/demo/topojson-projection/demo.js |
|  Modified | samples/maps/demo/us-counties/demo.js |
|  Modified | samples/maps/demo/us-data-labels/demo.js |
|  Modified | samples/maps/demo/all-areas-as-null/demo.js |
|  Modified | samples/highcharts/accessibility/advanced-accessible/demo.js |
|  Modified | samples/highcharts/accessibility/internationalization/demo.js |
|  Modified | samples/highcharts/demo/advanced-accessible/demo.js |
|  Modified | samples/highcharts/website/static-candlestick/demo.js |
|  Modified | samples/stock/demo/all-indicators/demo.js |
|  Modified | samples/stock/demo/area/demo.js |
|  Modified | samples/stock/demo/areaspline/demo.js |
|  Modified | samples/stock/demo/basic-line/demo.js |
|  Modified | samples/stock/demo/candlestick/demo.js |
|  Modified | samples/stock/demo/compare/demo.js |
|  Modified | samples/stock/demo/dynamic-update/demo.js |
|  Modified | samples/stock/demo/flags-general/demo.js |
|  Modified | samples/stock/demo/flags-placement/demo.js |
|  Modified | samples/stock/demo/flags-shapes/demo.js |
|  Modified | samples/stock/demo/hlc/demo.js |
|  Modified | samples/highcharts/accessibility/accessible-line/demo.js |
|  Modified | samples/highcharts/accessibility/advanced-accessible/demo.js |
|  Modified | samples/highcharts/accessibility/internationalization/demo.js |
|  Modified | samples/highcharts/demo/accessible-line/demo.js |
|  Modified | samples/highcharts/demo/advanced-accessible/demo.js |
|  Modified | samples/highcharts/website/icon-chart/demo.js |
|  Modified | samples/highcharts/website/static-candlestick/demo.js |
|  Modified | samples/highcharts/website/static-chart/demo.js |
|  Modified | samples/gantt/demo/custom-labels/demo.js |
|  Modified | samples/gantt/demo/download-pdf/demo.js |
|  Modified | samples/gantt/demo/interactive-gantt/demo.js |
|  Modified | samples/gantt/demo/inverted/demo.js |
|  Modified | samples/gantt/demo/left-axis-table/demo.js |
|  Modified | samples/gantt/demo/progress-indicator/demo.js |
|  Modified | samples/gantt/demo/project-management/demo.js |
|  Modified | samples/gantt/demo/resource-management/demo.js |
|  Modified | samples/gantt/demo/styled-mode/demo.js |
|  Modified | samples/gantt/demo/subtasks/demo.js |
|  Modified | samples/gantt/demo/with-navigation/demo.js |
|  Modified | samples/highcharts/demo/3d-area-multiple/demo.js |
|  Modified | samples/highcharts/demo/arc-diagram/demo.js |
|  Modified | samples/highcharts/demo/column-comparison/demo.js |
|  Modified | samples/highcharts/demo/funnel3d/demo.js |
|  Modified | samples/highcharts/demo/line-boost/demo.js |
|  Modified | samples/highcharts/demo/network-graph/demo.js |
|  Modified | samples/highcharts/demo/parallel-coordinates/demo.js |
|  Modified | samples/highcharts/demo/scatter-boost/demo.js |
|  Modified | samples/highcharts/demo/spline-symbols/demo.js |
|  Modified | samples/highcharts/demo/streamgraph/demo.js |
|  Modified | samples/highcharts/demo/synchronized-charts/demo.js |
|  Modified | samples/highcharts/demo/treemap-large-dataset/demo.js |

</p>
</details>

2022-04-27 10:29 UTC, TorsteinHonsi requested changes
Thanks! As you mentioned, I agree we should use the Highcharts `error` feature instead of `console.warn`, in order to get the warning into our usual error flow (with its hooks for error handling).

2022-04-28 06:58 UTC, TorsteinHonsi approved these changes
Thanks!

2022-04-28 06:58 UTC, merged