bugfix/15608-macd-color
highcharts/highcharts pull request #17334
Opened 2022-05-27 14:04 UTC by karolkolodziej

Fixed #15608, the MACD indicator did not have default colors.

2022-05-27 14:24 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| indicators/indicators-all.js | **22.7 kB**<br>99.5 kB | **22.8 kB**<br>100.1 kB | **94 B**<br>597 B |

2022-05-27 14:27 UTC, circleci-mu commented
## Visual test results - Differences found
Found **6** diffing sample(s). [Please review the differences.](https://vrevs.highsoft.com/pr/17334/review)

2022-05-31 08:38 UTC, pawelfus requested changes
I think both lines should have a color different from the histogram's columns (and different from each other of course)

2022-06-01 12:34 UTC, karolkolodziej commented on ts/Stock/Indicators/MACD/MACDIndicator.ts
> +                    this.options.signalLine.styles &&
It is optional see:
``` ts
export interface MACDLineOptions {
    styles?: MACDLineStyleOptions;
    zones?: Array<SeriesZonesOptions>;
}
```

2022-06-01 14:45 UTC, pawelfus approved these changes
Thanks!

2022-06-07 12:54 UTC, TorsteinHonsi approved these changes

2022-06-07 12:54 UTC, merged