bugfix/17331-panning-type-type
highcharts/highcharts pull request #17354
Opened 2022-06-03 15:44 UTC by KacperMadej

Fixed #17331, resolved TS type collision.

---
The collision is caused by the usage of properties with the same key/name. This fix is from the `chart.panning.type` point of view (instead of the attempt in #17332 where I tried with `series.map.data.geometry.type`).

2022-06-03 16:03 UTC, circleci-mu commented
### File size comparison
No differences found

2022-06-03 16:06 UTC, circleci-mu commented
## Visual test results - No difference found

2022-06-13 12:48 UTC, bre1470 requested changes
This should be solvable with a `@declare` tag, but does not work:
```
         * @declare    Highcharts.ChartPanningTypeValue
         * @type       {string}
         * @validvalue ["x", "y", "xy"]
         * @default    {highcharts|highstock} x
         * @default    {highmaps} xy
```
I will fix the generator and give you a note.

2022-06-13 14:11 UTC, bre1470 commented
You can install `github:highcharts/highcharts-declarations-generator#v1.1.22` now and combine `@declare` with `@validvalue` to avoid conflicts.

2022-06-13 14:21 UTC, bre1470 requested changes

2022-06-13 14:21 UTC, bre1470 commented on ts/Core/Chart/Chart.ts
> +
You can reduced this in the other doclet to `@declare Highcharts.OptionsChartPanningTypeValue` and keep there @validvalue and @type.

2022-08-23 10:28 UTC, TorsteinHonsi commented
@KacperMadej

2022-10-04 13:11 UTC, bre1470 approved these changes
Thank you! Looks good. 👍

2022-10-04 14:06 UTC, TorsteinHonsi approved these changes

2022-10-04 14:06 UTC, merged