featrue/17285-nodeOpacity
highcharts/highcharts pull request #17448
Opened 2022-06-28 10:16 UTC by karolkolodziej

Feature #17285, added `nodeOpacity` property for the `sankey` series.

2022-06-28 10:39 UTC, circleci-mu commented
### File size comparison
No differences found

2022-06-28 10:41 UTC, circleci-mu commented
## Visual test results - Differences found
Found **20** diffing sample(s). [Please review the differences.](https://vrevs.highsoft.com/pr/17448/review)

2022-06-28 12:31 UTC, pawelfus requested changes
Two minor things:
- a tiny change in the docs 
- `dataLabels` should inherit the opacity too

I'm not sure about the organization and the dependency wheel series types, up to @TorsteinHonsi

2022-06-28 12:31 UTC, pawelfus commented on ts/Series/Sankey/SankeySeries.ts
> +                 * Opacity for the links between nodes in the sankey diagram in
for the nodes*

2022-06-28 14:54 UTC, karolkolodziej commented
@raf18seb visual comparison should be sufficient ;)

2022-06-29 07:39 UTC, pawelfus approved these changes
> Are the visual changes acceptable or should I adjust the default settings?

I'm not sure. I think the Organization chart should either set the inactive state to links too or remain unchanged. 

The rest looks good 👍

2022-07-04 08:00 UTC, TorsteinHonsi requested changes
> I'm not sure about the organization and the dependency wheel series types, up to @TorsteinHonsi

I think those are good once we fix the problem with the opacity being applied twice.

2022-07-04 10:25 UTC, TorsteinHonsi approved these changes
Thanks!

2022-07-04 10:25 UTC, merged