bugfix/17472-searchPointByAngle-polar `
highcharts/highcharts pull request #17485
Opened 2022-07-08 13:10 UTC by karolkolodziej

Fixed #17472, shared tooltip did not work.in the polar chart.

2022-07-08 13:16 UTC, bre1470 requested changes
One thing about typing needs be fixed.

Otherwise it looks good. The only drawback might be that is not accessible anymore, but it does not look like it is used outside of polar anyway.

2022-07-08 13:16 UTC, bre1470 commented on ts/Series/PolarComposition.ts
> +            'searchPointByAngle' :
`'searchPointByAngle'` is now a string literal type. Try `typeof searchPointByAngle`

2022-07-08 13:24 UTC, bre1470 approved these changes
Thanks! Looks good. 👍

2022-07-08 13:39 UTC, circleci-mu commented
### File size comparison
No differences found

2022-07-08 13:41 UTC, circleci-mu commented
## Visual test results - No difference found

2022-08-05 07:47 UTC, TorsteinHonsi approved these changes

2022-08-05 07:47 UTC, merged

2022-08-12 06:35 UTC, GabrieleT0 commented
it seems that the problem is not solved, in this example it is still present: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/polar-spider

2022-08-12 11:34 UTC, bre1470 commented
Thank you for the feedback. The changes are not yet released, see https://jsfiddle.net/bre1470/dk6ypz3w/ for the working example based on the current GitHub master.

2022-08-12 11:40 UTC, GabrieleT0 commented
Thank you so much!

2022-08-12 11:44 UTC, GabrieleT0 commented
There is a date for the release? I'm doing my bechelor's thesis and I'm using Hightchart, it's very important for me. Thank you.

2022-08-15 07:58 UTC, bre1470 commented
We expect the next release to be ready this month.