docs/15216-datalabels-zindex
highcharts/highcharts pull request #17494
Opened 2022-07-12 10:42 UTC by madepiet

Fixed #15216 API for dataLabels.zIndex.

2022-07-12 20:51 UTC, KacperMadej approved these changes

2022-08-05 12:13 UTC, TorsteinHonsi requested changes
Thanks! A little chage required to adhere to the style guide.

2022-08-05 12:13 UTC, TorsteinHonsi commented on ts/Core/Series/SeriesDefaults.ts
> +         * or use a zIndex of 2 to display it behind the series.
1. No line wraps without a paragraph, [see the style guide](https://github.com/highcharts/highcharts/blob/master/repo-guidelines.md#1-avoid-line-breaks-without-paragraphs).
2. Also, zIndex is code, so it should be in back ticks `zIndex`.

2022-08-10 08:47 UTC, TorsteinHonsi approved these changes

2022-08-10 08:47 UTC, merged