Demos/demos data update2
highcharts/highcharts pull request #17504
Opened 2022-07-14 06:15 UTC by fanuntez

Demos data

2022-07-14 06:43 UTC, circleci-mu commented
### File size comparison
No differences found

2022-07-14 06:45 UTC, circleci-mu commented
## Visual test results - Differences found
Found **7** diffing sample(s). [Please review the differences.](https://vrevs.highsoft.com/pr/17504/review)


---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  Modified | samples/highcharts/demo/polar-radial-bar/demo.js |
|  Modified | samples/highcharts/demo/polygon/demo.js |
|  Modified | samples/highcharts/demo/parliament-chart/demo.js |
|  Modified | samples/highcharts/demo/dumbbell/demo.js |
|  Modified | samples/highcharts/demo/bar-negative-stack/demo.js |
|  Modified | samples/highcharts/demo/organization-chart/demo.js |
|  Modified | samples/highcharts/demo/line-basic/demo.js |
|  Modified | samples/highcharts/demo/column-comparison/demo.js |

</p>
</details>

2022-08-05 13:29 UTC, TorsteinHonsi requested changes
Nice work! Some minor change requests.

2022-08-18 11:31 UTC, fanuntez commented on samples/highcharts/demo/combo-dual-axes/demo.js
> +        text: 'Average Monthly Temperature and Rainfall in Karasjok, 2021'
Didn't think this one through :sweat_smile:

2022-08-22 10:12 UTC, merged