bugfix/17522-lastPrice-label
highcharts/highcharts pull request #17524
Opened 2022-07-20 11:08 UTC by karolkolodziej

Fixed #17522, when the `lastPrice` label was enabled, there was an error in the console.

2022-07-20 11:27 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highstock.js | **131.7 kB**<br>396.8 kB | **131.7 kB**<br>396.9 kB | **2 B**<br>20 B |

2022-07-20 11:29 UTC, circleci-mu commented
## Visual test results - No difference found

2022-07-20 12:40 UTC, raf18seb requested changes
I have one comment, see below

2022-07-20 12:40 UTC, raf18seb commented on samples/unit-tests/indicator-price-indicator/recalculations/demo.js
> +    });
Please use one `redraw` instead of multiple

2022-07-28 11:51 UTC, raf18seb approved these changes
Thanks!

2022-08-05 07:49 UTC, TorsteinHonsi approved these changes

2022-08-05 07:49 UTC, merged