New demos for color axis
highcharts/highcharts pull request #17544
Opened 2022-07-28 13:49 UTC by kamil-musialowski

Added new API demos for `colorAxis.stops` and `series.colorKey`.

2022-07-28 14:01 UTC, raf18seb requested changes
Nice demos! I have a few comments, see below

2022-07-28 14:01 UTC, raf18seb commented on samples/highcharts/coloraxis/coloraxis-stops/demo.js
> +    document.getElementById('darkThemeBtn').addEventListener('click', function () {
Same as above

2022-07-28 14:09 UTC, circleci-mu commented
### File size comparison
No differences found

2022-07-28 14:12 UTC, circleci-mu commented
## Visual test results - No difference found

---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  Added | samples/highcharts/coloraxis/color-key-with-stops/demo.js |
|  Added | samples/highcharts/coloraxis/coloraxis-stops/demo.js |

</p>
</details>

2022-07-29 12:37 UTC, raf18seb approved these changes
Thanks!

2022-08-04 12:32 UTC, TorsteinHonsi approved these changes
Thanks, nice demos!

2022-08-04 12:32 UTC, merged