Refactor arearange/parallel axis: use ordered events
highcharts/highcharts pull request #17638
Opened 2022-08-24 10:19 UTC by TorsteinHonsi

Used ordered events (`afterTranslate`) in order to avoid `parallelAxis` logic inside the `arearange` module. 

_Disclaimer_
No TypeScript was harmed during this PR. But some any-casts were fixed.

2022-08-24 10:39 UTC, circleci-mu commented
### File size comparison
No differences found

2022-08-24 10:41 UTC, circleci-mu commented
## Visual test results - Differences found
Found **2** diffing sample(s). [Please review the differences.](https://vrevs.highsoft.com/pr/17638/review)

2022-08-25 12:43 UTC, bre1470 requested changes
Looks overall good! 👍 

Maybe something to optimize...

2022-08-25 12:43 UTC, bre1470 commented on ts/Series/AreaRange/AreaRangePoint.ts
> +    public plotLowX?: number = void 0;
If it is optional we do not have assign undefined.

2022-08-25 12:43 UTC, bre1470 commented on ts/Series/ColumnRange/ColumnRangeSeries.ts
> +                    (point as any).rectPlotY,
as `PolarPoint`?

2022-08-29 12:02 UTC, K009 approved these changes
👍

2022-09-06 13:22 UTC, bre1470 approved these changes

2022-09-07 07:27 UTC, merged