bugfix/17177-followtouchmove-update
highcharts/highcharts pull request #17729
Opened 2022-09-14 13:22 UTC by kamil-musialowski

Fixed #17177, updating followTouchMove didn't work.

Demo for testing: https://jsfiddle.net/BlackLabel/c3qkuzvp/
API: https://api.highcharts.com/highcharts/tooltip.followTouchMove

2022-09-19 09:07 UTC, circleci-mu commented
## Visual test results - No difference found

2022-09-19 11:08 UTC, TorsteinHonsi requested changes
Thanks for the fix!

Moving the `pick` statement out to where `followTouchMove` is used is a good idea, since it was previously only set once. 

However, we now have the same code appearing three times in the codebase, and twice in the same function:
`pick((tooltip && tooltip.options.followTouchMove), true)`

To reduce the code size, can you try one of these?
1. Restore `this.followTouchMove`, but move the assignment to `Pointer.onContainerTouchStart`. Thereby it should always be up-to-date when needed.
2. In the `pinch` function, create a local variable `const followTouchMove = touchesLength === 1 && pick(....)`.

Then you can test the impact against master using `gulp filesize`. The first approach has the advantage of only doing the calculation once, and the advantage of the second is that we avoid setting a global property.

2022-09-21 14:07 UTC, kamil-musialowski commented
Thank you for the review, it's been really helpful in understanding different approaches while working with our Core.

> 1. Restore this.followTouchMove, but move the assignment to Pointer.onContainerTouchStart. Thereby it should always be up-to-date when needed.
> 2. In the pinch function, create a local variable const followTouchMove = touchesLength === 1 && pick(....).

I have tested both of the proposed solutions, and it turns out that the second approach is a bit better (305.28kB on no.1 vs 305.22kB on no.2), so that's the one commited to this PR.

2022-09-26 09:04 UTC, TorsteinHonsi approved these changes

2022-09-26 09:04 UTC, merged