Enhancement: exporting button useHTML
highcharts/highcharts pull request #17740
Opened 2022-09-19 12:19 UTC by TorsteinHonsi

Added `exporting.buttonOptions.useHTML` to allow HTML with icons etc. in exporting buttons.

2022-09-19 12:38 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| modules/exporting.js | **7.2 kB**<br>19.1 kB | **7.2 kB**<br>19.1 kB | **10 B**<br>38 B |

2022-09-19 12:40 UTC, circleci-mu commented
## Visual test results - No difference found

---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  Added | samples/highcharts/exporting/buttons-text-usehtml/demo.js |

</p>
</details>

2022-09-19 12:52 UTC, herndlm commented
Hey, regarding
> Figure out why the [standard button doesn't work](https://jsfiddle.net/highcharts/mpa29qcr/) with useHTML
if you mean the weird hover/click behaviour - this seems to be fixable with e.g.
```css
div.highcharts-button span {
    pointer-events: none;
}
```
See also http://jsfiddle.net/zfngxoow/6/, in my PR I linked an old state that was missing that CSS

2022-09-19 20:43 UTC, TorsteinHonsi commented
> this seems to be fixable with e.g.

Yes it does, but that has some side effects in cases where we actually want to be able to interact with the span. Before I accept that solution, I'll see if it can be fixed at a deeper level.

2022-09-20 19:44 UTC, bre1470 requested changes
- The code side looks good, but something is off with the implementation.
- In the preview the symbol highlights disappear as soon as I am over the symbol. The click only works on the highlight (in the padding space).
- There is also a padding issue with the right side of the highlight.
- In highcharts-utils I do not see any symbols in the preview sample. There is no network failure so I guess the CSS lacks something.

2022-09-21 08:47 UTC, bre1470 approved these changes
Tested with the wrong commit. Works flawless. 👍

2022-09-21 08:47 UTC, merged