Tools: Reduced dependencies
highcharts/highcharts pull request #17772
Opened 2022-09-23 10:08 UTC by bre1470

- Replaced mkdirp with fs.mkdir.
- Fixed sass.

2022-09-23 10:22 UTC, circleci-mu commented
## Visual test results - No difference found

2022-09-23 11:29 UTC, circleci-mu commented
### File size comparison
No differences found

2022-09-27 10:32 UTC, TorsteinHonsi requested changes
Thanks! We're using stylelint though. It is the CSS equivalent of ESLint.

https://github.com/highcharts/highcharts/blob/9cc8e25da44d59a3cdb2017eb611cea5e4fbaeb9/package.json#L113-L122

2022-09-27 10:43 UTC, bre1470 commented
stylelint = +75 node_modules 😞

2022-09-27 11:16 UTC, TorsteinHonsi approved these changes

2022-09-27 11:17 UTC, merged