Migration to LegendItem.legendItem
highcharts/highcharts pull request #17770
Opened 2022-09-22 13:09 UTC by bre1470

- Moved legendItem/legendLine/legendSymbol to legendData.item/.line/.symbol.
- Added doclets for `Highcharts.LegendItemObject`, `Highcharts.Series#color`, and `Highcharts.Series#legendItem`.
- Added type test for `Highcharts.Series#legendItem`.
- Fixed #16846

2022-09-22 13:29 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts.js | **99.7 kB**<br>296.3 kB | **99.8 kB**<br>296.5 kB | **127 B**<br>281 B |
| highstock.js | **132.6 kB**<br>401.3 kB | **132.6 kB**<br>401.5 kB | **-27 B**<br>284 B |
| highmaps.js | **125.2 kB**<br>380.9 kB | **125.3 kB**<br>381.3 kB | **113 B**<br>392 B |
| highcharts-gantt.js | **135.6 kB**<br>405.8 kB | **135.7 kB**<br>406.1 kB | **84 B**<br>284 B |
| modules/accessibility.js | **35.2 kB**<br>127.6 kB | **35.2 kB**<br>127.7 kB | **50 B**<br>120 B |
| modules/heatmap.js | **6.8 kB**<br>19.5 kB | **6.8 kB**<br>19.5 kB | **-1 B**<br>38 B |

2022-09-29 11:29 UTC, TorsteinHonsi commented
It's quite a big overhead. I didn't fine read the changes, but do you have any immediate thoughts about this?
![Skjermbilde 2022-09-29 kl  13 27 42](https://user-images.githubusercontent.com/227836/193019941-3e34b40b-c9a9-4ebc-bede-c5b408294ce3.png)

2022-09-30 11:35 UTC, bre1470 commented
I optimized access, but there is not much more left. The 300 kB likely come from the added path element `.legendData.` which sums up and can not be minified. I use local variables where useful, but handling happens in many different places.
57 times x 11 bytes = 627 bytes - declarations.

2022-10-03 08:47 UTC, TorsteinHonsi requested changes
In addition to the inline comment, I think we should look into naming. 

I think `legendItem` is a more appropriate name than `legendData`. The only downside is a possible naming collision with older HC version, where `legendItem` means the text SVGLabel itself. But implementations refering to `legendItem` will fail anyway, so I don't see that as much of a problem. 

Then if we call it `legendItem` I think what we currently call `legendData.item` should be called `legendItem.text` (or label?), which is more descriptive.

2022-10-03 08:47 UTC, TorsteinHonsi commented on ts/Core/Legend/Legend.ts
>          );
Is this used? I thought `item.legendLine` as moved to `legendData.line`? And if so, we should add `line` to the array at line 502.

2022-10-03 08:47 UTC, TorsteinHonsi commented on ts/Core/Legend/Legend.ts
> +        }
We can probably just call `legend.destroyItem` for each item.

2022-10-03 08:47 UTC, TorsteinHonsi commented on ts/Core/Legend/Legend.ts
> +        }
... Then the `destroyThat` function can be inlined again.

2022-10-05 08:58 UTC, TorsteinHonsi commented
To do: 

> I think `legendItem` is a more appropriate name than `legendData`.

2022-10-06 16:01 UTC, TorsteinHonsi approved these changes

2022-10-06 16:01 UTC, merged