Fixed drag and drop of packed bubbles.
highcharts/highcharts pull request #17793
Opened 2022-09-28 13:13 UTC by bre1470

Fixed #17785

2022-09-28 13:33 UTC, circleci-mu commented
### File size comparison
No differences found

2022-09-28 13:35 UTC, circleci-mu commented
## Visual test results - No difference found

2022-09-29 10:38 UTC, kamil-musialowski approved these changes
Everything works fine now!

2022-09-29 11:22 UTC, TorsteinHonsi requested changes
Thanks!

As this is a bugfix, appropriate tagging and description is missing though: https://github.com/highcharts/highcharts/tree/master/changelog#writing-content-for-the-changelog

2022-09-30 08:00 UTC, TorsteinHonsi approved these changes

2022-09-30 08:00 UTC, merged