Added useHTML for series-label
highcharts/highcharts pull request #17792
Opened 2022-09-28 09:05 UTC by MarkusBarstad

Series-labels now support HTML-formatting. See #17282

2022-09-28 09:17 UTC, TorsteinHonsi requested changes
Thanks!

It must also be documented in the API. Add it to [SeriesLabelDefaults.ts](https://github.com/highcharts/highcharts/blob/v10.2.1/ts/Extensions/SeriesLabel/SeriesLabelDefaults.ts) with a description.

2022-09-28 09:25 UTC, circleci-mu commented
### File size comparison
No differences found

2022-09-28 09:28 UTC, circleci-mu commented
## Visual test results - No difference found

2022-09-28 10:22 UTC, MarkusBarstad commented
> Thanks!
> 
> It must also be documented in the API. Add it to [SeriesLabelDefaults.ts](https://github.com/highcharts/highcharts/blob/v10.2.1/ts/Extensions/SeriesLabel/SeriesLabelDefaults.ts) with a description.

I was a bit unsure about where in `SeriesLabelDefaults.ts` to put it so I put it after `style` since this follows the order of the `SeriesLabelOptions` in `SeriesLabelOptions.d.ts`

2022-09-28 10:26 UTC, MarkusBarstad commented
Woops i closed this PR on accident, sorry about that! x)

2022-09-29 11:25 UTC, TorsteinHonsi approved these changes

2022-09-29 11:25 UTC, merged