bugfix/17741-stocktools-update
highcharts/highcharts pull request #17883
Opened 2022-10-25 10:14 UTC by bm64

Fixed #17741, Stock Tools GUI was not working after update.

2022-10-25 10:34 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| modules/annotations.js | **17.9 kB**<br>63.7 kB | **17.9 kB**<br>63.7 kB | **12 B**<br>12 B |
| modules/annotations-advanced.js | **24.7 kB**<br>96.4 kB | **24.7 kB**<br>96.4 kB | **10 B**<br>12 B |

2022-10-25 10:37 UTC, circleci-mu commented
## Visual test results - No difference found

2022-10-25 11:44 UTC, pawelfus requested changes
The test is missing

2022-10-31 10:34 UTC, pawelfus approved these changes
Thanks!

2022-10-31 13:51 UTC, TorsteinHonsi approved these changes

2022-10-31 13:51 UTC, merged