Stock Tools GUI - restore inactive state for indicators button
highcharts/highcharts pull request #17953
Opened 2022-11-08 14:48 UTC by bm64

Fixed #16487, Indicators button in Stock Tools GUI was active after popup close.

2022-11-09 10:15 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| modules/annotations.js | **17.9 kB**<br>63.7 kB | **17.9 kB**<br>63.8 kB | **34 B**<br>124 B |
| modules/annotations-advanced.js | **24.8 kB**<br>96.4 kB | **24.8 kB**<br>96.6 kB | **51 B**<br>124 B |

2022-11-15 10:20 UTC, TorsteinHonsi commented
Pending review by @pawelfus

2022-11-15 10:47 UTC, pawelfus requested changes
Instead of adding more `indicators` related code in Popup.ts, could you solve it in a different way? To me, it seems "X"-button fires the` closePopup` event, but not the `deselectButton` event (like "add"-button does) - could you check it, please?

2022-11-15 15:48 UTC, pawelfus approved these changes
Approved, thank you!

2022-11-16 07:39 UTC, TorsteinHonsi approved these changes

2022-11-16 07:39 UTC, merged