Added getting started page in Highcharts Stock docs.
highcharts/highcharts pull request #17959
Opened 2022-11-09 15:40 UTC by bm64

Added getting started page in Highcharts Stock docs.

2022-11-09 16:00 UTC, circleci-mu commented
### File size comparison
No differences found

2022-11-10 10:59 UTC, pawelfus requested changes
One tiny thing, otherwise good!

2022-11-10 10:59 UTC, pawelfus commented on docs/stock/getting-started-stock.md
> +    <script src="https://code.highcharts.com/stock/highstock.js"></script>
`highstock.js` -> `modules/stock.js`

2022-11-14 13:48 UTC, pawelfus approved these changes

2022-11-14 13:49 UTC, pawelfus commented
A word of explanation:
All other products have "getting started" doc-page. This one is almost the same as the one for the Gantt product

2022-11-14 18:22 UTC, TorsteinHonsi approved these changes
Thanks!

2022-11-14 18:22 UTC, merged