bugfix/17918-inset-points-zoom
highcharts/highcharts pull request #17996
Opened 2022-11-18 10:31 UTC by kamil-musialowski

Fixed #17918, zooming to insets in TopoJSON maps was not working.

2022-11-18 10:41 UTC, DJTechnoo approved these changes
To me it looks good!

2022-11-18 10:51 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highmaps.js | **125.5 kB**<br>381.2 kB | **125.5 kB**<br>381.4 kB | **58 B**<br>259 B |

2022-11-18 10:53 UTC, circleci-mu commented
## Visual test results - No difference found

2022-11-18 11:00 UTC, hubertkozik requested changes
Looks great to me! I have marked only editorial cases - not relevant to code logic.

2022-11-18 11:00 UTC, hubertkozik commented on ts/Series/Map/MapPoint.ts
> +            const inset = isNumber(point.insetIndex) &&
I would remove this 'enter' / new line after the if statement line. I have checked other HC files and in 99% of cases, there is no new line after the if statement 😊

2022-11-18 14:05 UTC, madepiet approved these changes

2022-11-20 10:40 UTC, hubertkozik approved these changes
Good job! Thanks!

2022-11-21 09:31 UTC, magdalena-gut approved these changes

2022-11-21 09:40 UTC, kamil-musialowski commented
@TorsteinHonsi, as you have asked in #17918, we checked for similar code implementations in the core, but we haven't found anything - so we decided to stick with your solution as it is.

Also, I have decided to change the map in the unit test (so that it's also usable for TopoJSON insets), so please take a look if you are okay with it.

Thank you!

2022-11-21 10:24 UTC, TorsteinHonsi approved these changes
Thanks, it looks good!

Regarding the unit tests, we have a simplified map for insets at http://localhost:3030/samples/#test/unit-tests/maps/mapview-inset, but I'm okay with changing the TopoJSON test too.

2022-11-21 10:24 UTC, merged