DataOnDemand
highcharts/highcharts pull request #17993
Opened 2022-11-17 18:34 UTC by bre1470

2022-11-17 18:55 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts.js | **99.7 kB**<br>295.5 kB | **99.8 kB**<br>295.6 kB | **45 B**<br>65 B |
| highstock.js | **132.7 kB**<br>400.6 kB | **132.8 kB**<br>400.7 kB | **106 B**<br>65 B |
| highmaps.js | **125.1 kB**<br>380.6 kB | **125.2 kB**<br>380.6 kB | **66 B**<br>65 B |
| highcharts-gantt.js | **135.3 kB**<br>405.4 kB | **135.4 kB**<br>405.4 kB | **34 B**<br>65 B |
| modules/annotations.js | **17.9 kB**<br>63.7 kB | **17.9 kB**<br>63.7 kB | **7 B**<br>10 B |
| modules/annotations-advanced.js | **24.8 kB**<br>96.4 kB | **24.8 kB**<br>96.4 kB | **8 B**<br>10 B |

2022-11-17 18:57 UTC, circleci-mu commented
## Visual test results - No difference found

---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  ? | samples/highcharts/blog/blog-landing-page/demo.js |
|  ? | samples/highcharts/blog/blog-custom-map/demo.js |
|  ? | samples/highcharts/blog/homepage/demo.js |
|  ? | samples/highcharts/blog/blog-planet-atmospheres/demo.js |
|  ? | samples/highcharts/blog/blog-themes-demo/demo.js |
|  ? | samples/highcharts/blog/blog-update-options/demo.js |

</p>
</details>

2022-11-18 06:34 UTC, pawellysy reviewed
Looks fine, but is there any demo/test, where we could test this functionality?

2022-11-18 08:22 UTC, karolkolodziej requested changes

2022-11-18 08:22 UTC, karolkolodziej commented on ts/Data/Stores/DataStore.ts
> +     * Regular expression to extract the store type (group 1) from the
The name of the variable probably needs to be changed to match the comment.

2022-11-18 09:27 UTC, karolkolodziej approved these changes

2022-11-18 10:15 UTC, bre1470 commented
@pawellysy I like to use it in this PR: https://github.com/highcharts/highcharts/pull/17992

2022-11-18 11:29 UTC, merged