Db/one direction sync
highcharts/highcharts pull request #18005
Opened 2022-11-21 13:54 UTC by goransle

2022-11-21 14:35 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts.js | **99.7 kB**<br>295.5 kB | **99.8 kB**<br>295.6 kB | **46 B**<br>65 B |
| highstock.js | **132.7 kB**<br>400.6 kB | **132.8 kB**<br>400.7 kB | **106 B**<br>65 B |
| highmaps.js | **125.1 kB**<br>380.6 kB | **125.2 kB**<br>380.6 kB | **67 B**<br>65 B |
| highcharts-gantt.js | **135.3 kB**<br>405.4 kB | **135.4 kB**<br>405.4 kB | **34 B**<br>65 B |
| modules/annotations.js | **17.9 kB**<br>63.7 kB | **17.9 kB**<br>63.7 kB | **8 B**<br>10 B |
| modules/annotations-advanced.js | **24.8 kB**<br>96.4 kB | **24.8 kB**<br>96.4 kB | **8 B**<br>10 B |

2022-11-21 14:38 UTC, circleci-mu commented
## Visual test results - No difference found

---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  ? | samples/highcharts/blog/blog-landing-page/demo.js |
|  ? | samples/highcharts/blog/blog-custom-map/demo.js |
|  ? | samples/highcharts/blog/homepage/demo.js |
|  ? | samples/highcharts/blog/blog-planet-atmospheres/demo.js |
|  ? | samples/highcharts/blog/blog-themes-demo/demo.js |
|  ? | samples/highcharts/blog/blog-update-options/demo.js |

</p>
</details>

2022-11-23 07:12 UTC, TorsteinHonsi reviewed
`'visibility': true,` is not consistent with our common naming conventions. In Highcharts we use `visible: true` since it's a boolean.

2022-11-23 07:25 UTC, goransle commented
> `'visibility': true,` is not consistent with our common naming conventions. In Highcharts we use `visible: true` since it's a boolean.

Yeah, the naming is a separate issue 😓 Note that this refers to the name of the "events" that are synced, so i.e. `visible` might not make sense in this context.

2022-11-23 08:07 UTC, karolkolodziej requested changes
To do:
- [ ] Requested changes.
- [ ] `Component.ts` cleanup.
- [ ] The difference between the `emitter` and `hander` needs to be described.

In addition to @TorsteinHonsi comment, setting `visible: true` would imply that we actually make something visible where we only sync show/hide events. 
However, if we decided to go that path `selection` also needs to be changed to `selected`

2022-11-23 08:17 UTC, goransle commented on ts/Dashboard/Component/Component.ts
> +                  Sync.defaultHandlers[handlerName];
hmm, eslint complains otherwise 😖

2022-11-23 11:58 UTC, goransle commented on samples/cypress/dashboard/chart-interaction-one-way/demo.mjs
> +import Dashboard from '../../../../code/es-modules/Dashboard/Dashboard.js';
Seems like there's something funny going on with the module loading again 😢

2022-11-29 09:16 UTC, pawellysy approved these changes
Looks good!

2022-12-05 09:43 UTC, merged