Db/datagridcomponent-bindings
highcharts/highcharts pull request #18079
Opened 2022-12-02 13:52 UTC by sebastianbochan

### Issues:
- [ ] - bindings did not support datagrid
- [ ] - datagrid plugin is not initialized (missing constructor)

2022-12-02 14:56 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts.js | **99.6 kB**<br>295.9 kB | **99.7 kB**<br>296.0 kB | **43 B**<br>65 B |
| highstock.js | **132.8 kB**<br>401.0 kB | **132.8 kB**<br>401.0 kB | **37 B**<br>65 B |
| highmaps.js | **125.4 kB**<br>381.3 kB | **125.5 kB**<br>381.3 kB | **56 B**<br>65 B |
| highcharts-gantt.js | **135.6 kB**<br>405.7 kB | **135.6 kB**<br>405.8 kB | **47 B**<br>65 B |
| modules/annotations.js | **17.9 kB**<br>63.8 kB | **17.9 kB**<br>63.8 kB | **8 B**<br>10 B |
| modules/annotations-advanced.js | **24.8 kB**<br>96.5 kB | **24.8 kB**<br>96.5 kB | **8 B**<br>10 B |

2022-12-02 14:59 UTC, circleci-mu commented
## Visual test results - No difference found

---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  ? | samples/highcharts/blog/blog-landing-page/demo.js |
|  ? | samples/highcharts/blog/blog-custom-map/demo.js |
|  ? | samples/highcharts/blog/homepage/demo.js |
|  ? | samples/highcharts/blog/blog-planet-atmospheres/demo.js |
|  ? | samples/highcharts/blog/blog-themes-demo/demo.js |
|  ? | samples/highcharts/blog/blog-update-options/demo.js |

</p>
</details>

2022-12-05 14:02 UTC, bre1470 approved these changes
Looks good! 👍

2022-12-05 14:02 UTC, bre1470 commented on ts/masters/modules/dashboard-plugin.src.ts
> +    DataGridPlugin.custom.connectDataGrid(DataGrid);
This is just for classic mode. This part is not for ESM-based demos.

2022-12-05 14:02 UTC, bre1470 commented on ts/masters/modules/dashboard-plugin.src.ts
>  if (G.win.Dashboard) {
In ESM you have to do the connection yourself.

2022-12-14 08:11 UTC, karolkolodziej approved these changes
This part looks good! In the future, this demo needs some cleaning :)

2022-12-14 08:28 UTC, pawellysy requested changes
Few comments

2022-12-14 08:28 UTC, pawellysy commented on ts/Dashboard/Actions/Bindings.ts
>                  const componentClass = Component.getComponent(json.$class);
If this is only for `Highcharts` Component, there is no need for selecting the correct component, we can define it straight away.

2022-12-14 09:34 UTC, pawellysy approved these changes
Looks good!

2022-12-14 09:48 UTC, merged