Db/remove-heat
highcharts/highcharts pull request #18120
Opened 2022-12-09 12:34 UTC by bre1470

2022-12-09 12:53 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts.js | **99.6 kB**<br>295.9 kB | **99.7 kB**<br>296.0 kB | **43 B**<br>65 B |
| highstock.js | **132.8 kB**<br>401.0 kB | **132.8 kB**<br>401.0 kB | **37 B**<br>65 B |
| highmaps.js | **125.4 kB**<br>381.3 kB | **125.5 kB**<br>381.3 kB | **55 B**<br>65 B |
| highcharts-gantt.js | **135.6 kB**<br>405.7 kB | **135.6 kB**<br>405.8 kB | **48 B**<br>65 B |
| modules/annotations.js | **17.9 kB**<br>63.8 kB | **17.9 kB**<br>63.8 kB | **8 B**<br>10 B |
| modules/annotations-advanced.js | **24.8 kB**<br>96.5 kB | **24.8 kB**<br>96.5 kB | **8 B**<br>10 B |

2022-12-09 13:17 UTC, karolkolodziej requested changes
Looks ok but I'm not sure if the color axis is necessary.
I would remove it.

2022-12-12 07:04 UTC, karolkolodziej approved these changes

2022-12-12 08:06 UTC, TorsteinHonsi commented
Some improvements for the map (besides just acting as navigation)

* Colored markers for the cities. Tie it up to the `colorAxis` and give it a color that corresponds to the current temperature. Consider `mapbubble`, or bigger markers.
* Data labels could also print the current temperature to make the map more relevant. How about a bigger marker or bubble with the temperature inside? For inspiration: https://jsfiddle.net/highcharts/v284de5y/1/
* The legend, saying "World Map" and "Cities" is stating the obvious and can be removed.
* Preferably use the default projection.
* Add some color to the land mass, but that's probably up to the designer.

2022-12-12 08:12 UTC, pawellysy approved these changes
👍

2022-12-12 11:03 UTC, merged