Tools: build for Evergreen browsers
highcharts/highcharts pull request #18189
Opened 2022-12-21 13:22 UTC by raf18seb

Added tasks for making a copy of `code` folder into `code/es5` folder (but without any dts files).

2022-12-21 13:27 UTC, raf18seb commented
Q: Should I not create new `tools/build-es5` util but instead maybe add a parameter handled by the existing `tools/build.js`?

2022-12-21 13:31 UTC, TorsteinHonsi commented
> Q: Should I not create new tools/build-es5 util but instead maybe add a parameter handled by the existing tools/build.js

In general, if we end up with a solution where the same (or similar) tooling code is duplicated in two related tasks, it is not optimal. It is more secure and more maintainable if we don't repeat ourselves.

2022-12-21 13:42 UTC, circleci-mu commented
### File size comparison
No differences found

2022-12-21 13:45 UTC, circleci-mu commented
## Visual test results - Differences found
Found **4** diffing sample(s). [Please review the differences.](https://vrevs.highsoft.com/pr/18189/review)

2022-12-21 14:03 UTC, bre1470 commented
@TorsteinHonsi How different do you expect the `es5` pipeline to be in 6 months?

2022-12-21 14:18 UTC, TorsteinHonsi commented
> How different do you expect the es5 pipeline to be in 6 months?

@bre1470 Not very different... I don't expect us to spend too much resources on optimizing the legacy pipeline, but just make sure it works.

2023-01-04 08:40 UTC, TorsteinHonsi requested changes
Thanks, I finally got to review this.

I noticed that the compiled JS files are not generated for the `es5` folder. Only `.src.js`. We should generated compiled files.

On an opposite note, the `es-modules` filed were generated for es5. Do we need those for the legacy path? Or can we assume that those who load `es-modules` require modern browsers? It would save us some complexity, and I think it's a fair assumption to make. 

@bre1470 FYI

2023-01-04 09:18 UTC, bre1470 commented
That is fair assumption imho. I suggest to move to a version with Promise support out of the box, I believe it's `ES2016` as target. So we will need some extra CLI argument for the gulp task for `ES5` target.

2023-01-09 13:58 UTC, raf18seb commented
> I noticed that the compiled JS files are not generated for the es5 folder. Only .src.js. We should generated compiled files.

It turned out that the order of tasks was incorrect (first should be `scripts-es5` to create `es5/` folder, then `scripts-compile` to compile all the `.src.js` files). I wrote the whole new script before I figured out this small order issue 😅

The `es5/es-modules` folder is now simply being deleted at the end of `scripts-es5` run.

2023-01-09 18:22 UTC, bre1470 requested changes
Some comments before the session tomorrow.

2023-01-09 18:22 UTC, bre1470 commented on tools/build.js
>          css: './code/js/es-modules'
Two thoughts here:
- `path.join` from `require('path')` is the proper way to connect path fragments
- Not related to your work, so you do not need to fix it. I just notice that the css path makes no sense. There is no `code/js` folder structure anywhere

2023-01-09 18:22 UTC, bre1470 commented on tools/gulptasks/scripts-es5.js
> +                path => path.endsWith('.d.ts') && fsLib.deleteFile(path)
Invalid masters DTS can be ignored in our case as es5 does not provide DTS files, if I am not mistaken. This needs some investigation.

2023-01-12 09:19 UTC, TorsteinHonsi approved these changes
Thanks! Pending approval by @bre1470 .

2023-01-12 13:56 UTC, bre1470 approved these changes
Good job. 👍 `scripts-es5` itself does create `code/es5` but the `dist` task fails with
```
Error: Could not find tmp/demo/sidebar.html
  If demos are built elsewhere, the path can be specified in git-ignore-me.properties by the demos.path property.
    at getLocalSidebar (/Users/highsoft/GitHub/highcharts/tools/gulptasks/dist-examples.js:193:19)
```

Maybe it is unrelated, but it is not clear, if `code/es5` gets copied over into `../highcharts-dist`.
The `build/dist/highcharts/code/es5` is there were it should be.

2023-01-13 07:29 UTC, TorsteinHonsi approved these changes
Thanks!

The sidebar issue is being handled in https://github.com/highcharts/highcharts/issues/18234

2023-01-13 07:29 UTC, merged