refactor/heatmap types
highcharts/highcharts pull request #18182
Opened 2022-12-20 20:17 UTC by TorsteinHonsi

Refactoring, cleaning, optimizing and typesafing heatmap series.

2022-12-20 20:36 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highmaps.js | **125.9 kB**<br>382.3 kB | **125.9 kB**<br>382.3 kB | **13 B**<br>15 B |
| modules/heatmap.js | **6.9 kB**<br>19.6 kB | **6.9 kB**<br>19.6 kB | **15 B**<br>15 B |

2022-12-20 20:39 UTC, circleci-mu commented
## Visual test results - No difference found

---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  Modified | samples/maps/demo/heatmap/demo.js |
|  Modified | samples/maps/demo/heatmap/demo.js |

</p>
</details>

2022-12-21 09:02 UTC, bre1470 requested changes
Looks nice! Please see comments for optimizations.

2022-12-21 09:02 UTC, bre1470 commented on ts/Series/Heatmap/HeatmapPoint.ts
> +        super.applyOptions.call(this, options, x);
Good catch. Actually `super.applyOptions(options, x);` is sufficient.

2022-12-21 09:07 UTC, TorsteinHonsi commented on ts/Series/ColorMapComposition.ts
> +    ): ColorAttribsType {
It is by design. ColorAttribsType is a subset of SVGAttributes and CSSObject.

2022-12-21 10:03 UTC, MarkusBarstad approved these changes
A lot more readable!

2022-12-21 10:09 UTC, bre1470 approved these changes

2022-12-21 13:27 UTC, merged