bugfix/18025-gridlines-across-panes
highcharts/highcharts pull request #18203
Opened 2022-12-27 12:50 UTC by kamil-musialowski

Fixed #18025, gridlines were rendered across panes.

2022-12-27 13:12 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts.js | **99.8 kB**<br>296.2 kB | **99.7 kB**<br>296.2 kB | **-48 B**<br>51 B |
| highstock.js | **132.9 kB**<br>401.2 kB | **132.9 kB**<br>401.3 kB | **-4 B**<br>51 B |
| highmaps.js | **126.0 kB**<br>382.6 kB | **126.1 kB**<br>382.7 kB | **99 B**<br>51 B |
| highcharts-gantt.js | **135.7 kB**<br>406.0 kB | **135.7 kB**<br>406.0 kB | **-18 B**<br>47 B |

2022-12-27 13:14 UTC, circleci-mu commented
## Visual test results - Differences found
Found **1** diffing sample(s). [Please review the differences.](https://vrevs.highsoft.com/pr/18203/review)

2022-12-27 14:08 UTC, pawellysy requested changes
Good job! Few comments

2022-12-27 14:08 UTC, pawellysy commented on ts/Core/Axis/Axis.ts
> +        const evt: Partial<Event&Axis.PlotLinePathOptions> = {
When I think about it, I think it should be just `Partial<Axis.PlotLinePathOptions>`Since there are no `Event`'s attributes, but your call.

2022-12-27 14:08 UTC, pawellysy commented on ts/Core/Axis/Axis.ts
>          }
Now, when looking at it, the body of `between` function looks a lot like what we implemented. Could you maybe investigate, why didn't it work correctly?

2022-12-29 14:03 UTC, pawellysy approved these changes
Looks good!

2023-01-04 08:16 UTC, TorsteinHonsi approved these changes
Thanks!

2023-01-04 08:17 UTC, merged