Db/csv-component-demo
highcharts/highcharts pull request #18211
Opened 2022-12-28 13:12 UTC by sebastianbochan

2022-12-28 13:32 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts.js | **99.8 kB**<br>296.2 kB | **99.9 kB**<br>296.2 kB | **80 B**<br>65 B |
| highstock.js | **132.9 kB**<br>401.2 kB | **133.0 kB**<br>401.3 kB | **48 B**<br>65 B |
| highmaps.js | **126.0 kB**<br>382.6 kB | **126.1 kB**<br>382.7 kB | **87 B**<br>65 B |
| highcharts-gantt.js | **135.7 kB**<br>406.0 kB | **135.8 kB**<br>406.0 kB | **48 B**<br>65 B |
| modules/annotations.js | **17.9 kB**<br>63.8 kB | **17.9 kB**<br>63.8 kB | **8 B**<br>10 B |
| modules/annotations-advanced.js | **24.8 kB**<br>96.5 kB | **24.8 kB**<br>96.5 kB | **8 B**<br>10 B |

2022-12-28 13:35 UTC, circleci-mu commented
## Visual test results - Differences found
Found **5** diffing sample(s). [Please review the differences.](https://vrevs.highsoft.com/pr/18211/review)


---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  Modified | samples/highcharts/data/delimiters/demo.js |
|  ? | samples/highcharts/blog/blog-landing-page/demo.js |
|  ? | samples/highcharts/blog/blog-custom-map/demo.js |
|  ? | samples/highcharts/blog/homepage/demo.js |
|  ? | samples/highcharts/blog/blog-planet-atmospheres/demo.js |
|  ? | samples/highcharts/blog/blog-themes-demo/demo.js |
|  ? | samples/highcharts/blog/blog-update-options/demo.js |

</p>
</details>

2022-12-29 07:01 UTC, karolkolodziej requested changes
It looks like the sync between the CSV and charts is broken. 
Could you please investigate?

2022-12-29 12:45 UTC, sebastianbochan commented
When you click outside the textarea, the values are updated.

2022-12-29 13:45 UTC, karolkolodziej approved these changes

2022-12-30 08:44 UTC, bre1470 approved these changes
Looks good! 👍

2022-12-30 08:55 UTC, merged