bugfix/16841-stochastic-missing-D-line
highcharts/highcharts pull request #18220
Opened 2022-12-30 10:49 UTC by bm64

Fixes #16841, Slow Stochastic Indicator was missing %D line when K value was NaN.

2022-12-30 11:08 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| indicators/indicators-all.js | **22.8 kB**<br>99.7 kB | **22.8 kB**<br>99.8 kB | **-6 B**<br>26 B |

2022-12-30 11:11 UTC, circleci-mu commented
## Visual test results - No difference found

2023-01-02 13:59 UTC, pawelfus requested changes
Thanks!
See my comments inline

+ missing test

2023-01-02 13:59 UTC, pawelfus commented on ts/Stock/Indicators/Stochastic/StochasticIndicator.ts
> +            yData.push([isNaN(K) ? yData[yData.length - 1][0] : K, null]);
Can we add a few more conditions here?
1. When CL = 0, then we can render the line at 0 anyway
2. When it's a bug for the first point, then `yData[yData.length - 1]` will be undefined, so use simply `null`, but please check it (+test)

I couldn't find an official statement from the Stochastic's author in his paperwork about what should be done in this case, but repeating the value seems to be a reasonable solution (if the price is frozen, then the indicator will be too)

2023-01-23 09:08 UTC, TorsteinHonsi commented
@bm64 Pending resolution to @pawelfus' change request

2023-01-30 06:13 UTC, TorsteinHonsi commented
Pending final review from @pawelfus

2023-02-01 13:20 UTC, pawelfus requested changes
Some nit-picking again, sorry!
Overall looks (and works) well!

2023-02-01 13:20 UTC, pawelfus commented on ts/Stock/Indicators/Stochastic/StochasticIndicator.ts
> +                    yData[yData.length - 1] &&
Micro opt: cache manually the variable. In some cases browsers nicely cache the value, however, I'm not sure about this particular case - we actually do change the length of the array inside the if-else block. You can get the value easily from `push()`: `length = yData.push( ... );` and use it: `yData[length - 1]` or even better: `length = yData.push( ... ) - 1;` (however, personally, I don't like this hanging `-1` style). Or use it in a line above when pushing to `xData`

Note: I couldn't find how`.length` getter works - [ecma](https://262.ecma-international.org/13.0/#sec-properties-of-array-instances-length) is enigmatic. Does it actually look for the last object on the array, then read the index, then increment it?

2023-02-01 13:20 UTC, pawelfus commented on ts/Stock/Indicators/Stochastic/StochasticIndicator.ts
> +            if (isNaN(K)) {
Could you please add a comment with an explanation of what actually happens inside the if-else? The one we discussed a few weeks ago: imho the logic is not so self-explanatory

2023-02-06 14:34 UTC, TorsteinHonsi commented
Pending resolution to Pawel's change requests

2023-02-07 09:11 UTC, pawelfus approved these changes
Thanks!

2023-02-07 10:43 UTC, TorsteinHonsi approved these changes

2023-02-07 10:43 UTC, merged