db/navigator-climate-demo
highcharts/highcharts pull request #18223
Opened 2023-01-02 08:08 UTC by karolkolodziej

2023-01-02 08:26 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts.js | **99.8 kB**<br>296.2 kB | **99.8 kB**<br>296.2 kB | **78 B**<br>65 B |
| highstock.js | **132.9 kB**<br>401.2 kB | **133.0 kB**<br>401.3 kB | **48 B**<br>65 B |
| highmaps.js | **126.0 kB**<br>382.6 kB | **126.1 kB**<br>382.7 kB | **87 B**<br>65 B |
| highcharts-gantt.js | **135.7 kB**<br>406.0 kB | **135.8 kB**<br>406.0 kB | **48 B**<br>65 B |
| modules/annotations.js | **17.9 kB**<br>63.8 kB | **17.9 kB**<br>63.8 kB | **8 B**<br>10 B |
| modules/annotations-advanced.js | **24.8 kB**<br>96.5 kB | **24.8 kB**<br>96.5 kB | **8 B**<br>10 B |

2023-01-02 08:29 UTC, circleci-mu commented
## Visual test results - No difference found

---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  Modified | samples/highcharts/data/delimiters/demo.js |
|  ? | samples/highcharts/blog/blog-landing-page/demo.js |
|  ? | samples/highcharts/blog/blog-custom-map/demo.js |
|  ? | samples/highcharts/blog/homepage/demo.js |
|  ? | samples/highcharts/blog/blog-planet-atmospheres/demo.js |
|  ? | samples/highcharts/blog/blog-themes-demo/demo.js |
|  ? | samples/highcharts/blog/blog-update-options/demo.js |

</p>
</details>

2023-01-02 13:41 UTC, sebastianbochan approved these changes

2023-01-02 14:17 UTC, bre1470 commented
Looks good so far. Will you do the interactivity points after my PR of the detail chart, or should I wait for this one to merge?

2023-01-02 14:26 UTC, karolkolodziej commented
I can make it after yours PR :) feel free to merge yours :)

2023-01-02 15:11 UTC, bre1470 commented
Okay. Map PR is merged now. :)

2023-01-03 08:43 UTC, sebastianbochan requested changes

2023-01-03 08:43 UTC, sebastianbochan commented on samples/dashboard/demos/climate/demo.css
> +    fill: black;
I would prefer to use hex everywhere instead of mixing static values and hex.

2023-01-03 08:53 UTC, sebastianbochan approved these changes

2023-01-03 09:59 UTC, bre1470 approved these changes
There are some visual bugs in some ranges, but this seems to be something in Highcharts.

2023-01-03 10:28 UTC, merged