db/climate-marker
highcharts/highcharts pull request #18230
Opened 2023-01-02 17:02 UTC by bre1470

If we go with this design, we should reduce the number of cities.

2023-01-02 17:22 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts.js | **99.8 kB**<br>296.2 kB | **99.8 kB**<br>296.2 kB | **78 B**<br>65 B |
| highstock.js | **132.9 kB**<br>401.2 kB | **133.0 kB**<br>401.3 kB | **48 B**<br>65 B |
| highmaps.js | **126.0 kB**<br>382.6 kB | **126.1 kB**<br>382.7 kB | **87 B**<br>65 B |
| highcharts-gantt.js | **135.7 kB**<br>406.0 kB | **135.8 kB**<br>406.0 kB | **48 B**<br>65 B |
| modules/annotations.js | **17.9 kB**<br>63.8 kB | **17.9 kB**<br>63.8 kB | **8 B**<br>10 B |
| modules/annotations-advanced.js | **24.8 kB**<br>96.5 kB | **24.8 kB**<br>96.5 kB | **8 B**<br>10 B |

2023-01-02 17:24 UTC, circleci-mu commented
## Visual test results - No difference found

---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  Modified | samples/highcharts/data/delimiters/demo.js |
|  ? | samples/highcharts/blog/blog-landing-page/demo.js |
|  ? | samples/highcharts/blog/blog-custom-map/demo.js |
|  ? | samples/highcharts/blog/homepage/demo.js |
|  ? | samples/highcharts/blog/blog-planet-atmospheres/demo.js |
|  ? | samples/highcharts/blog/blog-themes-demo/demo.js |
|  ? | samples/highcharts/blog/blog-update-options/demo.js |

</p>
</details>

2023-01-03 10:52 UTC, pawelfus approved these changes

2023-01-03 10:52 UTC, pawelfus commented on samples/dashboard/demos/climate/demo.js
> +                            return labelFormatter(point.y, true);
Nitpicking: unnecessary extra argument

2023-01-03 11:19 UTC, TorsteinHonsi commented
> If we go with this design, we should reduce the number of cities.

I don't think we need to do that. The data labels handle overlapping gracefully. Instead, I think we should
* Use true data label mapmarkers as seen in the `maps/demo/mappoint-datalabels-mapmarker` demo. The difference is that the marker _is_ the label itself, instead of the label being superimposed on the point marker. The advantage being handling of label overlapping and, optionally, nice stacking of labels if `allowOverlap` is true.
* Show Celcius instead of Kelvin. That way we have mostly two digits and can...
* Make the labels smaller.

See the [Netatmo Weathermap](https://weathermap.netatmo.com/) for inpiration. Overlapping of labels isn't a problem.

2023-01-03 11:27 UTC, bre1470 commented on samples/dashboard/demos/climate/demo.js
> +                            return labelFormatter(point.y, true);
Good catch.

2023-01-03 13:39 UTC, TorsteinHonsi requested changes
Remaining change requests:
* Show Celcius instead of Kelvin. That way we have mostly two digits and can...
* Make the labels smaller.

2023-01-04 12:40 UTC, TorsteinHonsi commented
This can be avoided by setting ordering the points by descending latitude.
![Skjermbilde 2023-01-04 kl  13 38 09](https://user-images.githubusercontent.com/227836/210556838-c9baf651-d597-4372-a998-cc364c406dd4.png)

2023-01-05 07:26 UTC, karolkolodziej requested changes
After changing the navigator, the text inside the markers is not centered.
![image](https://user-images.githubusercontent.com/57004120/210724875-d295b366-45ec-4a59-98e4-eae8b3c10178.png)

2023-01-05 08:43 UTC, bre1470 commented
Yes, I noticed a lot is going on there.
- The styling fix unfortunately does not work for label shapes.
- The animation of label shapes has some position flaw, which makes them move with every redraw.
- In addition the border of the selected city is gone.
- Also the styling fix does not cover selected cities.

2023-01-05 10:12 UTC, bre1470 commented
> * Also the styling fix does not cover selected cities.

Pending PR: https://github.com/highcharts/highcharts/pull/18247

2023-01-05 14:18 UTC, sebastianbochan commented on samples/dashboard/demos/climate/demo.css
> +#world-map .highcharts-series-1 .highcharts-data-label:nth-child(odd) text {
We can use default style for text and use only `even` as extension. We do not need to declare odd and even.

2023-01-05 14:51 UTC, sebastianbochan approved these changes

2023-01-06 15:32 UTC, merged