Implemented Serialization Helper for GoogleSheets Converter.
highcharts/highcharts pull request #18236
Opened 2023-01-03 15:04 UTC by pawellysy

Implemented Serializer helper for google sheets converter.

2023-01-03 15:27 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts.js | **99.8 kB**<br>296.2 kB | **99.8 kB**<br>296.2 kB | **78 B**<br>65 B |
| highstock.js | **132.9 kB**<br>401.2 kB | **133.0 kB**<br>401.3 kB | **48 B**<br>65 B |
| highmaps.js | **126.0 kB**<br>382.6 kB | **126.1 kB**<br>382.7 kB | **87 B**<br>65 B |
| highcharts-gantt.js | **135.7 kB**<br>406.0 kB | **135.8 kB**<br>406.0 kB | **49 B**<br>65 B |
| modules/annotations.js | **17.9 kB**<br>63.8 kB | **17.9 kB**<br>63.8 kB | **8 B**<br>10 B |
| modules/annotations-advanced.js | **24.8 kB**<br>96.5 kB | **24.8 kB**<br>96.5 kB | **8 B**<br>10 B |

2023-01-03 15:30 UTC, circleci-mu commented
## Visual test results - Differences found
Found **1** diffing sample(s). [Please review the differences.](https://vrevs.highsoft.com/pr/18236/review)


---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  Modified | samples/highcharts/data/delimiters/demo.js |
|  ? | samples/highcharts/blog/blog-landing-page/demo.js |
|  ? | samples/highcharts/blog/blog-custom-map/demo.js |
|  ? | samples/highcharts/blog/homepage/demo.js |
|  ? | samples/highcharts/blog/blog-planet-atmospheres/demo.js |
|  ? | samples/highcharts/blog/blog-themes-demo/demo.js |
|  ? | samples/highcharts/blog/blog-update-options/demo.js |

</p>
</details>

2023-01-03 18:56 UTC, bre1470 requested changes

2023-01-03 18:56 UTC, bre1470 commented on ts/Dashboard/SerializeHelper/GoogleSheetsConverterHelper.ts
> +        parseDateFn?: string;
This is not implemented and should be removed.

2023-01-03 18:56 UTC, bre1470 commented on ts/Dashboard/SerializeHelper/GoogleSheetsConverterHelper.ts
> +
Spacing should be corrected. Same over import section comment.

2023-01-04 09:11 UTC, bre1470 approved these changes
Thank you! Looks good. 👍

2023-01-04 09:16 UTC, karolkolodziej approved these changes

2023-01-04 09:16 UTC, karolkolodziej commented on ts/Dashboard/SerializeHelper/GoogleSheetsConverterHelper.ts
> +const { merge } = U;
Move declaration under the direct import.

2023-01-04 09:38 UTC, merged