bugfix/18166-mapline-stroke-width-zoom-scale
highcharts/highcharts pull request #18253
Opened 2023-01-05 14:32 UTC by kamil-musialowski

Fixed #18166, line width set on point was not scaling on zoom in `mapline`.

2023-01-05 14:52 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highmaps.js | **126.1 kB**<br>382.7 kB | **126.0 kB**<br>382.9 kB | **-68 B**<br>231 B |

2023-01-05 14:55 UTC, circleci-mu commented
## Visual test results - Differences found
Found **1** diffing sample(s). [Please review the differences.](https://vrevs.highsoft.com/pr/18253/review)

2023-01-09 09:20 UTC, DJTechnoo approved these changes

2023-01-09 10:49 UTC, magdalena-gut approved these changes

2023-01-10 14:43 UTC, madepiet approved these changes

2023-01-12 09:14 UTC, TorsteinHonsi requested changes
Awesome, it works great for both `map` and `mapline` series. With smooth animation and all 👏 

As a further improvement, I think we should refactor out the `series.point` loop so that we don't repeat ourselves. The logic inside is repeated twice in MapSeries.ts, the only difference is the `scale` or `scaleStep`.

2023-01-16 09:03 UTC, TorsteinHonsi approved these changes

2023-01-16 09:03 UTC, merged