Migration: SMAIndicator
highcharts/highcharts pull request #18267
Opened 2023-01-09 15:42 UTC by marvin19

Improved SMAIndicator.

2023-01-09 16:05 UTC, circleci-mu commented
## Visual test results - No difference found

2023-01-09 17:46 UTC, bre1470 requested changes
Thank you. Some requests:
- [ ] `/* eslint-disable/enable valid-jsdoc */` are redundant and can be removed. The rule has been relaxed and downgraded to a warning.
- [ ] Indicator options lacks the last section comment.

2023-01-10 10:05 UTC, bre1470 requested changes

2023-01-10 10:05 UTC, bre1470 commented on ts/Stock/Indicators/IKH/IKHIndicator.ts
> +     */
This comment should be removed. We already have the comment above this one.

2023-01-10 10:05 UTC, bre1470 commented on ts/Stock/Indicators/SMA/SMAIndicator.ts
> +     */
Same here.

2023-01-12 11:38 UTC, TorsteinHonsi approved these changes
Thanks!

2023-01-12 11:38 UTC, merged