db/chart-update-store
highcharts/highcharts pull request #18270
Opened 2023-01-10 11:37 UTC by karolkolodziej

- [ ] Basic functionality 
- [ ] Restore focus on input 
- [ ] Test

2023-01-10 11:57 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts.js | **99.8 kB**<br>296.3 kB | **100.0 kB**<br>296.3 kB | **206 B**<br>65 B |
| highstock.js | **132.9 kB**<br>401.3 kB | **133.0 kB**<br>401.4 kB | **44 B**<br>65 B |
| highmaps.js | **126.1 kB**<br>382.7 kB | **126.2 kB**<br>382.8 kB | **126 B**<br>65 B |
| highcharts-gantt.js | **135.8 kB**<br>406.1 kB | **135.8 kB**<br>406.1 kB | **36 B**<br>65 B |
| modules/annotations.js | **17.9 kB**<br>63.8 kB | **18.0 kB**<br>63.8 kB | **8 B**<br>10 B |
| modules/annotations-advanced.js | **24.8 kB**<br>96.5 kB | **24.8 kB**<br>96.5 kB | **8 B**<br>10 B |

2023-01-10 12:20 UTC, circleci-mu commented
## Visual test results - No difference found

---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  Modified | samples/highcharts/data/delimiters/demo.js |
|  ? | samples/highcharts/blog/blog-landing-page/demo.js |
|  ? | samples/highcharts/blog/blog-custom-map/demo.js |
|  ? | samples/highcharts/blog/homepage/demo.js |
|  ? | samples/highcharts/blog/blog-planet-atmospheres/demo.js |
|  ? | samples/highcharts/blog/blog-themes-demo/demo.js |
|  ? | samples/highcharts/blog/blog-update-options/demo.js |

</p>
</details>

2023-01-10 15:56 UTC, bre1470 requested changes
Please see comments.

2023-01-10 16:39 UTC, pawellysy approved these changes

2023-01-12 13:45 UTC, bre1470 approved these changes

2023-01-12 13:45 UTC, bre1470 commented on ts/Extensions/DashboardPlugins/DataGridComponent.ts
> +                    });
Good job. 👍 It is quite some overhead. Let's do this for now. Maybe in the future we should check, if we can save and check the `table.version` property.

2023-01-12 14:04 UTC, merged