db/climate-hamburger
highcharts/highcharts pull request #18280
Opened 2023-01-11 14:33 UTC by karolkolodziej

2023-01-11 14:53 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts.js | **99.8 kB**<br>296.3 kB | **100.0 kB**<br>296.3 kB | **206 B**<br>65 B |
| highstock.js | **132.9 kB**<br>401.3 kB | **133.0 kB**<br>401.4 kB | **44 B**<br>65 B |
| highmaps.js | **126.1 kB**<br>382.7 kB | **126.2 kB**<br>382.8 kB | **126 B**<br>65 B |
| highcharts-gantt.js | **135.8 kB**<br>406.1 kB | **135.8 kB**<br>406.1 kB | **38 B**<br>65 B |
| modules/annotations.js | **17.9 kB**<br>63.8 kB | **18.0 kB**<br>63.8 kB | **8 B**<br>10 B |
| modules/annotations-advanced.js | **24.8 kB**<br>96.5 kB | **24.8 kB**<br>96.5 kB | **8 B**<br>10 B |

2023-01-11 14:56 UTC, circleci-mu commented
## Visual test results - No difference found

---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  Modified | samples/highcharts/data/delimiters/demo.js |
|  ? | samples/highcharts/blog/blog-landing-page/demo.js |
|  ? | samples/highcharts/blog/blog-custom-map/demo.js |
|  ? | samples/highcharts/blog/homepage/demo.js |
|  ? | samples/highcharts/blog/blog-planet-atmospheres/demo.js |
|  ? | samples/highcharts/blog/blog-themes-demo/demo.js |
|  ? | samples/highcharts/blog/blog-update-options/demo.js |

</p>
</details>

2023-01-12 15:29 UTC, pawelfus commented on samples/dashboard/demos/climate/demo.js
> +                                    darModeClass = 'dark-mode';
I agree with your suggestion above: prefix + className, as we do in Highcharts.

2023-01-12 17:02 UTC, pawelfus commented
Note:
This PR causes loading sources in sync (instead of lazy-loading)

2023-01-13 10:46 UTC, sebastianbochan requested changes

2023-01-13 10:46 UTC, sebastianbochan commented on samples/dashboard/demos/climate/demo.js
> +                                    dataScope = 'TXC';
You can remove the `dataScope` from If/ELSE and place it after. 

```
let temperatureScale = temperatureScale === 'C' ? 'F' : 'C';

dataScope = 'TX' + temperatureScale;
```

2023-01-13 10:46 UTC, sebastianbochan commented on samples/dashboard/demos/climate/demo.js
> +    }
Just an idea to replace a lot of IFs with a more generic code

```
const columns = ['TN', 'TX'];
const metric = ['C', 'F'];

columns.forEach(column => {
   metric.forEach(metric => {
        if (!cityDataTable.columns[column][metric]) {
             cityDataTable.columns[column][metric] = cityDataTable.columns[column].map(el =>
            Highcharts.correctFloat(
                 metric === 'C' ? (el - 273.15) : (el * (9 / 5) - 459.67), 
            3)
        }
   });
});


```

2023-01-13 11:01 UTC, bre1470 requested changes

2023-01-13 11:01 UTC, bre1470 commented on samples/dashboard/demos/climate/demo.js
> +        cityDataTable.columns.TXC = cityDataTable.columns.TX.map(el =>
Use `DataTable.setColumns` and `const = DataTable.getColumn`.

2023-01-16 09:55 UTC, bre1470 approved these changes
Thank you! Looks good. 👍

2023-01-16 11:33 UTC, pawelfus approved these changes
Thanks!

2023-01-16 12:32 UTC, sebastianbochan approved these changes

2023-01-16 12:34 UTC, merged