db/navigator-colors
highcharts/highcharts pull request #18289
Opened 2023-01-12 13:35 UTC by bre1470

2023-01-12 13:58 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts.js | **99.8 kB**<br>296.3 kB | **100.0 kB**<br>296.3 kB | **206 B**<br>65 B |
| highstock.js | **132.9 kB**<br>401.3 kB | **133.0 kB**<br>401.4 kB | **44 B**<br>65 B |
| highmaps.js | **126.1 kB**<br>382.7 kB | **126.2 kB**<br>382.8 kB | **126 B**<br>65 B |
| highcharts-gantt.js | **135.8 kB**<br>406.1 kB | **135.8 kB**<br>406.1 kB | **38 B**<br>65 B |
| modules/annotations.js | **17.9 kB**<br>63.8 kB | **18.0 kB**<br>63.8 kB | **8 B**<br>10 B |
| modules/annotations-advanced.js | **24.8 kB**<br>96.5 kB | **24.8 kB**<br>96.5 kB | **8 B**<br>10 B |

2023-01-12 14:01 UTC, circleci-mu commented
## Visual test results - No difference found

---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  Modified | samples/highcharts/data/delimiters/demo.js |
|  ? | samples/highcharts/blog/blog-landing-page/demo.js |
|  ? | samples/highcharts/blog/blog-custom-map/demo.js |
|  ? | samples/highcharts/blog/homepage/demo.js |
|  ? | samples/highcharts/blog/blog-planet-atmospheres/demo.js |
|  ? | samples/highcharts/blog/blog-themes-demo/demo.js |
|  ? | samples/highcharts/blog/blog-update-options/demo.js |

</p>
</details>

2023-01-12 14:55 UTC, pawelfus commented
> I struggle with the shapes of the handle elements in navigator, because these are SVGs

Created simple arrows for that: https://jsfiddle.net/BlackLabel/xqew7o6p/

> And the reposition of the scrollbar to the top calls also for a hack.

Please, skip that.

2023-01-17 12:43 UTC, pawelfus requested changes
Looks good! Just some nitpicking:

- I don't believe I'm the one asking this.. 😅 but could you please move the right arrowhead by 1-2px to the right? The same distance from the mask border as the left one: 
![image](https://user-images.githubusercontent.com/1453926/212901213-551b9b64-8d8c-45d2-b6e2-4ff10a3d058a.png)
- could you change the scrollbar's track background? As for the scrollbar buttons, let's keep them as they are or use the same colors as mask arrows. What do you think @nasin ? Right now it's not possible to disable them

2023-01-17 12:54 UTC, nasin approved these changes
All of this looks good. I just noted that the highlight color for the table rows is different from what I have in Figma.

2023-01-17 12:54 UTC, nasin commented on samples/dashboard/demos/climate/demo.css
> +    background-color: #46475d;
I was using this as the highlight color for table cells: #5352BE

2023-01-18 13:30 UTC, sebastianbochan approved these changes

2023-01-18 14:53 UTC, pawelfus commented
I don't see my requested changes..?

2023-01-18 16:09 UTC, merged