Migration: DEMAIndicator
highcharts/highcharts pull request #18298
Opened 2023-01-13 14:51 UTC by marvin19

Improved DEMAIndicator and DEMAOptions. Also checked DEMAPoint.

2023-01-13 15:11 UTC, circleci-mu commented
### File size comparison
No differences found

2023-01-13 15:14 UTC, circleci-mu commented
## Visual test results - No difference found

2023-01-13 15:47 UTC, bre1470 requested changes
Some `prototype` references can be replaced with `super` calls.

2023-01-16 11:39 UTC, bre1470 approved these changes
Thank you! Looks good. 👍

2023-01-16 11:49 UTC, TorsteinHonsi approved these changes

2023-01-16 11:50 UTC, merged