Dashboards, added license header to all ts files, plugins and css.
highcharts/highcharts pull request #18308
Opened 2023-01-16 14:18 UTC by sebastianbochan

- [x] - CSS files
- [x] - TS modules
- [x] - TS classes
- [x] - plugins
- [x] - packages

2023-01-16 14:47 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts.js | **99.8 kB**<br>296.3 kB | **100.0 kB**<br>296.3 kB | **205 B**<br>65 B |
| highstock.js | **132.9 kB**<br>401.3 kB | **133.0 kB**<br>401.4 kB | **44 B**<br>65 B |
| highmaps.js | **126.1 kB**<br>382.7 kB | **126.2 kB**<br>382.8 kB | **126 B**<br>65 B |
| highcharts-gantt.js | **135.8 kB**<br>406.1 kB | **135.8 kB**<br>406.1 kB | **38 B**<br>65 B |
| modules/annotations.js | **17.9 kB**<br>63.8 kB | **18.0 kB**<br>63.8 kB | **8 B**<br>10 B |
| modules/annotations-advanced.js | **24.8 kB**<br>96.5 kB | **24.8 kB**<br>96.5 kB | **8 B**<br>10 B |

2023-01-17 07:54 UTC, pawellysy approved these changes

2023-01-17 11:32 UTC, karolkolodziej approved these changes

2023-01-17 12:23 UTC, pawelfus requested changes
Just a minor things

2023-01-17 12:23 UTC, pawelfus commented on css/dashboard/gui.scss
> + * @license Highcharts
Highcharts Dashboards*

2023-01-17 12:23 UTC, pawelfus commented on css/dashboard/lightDarkTheme.scss
> + * @license Highcharts
Highcharts Dashboards*

2023-01-17 12:23 UTC, pawelfus commented on css/datagrid.scss
> + * @license Highcharts
Highcharts Dashboards*
(probably in the future will be changed)

2023-01-17 14:24 UTC, pawelfus approved these changes
Thanks!

2023-01-17 14:25 UTC, merged