Db/edit mode design
highcharts/highcharts pull request #18322
Opened 2023-01-18 11:28 UTC by pawellysy

2023-01-18 11:49 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts.js | **99.8 kB**<br>296.3 kB | **100.0 kB**<br>296.3 kB | **205 B**<br>65 B |
| highstock.js | **132.9 kB**<br>401.3 kB | **133.0 kB**<br>401.4 kB | **44 B**<br>65 B |
| highmaps.js | **126.1 kB**<br>382.7 kB | **126.2 kB**<br>382.8 kB | **126 B**<br>65 B |
| highcharts-gantt.js | **135.8 kB**<br>406.1 kB | **135.8 kB**<br>406.1 kB | **38 B**<br>65 B |
| modules/annotations.js | **17.9 kB**<br>63.8 kB | **18.0 kB**<br>63.8 kB | **8 B**<br>10 B |
| modules/annotations-advanced.js | **24.8 kB**<br>96.5 kB | **24.8 kB**<br>96.5 kB | **9 B**<br>10 B |

2023-01-18 11:52 UTC, circleci-mu commented
## Visual test results - No difference found

---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  Modified | samples/highcharts/data/delimiters/demo.js |
|  ? | samples/highcharts/blog/blog-landing-page/demo.js |
|  ? | samples/highcharts/blog/blog-custom-map/demo.js |
|  ? | samples/highcharts/blog/homepage/demo.js |
|  ? | samples/highcharts/blog/blog-planet-atmospheres/demo.js |
|  ? | samples/highcharts/blog/blog-themes-demo/demo.js |
|  ? | samples/highcharts/blog/blog-update-options/demo.js |

</p>
</details>

2023-01-18 13:30 UTC, sebastianbochan requested changes

2023-01-18 13:30 UTC, sebastianbochan commented on samples/dashboard/demos/climate/demo.css
> +    background: #646479;
I see some colors (like this `#646479` ) in a few places, I suggest extracting them to separate variables and using then.

2023-01-18 14:23 UTC, karolkolodziej requested changes
Please adjust styling when dragging elements.

2023-01-23 08:06 UTC, karolkolodziej approved these changes

2023-01-23 13:16 UTC, bre1470 approved these changes
FYI: After drop and leaving edit mode some container marking does not vanish. Not sure if this falls into the scope of this PR.

<img width="1113" alt="Screenshot 2023-01-23 at 14 15 11" src="https://user-images.githubusercontent.com/40056287/214049042-5fd86f8b-d348-4cd8-b85e-687680355924.png">

2023-01-23 15:18 UTC, pawellysy commented
@bre1470  I will report as a seperate bug 👍

2023-01-23 15:18 UTC, merged