Db/docs edit mode
highcharts/highcharts pull request #18333
Opened 2023-01-20 15:34 UTC by pawellysy

2023-01-20 15:57 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts.js | **99.8 kB**<br>296.3 kB | **100.0 kB**<br>296.3 kB | **206 B**<br>65 B |
| highstock.js | **132.9 kB**<br>401.3 kB | **133.0 kB**<br>401.4 kB | **45 B**<br>65 B |
| highmaps.js | **126.1 kB**<br>382.7 kB | **126.2 kB**<br>382.8 kB | **125 B**<br>65 B |
| highcharts-gantt.js | **135.8 kB**<br>406.1 kB | **135.8 kB**<br>406.1 kB | **38 B**<br>65 B |
| modules/annotations.js | **17.9 kB**<br>63.8 kB | **18.0 kB**<br>63.8 kB | **8 B**<br>10 B |
| modules/annotations-advanced.js | **24.8 kB**<br>96.5 kB | **24.8 kB**<br>96.5 kB | **8 B**<br>10 B |

2023-01-20 16:00 UTC, circleci-mu commented
## Visual test results - No difference found

---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  Modified | samples/highcharts/data/delimiters/demo.js |
|  ? | samples/highcharts/blog/blog-landing-page/demo.js |
|  ? | samples/highcharts/blog/blog-custom-map/demo.js |
|  ? | samples/highcharts/blog/homepage/demo.js |
|  ? | samples/highcharts/blog/blog-planet-atmospheres/demo.js |
|  ? | samples/highcharts/blog/blog-themes-demo/demo.js |
|  ? | samples/highcharts/blog/blog-update-options/demo.js |

</p>
</details>

2023-01-23 08:29 UTC, karolkolodziej requested changes

2023-01-23 08:29 UTC, karolkolodziej commented on docs/dashboards/edit-mode.md
> +<div id="container" class="highcharts-dashboard"></div>
Add `Tab`

2023-01-23 08:29 UTC, karolkolodziej commented on docs/dashboards/edit-mode.md
> +When edit mode is enabled, the appearance of the dashboard changes. When a cell is hovered it gets blue border and the row, in which the cell is, gets green border. Additionally both row and cell get
Typo `wich`

2023-01-23 08:29 UTC, karolkolodziej commented on docs/dashboards/edit-mode.md
> +            contextMenu: {
We also should describe what can be configured in the `contextMenu`.

2023-01-23 08:46 UTC, karolkolodziej approved these changes

2023-01-23 08:46 UTC, karolkolodziej commented on docs/dashboards/edit-mode.md
> +the `contextMenu` option also allows you to edit, what should be inside the menu, which shows after clicking on the burger menu.  The items can either be a string like `editMode` if it is a default b
Capital `T`

2023-01-23 15:07 UTC, bre1470 commented on docs/dashboards/edit-mode.md
> +When edit mode is enabled, the appearance of the dashboard changes. When a cell is hovered it gets blue border and the row, in which the cell is, gets green border. Additionally both row and cell get
`row, in which the cell is` => `row, containing the cell,` or at least `row, in which the cell is present`

2023-01-24 12:19 UTC, sebastianbochan approved these changes

2023-01-24 12:42 UTC, merged