Pie chart race demo
highcharts/highcharts pull request #18359
Opened 2023-01-24 21:09 UTC by mekhatria

Blog for pie chart race demo

2023-01-24 21:31 UTC, circleci-mu commented
### File size comparison
No differences found

2023-01-24 21:34 UTC, circleci-mu commented
## Visual test results - No difference found

---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  Added | samples/highcharts/blog/pie-chart-race/demo.js |

</p>
</details>

2023-01-25 07:02 UTC, TorsteinHonsi requested changes
Thanks! Looks nice. 

I did some changes already:

1. Removed some dead code related to data label content animation, axes and stuff. Seems like this was copied from the bar race demo
2. Fixed the data source. Also made a description for how to use `/samples/data`, see https://github.com/highcharts/highcharts/blob/5d0bb24a9b88862f09ccf9db1299a997844e832e/samples/readme.md#useful-tips-for-setting-up-tests .

Last point, I think this sample now qualifies for the demo section (under pies and donuts), so if you move it to `/demos` and add the appropriate properties in `demo.details` we have another nice demo there.

2023-01-25 07:03 UTC, TorsteinHonsi commented on samples/highcharts/blog/pie-chart-race/demo.details
> + name: A pie chart race to display nuclear enegery production
A bit too verbose for the title (this will show up in the demo thumbnail listing).  "Donut chart race" will do.

2023-01-26 20:32 UTC, mekhatria commented on samples/highcharts/blog/pie-chart-race/demo.js
> +                                ]
Yes, I copied the code from bar-race. What should be done about this part?

2023-01-30 06:17 UTC, TorsteinHonsi commented on samples/highcharts/blog/pie-chart-race/demo.js
> +                                ]
It can be deleted

2023-01-30 07:48 UTC, TorsteinHonsi approved these changes

2023-01-30 07:49 UTC, merged