db/kpi-plugin
highcharts/highcharts pull request #18352
Opened 2023-01-24 13:21 UTC by karolkolodziej

Added `KPIComponent` to `HighchartsPlugin`.

- [ ] TS

2023-01-24 13:41 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts.js | **99.8 kB**<br>296.3 kB | **100.0 kB**<br>296.3 kB | **205 B**<br>65 B |
| highstock.js | **132.9 kB**<br>401.3 kB | **133.0 kB**<br>401.4 kB | **44 B**<br>65 B |
| highmaps.js | **126.1 kB**<br>382.7 kB | **126.2 kB**<br>382.8 kB | **126 B**<br>65 B |
| highcharts-gantt.js | **135.8 kB**<br>406.1 kB | **135.8 kB**<br>406.1 kB | **38 B**<br>65 B |
| modules/annotations.js | **17.9 kB**<br>63.8 kB | **18.0 kB**<br>63.8 kB | **8 B**<br>10 B |
| modules/annotations-advanced.js | **24.8 kB**<br>96.5 kB | **24.8 kB**<br>96.5 kB | **9 B**<br>10 B |

2023-01-24 13:44 UTC, circleci-mu commented
## Visual test results - No difference found

---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  Modified | samples/highcharts/data/delimiters/demo.js |
|  ? | samples/highcharts/blog/blog-landing-page/demo.js |
|  ? | samples/highcharts/blog/blog-custom-map/demo.js |
|  ? | samples/highcharts/blog/homepage/demo.js |
|  ? | samples/highcharts/blog/blog-planet-atmospheres/demo.js |
|  ? | samples/highcharts/blog/blog-themes-demo/demo.js |
|  ? | samples/highcharts/blog/blog-update-options/demo.js |

</p>
</details>

2023-01-24 14:40 UTC, sebastianbochan approved these changes

2023-01-24 17:23 UTC, pawellysy requested changes
Good job! Minor changes requested tho

2023-01-24 17:23 UTC, pawellysy commented on ts/Dashboard/Actions/Bindings.ts
> +        const componentContainer = document.getElementById(options.cell);
Add the type narrowing here as `HTMLComponent | null` and delete it elsewhere

2023-01-24 17:23 UTC, pawellysy commented on ts/Dashboard/Actions/Bindings.ts
> +                            parentElement: componentContainer as HTMLDOMElement,
Delete type casting

2023-01-24 17:23 UTC, pawellysy commented on ts/Dashboard/Actions/Bindings.ts
> +                                parentElement: componentContainer as HTMLDOMElement,
delete type casting

2023-01-24 17:23 UTC, pawellysy commented on ts/Dashboard/Actions/Bindings.ts
> +                                parentElement: componentContainer as HTMLDOMElement
delete type casting

2023-01-24 17:23 UTC, pawellysy commented on ts/Dashboard/Actions/Bindings.ts
> +                                parentElement: componentContainer as HTMLDOMElement
delete type casting

2023-01-24 18:07 UTC, bre1470 reviewed
It looks a bit strange with the default chart height of 400 pixel. I would expect that a KPI by default becomes a squared component.

2023-01-25 07:12 UTC, karolkolodziej commented
@bre1470 I agree but this was not a scope of this issue. I will create a separate one where we can discuss all the default options and styling for KPI.

2023-01-25 09:06 UTC, bre1470 approved these changes

2023-01-25 09:08 UTC, pawellysy approved these changes
LGTM!

2023-01-25 09:23 UTC, merged