bugfix/18305-custom-marker-size-update
highcharts/highcharts pull request #18354
Opened 2023-01-24 14:20 UTC by kamil-musialowski

Fixed #18305, updating the marker size from a button was not working, if the initial size was not set.

Demo for testing: https://jsfiddle.net/BlackLabel/xjeLkv3u/

This bug only happened while updating from a button click. Updating outside of `addEventListener` worked fine, therefore I was not able to create tests for this one.

2023-01-24 14:40 UTC, circleci-mu commented
### File size comparison
No differences found

2023-01-24 14:43 UTC, circleci-mu commented
## Visual test results - No difference found

2023-01-25 09:24 UTC, TorsteinHonsi requested changes
Thanks! Although we must assume that the order of the picked elements was there for a reason, this changes seems legit and I can't think of a way it would break. 

We need a unit test for it though. Preferrably find an existing test that deals with markers, and add an `.update` there.

2023-01-26 11:20 UTC, kamil-musialowski commented
@TorsteinHonsi I had to add the update and test in a tricky way, since I was not able to do that with a simple `series.update`. 
[This demo](https://jsfiddle.net/BlackLabel/yw836hu0/) explains it a bit further, why a standard update does not throw an error in tests.

2023-01-26 15:23 UTC, TorsteinHonsi approved these changes
Thanks, it looks good. 

I don't fully understand why the test has to be inside the `render` callback. But I understand this problem that the image size is cached the first time the image is loaded, then the size is read from cache after that.

2023-01-26 15:23 UTC, merged