db/main-readme
highcharts/highcharts pull request #18365
Opened 2023-01-25 09:50 UTC by karolkolodziej

Added the main readme.

- [ ]  Installation
- [ ] Components
- [ ] Working with Data
- [ ] GUI
- [ ] Edit Mode
- [ ] Your First Dashboard
- [ ]  FAQ

2023-01-25 10:27 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts.js | **99.8 kB**<br>296.3 kB | **100.0 kB**<br>296.3 kB | **205 B**<br>65 B |
| highstock.js | **132.9 kB**<br>401.3 kB | **133.0 kB**<br>401.4 kB | **43 B**<br>65 B |
| highmaps.js | **126.1 kB**<br>382.7 kB | **126.2 kB**<br>382.8 kB | **126 B**<br>65 B |
| highcharts-gantt.js | **135.8 kB**<br>406.1 kB | **135.8 kB**<br>406.1 kB | **39 B**<br>65 B |
| modules/annotations.js | **17.9 kB**<br>63.8 kB | **18.0 kB**<br>63.8 kB | **8 B**<br>10 B |
| modules/annotations-advanced.js | **24.8 kB**<br>96.5 kB | **24.8 kB**<br>96.5 kB | **8 B**<br>10 B |

2023-01-25 10:30 UTC, circleci-mu commented
## Visual test results - No difference found

---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  Modified | samples/highcharts/data/delimiters/demo.js |
|  ? | samples/highcharts/blog/blog-landing-page/demo.js |
|  ? | samples/highcharts/blog/blog-custom-map/demo.js |
|  ? | samples/highcharts/blog/homepage/demo.js |
|  ? | samples/highcharts/blog/blog-planet-atmospheres/demo.js |
|  ? | samples/highcharts/blog/blog-themes-demo/demo.js |
|  ? | samples/highcharts/blog/blog-update-options/demo.js |

</p>
</details>

2023-01-25 14:56 UTC, sebastianbochan requested changes

2023-01-25 14:56 UTC, sebastianbochan commented on ts/Dashboard/README.md
> +Each dashboard is built with different components. You can add the most basic HTMLComponent where you can add some text, image etc.
Can we wrap names like HTMLComponent into `HTMLComponent`? It will increase readibility

2023-01-25 16:40 UTC, pawellysy requested changes
FAQ?

2023-01-26 10:05 UTC, bre1470 requested changes
Good job! 👍 Just some adjustments...

2023-01-26 10:05 UTC, bre1470 commented on ts/Dashboard/README.md
> +The Edit Mode is a part of the dashboard that allows you to edit the dashboard. You can add, remove and edit components. <br>
There is not need for `<br>`. You can add double space at the end to create a paragraph.

2023-01-26 10:05 UTC, bre1470 commented on ts/Dashboard/README.md
> +To enable the Edit Mode you have to add the `highcharts-dashboard` class to the div where the dashboard is placed. <br>
= `highcharts-dashboards`

2023-01-26 10:05 UTC, bre1470 commented on ts/Dashboard/README.md
> +More about the Edit Mode in the [documentation](https://highcharts.com/docs/dashboards/edit-mode).
The links are not a11y-friendly. The text link needs to be more specific. `You find more information in the [Edit Mode documentation](…` for e.g. helps more than multiple links saying "documentation".

2023-01-26 10:57 UTC, sebastianbochan approved these changes

2023-01-26 12:58 UTC, bre1470 approved these changes
Thank you! Looks good. 👍

2023-01-26 13:53 UTC, merged