18069 remove ie8 support
highcharts/highcharts pull request #18367
Opened 2023-01-25 10:22 UTC by MarkusBarstad

2023-01-26 13:40 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts.js | **100.0 kB**<br>296.5 kB | **99.6 kB**<br>295.6 kB | **-429 B**<br>-960 B |
| highstock.js | **132.8 kB**<br>401.6 kB | **132.5 kB**<br>400.7 kB | **-289 B**<br>-954 B |
| highmaps.js | **126.3 kB**<br>383.0 kB | **126.0 kB**<br>382.0 kB | **-294 B**<br>-998 B |
| highcharts-gantt.js | **135.6 kB**<br>406.3 kB | **135.2 kB**<br>405.4 kB | **-351 B**<br>-960 B |
| modules/accessibility.js | **35.3 kB**<br>127.9 kB | **35.3 kB**<br>127.9 kB | **-2 B**<br>-36 B |
| modules/exporting.js | **7.2 kB**<br>19.2 kB | **7.2 kB**<br>19.2 kB | **-18 B**<br>-49 B |
| modules/heatmap.js | **6.9 kB**<br>19.5 kB | **6.9 kB**<br>19.5 kB | **-4 B**<br>-10 B |

2023-01-26 15:08 UTC, TorsteinHonsi reviewed
Some preliminary comments 👇

2023-01-26 15:56 UTC, MarkusBarstad commented on ts/Core/Renderer/SVG/SVGElement.ts
> +        if (pick(doc.hidden, false)) {
Yeah, good point. 

I can see that it [is supported from IE 10](https://caniuse.com/?search=document.hidden) so I guess we will have to keep at least msHidden to support IE9. 

I am having a hard time finding docs on support for webkitHidden but I will use a browser-tester and see if we need it.

2023-01-31 10:06 UTC, MarkusBarstad commented on ts/Core/Renderer/SVG/SVGElement.ts
> +        if (pick(doc.hidden, false)) {
I am struggling a bit to find data on this (as well as sufficiently testing it) but `caniuse.com` [claims document.hidden](https://caniuse.com/?search=document.hidden) is not supported before IE10.

2023-01-31 11:40 UTC, TorsteinHonsi commented on ts/Core/Renderer/SVG/SVGElement.ts
> +        if (pick(doc.hidden, false)) {
Okay, thanks! Let's just go with `if (doc.hidden)` then. If it becomes a problem (not likely), we can make a simple polyfill for the legacy builds.

2023-02-09 14:17 UTC, TorsteinHonsi commented on ts/Core/Series/Series.ts
>          let animDuration = (!series.finishedAnimating && chart.renderer.isSVG) ?
The `chart.renderer.isSVG` condition can be removed here, ref the removed comment.

2023-03-02 12:20 UTC, TorsteinHonsi requested changes
Thanks, nice work! See inline comments.

2023-03-06 10:28 UTC, TorsteinHonsi approved these changes
🎉

2023-03-06 10:28 UTC, merged