Migration: MACDIndicator
highcharts/highcharts pull request #18384
Opened 2023-01-27 07:59 UTC by marvin19

Improved MACDIndicator and MACDOptions, also checked MACDPoint.

2023-01-27 08:20 UTC, circleci-mu commented
### File size comparison
No differences found

2023-01-27 08:22 UTC, circleci-mu commented
## Visual test results - No difference found

2023-01-31 11:56 UTC, bre1470 requested changes
Some class options have undefined type and therefor can be optional without `= void 0` assignment.

2023-02-02 08:40 UTC, bre1470 approved these changes

2023-02-02 09:52 UTC, TorsteinHonsi approved these changes

2023-02-02 09:52 UTC, merged