Updated timeline styles
highcharts/highcharts pull request #18421
Opened 2023-02-01 17:14 UTC by nasin

Hi, I updated this demo using the styles from the version on the About Us page on highcharts.com.

2023-02-01 17:36 UTC, circleci-mu commented
### File size comparison
No differences found

2023-02-01 17:39 UTC, circleci-mu commented
## Visual test results - Differences found
Found **1** diffing sample(s). [Please review the differences.](https://vrevs.highsoft.com/pr/18421/review)


---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  Modified | samples/highcharts/demo/combo-timeline/demo.js |

</p>
</details>

2023-02-02 07:53 UTC, TorsteinHonsi commented
Thanks! Before I do a detailed review, can you update it with recent data? See http://localhost:3030/samples/#view/highcharts/studies/combo-timeline-updated . And we should fill in the years after 2019. HR can provide the numbers.

2023-02-06 22:22 UTC, nasin commented
Hi, I updated the data. I had revenue and employee data from HR already (for the About Us verson of this chart), and I added it, but you should look and see if I did it right because all the employees post August 2019 are nameless in the data I used.

Also, I need updated Google trends data. Should I ask Marketing?

2023-02-08 10:29 UTC, TorsteinHonsi requested changes
Thanks so far! 

We also want to remove the Google Translate series.

2023-02-08 10:29 UTC, TorsteinHonsi commented on samples/highcharts/demo/combo-timeline/demo.js
> +const moreEmployees = [
Looks like employees before 2019 are loaded from the HTML table then this is added for employees after 2019? That's not consistent. Add the new ones to the HTML table instead, if that is how we did it from before.

2023-02-08 10:29 UTC, TorsteinHonsi commented on samples/highcharts/demo/combo-timeline/demo.js
> +        data: getTurnover().concat(moreEmployees)
Do not concat `moreEmployees`, the newer employees should be added to the HTML table like the others.

2023-02-09 19:11 UTC, sigrunnu commented
I have no idea if I did it right, I think I might just changed it back to the way it was before Nancy's changes..
The shape of the flags are now back to `squarepin`, the only problem is that I did not manage to set the border-radius, so it doesn't look as good.

The 'award' flags are changed to annotations and I am not sure how to add tooltips to them. 
@TorsteinHonsi

2023-02-09 19:25 UTC, TorsteinHonsi commented
You mean this one?
> Torstein: Remove graphics for the flag backgrounds. Instead, define custom symbols. If that fails, use Annotations.

I added my name there because I thought I should do it :) But no worries, now I have a better starting point.

But you can still remove the `moreEmployees` array and add the newcomers into the HTML table with the rest.

2023-02-09 19:49 UTC, sigrunnu commented
Yes, that one, thought that meant you wrote it.. Well, hopefully the starting point is not worse  :)
I'll do the other stuff then!

2023-02-13 17:07 UTC, sigrunnu commented
> But you can still remove the moreEmployees array and add the newcomers into the HTML table with the res

HR mentioned that we are not allowed to use people's names in the demo. Do you still think it is better to update the table as  it won't add anything extra to it? @TorsteinHonsi

2023-03-09 07:45 UTC, TorsteinHonsi reviewed
Thanks @sigrunnu !

This demo now has some features that we can't use in our demo pages, like hard graphics for the flags. And I don't have time to fix it until after v11. 

I think we should go back to the master and apply the updated data to that chart without touching the design in this round. Can you do that? Then we will close this PR and make a new one that only updates the data.

2023-03-14 10:40 UTC, closed without merging