docs/18278-mapview-reference
highcharts/highcharts pull request #18431
Opened 2023-02-02 14:31 UTC by madepiet

Fixed #18278, MapView/MapChart API.

2023-02-02 14:52 UTC, circleci-mu commented
### File size comparison
No differences found

2023-02-02 14:55 UTC, circleci-mu commented
## Visual test results - No difference found

2023-02-02 15:49 UTC, bre1470 requested changes

2023-02-02 15:49 UTC, bre1470 commented on ts/Core/Chart/MapChart.ts
> +
This should be over the assignment. If JSDoc does not pick it up, then move the doclet to the end of `MapView.ts` followed by `'';`.

2023-02-02 15:50 UTC, bre1470 commented on ts/Core/Chart/MapChart.ts
> +
I mean this assignment: https://github.com/highcharts/highcharts/blob/master/ts/Maps/MapView.ts#L1374

2023-02-03 12:24 UTC, bre1470 approved these changes
Thank you! Looks good. 👍

2023-02-03 14:44 UTC, TorsteinHonsi approved these changes
Thanks!

2023-02-03 14:44 UTC, merged