feature/18433-gauge-percentage-property
highcharts/highcharts pull request #18448
Opened 2023-02-06 18:04 UTC by Vazonik

Added the `point.percentage` property for gauge charts.

2023-02-06 18:28 UTC, circleci-mu commented
## Visual test results - Differences found
Found **6** diffing sample(s). [Please review the differences.](https://vrevs.highsoft.com/pr/18448/review)

2023-02-06 19:11 UTC, karolkolodziej requested changes
It looks good, but could you please add a test for that? Please reuse the already existing one for the gauge.

2023-02-06 19:11 UTC, karolkolodziej commented on ts/Series/Gauge/GaugeSeries.ts
> +            if (point.y || point.y === 0) {
We have a utils method called `defined` which will fit perfectly here.

2023-02-06 19:11 UTC, karolkolodziej commented on ts/Series/Gauge/GaugeSeries.ts
> +                    ((point.y - yAxis.min) / (yAxis.max - yAxis.min)) * 100;
You can also check if the range exists in order to avoid dividing by zero.

2023-02-07 11:57 UTC, TorsteinHonsi commented
In addition to Karol's comments, we also need a unit test. The cheapest approach is to find an existing gauge or solid gauge test and add an assertion for the percentage.

2023-02-08 16:05 UTC, TorsteinHonsi approved these changes
Thanks!

2023-02-08 16:05 UTC, merged