samples/jsfiddle-2-samples-4
highcharts/highcharts pull request #18447
Opened 2023-02-06 16:42 UTC by sigrunnu

Found a few more demos that needs to be moved

2023-02-06 17:05 UTC, circleci-mu commented
### File size comparison
No differences found

2023-02-06 17:08 UTC, circleci-mu commented
## Visual test results - Differences found
Found **4** diffing sample(s). [Please review the differences.](https://vrevs.highsoft.com/pr/18447/review)


---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  Added | samples/highcharts/blog/top-headline-phrases/demo.js |

</p>
</details>

2023-02-08 08:18 UTC, TorsteinHonsi commented
While you're at it, can you remove this one `highcharts/blog/activity-gauge` ? And in the blog, we would include `highcharts/demo/gauge-activity` instead. The first one seems to be a copy of the demo, except it doesn't work well.

2023-02-08 08:19 UTC, sigrunnu commented
I'll remove it! Also, do you know why the review tool is failing?
@TorsteinHonsi

2023-02-08 11:49 UTC, TorsteinHonsi requested changes
Thanks! Some minor adjustments.

2023-02-08 11:49 UTC, TorsteinHonsi commented on samples/highcharts/blog/aapl-price/demo.details
> + name: AAPL Price
It's the same as http://localhost:3030/samples/#view/stock/demo/basic-line, use that instead

2023-02-08 11:49 UTC, TorsteinHonsi commented on samples/highcharts/blog/color-blindness/demo.details
> +   -
Funny dash - probably not valid YAML

2023-02-08 11:49 UTC, TorsteinHonsi commented on samples/highcharts/blog/movie-cummulative-income/demo.html
> +<div id="container" style="margin: 0; height:600px"></div>
Move the inline CSS to demo.css

2023-02-08 11:49 UTC, TorsteinHonsi commented on test/json-sources.js
> +    "https://cdn.jsdelivr.net/gh/highcharts/highcharts@v7.0.0/samples/data/usdeur.json":
This is probably not needed as we remove the stock demo and use our existing stock line

2023-02-08 20:22 UTC, TorsteinHonsi approved these changes

2023-02-08 20:22 UTC, merged