db/resizer-height-datagrid
highcharts/highcharts pull request #18453
Opened 2023-02-07 11:54 UTC by sebastianbochan

2023-02-07 12:16 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts.js | **100.0 kB**<br>296.5 kB | **100.1 kB**<br>296.6 kB | **72 B**<br>65 B |
| highstock.js | **132.8 kB**<br>401.6 kB | **132.9 kB**<br>401.7 kB | **88 B**<br>65 B |
| highmaps.js | **126.3 kB**<br>383.0 kB | **126.5 kB**<br>383.1 kB | **206 B**<br>65 B |
| highcharts-gantt.js | **135.6 kB**<br>406.3 kB | **135.5 kB**<br>406.4 kB | **-34 B**<br>65 B |
| modules/annotations.js | **17.9 kB**<br>63.8 kB | **18.0 kB**<br>63.8 kB | **8 B**<br>10 B |
| modules/annotations-advanced.js | **24.8 kB**<br>96.5 kB | **24.8 kB**<br>96.6 kB | **9 B**<br>10 B |

2023-02-07 12:18 UTC, circleci-mu commented
## Visual test results - No difference found

---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  Modified | samples/highcharts/data/delimiters/demo.js |
|  ? | samples/highcharts/blog/blog-landing-page/demo.js |
|  ? | samples/highcharts/blog/blog-custom-map/demo.js |
|  ? | samples/highcharts/blog/homepage/demo.js |
|  ? | samples/highcharts/blog/blog-planet-atmospheres/demo.js |
|  ? | samples/highcharts/blog/blog-themes-demo/demo.js |
|  ? | samples/highcharts/blog/blog-update-options/demo.js |

</p>
</details>

2023-02-07 13:09 UTC, karolkolodziej requested changes

2023-02-07 13:09 UTC, karolkolodziej commented on ts/Extensions/DashboardPlugins/DataGridComponent.ts
> +        return this;
There is no need to return anything here.

2023-02-07 13:15 UTC, karolkolodziej approved these changes

2023-02-09 13:50 UTC, goransle approved these changes
Looks good!

2023-02-13 11:15 UTC, pawellysy approved these changes
Looks good!

2023-02-13 11:17 UTC, merged