bd/board-factory
highcharts/highcharts pull request #18481
Opened 2023-02-13 12:23 UTC by karolkolodziej

- [ ] Rename `Dashboards.Dashboard` into `Dashboard.Board`
- [ ] Implement `Dashboard.board` factory
- [ ] Fix demos
- [ ] Fix documentation

2023-02-13 12:48 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts.js | **100.0 kB**<br>296.5 kB | **100.1 kB**<br>296.6 kB | **71 B**<br>65 B |
| highstock.js | **132.8 kB**<br>401.6 kB | **132.9 kB**<br>401.7 kB | **89 B**<br>65 B |
| highmaps.js | **126.3 kB**<br>383.0 kB | **126.5 kB**<br>383.1 kB | **205 B**<br>65 B |
| highcharts-gantt.js | **135.6 kB**<br>406.3 kB | **135.5 kB**<br>406.4 kB | **-35 B**<br>65 B |
| modules/annotations.js | **17.9 kB**<br>63.8 kB | **18.0 kB**<br>63.8 kB | **7 B**<br>10 B |
| modules/annotations-advanced.js | **24.8 kB**<br>96.5 kB | **24.8 kB**<br>96.6 kB | **8 B**<br>10 B |

2023-02-13 12:51 UTC, circleci-mu commented
## Visual test results - No difference found

---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  Modified | samples/highcharts/data/delimiters/demo.js |
|  ? | samples/highcharts/blog/blog-landing-page/demo.js |
|  ? | samples/highcharts/blog/blog-custom-map/demo.js |
|  ? | samples/highcharts/blog/homepage/demo.js |
|  ? | samples/highcharts/blog/blog-planet-atmospheres/demo.js |
|  ? | samples/highcharts/blog/blog-themes-demo/demo.js |
|  ? | samples/highcharts/blog/blog-update-options/demo.js |

</p>
</details>

2023-02-13 15:11 UTC, sebastianbochan approved these changes

2023-02-14 10:09 UTC, goransle approved these changes
LGTM

2023-02-14 10:59 UTC, bre1470 requested changes

2023-02-14 10:59 UTC, bre1470 commented on ts/masters/dashboards.src.ts
> +    board: Dashboard.board,
The import should be renamed as well, so you can skip the colon thing.

2023-02-14 10:59 UTC, bre1470 commented on samples/dashboards/demos/climate/demo.js
> +    return new Promise(resolve => new Dashboards.Board('container', {
As a reference demo this should have the `Dashboards.board` call.

2023-02-14 10:59 UTC, bre1470 commented on docs/dashboards/your-first-dashboard.md
> +    or the constructor to create a new instance of the dashboard:
or the class `Dashboards.Board`…

2023-02-14 12:02 UTC, pawellysy approved these changes
LGTM! :D

2023-02-14 13:27 UTC, bre1470 requested changes
I do not see the point done:
- Rename Dashboards.Dashboard into Dashboards.Board

2023-02-14 13:45 UTC, karolkolodziej commented
@bre1470 [isn't it that?](https://github.com/highcharts/highcharts/pull/18481/files#diff-af80584fc55104f51ff478328047f79b9630f972378d89ca846d93ecba4f1d8aR56)

2023-02-14 15:15 UTC, bre1470 commented
Okay, I understand now. I am expecting the rename of the file as well. So, from `ts/Dashboards/Dashboard.ts` to `ts/Dashboards/Board.ts` plus the adjustments of imports.

2023-02-15 07:51 UTC, bre1470 commented
@pawelfus
Should also `X.dashboard` properties (reference of `Board` class) be renamed?

2023-02-15 08:14 UTC, karolkolodziej commented
IMO it will be cleaner and shorter if we use `xxx.board` instead of `xxx.dashboard` when referring to the `Board` instance.

2023-02-15 08:41 UTC, bre1470 requested changes
Cypress imports need adjustment.

2023-02-15 08:57 UTC, pawelfus commented
> @pawelfus Should also `X.dashboard` properties (reference of `Board` instance) be renamed?

Yes, please do 👍 Note: I wouldn't agree to change like `series.chart` => `series.c`, because that would break existing implementations, but in this case - just checked with Karol docs and there's no place we recommend this, so it's safe 👍

2023-02-15 10:23 UTC, bre1470 approved these changes
Thank you! Looks good. 👍

2023-02-15 10:25 UTC, merged