bugfix/18245-map-zoom-buttons-style
highcharts/highcharts pull request #18489
Opened 2023-02-13 16:58 UTC by Vazonik

Fixed #18245, centered map navigation buttons' text.

2023-02-13 17:20 UTC, circleci-mu commented
### File size comparison
No differences found

2023-02-13 17:23 UTC, circleci-mu commented
## Visual test results - Differences found
Found **5** diffing sample(s). [Please review the differences.](https://vrevs.highsoft.com/pr/18489/review)

2023-02-14 13:15 UTC, TorsteinHonsi requested changes
Thanks! The change is good, but this file is going to disappear in v11, which is soon to be released. So merging it now will only cause a merge conflict and risk that the change gets lost. Can you create a PR based on the `v11` branch instead? Then you will have to apply the same changes to the `css/highcharts.css` file.

2023-02-14 15:59 UTC, Vazonik commented
PR based on the `v11` branch: #18495

2023-02-14 15:59 UTC, closed without merging