db/css-variables-gui
highcharts/highcharts pull request #18499
Opened 2023-02-15 08:39 UTC by karolkolodziej

2023-02-15 09:01 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts.js | **100.1 kB**<br>296.4 kB | **100.1 kB**<br>296.4 kB | **15 B**<br>65 B |
| highstock.js | **132.8 kB**<br>401.5 kB | **132.9 kB**<br>401.5 kB | **37 B**<br>65 B |
| highmaps.js | **126.3 kB**<br>382.8 kB | **126.2 kB**<br>382.9 kB | **-94 B**<br>65 B |
| highcharts-gantt.js | **135.5 kB**<br>406.2 kB | **135.6 kB**<br>406.2 kB | **38 B**<br>65 B |
| modules/annotations.js | **17.9 kB**<br>63.8 kB | **18.0 kB**<br>63.8 kB | **8 B**<br>10 B |
| modules/annotations-advanced.js | **24.8 kB**<br>96.5 kB | **24.8 kB**<br>96.6 kB | **8 B**<br>10 B |

2023-02-15 09:04 UTC, circleci-mu commented
## Visual test results - No difference found

---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  Modified | samples/highcharts/data/delimiters/demo.js |
|  ? | samples/highcharts/blog/blog-landing-page/demo.js |
|  ? | samples/highcharts/blog/blog-custom-map/demo.js |
|  ? | samples/highcharts/blog/homepage/demo.js |
|  ? | samples/highcharts/blog/blog-planet-atmospheres/demo.js |
|  ? | samples/highcharts/blog/blog-themes-demo/demo.js |
|  ? | samples/highcharts/blog/blog-update-options/demo.js |

</p>
</details>

2023-02-16 08:55 UTC, bre1470 requested changes

2023-02-17 09:05 UTC, goransle approved these changes
LGTM!

2023-02-17 09:07 UTC, bre1470 requested changes

2023-02-17 09:07 UTC, bre1470 commented on css/dashboards/lightDarkTheme.scss
>      }
Here is plural missing.

2023-02-17 11:06 UTC, sebastianbochan approved these changes

2023-02-17 12:15 UTC, merged