bugfix/18276-touchscreen-annotation-select
highcharts/highcharts pull request #18515
Opened 2023-02-17 12:03 UTC by kamil-musialowski

Fixed #18276, annotations touch was not captured on mobile devices.

2023-02-17 12:05 UTC, kamil-musialowski commented on ts/Core/Renderer/SVG/SVGElement.ts
> +            (element as any)['on' + eventType] = handler;
I'm not happy about this `any` casting. 
@bre1470 Could you please have a look at this one?

2023-02-17 12:23 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts.js | **100.1 kB**<br>296.4 kB | **100.1 kB**<br>296.7 kB | **68 B**<br>298 B |
| highstock.js | **132.8 kB**<br>401.5 kB | **132.9 kB**<br>401.8 kB | **129 B**<br>298 B |
| highmaps.js | **126.3 kB**<br>382.8 kB | **126.4 kB**<br>383.1 kB | **119 B**<br>298 B |
| highcharts-gantt.js | **135.5 kB**<br>406.2 kB | **135.7 kB**<br>406.5 kB | **142 B**<br>293 B |

2023-02-17 12:26 UTC, circleci-mu commented
## Visual test results - No difference found

2023-02-20 14:56 UTC, pawelfus requested changes
I don't think we want to go back to a state where `on()` used to implement `click = touchStart + touchMove + touchEnd`. Could you confirm @TorsteinHonsi ?

If that's the case, then I see two alternative solutions:
1. In `NavigationBindings.ts` we have `selectAndShowPopup` assigned to `click` -> we can assign it also to `touchDown`. Sounds like the easiest solution - could you try it?
2. In `EventEmitter.ts` we have `addEvents()` method responsible for adding `click` callback. Perhaps we could move the logic there. But we go back to the question if we should implement `Annotation.options.event.click` as `touchStart + touchMove + touchEnd` too. If there was a reason to resign from `SVGElement.on('click')` = `touchClick`, perhaps we shouldn't repeat this in Annotations

2023-02-20 15:29 UTC, TorsteinHonsi commented
Confirmed. We've been there before. Better to go with one of Pawel's proposed solutions and keep this out of the core. Also see how we're handling touch events in other parts of the code base.

2023-02-21 12:03 UTC, kamil-musialowski commented
@pawelfus With the current commit, there is no `if` check, that would prevent calling the `touchend` event in case of a finger drag event. Should it be implemented here?

2023-03-02 11:59 UTC, pawelfus approved these changes
Looks good, thanks!

2023-03-06 06:27 UTC, TorsteinHonsi approved these changes

2023-03-06 06:27 UTC, merged