ts/migration-psarindicator
highcharts/highcharts pull request #18529
Opened 2023-02-20 09:34 UTC by marvin19

Improved PSARIndicator.

2023-02-20 09:55 UTC, circleci-mu commented
### File size comparison
No differences found

2023-02-20 09:58 UTC, circleci-mu commented
## Visual test results - No difference found

2023-02-20 12:33 UTC, bre1470 requested changes
One thing can be done. Remove the lines here https://github.com/highcharts/highcharts/blob/08fd102498f2e94d460fe3cbad47bb9d6aae2fcd/ts/Stock/Indicators/PSAR/PSARIndicator.ts#L408-L410. This is only needed in the class structure. In class prototype (interface) the type definition is enough.

2023-02-28 15:58 UTC, bre1470 requested changes
Sorry for the mess. I did not expect visual tests to fail. Please move the `nameComponents` property from interface to class.

2023-03-03 09:26 UTC, bre1470 approved these changes
Thank you! Looks good. 👍

2023-03-03 13:21 UTC, TorsteinHonsi approved these changes

2023-03-03 13:21 UTC, merged