bugfix/18501-stack-labels-vertical-align-logarithmic
highcharts/highcharts pull request #18534
Opened 2023-02-20 12:18 UTC by hubertkozik

Fixed #18501, vertical alignment of stack labels didn't work with logarithmic axes.

2023-02-20 12:39 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts.js | **100.1 kB**<br>296.4 kB | **100.1 kB**<br>296.4 kB | **73 B**<br>42 B |
| highstock.js | **132.8 kB**<br>401.5 kB | **132.8 kB**<br>401.5 kB | **25 B**<br>35 B |
| highmaps.js | **126.3 kB**<br>382.9 kB | **126.3 kB**<br>382.9 kB | **-88 B**<br>42 B |
| highcharts-gantt.js | **135.5 kB**<br>406.2 kB | **135.6 kB**<br>406.2 kB | **36 B**<br>42 B |

2023-02-20 12:41 UTC, circleci-mu commented
## Visual test results - No difference found

2023-02-22 22:57 UTC, TorsteinHonsi requested changes
Thanks! In addition to the inline comment, I'm curious why `axis.min` must be run through `log2lin`. We are already doing that [in the setTickInterval function](https://github.com/highcharts/highcharts/blob/0722252494fed0d83e4a52c2ed2711c53707c044/ts/Core/Axis/Axis.ts#L1703), so it should be ready to use. Or is it too late?

2023-02-22 22:57 UTC, TorsteinHonsi commented on ts/Core/Axis/Stacking/StackItem.ts
> +                    Math.pow(10, axis.min) : 0)),
Use the `lin2log` function as usual. We can also do an _or_ statement. So something like

```ts
            yZero = axis.toPixels(
                boxBottom ||
                (isNumber(axis.min) && axis.logarithmic?.log2lin(axis.min)) ||
                0
            ),
            
```.

2023-02-24 07:02 UTC, hubertkozik commented
Yes, `correctFloat` is working correctly, but it is rounding a number, which is a bad value for `yZero` variable. We need to have there a bottom value of the yAxis - in this demo: https://jsfiddle.net/BlackLabel/sreodwg6/ it is a 125, which is saved to `chart.yAxis[0].min` as 2.0969100130080562 and we need to recalculate it.

My mistake, I should use `lin2log`at first, sorry for that!

2023-02-24 13:41 UTC, TorsteinHonsi approved these changes

2023-02-24 13:42 UTC, merged