db/light-dark-theme-docs
highcharts/highcharts pull request #18568
Opened 2023-02-24 07:50 UTC by karolkolodziej

Added documentation for light and dark themes.

2023-02-24 08:10 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts.js | **100.1 kB**<br>296.4 kB | **100.1 kB**<br>296.4 kB | **16 B**<br>65 B |
| highstock.js | **132.8 kB**<br>401.5 kB | **132.9 kB**<br>401.5 kB | **37 B**<br>65 B |
| highmaps.js | **126.3 kB**<br>382.8 kB | **126.2 kB**<br>382.9 kB | **-94 B**<br>65 B |
| highcharts-gantt.js | **135.5 kB**<br>406.2 kB | **135.6 kB**<br>406.2 kB | **38 B**<br>65 B |
| modules/annotations.js | **17.9 kB**<br>63.8 kB | **18.0 kB**<br>63.8 kB | **8 B**<br>10 B |
| modules/annotations-advanced.js | **24.8 kB**<br>96.5 kB | **24.8 kB**<br>96.6 kB | **8 B**<br>10 B |

2023-02-24 08:14 UTC, circleci-mu commented
## Visual test results - No difference found

---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  Modified | samples/highcharts/data/delimiters/demo.js |
|  ? | samples/highcharts/blog/blog-landing-page/demo.js |
|  ? | samples/highcharts/blog/blog-custom-map/demo.js |
|  ? | samples/highcharts/blog/homepage/demo.js |
|  ? | samples/highcharts/blog/blog-planet-atmospheres/demo.js |
|  ? | samples/highcharts/blog/blog-themes-demo/demo.js |
|  ? | samples/highcharts/blog/blog-update-options/demo.js |

</p>
</details>

2023-02-24 13:40 UTC, TorsteinHonsi requested changes

2023-02-24 13:40 UTC, TorsteinHonsi commented on docs/dashboards/light-dark-theme.md
> +By default, the theme is set to light. But it adjusts itself to the user's system settings.
More precisely, it defaults to the system default through the `prefers-color-scheme` media query.

2023-02-24 13:40 UTC, TorsteinHonsi commented on docs/dashboards/light-dark-theme.md
> +    <div id="container" class="dashboards-dark ">
All the other class names are namespaced as `highcharts-dashboards-*`. I think we should follow that convension. Requires `gui.css` to be updated.

2023-02-27 08:38 UTC, TorsteinHonsi approved these changes

2023-02-27 13:59 UTC, sebastianbochan approved these changes

2023-02-28 07:18 UTC, merged