bugfix/18590-topojson-from-highcharts-maps-array
highcharts/highcharts pull request #18609
Opened 2023-03-02 14:56 UTC by jakubSzuminski

Fixed #18590, TopoJSON maps work correctly when strings are passed to `chart.map`. 

The problem was that in the `getGeoMap` function we assumed that when there was a string passed to `chart.map` that `Highcharts.maps[map]` was a GeoJSON. Adding a `topo2geo` conversion for `TopoJSON` maps solves this problem.

2023-03-02 15:55 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highmaps.js | **126.4 kB**<br>382.7 kB | **126.5 kB**<br>382.7 kB | **12 B**<br>31 B |

2023-03-02 15:57 UTC, circleci-mu commented
## Visual test results - No difference found

2023-03-02 18:19 UTC, hubertkozik requested changes
Good job with finding a cause! We need also a test for this issue, can you add it?

2023-03-02 18:19 UTC, hubertkozik commented on ts/Maps/MapView.ts
> +            }
Do we need to create an extra variable for `maps[map]`? In my opinion, we don't need that declaration.

2023-03-06 06:25 UTC, TorsteinHonsi commented
Good job! I second Hubert's requests.

2023-03-06 08:46 UTC, hubertkozik approved these changes
LGTM!

2023-03-06 09:01 UTC, merged