Migration: NATRIndicator
highcharts/highcharts pull request #18629
Opened 2023-03-07 10:12 UTC by marvin19

Improved NATRIndicator and NATROptions, also checked NATRPoint.

2023-03-07 10:33 UTC, circleci-mu commented
### File size comparison
No differences found

2023-03-07 10:36 UTC, circleci-mu commented
## Visual test results - No difference found

2023-03-07 12:37 UTC, bre1470 requested changes

2023-03-07 12:37 UTC, bre1470 commented on ts/Stock/Indicators/NATR/NATRIndicator.ts
>                  ATRIndicator.prototype.getValues.apply(this, arguments)
A `super` would be super here.

2023-03-31 09:35 UTC, bre1470 approved these changes
Thank you! Looks good. 👍

2023-03-31 10:08 UTC, TorsteinHonsi approved these changes
Thanks!

2023-03-31 10:08 UTC, merged