bugfix/17142-venn-sets-comma-issue
highcharts/highcharts pull request #18633
Opened 2023-03-07 15:17 UTC by jakubSzuminski

Fixed #17142, Venn diagram did not work when there was a comma in the string in the `series.data.sets` array.

**Example** of the problem: 
`['A,']` and `['B']` = `'A,,B'` `(combination)` which caused issues when `combination.split(',')`

**Solution:**
I join the elements of the array with a string `SPLIT//COMBINATIONS` which is unlikely to occur in user's code, but maybe we would want to join the sets with another unique string.

2023-03-07 15:39 UTC, circleci-mu commented
### File size comparison
No differences found

2023-03-07 15:43 UTC, circleci-mu commented
## Visual test results - No difference found

2023-03-08 08:58 UTC, TorsteinHonsi requested changes
Thanks! Please add a test too. Preferably modify an existing venn test so that we don't add to the test processing time.

Besides, there are some `any` casts in the code that you modified - since you're working on this code now and have an understanding, maybe you can take the opportunity to fix the typing?

Not so important, and don't spend too much time on this: Why are we using a string that we concatenate and split, instead of an array? I understand it if it's used for indexing an object, otherwise an array would probably be cleaner.

2023-03-08 13:53 UTC, pawellysy approved these changes
Thanks!

2023-03-10 16:00 UTC, jakubSzuminski commented
1. I've added a test case for `,` in strings

2. When it comes to the types, I recognized that there are a few stages there:
- 1 - `relations` are created in `VennUtils.processVennData()` which is an array of objects with only `sets` and `value` properties (even though the `VennRelationObject` also had `circle, overlapping, totalOverlap` as required properties)
- 2 - after `VennSeries.layout()` the `circle` is added to each of the `relations` so I decided to make `circle` optional (because it doesn't appear in the first step, the `relations` are "extended")
- 3 - then, the `overlapping` and `totalOverlap` are added in `addOverlapToSets()` so I also decided to make them optional (as they do not appear in the first and second step)
Then, I fixed `any` casting in a few places by adding some `if` conditions.

3. In this case strings (which come from `Array.join(splitter)`) are used for object indexing so I did not change the method for now (but of course I'll do if you decide that we should). 
Also, I've added a `splitter` as a `public static` variable of `VennSeries` so that the user might easily override the `splitter` string to something else if he happens to use the `highcharts-split` in his `series.venn.sets`

2023-03-10 16:04 UTC, jakubSzuminski commented on ts/Series/Venn/VennUtils.ts
>                      }
I ran into a strange TypeScript issue here. I've tried to check if `typeof mapOfIdToProps[set].totalOverlap !== 'undefined'` and then add `relation.value` to it, but it did not seem to work as the TypeScript always threw 2532 error - `Object is possibly 'undefined'` (no matter how many conditions did I check that it is not `undefined`).

2023-03-13 07:35 UTC, TorsteinHonsi approved these changes
Okay, thanks for the clean up! Let's keep i like this.

2023-03-13 07:35 UTC, merged