Updated Highcharts Core animation
highcharts/highcharts pull request #18645
Opened 2023-03-09 18:24 UTC by nasin

Hi, I redid the Highcharts JS (Core) product animation since we renamed the it Core. Marketing has approved the concept.

2023-03-09 18:44 UTC, circleci-mu commented
### File size comparison
No differences found

2023-03-09 18:47 UTC, circleci-mu commented
## Visual test results - No difference found

---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  Modified | samples/highcharts/website/icon-chart/demo.js |

</p>
</details>

2023-03-13 08:00 UTC, TorsteinHonsi requested changes
Thanks, looking good! When looking at it in the utils the chart title is visible though...

2023-03-13 12:42 UTC, nasin commented
Thanks! I removed the title from the chart configuration.

2023-03-14 10:35 UTC, TorsteinHonsi approved these changes

2023-03-14 10:35 UTC, merged