db/sync-class-docs
highcharts/highcharts pull request #18661
Opened 2023-03-14 11:08 UTC by pawellysy

Added sync class doclets.

2023-03-14 11:20 UTC, goransle approved these changes
Looks good 👍

2023-03-14 11:27 UTC, bre1470 requested changes

2023-03-14 11:27 UTC, bre1470 commented on ts/Dashboards/Components/Sync/Sync.ts
> +     * Default handlers for the sync class.
It would be good to have some info about when this needs to be used/set.

2023-03-14 11:27 UTC, bre1470 commented on ts/Dashboards/Components/Sync/Sync.ts
> +     * If the component is currently syncing.
If = Whether

2023-03-14 11:30 UTC, pawellysy commented on ts/Series/Sunburst/SunburstSeries.ts
> +        // if (hackDataLabelAnimation) {
🤦

2023-03-14 11:33 UTC, circleci-mu commented
## Visual test results - No difference found

---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  Modified | samples/highcharts/data/delimiters/demo.js |
|  ? | samples/highcharts/blog/blog-landing-page/demo.js |
|  ? | samples/highcharts/blog/blog-custom-map/demo.js |
|  ? | samples/highcharts/blog/homepage/demo.js |
|  ? | samples/highcharts/blog/blog-planet-atmospheres/demo.js |
|  ? | samples/highcharts/blog/blog-themes-demo/demo.js |
|  ? | samples/highcharts/blog/blog-update-options/demo.js |

</p>
</details>

2023-03-15 06:24 UTC, karolkolodziej approved these changes

2023-03-15 06:24 UTC, karolkolodziej commented on ts/Dashboards/Components/Sync/Sync.ts
> +     * different Components, where default syncs are added. Allows overwrithing
```suggestion
     * different Components, where default syncs are added. Allows overwriting
```

2023-03-15 06:24 UTC, karolkolodziej commented on ts/Dashboards/Components/Sync/Sync.ts
> +     * @param emitter The emitter to register
```suggestion
     * @param emitter 
     The emitter to register.
```

2023-03-15 06:24 UTC, karolkolodziej commented on ts/Dashboards/Components/Sync/Sync.ts
> +     * if the emitter is registered
```suggestion
     * Whether the emitter is registered.
```

2023-03-15 06:24 UTC, karolkolodziej commented on ts/Dashboards/Components/Sync/Sync.ts
> +     * if the handler is registered.
```suggestion
     * Whether the handler is registered.
```

2023-03-15 06:24 UTC, karolkolodziej commented on ts/Dashboards/Components/Sync/Sync.ts
> +     * The emitters and handlers to use for each event
```suggestion
     * The emitters and handlers to use for each event.
```

2023-03-15 06:24 UTC, karolkolodziej commented on ts/Dashboards/Components/Sync/Sync.ts
>  class Sync {
Question- Do we need to publically document that class?
Shouldn't it be marked as `internal`?

2023-03-15 09:12 UTC, TorsteinHonsi approved these changes
Approved, given that the other change requests are fixed.

2023-03-24 13:23 UTC, sebastianbochan approved these changes

2023-03-28 11:05 UTC, merged