bugfix/18542-map-panning-update-zoom
highcharts/highcharts pull request #18666
Opened 2023-03-14 12:21 UTC by hubertkozik

Fixed #18542, panning in zoomed-in Orthographic projection didn't work.

2023-03-14 12:42 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highmaps.js | **126.3 kB**<br>382.8 kB | **126.3 kB**<br>382.9 kB | **34 B**<br>130 B |

2023-03-14 12:45 UTC, circleci-mu commented
## Visual test results - No difference found

2023-03-16 09:15 UTC, magdalena-gut approved these changes

2023-03-16 10:14 UTC, madepiet approved these changes

2023-03-20 08:52 UTC, TorsteinHonsi requested changes
Thanks!

There is an issue we need to deal with: In https://jsfiddle.net/highcharts/8nkdz1oL/, grab Spain and drag straight right out of the chart => console complains about NaN, and the view is frozen.

In the current official release it actually also freezes, but not until dragging all the way of of the chart and releasing the mouse outside.

2023-03-20 10:24 UTC, KacperMadej commented
@TorsteinHonsi 
There is or was a concept of a change between pan-rotate and pan-translate in Orthographic projection based on the current zoom and not what is the entire data set. With this, if you zoom in enough, you can pan-translate. The pan-rotate should also be disabled if only a part of the world is loaded (e.g. only 1 continent). Should all of this still be the case?

2023-03-28 10:20 UTC, KacperMadej approved these changes

2023-03-29 07:26 UTC, TorsteinHonsi approved these changes

2023-03-29 07:26 UTC, merged