db/confirmation-popup-refactor
highcharts/highcharts pull request #18671
Opened 2023-03-15 08:18 UTC by karolkolodziej

Refactored confirmation popup to use the `BaseForm`.

2023-03-15 08:37 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts.js | **100.2 kB**<br>296.6 kB | **100.2 kB**<br>296.7 kB | **34 B**<br>65 B |
| highstock.js | **132.9 kB**<br>401.5 kB | **133.0 kB**<br>401.5 kB | **40 B**<br>65 B |
| highmaps.js | **126.3 kB**<br>382.8 kB | **126.3 kB**<br>382.8 kB | **-7 B**<br>65 B |
| highcharts-gantt.js | **135.5 kB**<br>406.4 kB | **135.6 kB**<br>406.5 kB | **41 B**<br>65 B |
| modules/annotations.js | **18.1 kB**<br>64.6 kB | **18.1 kB**<br>64.6 kB | **7 B**<br>10 B |
| modules/annotations-advanced.js | **25.0 kB**<br>97.4 kB | **25.0 kB**<br>97.4 kB | **7 B**<br>10 B |

2023-03-15 08:40 UTC, circleci-mu commented
## Visual test results - No difference found

---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  Modified | samples/highcharts/data/delimiters/demo.js |
|  ? | samples/highcharts/blog/blog-landing-page/demo.js |
|  ? | samples/highcharts/blog/blog-custom-map/demo.js |
|  ? | samples/highcharts/blog/homepage/demo.js |
|  ? | samples/highcharts/blog/blog-planet-atmospheres/demo.js |
|  ? | samples/highcharts/blog/blog-themes-demo/demo.js |
|  ? | samples/highcharts/blog/blog-update-options/demo.js |

</p>
</details>

2023-03-15 14:54 UTC, sebastianbochan requested changes

2023-03-15 14:54 UTC, sebastianbochan commented on css/dashboards/gui.css
> +    overflow-y: hidden;
Replace
```
overflow-x: hidden;
overflow-y: hidden;
```
with
```
overflow:hidden
```

2023-03-15 14:54 UTC, sebastianbochan commented on css/dashboards/gui.css
> +    max-width: 600px;
In case of `width: 200px;` the `max-width` will not be used anymore.

2023-03-15 14:54 UTC, sebastianbochan commented on css/dashboards/gui.css
> +    min-width: 300px;
The `min-width` is bigger than `width`. We should use the only one.

2023-03-15 14:54 UTC, sebastianbochan commented on css/dashboards/gui.css
> +    padding: 10px;
In case of background-position 50/50%, you can declare only width/height. The padding is unecessary.

2023-03-15 18:11 UTC, pawellysy requested changes

2023-03-15 18:11 UTC, pawellysy commented on css/dashboards/gui.css
>      left: calc(50% - 150px);
maybe instead of this left, we could go with:
```css
left: 50%
transform: translate(-50%, 0)
```

2023-03-16 08:46 UTC, karolkolodziej commented on ts/Dashboards/EditMode/EditMode.ts
> +            EditGlobals.iconsURL,
Any suggestions?

2023-03-16 09:26 UTC, sebastianbochan approved these changes

2023-03-16 09:33 UTC, pawellysy commented on ts/Dashboards/EditMode/EditMode.ts
> +            EditGlobals.iconsURL,
Can be referenced as a value in the Class IMO.

2023-03-16 11:13 UTC, pawellysy commented on ts/Dashboards/EditMode/EditMode.ts
> +            EditGlobals.iconsURL,
nvm, leave as it is

2023-03-16 11:13 UTC, pawellysy approved these changes

2023-03-16 11:22 UTC, merged