db/iconURLPrefix
highcharts/highcharts pull request #18703
Opened 2023-03-21 13:05 UTC by karolkolodziej

Added `iconURLPrefix`.

2023-03-21 13:27 UTC, circleci-mu commented
## Visual test results - No difference found

---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  Modified | samples/highcharts/data/delimiters/demo.js |
|  ? | samples/highcharts/blog/blog-landing-page/demo.js |
|  ? | samples/highcharts/blog/blog-custom-map/demo.js |
|  ? | samples/highcharts/blog/homepage/demo.js |
|  ? | samples/highcharts/blog/blog-planet-atmospheres/demo.js |
|  ? | samples/highcharts/blog/blog-themes-demo/demo.js |
|  ? | samples/highcharts/blog/blog-update-options/demo.js |

</p>
</details>

2023-03-22 08:50 UTC, pawellysy approved these changes
Looks good!

2023-03-24 13:20 UTC, sebastianbochan requested changes

2023-03-24 13:20 UTC, sebastianbochan commented on ts/Dashboards/EditMode/EditMode.ts
> +    public iconsURLPrefix: string;
Why do not place the default value here? In terms of it, we can simplify the condition

```
options && options.iconsURLPrefix ||
            'https://code.highcharts.com/@product.version@/gfx/dashboard-icons/';
```

2023-03-27 09:27 UTC, merged