Added modifier support to ChainModifier options.
highcharts/highcharts pull request #18707
Opened 2023-03-21 16:56 UTC by bre1470

2023-03-22 06:42 UTC, karolkolodziej approved these changes

2023-03-22 06:42 UTC, karolkolodziej requested changes
Please resolve conflicts and check linter

2023-04-03 13:16 UTC, circleci-mu commented
## Visual test results - No difference found

2023-04-03 13:28 UTC, karolkolodziej approved these changes

2023-04-12 12:10 UTC, sebastianbochan approved these changes

2023-04-14 11:09 UTC, goransle approved these changes

2023-04-17 08:11 UTC, merged