db/JSON-api
highcharts/highcharts pull request #18719
Opened 2023-03-23 08:04 UTC by karolkolodziej

Marked some of the JSON properties and methods as internal.

2023-03-23 08:27 UTC, circleci-mu commented
## Visual test results - No difference found

---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  Modified | samples/highcharts/data/delimiters/demo.js |
|  ? | samples/highcharts/blog/blog-landing-page/demo.js |
|  ? | samples/highcharts/blog/blog-custom-map/demo.js |
|  ? | samples/highcharts/blog/homepage/demo.js |
|  ? | samples/highcharts/blog/blog-planet-atmospheres/demo.js |
|  ? | samples/highcharts/blog/blog-themes-demo/demo.js |
|  ? | samples/highcharts/blog/blog-update-options/demo.js |

</p>
</details>

2023-03-24 13:25 UTC, sebastianbochan requested changes

2023-03-24 13:25 UTC, sebastianbochan commented on ts/Dashboards/Components/Component.ts
> +     * // JSON compatible options for export
Do we need `//` here? :)

2023-03-27 07:30 UTC, sebastianbochan approved these changes

2023-03-27 08:29 UTC, pawellysy approved these changes

2023-03-27 08:40 UTC, merged