bugfix/18074-dragdrop-mappoint
highcharts/highcharts pull request #18721
Opened 2023-03-23 10:00 UTC by hubertkozik

Fixed #18074, the Draggable Points module didn't work for MapPoints.

2023-03-23 10:20 UTC, circleci-mu commented
### File size comparison
No differences found

2023-03-23 21:45 UTC, magdalena-gut commented on samples/unit-tests/dragdrop/mappoint/demo.js
> +    assert.ok(
What about combining these two checks to  `assert.ok(point.plotX < oldPointPlotX && point.plotY < oldPointPlotY)` ? Similar situation to `assert.strictEqual` above.

2023-03-24 14:59 UTC, KacperMadej approved these changes

2023-03-30 18:06 UTC, TorsteinHonsi requested changes
How does a draggable map area work? We need a visual sample too in addition to the unit test.

2023-03-31 10:09 UTC, hubertkozik commented
Drag drop has never worked for MapSeries in Highcharts Maps. Furthermore, MapSeries doesn't have simple lon / lat positions to change it with a mouse move. In this bugfix, I focused on removing the regression about DragDrop for MapPoints, which was present after some major changes in Highcharts Maps v9.3.3. Adding a DragDrop for MapSeries would be a totally new feature and it would require a lot more time to implement it (from scratch).

2023-04-11 06:51 UTC, TorsteinHonsi approved these changes
Awesome, thanks!

2023-04-11 06:52 UTC, TorsteinHonsi requested changes
... but please resolve the conflict :/

2023-04-11 08:28 UTC, TorsteinHonsi approved these changes

2023-04-11 08:28 UTC, merged