db/component-width-unify
highcharts/highcharts pull request #18728
Opened 2023-03-24 14:07 UTC by sebastianbochan

2023-03-24 14:29 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts.js | **100.2 kB**<br>296.6 kB | **100.2 kB**<br>296.7 kB | **35 B**<br>65 B |
| highstock.js | **133.0 kB**<br>401.5 kB | **133.0 kB**<br>401.5 kB | **36 B**<br>65 B |
| highmaps.js | **126.2 kB**<br>382.8 kB | **126.3 kB**<br>382.8 kB | **33 B**<br>65 B |
| highcharts-gantt.js | **135.5 kB**<br>406.4 kB | **135.6 kB**<br>406.5 kB | **51 B**<br>65 B |
| modules/annotations.js | **18.1 kB**<br>64.6 kB | **18.1 kB**<br>64.6 kB | **7 B**<br>10 B |
| modules/annotations-advanced.js | **25.0 kB**<br>97.4 kB | **25.0 kB**<br>97.4 kB | **8 B**<br>10 B |

2023-03-24 14:56 UTC, pawelfus approved these changes
Thanks!

2023-03-24 14:56 UTC, pawelfus commented on samples/dashboards/demos/layout-nested/demo.js
> +                                            id: 'dashboard-col-layout-2b',
unnecessary comma 😬

2023-03-27 06:51 UTC, karolkolodziej requested changes

2023-03-27 06:51 UTC, karolkolodziej commented on ts/Dashboards/Layout/Cell.ts
> +    }
```suggestion
    private convertWidthToValue(width: number|string): string {
        if (typeof width === 'number') {
            return width + 'px';
        }
        if (/px/.test(width)) {
            return width;
        }

        return GUIElement.getPercentageWidth(width) || '';
    }
```

2023-03-27 08:29 UTC, pawellysy approved these changes

2023-03-27 09:08 UTC, sebastianbochan commented on ts/Dashboards/Layout/Cell.ts
> +    }
Nice!

2023-03-27 09:10 UTC, karolkolodziej approved these changes

2023-03-27 11:38 UTC, merged