Db/synchandler doclets
highcharts/highcharts pull request #18723
Opened 2023-03-23 11:27 UTC by goransle

2023-03-23 11:47 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts.js | **100.2 kB**<br>296.6 kB | **100.2 kB**<br>296.7 kB | **35 B**<br>65 B |
| highstock.js | **133.0 kB**<br>401.5 kB | **133.0 kB**<br>401.5 kB | **36 B**<br>65 B |
| highmaps.js | **126.2 kB**<br>382.8 kB | **126.3 kB**<br>382.8 kB | **33 B**<br>65 B |
| highcharts-gantt.js | **135.5 kB**<br>406.4 kB | **135.6 kB**<br>406.5 kB | **51 B**<br>65 B |
| modules/annotations.js | **18.1 kB**<br>64.6 kB | **18.1 kB**<br>64.6 kB | **7 B**<br>10 B |
| modules/annotations-advanced.js | **25.0 kB**<br>97.4 kB | **25.0 kB**<br>97.4 kB | **7 B**<br>10 B |

2023-03-23 11:50 UTC, circleci-mu commented
## Visual test results - No difference found

---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  Modified | samples/highcharts/data/delimiters/demo.js |
|  ? | samples/highcharts/blog/blog-landing-page/demo.js |
|  ? | samples/highcharts/blog/blog-custom-map/demo.js |
|  ? | samples/highcharts/blog/homepage/demo.js |
|  ? | samples/highcharts/blog/blog-planet-atmospheres/demo.js |
|  ? | samples/highcharts/blog/blog-themes-demo/demo.js |
|  ? | samples/highcharts/blog/blog-update-options/demo.js |

</p>
</details>

2023-03-24 08:53 UTC, karolkolodziej requested changes

2023-03-24 08:53 UTC, karolkolodziej commented on ts/Dashboards/Components/Sync/Emitter.ts
> +     * Adds an emitter to the emitter regisitry.
```suggestion
     * Adds an emitter to the emitter registry.
```

2023-03-24 08:55 UTC, karolkolodziej commented
Looks good but I'd like to know if we should show all of that.

IMO the `OptionsEntry` should be enough for now especially after we establish that there should not be any standalone components.

2023-03-24 13:06 UTC, pawelfus reviewed
+1 to what Karol said: how much of it is necessary to build a dashboard? Which other part is necessary to build custom components and create sync between those and existing ones?

2023-03-24 13:14 UTC, sebastianbochan approved these changes

2023-03-27 07:53 UTC, goransle commented
> +1 to what Karol said: how much of it is necessary to build a dashboard? Which other part is necessary to build custom components and create sync between those and existing ones?

`OptionsEntry` should cover it it for most use cases.

2023-03-30 07:25 UTC, circleci-mu commented
## Cypress visual test results

2023-03-31 08:46 UTC, pawelfus approved these changes
Thanks!

2023-03-31 11:42 UTC, bre1470 approved these changes
Looks good. 👍

2023-04-03 08:32 UTC, pawellysy approved these changes

2023-04-03 10:36 UTC, karolkolodziej approved these changes

2023-04-12 08:50 UTC, merged