Db/sync extremes
highcharts/highcharts pull request #18766
Opened 2023-03-30 08:11 UTC by goransle

Removed separate panning sync option/handler, renamed `selection` to `extremes`

2023-03-30 08:20 UTC, circleci-mu commented
## Cypress visual test results

2023-04-14 07:44 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| modules/dashboards-plugin.js | **18.0 kB**<br>67.8 kB | **17.9 kB**<br>67.3 kB | **-141 B**<br>-533 B |

2023-04-28 08:07 UTC, karolkolodziej requested changes
In `dashboards/demos/axes-sync` I'm getting:
![image](https://user-images.githubusercontent.com/57004120/235091816-6ff003de-273b-435e-a18f-01af139ab7d9.png)

2023-04-28 08:07 UTC, karolkolodziej commented on samples/cypress/dashboards/sync/chart-extremes/demo.details
> +  - Torstein Hønsi
Are you sure?

2023-04-28 09:27 UTC, bre1470 commented
In master / master merge it became `Dashboards.DataConnector.registry.CSV`, so maybe recompile to fix the issue?

2023-04-28 10:05 UTC, bre1470 commented
Reset Zoom is not working for me in axes-sync.

2023-04-28 10:14 UTC, goransle commented
> 

As in it does not reset the chart you are clicking the button on? Or not resetting the linked chart? The latter is intended to simplify things, but I can probably bring back the reset-sync.

2023-05-01 07:32 UTC, pawellysy approved these changes

2023-05-03 07:27 UTC, karolkolodziej requested changes
I'm also in favour of syncing the Reset zoom button.

2023-05-12 07:40 UTC, bre1470 requested changes
This PR would restore regressions

2023-05-22 10:21 UTC, goransle commented
Visual comparison error is likely due to outdated `highcharts-utils` on `dashboard/main`

2023-05-22 11:36 UTC, sebastianbochan approved these changes

2023-05-23 06:18 UTC, merged