bugfix/18643-indicator-error
highcharts/highcharts pull request #18791
Opened 2023-04-05 13:04 UTC by jakubjanuchta

Fixed #18643, indicator threw volumeSeriesID error on range selector click

2023-04-05 13:25 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts.js | **100.2 kB**<br>296.6 kB | **100.2 kB**<br>296.6 kB | **3 B**<br>18 B |
| highstock.js | **133.0 kB**<br>401.5 kB | **133.0 kB**<br>401.6 kB | **30 B**<br>18 B |
| highmaps.js | **126.3 kB**<br>382.9 kB | **126.4 kB**<br>382.9 kB | **50 B**<br>18 B |
| highcharts-gantt.js | **135.6 kB**<br>406.5 kB | **135.6 kB**<br>406.5 kB | **50 B**<br>18 B |
| indicators/indicators-all.js | **23.0 kB**<br>99.1 kB | **23.0 kB**<br>99.2 kB | **18 B**<br>14 B |

2023-04-05 14:28 UTC, pawelfus requested changes

2023-04-05 14:28 UTC, pawelfus commented on ts/Stock/Indicators/SMA/SMAIndicator.ts
> +                if (!isUpdating) {
Instead of:
```ts
if () {
  if () {
    // code
  }
}
```
You can do:
```ts
if () {
  return;
}

if () {
  // code
}
```

2023-04-05 14:41 UTC, pawelfus commented
A short explanation to @TorsteinHonsi :

Tech Indicators are calculated after series are linked to each other (thanks to that, we don't care about the order of series in `series` array).

When you configure RangeSelector to set `dataGrouping` on click, then under the hood you call `series.update()`. Which means `series.remove` + `series.init`. And both of these methods cause linking series. After linking in `remove()`, the linked parent series is missing, thus an error in the console.

To solve it, we pass on `keepEvents`/`isUpdating` flag from `series.update()` method to `recalculateValues()`, so when linking happens, we simply skip calculating values.

Note: Updating DG from RangeSelector is just one scenario, others can happen too (simple example: https://jsfiddle.net/BlackLabel/8kjd5g71/ = two consequent updates, indicator without a redraw)

2023-04-07 08:11 UTC, pawelfus approved these changes
Thanks!

Extra request: VbP also has a bit different solution to overcome this issue. Could you try removing logic in `VbP.init` and see if that helps?

2023-04-07 08:11 UTC, pawelfus commented on ts/Stock/Indicators/SMA/SMAIndicator.ts
> +            function ({ isUpdating }: AnyRecord): void {
Probably type:
```ts
function (event: { isUpdating: boolean })
```
 would be better. Or perhaps
 
```ts
function (event: Event&{ isUpdating: boolean })
```

Or shall we create a separate interface for it? 🤔 What do you think @bre1470

2023-04-07 09:52 UTC, jakubjanuchta commented
> Thanks!
> 
> Extra request: VbP also has a bit different solution to overcome this issue. Could you try removing logic in `VbP.init` and see if that helps?

Thanks @pawelfus!
As discussed, it cannot be checked because of another issue related to VBP series

2023-04-11 06:33 UTC, merged