DataPool demo
highcharts/highcharts pull request #18810
Opened 2023-04-11 17:14 UTC by bre1470

Builds on #18787

2023-04-11 17:37 UTC, circleci-mu commented
## Visual test results - No difference found

---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  Added | samples/highcharts/data-tools/datapool-html/demo.js |

</p>
</details>

2023-04-20 05:50 UTC, goransle approved these changes
Looking good

2023-04-20 05:59 UTC, karolkolodziej approved these changes

2023-04-20 12:30 UTC, pawellysy approved these changes
LGTM!

2023-04-21 09:50 UTC, TorsteinHonsi approved these changes
Looks good!

2023-04-24 08:16 UTC, sebastianbochan requested changes

2023-04-24 08:16 UTC, sebastianbochan commented on samples/highcharts/data-tools/datapool-html/demo.css
> +    --color-foreground: #000;
IMO would be better to use --color-text, because of using for param `color:` that is applied for the font.

2023-05-02 09:14 UTC, merged