Db/component options parser
highcharts/highcharts pull request #18819
Opened 2023-04-13 07:55 UTC by pawellysy

2023-04-13 08:18 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| modules/dashboards-plugin.js | **18.0 kB**<br>67.8 kB | **18.0 kB**<br>68.0 kB | **2 B**<br>137 B |
| dashboards.js | **46.5 kB**<br>163.1 kB | **40.8 kB**<br>152.0 kB | **-5831 B**<br>-11322 B |

2023-04-13 08:20 UTC, circleci-mu commented
## Cypress visual test results

2023-04-21 09:17 UTC, sebastianbochan requested changes

2023-04-21 09:17 UTC, sebastianbochan commented on ts/Dashboards/Components/HTMLComponent.ts
> +                Component.defaultOptions.editableOptions?.concat(
Remove optional chaining.

2023-04-21 09:21 UTC, sebastianbochan requested changes

2023-04-21 09:21 UTC, sebastianbochan commented on samples/dashboards/demos/minimal/demo.js
> +board.editMode.sidebar.show(cell);
Possible issue with toolbars.

2023-04-21 09:21 UTC, sebastianbochan commented on test/cypress/integration/Dashboards/edit-component.cy.js
> +    it.skip('should be able update chart ID via edit mode GUI', function() {
Test should not be skipped.

2023-04-21 09:21 UTC, sebastianbochan commented on ts/Dashboards/EditMode/AccordeonMenu.ts
> +                // console.log('Invalid JSON passed to the chart chart config');
Return any error or console log at least?

2023-04-21 09:21 UTC, sebastianbochan commented on ts/Dashboards/EditMode/EditGlobals.ts
> +        'https://cdn.jsdelivr.net/gh/highcharts/highcharts@0b8caf6/gfx/dashboard-icons/',
Would be good to update the URL, because of changed close btn icon

2023-04-21 09:21 UTC, sebastianbochan commented on ts/Dashboards/EditMode/EditGlobals.ts
> +        accordeonNestedContent: string;
```
accordeonNestedHeader: string;
        accordeonNestedHeaderBtn: string;
        accordeonNestedHeaderIcon: string;
        accordeonNestedContent: string;
```
Are not necessary.

2023-04-24 07:28 UTC, goransle commented on ts/Dashboards/EditMode/EditGlobals.ts
> +        chartConfig: 'Chart configuration',
`configuration`

2023-04-24 07:34 UTC, goransle requested changes
Looks good, the failing Cypress test needs updating though

2023-04-24 08:15 UTC, karolkolodziej requested changes
- [x] If I expand some of the accordion menu the buttons at the bottom are not fully visible:
![image](https://user-images.githubusercontent.com/57004120/233933838-c6d152db-1623-4de2-aa9c-0b402f188f39.png)

- [x] Credits and data labels toggle doesn't work
![image](https://user-images.githubusercontent.com/57004120/233934294-d2561953-251d-4ed5-b4c5-002a69068a74.png)

- [x] When you add a component by dropping it, the background is not faded

2023-04-24 08:15 UTC, karolkolodziej commented on ts/Dashboards/EditMode/AccordeonMenu.ts
> +import type Component from '../Components/Component.js';
no need for `.js`

2023-04-24 08:15 UTC, karolkolodziej commented on ts/Dashboards/EditMode/EditRenderer.ts
> +    checked?: boolean
description is missing

2023-04-24 08:21 UTC, sebastianbochan commented on css/dashboards/gui.css
> +    --highcharts-neutral-color-10: #e7e7ec;
After the last merge, it is. :)

Pawel, we can remove it from here.

2023-04-24 08:21 UTC, sebastianbochan commented on css/dashboards/gui.css
> +    width: calc(100% - 20px);
Any sugestion?

2023-04-24 08:21 UTC, sebastianbochan commented on css/dashboards/gui.css
> +    width: calc(100% - 6px);
Because of paddings.

2023-04-24 08:22 UTC, sebastianbochan commented on ts/Dashboards/EditMode/AccordeonMenu.ts
> +            { className: EditGlobals.classNames.accordeonMenuButtonsContainer },
What do you mean?

2023-04-24 09:25 UTC, pawellysy commented on ts/Dashboards/EditMode/EditGlobals.ts
> +    iconsURLPrefix:
It is, until the release.

2023-04-24 10:23 UTC, pawelfus requested changes
A few bugs:

1. [minimal](http://utils.highcharts.local/samples/#view/dashboards/demos/minimal) demo, steps:
  - Enter edit mode, on the bottom left there are some unnecessary icons:
![image](https://user-images.githubusercontent.com/1453926/233968088-db820e24-bf92-4e90-af50-7252112abf05.png)

2. xAxis, yAxis, tooltip.format, dataLabels and credits options don't work
3. Dark-theme:

- Dropdowns are unreadable and inputs are not changed:
![image](https://user-images.githubusercontent.com/1453926/233969686-79ea5760-9c62-489c-9f39-f87811dddd86.png)

- @karolkolodziej - are styles RWD icons merged (your PR)? Just want to make sure something is not accidentally broken: 
![image](https://user-images.githubusercontent.com/1453926/233969285-53d1526b-d2cf-489f-aacf-a0fe6bba2bf9.png)

2023-04-25 10:06 UTC, sebastianbochan approved these changes

2023-04-25 12:14 UTC, karolkolodziej approved these changes

2023-04-25 19:57 UTC, pawellysy commented
@pawelfus the updates with sidebar are working, but there is something wrong with multiple updates: https://jsfiddle.net/BlackLabel/kret8ah1/

(Probably with the updates of the API options, which can be objects and arrays simultaneously like the axes).

Probably the issue is connected to the update of the options done here: https://github.com/highcharts/highcharts/blob/30b4d4ad0511e894527b1529c04c63ea93fd2503/ts/Extensions/DashboardPlugins/HighchartsComponent.ts#L307-L315

I'd leave it as it is, and fix it in the separate ticket, because this bug was present for some time, and with the sidebar refactor it got more visible and easy to reproduce.

2023-04-26 15:03 UTC, pawelfus requested changes
Looks really good, just a minor nitpicking!

2023-04-27 07:30 UTC, pawellysy commented on ts/Extensions/DashboardPlugins/HighchartsComponent.ts
> +            (Component.defaultOptions.editableOptions || []).concat([
I'd leave it as it is because it is not so big yet. But something to keep in mind in future

2023-04-27 08:24 UTC, bre1470 commented on ts/Dashboards/EditMode/SidebarPopup.ts
> +                                    'WjQM3VeT0AAAAASUVORK5CYII='
Or it goes into CSS and gets triggered with a style class.

2023-04-27 12:59 UTC, sebastianbochan commented
It looks like a bug with dragging, not related to sidebar.

2023-04-27 13:14 UTC, pawellysy commented
@bre1470 check out the `dashboards/main` vs `dashboards/mvp` branches and try to select text on those 2 branches (without drag and drop). It got changed elsewhere, and probably was never connected to dragging. On the other hand, the hover effect on charts/datagrid was also triggered on dashboards/mvp, so I'd deal with it in the seperate ticket.

2023-04-28 12:01 UTC, bre1470 approved these changes
Okay. Great job! 👍

2023-04-29 12:44 UTC, merged