feature/12523-pointandfigure-series
highcharts/highcharts pull request #18855
Opened 2023-04-20 08:52 UTC by kamil-musialowski

2023-04-20 09:13 UTC, circleci-mu commented
### File size comparison
No differences found

2023-04-20 09:16 UTC, circleci-mu commented
## Visual test results - No difference found

2023-04-20 14:14 UTC, pawelfus requested changes
Overall looks good! 
Just a minor nitpicking 👍

2023-04-20 14:14 UTC, pawelfus commented on samples/highcharts/studies/pointandfigure/demo.js
> +        symbolUp: {
`markerUp` seems to fit a bit better here since we have `marker` for "`down`"

2023-04-20 14:14 UTC, pawelfus commented on samples/highcharts/studies/pointandfigure/demo.js
> +    // Options
Missing default options for:
- `boxSize` (I think we agreed on percentage, like 5%?)
- `reversalAmount` (defaults to 3x, right?)

2023-04-24 13:38 UTC, pawelfus approved these changes
Thanks!

2023-04-28 07:30 UTC, TorsteinHonsi approved these changes

2023-04-28 07:30 UTC, merged