db/dataPool-connector-names
highcharts/highcharts pull request #18875
Opened 2023-04-25 13:54 UTC by karolkolodziej

Added method that returns names of connectors.

2023-04-25 14:07 UTC, circleci-mu commented
## Cypress visual test results

 * [cypress/snapshots/diff/test/cypress/visual/Dashboards.cy.js/dashboard-climate-loaded-diff.png](https://vrevs.highsoft.com/api/assets/visualtests/diffs/pullrequests/18875/cypress/snapshots/diff/test/cypress/visual/Dashboards.cy.js/dashboard-climate-loaded-diff.png)

2023-04-25 14:14 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| dashboards.js | **46.5 kB**<br>163.1 kB | **46.5 kB**<br>163.2 kB | **1 B**<br>106 B |

2023-04-25 14:19 UTC, sebastianbochan requested changes

2023-04-25 14:19 UTC, sebastianbochan commented on ts/Data/DataPool.ts
> +        return this.options.connectors.map(
We should not use `.map`, `.filter` due to performance reasons.

2023-04-25 19:41 UTC, pawellysy requested changes
Could you add Unit test to that? 😅

2023-04-26 08:19 UTC, sebastianbochan approved these changes

2023-04-26 10:10 UTC, bre1470 approved these changes
Looks good. 👍

2023-04-26 10:33 UTC, merged