bugfix/17791-wrong-extremes-one-point-multiple-series
highcharts/highcharts pull request #18897
Opened 2023-04-27 14:43 UTC by hubertkozik

Fixed #17791, `pointRange` wasn't calculated for multiple series with single points.

____

This was an issue, which was reported by users many times, e.g. 
- https://github.com/highcharts/highcharts/issues/7220
- https://github.com/highcharts/highcharts/issues/7346
- https://github.com/highcharts/highcharts/issues/4112
- https://github.com/highcharts/highcharts/issues/3071
- https://github.com/highcharts/highcharts/issues/712
- https://github.com/highcharts/highcharts/issues/987

I think it would be good to make native support in HC Core for this problem.

2023-04-27 15:04 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts.js | **98.4 kB**<br>279.6 kB | **98.5 kB**<br>280.0 kB | **176 B**<br>398 B |
| highstock.js | **130.6 kB**<br>378.6 kB | **130.7 kB**<br>379.0 kB | **158 B**<br>396 B |
| highmaps.js | **123.4 kB**<br>356.3 kB | **123.5 kB**<br>356.7 kB | **123 B**<br>396 B |
| highcharts-gantt.js | **133.2 kB**<br>384.5 kB | **133.4 kB**<br>384.9 kB | **138 B**<br>396 B |

2023-04-27 15:07 UTC, circleci-mu commented
## Visual test results - No difference found

2023-04-28 07:19 UTC, TorsteinHonsi requested changes
Thanks! 

Since we're now in the core of the core, I was hoping for a more compact solution. We already have the `Axis.getClosest` function that is supposed to return the distance between the closest points. A modification of that function shows promising results:

```ts
    public getClosest(): number {
        let ret: any,
            closestSingle = Infinity;

        if (this.categories) {
            ret = 1;
        } else {
            const singleXs: number[] = [];
            this.series.forEach(function (series): void {
                const seriesClosest = series.closestPointRange,
                    visible = series.visible ||
                        !series.chart.options.chart.ignoreHiddenSeries;

                if (series.xData?.length === 1) {
                    singleXs.push(series.xData[0]);
                } else if (
                    !series.noSharedTooltip &&
                    defined(seriesClosest) &&
                    visible
                ) {
                    ret = defined(ret) ?
                        Math.min(ret, seriesClosest) :
                        seriesClosest;
                }
            });
            if (singleXs.length) {
                singleXs.sort((a, b): number => a - b);
                let i = singleXs.length;
                while (--i) {
                    const distance = singleXs[i] - singleXs[i - 1];
                    if (distance > 0 && distance < closestSingle) {
                        closestSingle = distance;
                    }
                }
            }
        }
        return Math.min(closestSingle, ret || Infinity);
    }
```
I tested this successfully on the OP demo, but not on your unit tests, so there may be edge cases I didn't think of. If this is a viable way forward, we should also
* Clean up the use of any/Inifinity/defined in the logic. We can probably just start out with Infinity for both variants, then return the number only if it is < Infinity.
* Assess whether it is better to refactor the get-smallest-distance code into a utility function to avoid repeating ourselves. It is now used in [Series.ts](https://github.com/highcharts/highcharts/blob/6af547daa0aaecae9bb1ed1b0b59453e600053b6/ts/Core/Series/Series.ts#L1690-L1718), [Axis.ts](https://github.com/highcharts/highcharts/blob/6af547daa0aaecae9bb1ed1b0b59453e600053b6/ts/Core/Axis/Axis.ts#L1261-L1274) and maybe other places, plus now this new logic.

2023-05-17 08:20 UTC, hubertkozik commented
@TorsteinHonsi I have decided to not refactor code in [Series.ts](https://github.com/highcharts/highcharts/blob/6af547daa0aaecae9bb1ed1b0b59453e600053b6/ts/Core/Series/Series.ts#L1690-L1718) because it is the only place in HC, where `closestPointRange` is calculated for only one series. The other places are calculating the `closestPointRange` based on all series on one axis - that's why I have moved the code to a utility function. By the way, changes in `Axis.getClosest` method are enough to fix the main bug.

2023-05-23 10:24 UTC, TorsteinHonsi approved these changes

2023-05-23 10:25 UTC, merged