bugfix/14602-arearange-label-on-area-true
highcharts/highcharts pull request #18896
Opened 2023-04-27 13:49 UTC by jakubjanuchta

Fixed #14602, arearange label onArea: true was not implemented.

2023-04-27 14:10 UTC, circleci-mu commented
### File size comparison
No differences found

2023-04-27 14:12 UTC, circleci-mu commented
## Visual test results - No difference found

2023-04-28 07:33 UTC, TorsteinHonsi requested changes
Thanks, looks good!

For the unit test, can you add the series labels to one of the existing charts instead of creating a new `test` with a new chart? It's for keeping the performance of the test unit on a decent level.

2023-04-28 08:57 UTC, jakubjanuchta commented
> Thanks, looks good!
> 
> For the unit test, can you add the series labels to one of the existing charts instead of creating a new `test` with a new chart? It's for keeping the performance of the test unit on a decent level.

I wanted to extract this tests to a new chart for better visibility, but I understand that performance is more important in that case. I moved them to another test unit.

2023-04-28 09:09 UTC, TorsteinHonsi approved these changes
> I wanted to extract this tests to a new chart for better visibility, but I understand that performance is more important in that case. I moved them to another test unit.

@jakubjanuchta Sure, sometimes it is better to create a new to avoid big test monsters.

2023-04-28 09:09 UTC, merged