db/dark-mode-tweaks
highcharts/highcharts pull request #18959
Opened 2023-05-08 07:03 UTC by karolkolodziej

Simplified styling in the `climate` demo. 
Moved some of the stylings to `gui.css` and `datagrid.css`

2023-05-08 07:18 UTC, circleci-mu commented
## Cypress visual test results

 * [cypress/snapshots/diff/test/cypress/visual/Dashboards.cy.js/dashboard-climate-edit-mode-diff.png](https://vrevs.highsoft.com/api/assets/visualtests/diffs/pullrequests/18959/cypress/snapshots/diff/test/cypress/visual/Dashboards.cy.js/dashboard-climate-edit-mode-diff.png)

2023-05-08 07:22 UTC, circleci-mu commented
### File size comparison
No differences found

2023-05-08 12:27 UTC, bre1470 requested changes
KPI colors do not change with toggle - only with system-wide dark mode.

2023-05-10 09:09 UTC, pawellysy approved these changes
LGTM!

2023-05-10 10:51 UTC, sebastianbochan approved these changes

2023-05-10 22:55 UTC, bre1470 approved these changes

2023-05-11 06:08 UTC, merged