bugfix/18960-dumbbell-data-labels
highcharts/highcharts pull request #18973
Opened 2023-05-10 11:30 UTC by jakubSzuminski

Fixed #18960, dataLabels did not work for Dumbbell Series after update from Highcharts 10 to Highcharts 11.

The issue was the change of `ColumnRangeSeries.prototype.translate()` function which was used in `DumbellSeries` as a `setShapeArgs` function.

**Demo before fix:** https://jsfiddle.net/kluvin/a1Lg4k75/
**Demo after fix:** https://jsfiddle.net/BlackLabel/e9fa0ck8/

2023-05-10 11:48 UTC, circleci-mu commented
### File size comparison
No differences found

2023-05-10 11:51 UTC, circleci-mu commented
## Visual test results - No difference found

2023-05-11 10:24 UTC, karolkolodziej approved these changes
Please add test as Torstein mentioned

2023-05-11 11:46 UTC, jakubSzuminski commented
This dumbbell sample should pick up on this issue as the `dataLabels` are now shown.

2023-05-12 07:47 UTC, TorsteinHonsi requested changes

2023-05-12 07:47 UTC, TorsteinHonsi commented on samples/highcharts/demo/dumbbell/demo.js
This is the main demo that we display in our web pages, https://www.highcharts.com/demo/dumbbell

I don't think we should add data labels here, as it kind of clutters up the nice clean appearance of the chart. A Google Images search confirms that this chart type is more often used without data labels. We have a sample for `highcharts/series-dumbbell/styled-mode-dumbbell` that is not part of the website demos, we could add the labels there instead.

2023-05-12 08:48 UTC, jakubSzuminski commented on samples/highcharts/demo/dumbbell/demo.js
You're right. I'm sorry, my mistake. I've now enabled dataLabels for the `highcharts/series-dumbbell/styled-mode-dumbbell` sample.

2023-05-12 09:56 UTC, merged