db/fixed-dark-mode-demo
highcharts/highcharts pull request #19013
Opened 2023-05-17 12:33 UTC by sebastianbochan

2023-05-17 12:52 UTC, circleci-mu commented
### File size comparison
No differences found

2023-05-18 07:07 UTC, karolkolodziej requested changes

2023-05-18 07:07 UTC, karolkolodziej commented on samples/dashboards/demos/component-highcharts/demo.js
> +Highcharts.setOptions({
Why don't we enable that for each HighchartsComponent?

2023-05-18 07:07 UTC, karolkolodziej commented on samples/dashboards/demos/axes-sync/demo.css
> +@import url("https://code.highcharts.com/css/dashboards/gui.css");
It isn't fully solved.
![image](https://github.com/highcharts/highcharts/assets/57004120/f81dfffe-8b8e-4ed7-92e6-6fcdfa451d8f)

2023-05-19 06:53 UTC, karolkolodziej approved these changes
The code looks and works, but please check the conflicts and failing tests in Cypress before merging.

2023-05-22 11:11 UTC, bre1470 requested changes
`dashboards/cypress/add-layout` needs an update as well.

![Screenshot 2023-05-22 at 13 10 37](https://github.com/highcharts/highcharts/assets/40056287/816fa197-9902-498f-b8a8-7534a634f036)

2023-05-22 11:42 UTC, bre1470 approved these changes
@sebastianbochan
Okay, I see.

I also find it strange that there is a line in the menu itself. It looks like the demo is not up to date with styling in general.

2023-05-22 14:07 UTC, merged