bugfix/12063-packedbubble-bad-positions-after-width-update
highcharts/highcharts pull request #19020
Opened 2023-05-19 09:33 UTC by hubertkozik

Fixed #12063, packed bubble parent nodes had a bad position after the width update.

2023-05-19 09:54 UTC, circleci-mu commented
### File size comparison
No differences found

2023-05-19 09:56 UTC, circleci-mu commented
## Visual test results - No difference found

2023-05-19 11:38 UTC, pawelfus requested changes
Nice, minor change only

2023-05-19 11:38 UTC, pawelfus commented on ts/Series/PackedBubble/PackedBubbleSeries.ts
> +            this.parentNode.plotY &&
When checking the number-type value, always use `H.defined()`, so `0`-values are correctly handled. For example `plotX = 0` and `plotY = 0` (top left corner) would be skipped forever if that happens (unlikely, but still)

2023-05-19 12:40 UTC, pawelfus approved these changes
Thanks!

2023-05-22 06:20 UTC, TorsteinHonsi approved these changes
Thanks!

2023-05-22 06:20 UTC, merged