feature/19038-treegraph-fill-x-option
highcharts/highcharts pull request #19061
Opened 2023-05-29 10:40 UTC by Vazonik

Added the `fillX` option for the treegraph to fill the space in X by all visible points. See #19038.

2023-05-29 10:59 UTC, circleci-mu commented
### File size comparison
No differences found

2023-05-30 10:37 UTC, TorsteinHonsi requested changes
Thanks!

* First of all, we need a visual `@sample` to accompany the doclet for the new option.
* In the PR description, add a link to the API option for `fillX`. It does not yet exist, but it will do after release.

Another thing to consider - how does this work with an inverted treegraph?

2023-05-31 13:52 UTC, Vazonik commented
@TorsteinHonsi Thanks for the review!
After advice from the team, I decided to rename the option from `fillX` to `fillSpace`.

> Another thing to consider - how does this work with an inverted treegraph?

With both inverted chart and reversed series it seems to work fine. (I found one bug, but it's unrelated to this feature and I reported it here: #19068.)

2023-05-31 14:06 UTC, TorsteinHonsi requested changes
Thanks, nice demo! Just a little nitpicking now.

2023-05-31 14:06 UTC, TorsteinHonsi commented on samples/highcharts/series-treegraph/fillspace-option/demo.css
Just `series-treegraph/fillspace` will do for the file path. There are lots of options, we don't need `-option` as part of the path.

2023-05-31 14:06 UTC, TorsteinHonsi commented on samples/highcharts/series-treegraph/fillspace-option/demo.html
> +<button id="toggleCollapseNodeB">Toggle collapse of nodes B</button>
We use kebab-case for class names and id's in our demos.

2023-05-31 16:50 UTC, TorsteinHonsi approved these changes
Thanks! Now only awaiting CI.

2023-05-31 17:09 UTC, merged