bugfix/15569-zoom-by-drag-improvement
highcharts/highcharts pull request #19083
Opened 2023-06-02 13:14 UTC by kamil-musialowski

Fixed #15569, at rapid mouse movements outside the chart, zoom didn't work properly.

2023-06-02 13:38 UTC, circleci-mu commented
## Visual test results - No difference found

2023-06-07 08:06 UTC, pawelfus requested changes
Minor polishing in tests, otherwise good!

2023-06-07 08:06 UTC, pawelfus commented on samples/unit-tests/chart/zoomtype/demo.css
> +}
This will not work in Karma - CSS file (all together with HTML file) is not loaded

2023-06-07 09:09 UTC, pawelfus approved these changes
Looks good, works fine - should be ok, but let's get feedback from devs participating in #15569

2023-08-31 06:33 UTC, TorsteinHonsi approved these changes

2023-08-31 06:33 UTC, merged