bugfix/19121-measure-annotation-update
highcharts/highcharts pull request #19126
Opened 2023-06-09 09:52 UTC by jakubSzuminski

Fixed #19121, `Measure Annotation` went back to its initial position after update.

**GIF of the problem is here:** https://www.highcharts.com/forum/viewtopic.php?f=12&t=50985

**The source of the problem:**
1. When we create a new `Measure Annotation` its initial position is set in the `annotation.userOptions`
2. When we drag the `Measure Annotation` we update its coordinates in `annotation.options`
3. When we update the annotation - `Annotation.update(userOptions, redraw)` - we initialize the annotation with `userOptions` (set initially), not with `options` (which were updated after dragging)

**Simple solution:** updating both `options` and `userOptions` after dragging.

2023-06-09 09:56 UTC, jakubSzuminski commented
Alternative solution could be adding a `Measure.update()` method, which would take care of this case (I'm not sure which solution's better).

```
* Update the measure annotation.
* @private
*/
public update(
     userOptions: DeepPartial<AnnotationOptions>,
     redraw?: boolean | undefined
 ): void {
     // Need to update annotation coordinates after dragging, #19121.
     userOptions.typeOptions = {
         point: {
             x: this.startXMin,
             y: this.startYMin
         },
         ...userOptions.typeOptions
     };
     super.update(userOptions, redraw);
 }
```

2023-06-09 10:12 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| modules/annotations-advanced.js | **23.9 kB**<br>85.8 kB | **23.9 kB**<br>85.9 kB | **6 B**<br>71 B |

2023-06-09 10:15 UTC, circleci-mu commented
## Visual test results - Differences found
Found **1** diffing sample(s). [Please review the differences.](https://vrevs.highsoft.com/pr/19126/review)

2023-06-09 10:41 UTC, jakubSzuminski commented
**Demo before fix:** https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/stocktools/stocktools-thresholds
**Demo after fix:** https://jsfiddle.net/BlackLabel/Lp2gqm4o/

2023-06-14 10:56 UTC, pawelfus requested changes

2023-06-14 10:56 UTC, pawelfus commented on samples/unit-tests/annotations/annotations-measure/demo.js
> +    controller.mouseMove(bbox.x - 50, bbox.y);
As discussed on Slack: this means we need another solution

2023-06-15 06:36 UTC, merged