Heatmap interp boostbug
highcharts/highcharts pull request #19120
Opened 2023-06-08 09:11 UTC by MarkusBarstad

Fixed, segment of boosted points not drawing on the chart

2023-06-08 09:20 UTC, TorsteinHonsi requested changes
Thanks! 

The description (for the changelog) should be more, well, _descriptive_. It doesn't currently say it applies to the heatmap series, nor that it applies only when interpolation is true.

Also, please fix the conflicts.

I will follow up with a more detailed review.

2023-06-08 09:44 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highmaps.js | **125.4 kB**<br>360.0 kB | **125.2 kB**<br>359.7 kB | **-262 B**<br>-314 B |
| modules/heatmap.js | **7.3 kB**<br>19.1 kB | **7.2 kB**<br>18.8 kB | **-147 B**<br>-315 B |

2023-06-08 09:46 UTC, circleci-mu commented
## Visual test results - Differences found
Found **3** diffing sample(s). [Please review the differences.](https://vrevs.highsoft.com/pr/19120/review)

2023-06-08 10:27 UTC, TorsteinHonsi commented
There's something funny going on around the 15th-16th of may in the http://localhost:3030/samples/view?path=highcharts/studies/heatmap-interpolation demo. You can see it in the [visual diffs](https://vrevs.highsoft.com/pr/19120/review) too. Looks like a whole column is missing or something.

2023-06-10 06:14 UTC, TorsteinHonsi commented on ts/Series/Heatmap/HeatmapSeries.ts
>                                          widthLastIndex
If I change this from `widthLastIndex` to `canvasWidth`, the `studies/heatmap-interpolation` is correct. But then the other two demos break 🤷

2023-06-17 08:19 UTC, MarkusBarstad commented
Note: problem with reversion/inversion in last commit, should not be a major issue

2023-06-20 09:45 UTC, TorsteinHonsi commented
Putting this back in draft until it's considered read for review.

2023-08-22 13:23 UTC, TorsteinHonsi approved these changes
Thanks, the math looks good now! As far as I can see the interpolation is perfect in all cases.

2023-08-22 13:23 UTC, merged