Db/datapool connector rename
highcharts/highcharts pull request #19142
Opened 2023-06-13 09:13 UTC by pawellysy

2023-06-13 09:32 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| modules/dashboards-plugin.js | **18.4 kB**<br>66.8 kB | **18.4 kB**<br>66.8 kB | **3 B**<br>-27 B |
| dashboards.js | **42.1 kB**<br>144.7 kB | **42.1 kB**<br>144.7 kB | **2 B**<br>-34 B |

2023-06-13 10:51 UTC, karolkolodziej requested changes
Update Cypress demos.

2023-06-13 13:31 UTC, circleci-mu commented
## Cypress visual test results

2023-06-13 13:47 UTC, karolkolodziej approved these changes

2023-06-14 12:17 UTC, sebastianbochan approved these changes

2023-06-14 12:31 UTC, bre1470 approved these changes
One thing to change, otherwise it looks good. 👍

2023-06-14 12:31 UTC, bre1470 commented on ts/Data/DataPool.ts
> +        id: string
It is better to write here `connectorId` as each DataTable has also an `id`.

2023-06-15 08:23 UTC, merged