bugfix/19078-proximate-legend-enabling
highcharts/highcharts pull request #19153
Opened 2023-06-14 10:16 UTC by jakubSzuminski

Fixed #19078, proximate legend did not work after updating the `legend.enabled` property.

**Demo of the problem:** https://jsfiddle.net/BlackLabel/1cmx87k9/
**Demo after fix:** https://jsfiddle.net/BlackLabel/wftjvga3/

**Source of the problem:**
- `proximatePositions()` was called even when `legend.enabled = false` which caused multiple errors
- `proximatePositions()` and `positionItems()` functions were called only in the initial chart render, not after updating

2023-06-14 10:36 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts.js | **99.4 kB**<br>281.4 kB | **99.4 kB**<br>281.5 kB | **21 B**<br>51 B |
| highstock.js | **132.7 kB**<br>383.0 kB | **132.7 kB**<br>383.1 kB | **22 B**<br>55 B |
| highmaps.js | **125.4 kB**<br>360.0 kB | **125.4 kB**<br>360.0 kB | **10 B**<br>51 B |
| highcharts-gantt.js | **134.8 kB**<br>388.0 kB | **134.8 kB**<br>388.0 kB | **49 B**<br>49 B |

2023-06-14 10:39 UTC, circleci-mu commented
## Visual test results - No difference found

2023-06-14 15:07 UTC, hubertkozik requested changes
One comment on the current solution below. Also, please add a unit test to cover this case.

2023-06-15 06:25 UTC, TorsteinHonsi approved these changes
Thanks!

2023-06-15 06:26 UTC, merged