Db/visual test gh action
highcharts/highcharts pull request #19150
Opened 2023-06-14 05:58 UTC by goransle

2023-06-14 06:17 UTC, circleci-mu commented
## Cypress visual test results

2023-06-14 06:21 UTC, circleci-mu commented
### File size comparison
No differences found

2023-06-19 08:28 UTC, sebastianbochan approved these changes

2023-06-20 17:12 UTC, pawellysy approved these changes

2023-06-29 08:10 UTC, bre1470 requested changes
PR needs an update

2023-06-29 08:10 UTC, bre1470 commented on .github/workflows/dashboards-visual-test.yml
> +      - name: Build highcharts
`Build dashboards` job is missing

2023-06-29 08:10 UTC, bre1470 commented on .github/workflows/dashboards-visual-test.yml
> +      - name: Build highcharts
Same here.

2023-06-30 08:28 UTC, pawellysy approved these changes
lgtm

2023-06-30 10:34 UTC, bre1470 approved these changes
Thank you! Looks good. 👍

2023-07-03 08:23 UTC, oysteinmoseng approved these changes

2023-07-03 10:21 UTC, merged