db/adjust-demos-integration
highcharts/highcharts pull request #19182
Opened 2023-06-20 13:18 UTC by sebastianbochan

- [x] - replace `demos` with `demo`
- [x] - update paths in cypress tests
- [x] - update docs
- [x] - update details files

2023-06-20 13:39 UTC, circleci-mu commented
## Cypress visual test results

2023-06-20 14:00 UTC, circleci-mu commented
### File size comparison
No differences found

2023-06-22 06:32 UTC, karolkolodziej requested changes
- [ ] I think I tested sth and accidentally added more items to CSV for the `dashboards/cypress/component-datagrid`- the `Tuna` should be the last one 🙈

2023-06-22 06:32 UTC, karolkolodziej commented on samples/dashboards/demo/climate/demo.js
> +                    distance: -60,
Shouldn't be part of this commit ;) 
But if you would like to leave it, remove the positioner.

2023-06-22 07:51 UTC, pawelfus approved these changes
Thanks!

2023-06-22 08:19 UTC, karolkolodziej approved these changes

2023-06-22 08:58 UTC, sebastianbochan commented
> * [x]  I think I tested sth and accidentally added more items to CSV for the `dashboards/cypress/component-datagrid`- the `Tuna` should be the last one 🙈

It looks like breaks the cypress tests.

2023-06-23 10:27 UTC, pawellysy approved these changes

2023-06-23 12:25 UTC, bre1470 approved these changes
Looks good. 👍

2023-06-26 10:55 UTC, goransle commented
The visual test fails as it can no longer find the reference image because of the changing paths. Unless we want to write a script that tries to find path changes in the git log and do some magic with that‚ I suggest doing a manual comparison using the [test artifacts](https://app.circleci.com/pipelines/github/highcharts/highcharts/22170/workflows/da353831-6e4b-45bb-a7ce-d0ab65d0fb38/jobs/154939/artifacts)

2023-06-26 11:20 UTC, goransle approved these changes

2023-06-26 13:35 UTC, merged