GUI demos: initial commit
highcharts/highcharts pull request #19191
Opened 2023-06-22 09:05 UTC by LB0ge

Asana task link: https://app.asana.com/0/0/1204724384298610/f

2023-06-22 09:20 UTC, circleci-mu commented
## Cypress visual test results

2023-06-22 09:24 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| dashboards.js | **42.1 kB**<br>144.7 kB | **42.1 kB**<br>144.7 kB | **42 B**<br>-49 B |

2023-06-22 09:34 UTC, sebastianbochan approved these changes

2023-06-22 09:58 UTC, sebastianbochan commented
One remark, should it be `2 x nested` instead of `1 x nested`?

![Screenshot 2023-06-22 at 11 56 19](https://github.com/highcharts/highcharts/assets/2115686/dc49247f-fd15-4731-aa90-7271af1fa540)

2023-06-22 13:47 UTC, bre1470 approved these changes
Looks good. 👍

2023-06-22 13:57 UTC, karolkolodziej requested changes

2023-06-23 10:48 UTC, pawellysy approved these changes
Great job! Just one typo fix

2023-06-23 10:48 UTC, pawellysy commented on samples/dashboards/gui/dimensions/demo.html
> +>
```suggestion
Tuna, 214</pre>
```

2023-06-26 12:07 UTC, LB0ge commented on samples/dashboards/gui/dimensions/demo.js
> +                                    height: 450
`width` is already declared as string (%) in line 27. Should I declare one `height` as a string too?

2023-06-26 12:33 UTC, karolkolodziej commented on samples/dashboards/gui/dimensions/demo.js
> +                                    height: 450
You are right, I missed that- no there is no need to do so ;)

2023-06-26 12:33 UTC, karolkolodziej approved these changes

2023-06-26 12:34 UTC, LB0ge commented
> One remark, should it be `2 x nested` instead of `1 x nested`?
> 
> ![Screenshot 2023-06-22 at 11 56 19](https://user-images.githubusercontent.com/2115686/247895545-dc49247f-fd15-4731-aa90-7271af1fa540.png)

I believe this is correct as is. All three cells marked `2 x nested` are inside a layout which is inside another layout (ref. board configuration).

2023-06-26 14:09 UTC, sebastianbochan commented
> > One remark, should it be `2 x nested` instead of `1 x nested`?
> > ![Screenshot 2023-06-22 at 11 56 19](https://user-images.githubusercontent.com/2115686/247895545-dc49247f-fd15-4731-aa90-7271af1fa540.png)
> 
> I believe this is correct as is. All three cells marked `2 x nested` are inside a layout which is inside another layout (ref. board configuration).

Thank you for elaboration, now makes sense. 
Agree ;)

2023-06-27 06:41 UTC, LB0ge commented on samples/dashboards/gui/dimensions/demo.html
> +>
I will fix!

2023-06-27 09:38 UTC, sebastianbochan approved these changes

2023-06-27 09:38 UTC, sebastianbochan commented
LGTM 👍

2023-06-28 08:45 UTC, pawellysy approved these changes
LGTM

2023-06-28 09:42 UTC, karolkolodziej approved these changes

2023-06-28 11:50 UTC, bre1470 approved these changes
LGTM

2023-06-29 07:46 UTC, merged