db/edit-mode-drag-drop-enabled
highcharts/highcharts pull request #19207
Opened 2023-06-23 11:06 UTC by pawellysy

Implemented disabling drag&drop and resizer.

2023-06-23 11:23 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| dashboards.js | **42.1 kB**<br>144.7 kB | **42.1 kB**<br>144.9 kB | **48 B**<br>166 B |

2023-06-26 08:39 UTC, circleci-mu commented
## Cypress visual test results

 * [cypress/snapshots/diff/test/cypress/visual/Dashboards.cy.js/dashboard-climate-edit-mode-diff.png](https://vrevs.highsoft.com/api/assets/visualtests/diffs/pullrequests/19207/cypress/snapshots/diff/test/cypress/visual/Dashboards.cy.js/dashboard-climate-edit-mode-diff.png)

2023-06-26 09:33 UTC, karolkolodziej requested changes
- [ ] add test

2023-06-26 09:33 UTC, karolkolodziej commented on ts/Dashboards/EditMode/EditMode.ts
> +        editMode.dragDrop = new DragDrop(
Maybe add a comment on why this is always initialized.

2023-06-26 10:56 UTC, karolkolodziej approved these changes

2023-06-26 10:56 UTC, karolkolodziej commented on samples/dashboards/cypress/edit-mode-options/demo.html
> +<div id="container">
one line?

2023-06-26 10:56 UTC, karolkolodziej commented on samples/dashboards/cypress/edit-mode-options/demo.mjs
> +// Bring in other forms of Highcharts
Is this relevant?

2023-06-26 14:07 UTC, sebastianbochan requested changes

2023-06-26 14:07 UTC, sebastianbochan commented on samples/dashboards/cypress/edit-mode-options/demo.mjs
> +                }
You can simplify chart to 

```
chartOptions: {
                series: [
                    {
                        data: [1, 2, 1, 4]
                    }
                ],
```

2023-06-27 08:14 UTC, pawellysy commented on ts/Dashboards/EditMode/Toolbar/CellEditToolbar.ts
> +            [];
I'd leave it as it is :)

2023-06-27 09:34 UTC, sebastianbochan commented
Please check the cypress test.

2023-06-29 08:03 UTC, bre1470 approved these changes

2023-06-29 08:40 UTC, sebastianbochan approved these changes

2023-06-29 08:47 UTC, merged