Db/demos improvements v1
highcharts/highcharts pull request #19222
Opened 2023-06-26 15:50 UTC by pawellysy

2023-06-26 16:07 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts.js | **99.5 kB**<br>281.5 kB | **99.5 kB**<br>281.5 kB | **74 B**<br>17 B |
| highstock.js | **132.7 kB**<br>383.1 kB | **132.7 kB**<br>383.0 kB | **-35 B**<br>-22 B |
| highmaps.js | **125.5 kB**<br>360.0 kB | **125.4 kB**<br>360.1 kB | **-110 B**<br>23 B |
| highcharts-gantt.js | **134.4 kB**<br>386.6 kB | **134.9 kB**<br>388.0 kB | **458 B**<br>1444 B |
| indicators/indicators-all.js | **22.3 kB**<br>80.6 kB | **22.3 kB**<br>80.1 kB | **-72 B**<br>-589 B |
| modules/accessibility.js | **34.4 kB**<br>120.7 kB | **34.6 kB**<br>120.9 kB | **128 B**<br>255 B |
| modules/annotations.js | **17.5 kB**<br>58.7 kB | **17.5 kB**<br>58.7 kB | **-10 B**<br>-45 B |
| modules/annotations-advanced.js | **23.9 kB**<br>85.9 kB | **23.9 kB**<br>85.9 kB | **-14 B**<br>26 B |
| modules/boost.js | **15.4 kB**<br>44.7 kB | **15.4 kB**<br>44.7 kB | **53 B**<br>-12 B |
| modules/data.js | **7.4 kB**<br>19.7 kB | **7.3 kB**<br>19.1 kB | **-46 B**<br>-582 B |
| modules/exporting.js | **7.2 kB**<br>19.0 kB | **7.2 kB**<br>19.0 kB | **-1 B**<br>-1 B |
| modules/heatmap.js | **7.3 kB**<br>19.1 kB | **7.3 kB**<br>19.1 kB | **-1 B**<br>-1 B |
| modules/offline-exporting.js | **4.1 kB**<br>9.4 kB | **4.1 kB**<br>9.5 kB | **35 B**<br>88 B |
| modules/dashboards-plugin.js | **18.4 kB**<br>66.8 kB | **18.6 kB**<br>67.0 kB | **227 B**<br>250 B |
| dashboards.js | **42.1 kB**<br>144.7 kB | **42.1 kB**<br>144.4 kB | **25 B**<br>-309 B |
| datagrid.js | **14.6 kB**<br>40.9 kB | **14.6 kB**<br>40.9 kB | **-25 B**<br>-15 B |

2023-06-28 05:48 UTC, goransle approved these changes
Looking good

2023-06-28 06:11 UTC, karolkolodziej approved these changes

2023-06-28 11:49 UTC, sebastianbochan approved these changes

2023-06-28 12:19 UTC, bre1470 reviewed
I have some glitches. Maybe unrelated, idk.

2023-06-28 12:19 UTC, bre1470 commented on samples/dashboards/cypress/add-layout/demo.details
> + name: Dashboards cypress test
I do not see the DataGrid in Safari, but no error in console.

2023-06-28 12:19 UTC, bre1470 commented on samples/dashboards/cypress/component-loading/demo.mjs
> +
Unnecessary space

2023-06-28 12:19 UTC, bre1470 commented on samples/dashboards/cypress/dashboard-layout/demo.mjs
It is not loading for me in Safari
```
Highcharts and container are missing

Most likely this sample does not exist.
```
Web console:
```
Refused to apply a stylesheet because its hash, its nonce, or 'unsafe-inline' does not appear in the style-src directive of the Content Security Policy.
```

2023-06-29 08:04 UTC, bre1470 requested changes
Merge conflicts have to be resolved.

2023-06-29 12:52 UTC, pawellysy commented on samples/dashboards/cypress/dashboard-layout/demo.mjs
Fixed!

2023-06-29 14:47 UTC, bre1470 approved these changes
Thank you! Looks good. 👍

2023-06-29 15:57 UTC, merged