dash/exclude-datagrid-from-plugin-build
highcharts/highcharts pull request #19259
Opened 2023-06-30 12:26 UTC by pawellysy

Deleted DataGrid from dashboards-plugin build.

2023-06-30 12:38 UTC, karolkolodziej requested changes

2023-06-30 12:38 UTC, karolkolodziej commented on ts/masters-dashboards/modules/dashboards-plugin.src.ts
> +    DataGridPlugin.custom.connectDataGrid(G.win.DataGrid.DataGrid);
What if `G.win.DataGrid` is undefined :)

2023-06-30 12:39 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts.js | **99.5 kB**<br>281.5 kB | **99.5 kB**<br>281.5 kB | **79 B**<br>17 B |
| highstock.js | **132.7 kB**<br>383.1 kB | **132.7 kB**<br>383.0 kB | **-34 B**<br>-23 B |
| highmaps.js | **125.5 kB**<br>360.0 kB | **125.4 kB**<br>360.0 kB | **-113 B**<br>-10 B |
| highcharts-gantt.js | **134.4 kB**<br>386.6 kB | **134.9 kB**<br>388.0 kB | **461 B**<br>1443 B |
| indicators/indicators-all.js | **22.3 kB**<br>80.6 kB | **22.3 kB**<br>80.1 kB | **-70 B**<br>-588 B |
| modules/accessibility.js | **34.4 kB**<br>120.7 kB | **34.6 kB**<br>120.9 kB | **128 B**<br>255 B |
| modules/annotations.js | **17.5 kB**<br>58.7 kB | **17.5 kB**<br>58.7 kB | **-8 B**<br>-45 B |
| modules/annotations-advanced.js | **23.9 kB**<br>85.9 kB | **23.9 kB**<br>85.9 kB | **-13 B**<br>26 B |
| modules/boost.js | **15.4 kB**<br>44.7 kB | **15.4 kB**<br>44.7 kB | **54 B**<br>-11 B |
| modules/data.js | **7.4 kB**<br>19.7 kB | **7.3 kB**<br>19.1 kB | **-45 B**<br>-581 B |
| modules/offline-exporting.js | **4.1 kB**<br>9.4 kB | **4.1 kB**<br>9.5 kB | **34 B**<br>89 B |
| modules/dashboards-plugin.js | **18.4 kB**<br>66.8 kB | **18.4 kB**<br>66.8 kB | **-1 B**<br>-5 B |

2023-06-30 15:07 UTC, bre1470 approved these changes

2023-06-30 15:10 UTC, bre1470 commented
Not directly related, but could you fix the path to the plugin module in `./tools/gulptasks/pr-size-table.js` with this PR? Then we might have a chance that the visual comparison job succeeds again.

2023-07-03 05:45 UTC, karolkolodziej approved these changes

2023-07-03 07:00 UTC, sebastianbochan approved these changes

2023-07-03 07:17 UTC, merged