dash/serialization-component-update-state
highcharts/highcharts pull request #19252
Opened 2023-06-29 13:16 UTC by sebastianbochan

2023-06-29 13:33 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| dashboards.js | **42.1 kB**<br>144.4 kB | **42.1 kB**<br>144.5 kB | **34 B**<br>87 B |

2023-06-29 13:34 UTC, pawellysy requested changes

2023-06-29 13:34 UTC, pawellysy commented on test/cypress/integration/Dashboards/json-serialization.cy.js
> +    it('Component\'s state should be updated, after actions in sidebar', () => {
```suggestion
    it.skip('Component\'s state should be updated, after actions in sidebar', () => {
```

2023-06-29 13:55 UTC, circleci-mu commented
## Visual test results - Differences found
Found **1** diffing sample(s). [Please review the differences.](https://vrevs.highsoft.com/pr/19252/review)

2023-06-29 14:12 UTC, pawellysy approved these changes
LGTM

2023-06-30 05:37 UTC, karolkolodziej approved these changes

2023-06-30 07:59 UTC, merged