Dash/component spec demos
highcharts/highcharts pull request #19261
Opened 2023-06-30 12:59 UTC by DJTechnoo

2023-06-30 13:12 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts.js | **99.5 kB**<br>281.5 kB | **99.5 kB**<br>281.5 kB | **79 B**<br>17 B |
| highstock.js | **132.7 kB**<br>383.1 kB | **132.7 kB**<br>383.0 kB | **-34 B**<br>-23 B |
| highmaps.js | **125.5 kB**<br>360.0 kB | **125.4 kB**<br>360.0 kB | **-113 B**<br>-10 B |
| highcharts-gantt.js | **134.4 kB**<br>386.6 kB | **134.9 kB**<br>388.0 kB | **461 B**<br>1443 B |
| indicators/indicators-all.js | **22.3 kB**<br>80.6 kB | **22.3 kB**<br>80.1 kB | **-70 B**<br>-588 B |
| modules/accessibility.js | **34.4 kB**<br>120.7 kB | **34.6 kB**<br>120.9 kB | **128 B**<br>255 B |
| modules/annotations.js | **17.5 kB**<br>58.7 kB | **17.5 kB**<br>58.7 kB | **-8 B**<br>-45 B |
| modules/annotations-advanced.js | **23.9 kB**<br>85.9 kB | **23.9 kB**<br>85.9 kB | **-13 B**<br>26 B |
| modules/boost.js | **15.4 kB**<br>44.7 kB | **15.4 kB**<br>44.7 kB | **54 B**<br>-11 B |
| modules/data.js | **7.4 kB**<br>19.7 kB | **7.3 kB**<br>19.1 kB | **-45 B**<br>-581 B |
| modules/offline-exporting.js | **4.1 kB**<br>9.4 kB | **4.1 kB**<br>9.5 kB | **34 B**<br>89 B |
| modules/dashboards-plugin.js | **18.4 kB**<br>66.8 kB | **18.4 kB**<br>66.8 kB | **-1 B**<br>-5 B |
| dashboards.js | **42.1 kB**<br>144.7 kB | **42.0 kB**<br>144.1 kB | **-66 B**<br>-618 B |
| datagrid.js | **14.6 kB**<br>40.9 kB | **14.7 kB**<br>40.9 kB | **3 B**<br>-7 B |

2023-06-30 14:11 UTC, pawellysy requested changes
Great job! Just a few minor changes 👍

2023-06-30 14:11 UTC, pawellysy commented on samples/dashboards/datagrid-component/datagrid-options/demo.details
> +  - Karol Kolodziej
Fix title

2023-06-30 14:11 UTC, pawellysy commented on samples/dashboards/highcharts-components/chart-constructor-gantt/demo.js
> +const today = new Date(),
Maybe lets add another component, so that it is visible, that this is a Dashboards demo, not just Highcharts?

2023-07-03 07:01 UTC, karolkolodziej requested changes
I'm unable to see the `dashboards/datagrid-component/datagrid-options` Please merge the latest changes from the master and confirm that everything works as expected.

2023-07-03 07:06 UTC, sebastianbochan approved these changes

2023-07-03 07:06 UTC, sebastianbochan requested changes
Please check the cypress test, which is broken.

2023-07-03 08:08 UTC, bre1470 commented
`Dashboards/EditMode/dragdrop.cy.js` is failing.

```
Edit Mode options
    1) When disabling the dragDrop and resizer the menu should have only 2 items and resizer should not exist


  0 passing (5s)
  1 failing

  1) Edit Mode options
       When disabling the dragDrop and resizer the menu should have only 2 items and resizer should not exist:
     AssertionError: Timed out retrying after 4000ms: Expected to find element: `.**********-dashboards-edit-context-menu-btn`, but never found it.
      at Context.eval (webpack:///./test/cypress/support/index.js:143:7)
```

2023-07-03 10:35 UTC, sebastianbochan reviewed
I'm not pretty sure if we need setup legend options in simple charts.

Otherwise looks good to me.

2023-07-03 10:35 UTC, sebastianbochan commented on samples/dashboards/highcharts-components/chart-and-stock-constructors/demo.js
> +        y: 100
Do we need legend options in the basic chart?

2023-07-03 10:35 UTC, sebastianbochan commented on samples/dashboards/highcharts-components/chart-constructor-maps/demo.js
> +                    y: 100
Do we need legend options in simple chart?

2023-07-03 10:54 UTC, pawellysy approved these changes
LGTM!

2023-07-03 12:15 UTC, karolkolodziej approved these changes

2023-07-03 12:17 UTC, sebastianbochan approved these changes

2023-07-03 15:08 UTC, pawelfus approved these changes

2023-07-03 17:30 UTC, bre1470 approved these changes

2023-07-04 08:06 UTC, merged