bugfix/16784-wrong-extended-positions-calculations
highcharts/highcharts pull request #19262
Opened 2023-06-30 13:38 UTC by kamil-musialowski

Fixed #16784, calculations in extended ordinal position were wrong.

Test here: https://jsfiddle.net/BlackLabel/w4b2qjxg/
Grab the annotation, move it to the left (outside of the chart), try to bring it back. It shouldn't change it's length.

TODO: 

- [ ] Test
- [ ] Dragging annotation outside the dataset (i.e far left)

2023-06-30 13:40 UTC, pawelfus requested changes

2023-06-30 13:40 UTC, pawelfus commented on ts/Core/Axis/OrdinalAxis.ts
> +            ordinal.extendedOrdinalPositions = extendedOrdinalPositions;
Unnecessary line + I think you can remove from definitions `Ordinal.extendedOrdinalPositions` too

2023-06-30 13:42 UTC, pawelfus commented on ts/Core/Axis/OrdinalAxis.ts
> +                    fakeSeries.applyGrouping.apply(fakeSeries);
Waaait. The idea with `Axis.applyGrouping` (the method that calls `Series.applyGrouping`) is to use this method **after** each series has been processed (after `processData()`). Could you try it?

2023-06-30 13:58 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highstock.js | **132.7 kB**<br>383.0 kB | **132.6 kB**<br>382.9 kB | **-29 B**<br>-49 B |

2023-06-30 14:00 UTC, circleci-mu commented
## Visual test results - No difference found

2023-07-13 08:37 UTC, pawelfus requested changes
Minor polishing needed 👍

2023-07-13 08:37 UTC, pawelfus commented on samples/unit-tests/axis/ordinal/demo.js
> +    console.log(pixels);
Unnecessary console

2023-07-13 08:37 UTC, pawelfus commented on samples/unit-tests/axis/ordinal/demo.js
> +            },
Please, keep the original test and update series for your scenario. I don't know if the `Annotation dragged on ordinal axis charts should follow mouse pointer` assertion will be fine if we force grouping.

2023-07-13 08:37 UTC, pawelfus commented on ts/Core/Axis/OrdinalAxis.ts
> +                    // If the index is outside positions array,
Index? 🤔

2023-07-14 14:32 UTC, pawelfus approved these changes
Thanks!

2023-09-06 11:31 UTC, TorsteinHonsi requested changes
Can you check out the CI error complaining about `this.is()`?

2023-09-07 09:09 UTC, kamil-musialowski commented
@TorsteinHonsi 
This error comes from the point and figure JS demo (which I have created), and it only checks the series type. Local tests show nothing and honestly, I have no idea what could be causing this to fail on this particular branch (it's the first time I see an error regarding this demo).

https://github.com/highcharts/highcharts/blob/9360ca8eef784c8b9cd4238b0e0c5f302be5578e/samples/highcharts/studies/pointandfigure/demo.js#L181

Should we ignore it, or add some checks like this.is && this.is('...')?

2023-09-12 08:10 UTC, TorsteinHonsi commented
@kamil-musialowski I can reproduce it in the utils:

![Skjermbilde 2023-09-12 kl  10 07 51](https://github.com/highcharts/highcharts/assets/227836/f53a794f-e5e0-4c45-8974-aeff339036c0)

Rather than adding a test for `this.is` in the study, at least first we should try to understand why it happens. From the stack trace we can see that it origins from the `getExtendedPositions` function, which indicates that the connection to this PR is real.

2023-09-12 09:19 UTC, kamil-musialowski commented
@TorsteinHonsi Thank you for the help, I can see it in the utils now.

The error comes from the fact, that the overwritten `groupData` method is also called on `fakeSeries`, which does not have a `fakeSeries.is()` method. I'm not sure if it's something that should be handled inside Core. Do we need this `is()` method on fakeSeries?

If not, I think we should be safe with checking if series is fake i.e `if (series.yData)` or with the `this.is && this.is()` approach.

2023-09-12 09:57 UTC, TorsteinHonsi commented
Okay, I understand. It's probably okay just to change it in the pointandfigure study then.

2023-09-12 11:30 UTC, TorsteinHonsi approved these changes

2023-09-12 11:30 UTC, merged