bugfix/14108-exporting-xrange-csv-data
highcharts/highcharts pull request #19281
Opened 2023-07-03 14:14 UTC by madepiet

Fixed #14108, start and end dates in exported CSV data for X-range series.

2023-07-03 14:25 UTC, circleci-mu commented
### File size comparison
No differences found

2023-07-03 14:28 UTC, circleci-mu commented
## Visual test results - No difference found

2023-07-05 09:51 UTC, TorsteinHonsi requested changes
Thanks!

I think rather than concatenating it into the x column, we should treat x2 as a separate column. Because it is actually a separate data value, which can be handled in spreadsheets etc. Probably we need to prepend it to the local [pointArrayMap](https://github.com/highcharts/highcharts/blob/dfbb2302dea0a320329eef630e9f2ca3c8c2d93a/ts/Extensions/ExportData/ExportData.ts#L436-L438), then make sure it is formatted like a date when printed.

Also make sure this works with the gantt series. Gantt points use `start`, `end` instead of `x`, `x2`.

2023-07-13 12:05 UTC, madepiet commented
> Thanks!
> 
> I think rather than concatenating it into the x column, we should treat x2 as a separate column. Because it is actually a separate data value, which can be handled in spreadsheets etc. Probably we need to prepend it to the local [pointArrayMap](https://github.com/highcharts/highcharts/blob/dfbb2302dea0a320329eef630e9f2ca3c8c2d93a/ts/Extensions/ExportData/ExportData.ts#L436-L438), then make sure it is formatted like a date when printed.
> 
> Also make sure this works with the gantt series. Gantt points use `start`, `end` instead of `x`, `x2`.

For X-range we currently have the following cases:
- [With xAxis in datatime format](https://jsfiddle.net/BlackLabel/uktws5e0/)
- [And standard](https://jsfiddle.net/BlackLabel/qvfgm2n9/)

However, for Gantt we only have [datatime](https://jsfiddle.net/BlackLabel/jho1tqdc/) because for other data it takes the [date format anyway](https://jsfiddle.net/BlackLabel/kz7n1328/).

2023-09-05 08:51 UTC, TorsteinHonsi commented
I pushed a commit that makes more use of existing structures in the export-data module, so that we don't have to make special cases for the XRange series. Let's see how the CI turns out.

2023-09-15 09:58 UTC, TorsteinHonsi approved these changes

2023-09-15 09:58 UTC, merged