Samples/column rotated labels responsive
highcharts/highcharts pull request #19298
Opened 2023-07-04 13:10 UTC by fanuntez

Made labels more responsive.

[Asana task](https://app.asana.com/0/1203542399740129/1203592881281866/f)

2023-07-04 13:23 UTC, circleci-mu commented
### File size comparison
No differences found

2023-07-04 13:26 UTC, circleci-mu commented
## Visual test results - No difference found

---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  Modified | samples/highcharts/demo/column-rotated-labels/demo.js |
|  Modified | samples/highcharts/demo/column-rotated-labels/demo.js |

</p>
</details>

2023-07-05 10:18 UTC, TorsteinHonsi requested changes
Thanks!

I think we can simplify this a bit:
* We don't really need to keep abbreviated names when the rotation is -90, because there is vertical space for the full name. As a consequence, we can go back to the original, simpler data structure.
* We can simply set `autoRotation: [-45, -90]` to achieve responsive handling of the label rotation. See https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/column-rotated-labels .

2023-07-05 11:04 UTC, fanuntez commented
> Thanks!
> 
> I think we can simplify this a bit:
> 
> * We don't really need to keep abbreviated names when the rotation is -90, because there is vertical space for the full name. As a consequence, we can go back to the original, simpler data structure.
> * We can simply set `autoRotation: [-45, -90]` to achieve responsive handling of the label rotation. See https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/column-rotated-labels .

Should the dataLabels changes also be reverted back as on the original sample?

2023-07-07 06:29 UTC, TorsteinHonsi approved these changes

2023-07-07 06:29 UTC, merged