dash/columnAssignment-datagrid
highcharts/highcharts pull request #19330
Opened 2023-07-10 11:44 UTC by karolkolodziej

Fixed, the `columnAssignment` was not respected by the `DataGridComponent`.

2023-07-10 11:55 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| dashboards/modules/dashboards-plugin.js | **12.9 kB**<br>39.9 kB | **12.9 kB**<br>40.2 kB | **27 B**<br>217 B |

2023-07-10 11:58 UTC, circleci-mu commented
## Visual test results - No difference found

2023-07-11 06:41 UTC, pawellysy requested changes
I wonder, if this option should be named the same as in the HighchartsComponent. 
In the HighchartsComponent, this option transforms each of the columns to one of the values in the chart, so there are many options like `x`, `y`, `value`, `null` etc, and here there is only one option, `null`. So maybe we should create something like `ignoredColumns: Array<string> where all ignored columns are listed` or `visibleColumns` where the is other way around, or just delete this option from the API and just go with `columns.show = false`? 

Summoning @pawelfus

2023-07-11 09:59 UTC, pawelfus commented
Discussion summary: Green light for a different option, instead of `columnAssignment` one

2023-07-12 10:08 UTC, pawellysy approved these changes
LGTM!

2023-07-13 10:47 UTC, goransle commented on ts/Dashboards/Plugins/DataGridComponent.ts
> +                if (columnsToShow?.length) {
The method can probably just return `table` earlier `if( !columnsToShow.length )`.

2023-07-13 10:59 UTC, bre1470 reviewed
🙂

2023-07-13 11:03 UTC, bre1470 approved these changes

2023-07-13 11:13 UTC, sebastianbochan approved these changes

2023-07-13 11:13 UTC, sebastianbochan commented on samples/dashboards/cypress/component-datagrid/demo.mjs
> +            columnsToShow: ['Food', 'Vitamin A']
IMO `visibleColumns` or `displayColumns` sound more intuitive.

2023-07-13 11:14 UTC, sebastianbochan commented on samples/dashboards/cypress/component-datagrid/demo.mjs
> +            columnsToShow: ['Food', 'Vitamin A']
Similar suggestion to `notVisible` param, IMO `hidden` sounds more user-friendly.

2023-07-14 08:24 UTC, goransle approved these changes

2023-07-14 12:36 UTC, merged