samples/fan-chart
highcharts/highcharts pull request #19333
Opened 2023-07-10 15:40 UTC by KacperMadej

Added a fan chart demo.

2023-07-10 15:52 UTC, circleci-mu commented
### File size comparison
No differences found

2023-07-10 17:48 UTC, MarkusBarstad approved these changes
Looks good!

2023-07-11 06:58 UTC, hubertkozik approved these changes

2023-07-11 11:09 UTC, nasin approved these changes
Looks great!

2023-07-28 05:54 UTC, marvin19 approved these changes

2023-08-21 09:02 UTC, TorsteinHonsi requested changes
Thanks, looks nice!

2023-08-24 12:58 UTC, TorsteinHonsi approved these changes

2023-08-24 12:58 UTC, merged