bugfix/18988-inverted-sankey-offsets
highcharts/highcharts pull request #19334
Opened 2023-07-11 07:13 UTC by hubertkozik

Fixed #18988 and #17594, vertical and horizontal offsets for inverted Sankey and Organization charts didn't work correctly.

2023-07-11 07:24 UTC, circleci-mu commented
### File size comparison
No differences found

2023-07-11 07:26 UTC, circleci-mu commented
## Visual test results - No difference found

2023-08-22 08:28 UTC, TorsteinHonsi approved these changes
Thanks!

2023-08-22 08:29 UTC, TorsteinHonsi requested changes
Oops, there's a conflict. Please fix.

2023-08-22 08:30 UTC, hubertkozik commented
On it!

2023-08-22 13:09 UTC, TorsteinHonsi approved these changes

2023-08-22 13:10 UTC, merged