bugfix/13240-bubble-aligndatalabel-beyond-plotarea
highcharts/highcharts pull request #19365
Opened 2023-07-13 16:28 UTC by madepiet

Fixed #13240, using default data labels alignment for bubble series.

2023-08-18 12:44 UTC, TorsteinHonsi requested changes
By removing that function we can no longer align the data label within the bubble:

https://jsfiddle.net/mnkgbo06/

I think instead we need to look into how the `overflow` setting work. Does it only work to horizontal alignment?

2023-10-16 12:54 UTC, TorsteinHonsi commented
@madepiet Bump

2023-10-16 13:18 UTC, madepiet commented
> By removing that function we can no longer align the data label within the bubble:
> 
> https://jsfiddle.net/mnkgbo06/
> 
> I think instead we need to look into how the `overflow` setting work. Does it only work to horizontal alignment?

Yes, I started investigating the issue of how it behaves after changing axisBeforePadding. I'm back to work on it now so I'll give an update

2023-10-23 06:24 UTC, TorsteinHonsi approved these changes

2023-10-23 06:24 UTC, merged