dash/component-update-connector
highcharts/highcharts pull request #19406
Opened 2023-07-20 08:21 UTC by karolkolodziej

Fixed, sync was not preserved when the component updated its connector.

2023-07-20 08:32 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| dashboards/dashboards.js | **42.3 kB**<br>145.5 kB | **42.4 kB**<br>145.6 kB | **25 B**<br>55 B |
| dashboards/modules/dashboards-plugin.js | **13.7 kB**<br>42.6 kB | **13.7 kB**<br>42.6 kB | **13 B**<br>19 B |

2023-07-20 08:35 UTC, circleci-mu commented
## Visual test results - No difference found

2023-07-20 11:18 UTC, sebastianbochan approved these changes

2023-07-24 10:25 UTC, bre1470 requested changes

2023-07-24 10:25 UTC, bre1470 commented on ts/Dashboards/Components/Component.ts
> +        this.sync? this.sync.syncConfig = syncHandlers : void 0;
`npm run dtest`:
```
/Users/highsoft/Code/highcharts/ts/Dashboards/Components/Component.ts
  441:18  error  Operator '?' must be spaced  space-infix-ops
```

2023-07-24 11:06 UTC, bre1470 approved these changes

2023-07-24 12:06 UTC, merged