bugfix/19203-update-chart-plotoptions-pointstart
highcharts/highcharts pull request #19407
Opened 2023-07-20 08:59 UTC by jedrzejruta

Fixed #19203, `plotOptions.series.pointStart` couldn't be updated more than once.
Added tests for plot options updates.

2023-07-21 13:26 UTC, hubertkozik requested changes
Good job! Two comments below.

2023-07-21 13:26 UTC, hubertkozik commented on ts/Core/Series/Series.ts
> +
I think those lines are not necessary for that fix. It is checked in `hasOptionsChanged` method (`defined`) and also currently (in these lines) you are not checking plot options for exact series type (e.g. column). After removing these lines all tests pass.

2023-07-21 13:26 UTC, hubertkozik commented on ts/Core/Series/Series.ts
> +        if (oldOption && !defined(plotOptionsOption)) {
It would be good to add a comment here with the issue number and a short description of why it is here.

2023-07-24 13:43 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts.js | **99.6 kB**<br>281.5 kB | **99.7 kB**<br>281.9 kB | **132 B**<br>425 B |
| highstock.js | **132.7 kB**<br>383.0 kB | **132.9 kB**<br>383.5 kB | **142 B**<br>425 B |
| highmaps.js | **125.6 kB**<br>360.0 kB | **125.7 kB**<br>360.4 kB | **118 B**<br>425 B |
| highcharts-gantt.js | **134.9 kB**<br>388.0 kB | **135.0 kB**<br>388.4 kB | **121 B**<br>429 B |

2023-07-24 13:46 UTC, circleci-mu commented
## Visual test results - No difference found

2023-08-02 15:47 UTC, hubertkozik approved these changes
LGTM!

2023-08-21 07:42 UTC, TorsteinHonsi approved these changes
Thanks!

2023-08-21 07:43 UTC, merged