bugfix/19402-select-state-resize
highcharts/highcharts pull request #19409
Opened 2023-07-20 10:04 UTC by jakubSzuminski

Fixed #19402, PiePoint state changed after resize.

The `states.select.enabled = 'false'` is not respected for **PieSeries**.

**Demo of the problem:** https://jsfiddle.net/BlackLabel/srf259n4/
**Demo after fix:** https://jsfiddle.net/BlackLabel/0avzw6jt/

**Steps to follow:**
1. Select a point
2. Resize the window

2023-07-27 13:00 UTC, hubertkozik commented
Can you merge the master into that branch to pass CircleCi tests, please?

2023-07-28 09:19 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts.js | **99.6 kB**<br>281.5 kB | **99.6 kB**<br>281.5 kB | **0 B**<br>-13 B |
| highstock.js | **132.7 kB**<br>383.0 kB | **132.7 kB**<br>383.0 kB | **3 B**<br>-13 B |
| highmaps.js | **125.6 kB**<br>360.0 kB | **125.6 kB**<br>360.0 kB | **-1 B**<br>-13 B |
| highcharts-gantt.js | **134.9 kB**<br>388.0 kB | **134.9 kB**<br>388.0 kB | **1 B**<br>-13 B |

2023-07-28 09:23 UTC, circleci-mu commented
## Visual test results - No difference found

2023-08-18 13:26 UTC, TorsteinHonsi requested changes
Wow, that's a nice fix if it works reliably. 

This is actually a [repeated pattern throughout our code](https://github.com/search?q=repo%3Ahighcharts%2Fhighcharts+point.selected+%26%26+%27select%27+path%3A%2F%5Ets%5C%2F%2F&type=code). Can you go over the other occurrences and see if the same issue applies to them?

Next, if `pointAttribs` is always called with the `state` argument retrieved directly from the point, we can consider removing it altogether and read it inside the function.

2023-08-21 10:59 UTC, jakubSzuminski commented
You're right @TorsteinHonsi. 

I've removed the `state` argument from the `pointAttribs` function and from what what I've tested - there's no unexpected behavior. All the tests have passed so my guess is that it was unnecessary just like you said. I believe that the code looks cleaner now.

However, I've been thinking that we might want to consider making `point.state` not optional in TypeScript - if the `point.state` is always `normal` by default then we could get rid of many lines inside the `pointAttribs`.

`const state = point?.state || 'normal';` appears 13 times in the code (in `pointAttribs`) for 13 different series types. 

We could modify it and use `point.state` instead.

But maybe there's something that I did not take into consideration and it's not a good idea so please correct me if I'm wrong.

2023-08-22 12:46 UTC, TorsteinHonsi commented
> We could modify it and use point.state instead.

I think that's a good idea. We could set that default directly on the Point prototype.

2023-08-28 13:15 UTC, jakubSzuminski commented
I've been trying to make the `point.state` non-optional (always `normal` by default), but unfortunately a few problems in tests arose that I have not been able to solve yet. 

Depending on what you think is best we could:
- either merge this PR and I could start working on making the `point.state` non-optional in another pull request as a TypeScript refactor
- or I'll try to investigate this further and we'll wait with a merge until I find a good solution to all those tests that crash

@TorsteinHonsi please let me know what you think.

2023-08-28 13:27 UTC, TorsteinHonsi commented
Waiting is fine by me.

2023-10-05 15:24 UTC, jakubSzuminski commented
The `pointAttribs` function does not take `state` as an argument, because it's taken from `point.state` which is now non-optional (and can take values: `normal`, `inactive`, `hover`, `select`). All the tests have successfully passed.

2023-10-05 18:25 UTC, TorsteinHonsi commented
Do you know what the 73 visual diffs mean?

2023-10-10 11:14 UTC, jakubSzuminski commented
Are these visual diffs from the current code of this PR? I've checked all the samples where there is a "visual difference" and I did not notice anything undesired or unexpected. I did not modify any logic related to KDTree/searching for nearest point to the cursor so I'm not sure where these changes come from.

2023-10-13 07:57 UTC, TorsteinHonsi commented
Yes, these are visual diffs with the current changes. There seems to be some changes around the hovered point marker or halo.

2023-10-13 08:47 UTC, TorsteinHonsi commented
... but now the changes are gone, since merging the master 👍

2023-10-16 14:10 UTC, TorsteinHonsi requested changes
Thanks, nice work! I pushed some minor additions. 

Now for the sake of consistency, I think we should do the same refactoring with the `Series.markerAttribs` function. It is less used, so it shouldn't be too much work now that we already have the Point.state property.

2023-10-17 13:21 UTC, jakubSzuminski commented on ts/Core/Series/Series.ts
> +        );
You're right, I've added it in order to pass the `unit-tests/point/point`, but after diving deeper into it I've realised that it's not necessary so I removed it in the latest commit.

2023-10-18 11:23 UTC, jakubSzuminski commented on ts/Core/Series/Series.ts
> +        );
Unfortunately, it seems like removing it did not solve the issue. I'll investigate this and commit a fix after I find out the true source of the problem here.

2025-04-25 02:10 UTC, closed without merging