CSV demo with modifiers
highcharts/highcharts pull request #19452
Opened 2023-07-27 08:23 UTC by bre1470

2023-07-27 08:39 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| dashboards/dashboards.js | **42.4 kB**<br>145.6 kB | **42.3 kB**<br>145.5 kB | **-45 B**<br>-86 B |

2023-07-27 08:42 UTC, circleci-mu commented
## Visual test results - No difference found

---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  Added | samples/highcharts/data-tools/csv-modifiers/demo.js |

</p>
</details>

2023-08-03 11:54 UTC, bre1470 commented
Looks good, @pawellysy ! 👍

2023-08-03 12:24 UTC, sebastianbochan requested changes

2023-08-03 12:24 UTC, sebastianbochan commented on samples/highcharts/data-tools/csv-modifiers/demo.js
> +        type: 'line',
Line is the default type for HC, so you don't need to place it here.

2023-08-03 12:24 UTC, sebastianbochan commented on samples/highcharts/data-tools/csv-modifiers/demo.js
> +
Remove extra lines/spaces in the file.

2023-08-04 07:21 UTC, karolkolodziej approved these changes

2023-08-04 07:21 UTC, karolkolodziej commented on samples/highcharts/data-tools/csv-modifiers/demo.js
> +            extremes: true
Do we need extremes sync here? It only causes issues with the `reset zoom` button.

2023-08-04 07:39 UTC, sebastianbochan approved these changes

2023-08-04 08:21 UTC, karolkolodziej commented on samples/highcharts/data-tools/csv-modifiers/demo.js
> +            extremes: true
PS I reported this issue on Assana 😄

2023-08-04 08:54 UTC, pawelfus approved these changes
Thanks!

2023-08-04 09:41 UTC, merged