Dash/connector kpi
highcharts/highcharts pull request #19525
Opened 2023-08-09 13:36 UTC by pawellysy

2023-08-09 13:50 UTC, circleci-mu commented
## Visual test results - No difference found

2023-08-10 12:41 UTC, karolkolodziej requested changes

2023-08-10 12:41 UTC, karolkolodziej commented on ts/Dashboards/Components/KPIComponent.ts
> +    public getValue(): string|number|undefined {
The description is missing. Should it be public?

2023-08-10 12:41 UTC, karolkolodziej commented on ts/Dashboards/Components/KPIComponent.ts
> +
space

2023-08-10 12:41 UTC, karolkolodziej commented on ts/Dashboards/Components/KPIComponent.ts
> +    private updateElements(): void {
Description

2023-08-11 06:38 UTC, karolkolodziej approved these changes

2023-08-11 09:27 UTC, sebastianbochan approved these changes

2023-08-11 09:28 UTC, sebastianbochan commented
Please lint ;)

2023-08-11 12:30 UTC, merged