bugfix/16769-tunnel-annotation-log-axis
highcharts/highcharts pull request #19548
Opened 2023-08-11 14:36 UTC by kamil-musialowski

Fixed #16769, tunnel annotations had incorrect height on logarithmic axes.

2023-08-11 14:48 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| modules/annotations-advanced.js | **23.9 kB**<br>85.9 kB | **23.9 kB**<br>86.0 kB | **75 B**<br>162 B |

2023-08-11 14:51 UTC, circleci-mu commented
## Visual test results - No difference found

2023-09-19 06:55 UTC, TorsteinHonsi requested changes
Thanks!

There's an error while building images for the visual comparison. CI fails on the following command, try running this to debug:

`npx karma start test/karma-conf.js --tests stock/*/* --reference --browsercount 2 --no-fail-on-empty-test-suite`

You can narrow in on the problematic code by modifying the `--tests` argument and reduce the `--browsercount`.

2023-09-19 11:15 UTC, pawelfus approved these changes
Look good, thanks!

2023-09-19 13:04 UTC, merged