dash/climate-performance
highcharts/highcharts pull request #19547
Opened 2023-08-11 14:06 UTC by karolkolodziej

Fixed, improved extremes change in climate demo.

2023-08-11 14:17 UTC, circleci-mu commented
### File size comparison
No differences found

2023-08-14 05:40 UTC, goransle approved these changes
LGTM

2023-08-14 07:22 UTC, sebastianbochan requested changes

2023-08-14 07:22 UTC, sebastianbochan commented on samples/dashboards/demo/climate/demo.js
> +                                    console.time('updateBoard');
Do we need it here?

2023-08-14 08:04 UTC, pawellysy approved these changes
LGTM!

2023-08-14 10:33 UTC, bre1470 approved these changes
When the `selectionTimeout` is removed, the change of extremes is still stuttering, so the core issue is not solved.

2023-08-14 11:16 UTC, sebastianbochan approved these changes

2023-08-14 11:21 UTC, merged