bugfix/19505-missing-label-connector
highcharts/highcharts pull request #19556
Opened 2023-08-15 10:39 UTC by kamil-musialowski

Fixed #19505, label connector was not rendered in certain positions.

2023-08-15 10:50 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts.js | **99.6 kB**<br>281.5 kB | **99.6 kB**<br>281.5 kB | **-14 B**<br>-10 B |
| highstock.js | **132.7 kB**<br>383.1 kB | **132.7 kB**<br>383.1 kB | **1 B**<br>-12 B |
| highmaps.js | **125.6 kB**<br>360.1 kB | **125.6 kB**<br>360.0 kB | **15 B**<br>-12 B |
| highcharts-gantt.js | **134.9 kB**<br>388.0 kB | **134.9 kB**<br>388.0 kB | **15 B**<br>-13 B |

2023-08-15 10:55 UTC, circleci-mu commented
## Visual test results - Differences found
Found **317** diffing sample(s). [Please review the differences.](https://vrevs.highsoft.com/pr/19556/review)

2023-08-22 13:13 UTC, TorsteinHonsi commented
> Originally, the connector is rendered from the side of a label, so should it be rendered from the bottom left corner in that case?

@kamil-musialowski  Yes. That would prevent the connector from crossing over the labels. Just like the chevrons, they are added to whatever side is closest to the anchor. Not only right or left, but also top or bottom.

2023-08-30 07:58 UTC, TorsteinHonsi requested changes
Thanks! We now have a situation where the split tooltip is not working well, because the connector connects to the top or bottom of the rectangle. 

Consider the `highcharts/members/renderer-callout` demo, updated in my latest commit.

When the anchor is to the left or to the right of the callback, we want it to to be connected to the side. This is how it currently works in the master, so that should not change. Screenshot from the master:

![Skjermbilde 2023-08-30 kl  09 50 11](https://github.com/highcharts/highcharts/assets/227836/6b69fc1e-145f-458b-a709-d95e316f5351)

The only situation we want to fix is when the anchor is directly above or below the rounded corner. This is the case when the connector disappears in the master. In this case only, it should connect to the top or bottom side. Screenshot from the current state of this PR:

![Skjermbilde 2023-08-30 kl  09 57 49](https://github.com/highcharts/highcharts/assets/227836/9305e516-d222-4068-b32a-93d69096ad94)

2023-09-04 09:25 UTC, kamil-musialowski commented
Got it, thank you. Now it looks and behaves even better imo.

2023-09-05 05:30 UTC, TorsteinHonsi approved these changes

2023-09-05 05:31 UTC, merged