dash/docs-es-modules
highcharts/highcharts pull request #19557
Opened 2023-08-15 10:55 UTC by sebastianbochan

Added dashboard es-modules docs.

2023-08-15 11:07 UTC, circleci-mu commented
### File size comparison
No differences found

2023-08-15 11:10 UTC, circleci-mu commented
## Visual test results - No difference found

2023-08-15 12:31 UTC, goransle approved these changes
LGTM

2023-08-16 06:03 UTC, pawellysy requested changes
Looks good! Just small typos fixes

2023-08-16 06:03 UTC, pawellysy commented on docs/dashboards/installation-with-es-modules.md
> +package you could initialize it like:
```suggestion
First, make sure that a plugin supports loading over NPM and load the required
files. In the example `DataGrid` supports NPM loading, so after installing the
package you could initialise it like this:
```

2023-08-16 06:03 UTC, pawellysy commented on docs/dashboards/installation-with-es-modules.md
> +files to improve the load size and load time further. Create a NodeJS project
```suggestion
files to further improve the load size and load time. Create a NodeJS project
```

2023-08-16 06:28 UTC, karolkolodziej approved these changes

2023-08-16 06:28 UTC, karolkolodziej commented on docs/dashboards/installation-with-es-modules.md
> +                items: ['editMode']
We don't need that: `items: ['editMode']`

2023-08-16 07:33 UTC, pawellysy requested changes

2023-08-16 07:33 UTC, pawellysy commented on docs/dashboards/installation-with-es-modules.md
> +For a line chart create the JavaScript files as shown below.
Not `line chart`

2023-08-16 07:37 UTC, pawellysy approved these changes

2023-08-16 07:39 UTC, merged