dash/remove-parentElement
highcharts/highcharts pull request #19566
Opened 2023-08-16 12:48 UTC by sebastianbochan

Removed parentNode from the component.

2023-08-16 13:02 UTC, circleci-mu commented
## Visual test results - No difference found

2023-08-16 14:06 UTC, pawellysy requested changes
We want to delete the API Option `parentElement`, not the property itself.
https://github.com/highcharts/highcharts/blob/d56249fd87b3a6c56438bdceac78af25c8b2be6c/ts/Dashboards/Components/Component.ts#L1233-L1239
This one

2023-08-16 14:56 UTC, bre1470 commented
We can still access `parentElement` still via `cell.container`. IMHO the property is redundant.

2023-08-17 07:02 UTC, karolkolodziej approved these changes

2023-08-21 08:09 UTC, closed without merging