dash/a11y-minimal-demo
highcharts/highcharts pull request #19760
Opened 2023-09-14 13:59 UTC by sebastianbochan

Added a11y descriptions to parts of the minimal demo.

2023-09-14 14:06 UTC, circleci-mu commented
## Lighthouse report
### dashboards-demo-minimal.json
|   | Reference | Proposed | Diff |
| :---- | ------ | ----- | ----- |
| performance – score | 0.66 | 0.66 | 0.00 |
| first-contentful-paint – score | 0.97 | 0.97 | 0.00 |
| first-contentful-paint – milliseconds | 703.82 | 700.88 | -2.94 |
| first-meaningful-paint – score | 0.97 | 0.97 | 0.00 |
| first-meaningful-paint – milliseconds | 706.62 | 700.88 | -5.74 |
| dom-size – score | 1 | 1 | 0.00 |
| dom-size – elements | 331 | 334 | 3.00 |

2023-09-14 14:11 UTC, circleci-mu commented
### File size comparison
No differences found

2023-09-14 14:13 UTC, circleci-mu commented
## Visual test results - No difference found

2023-09-20 09:50 UTC, circleci-mu commented
## Benchmark report
### benchmarks/DataTable-loading-rows.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff |
| --- | --- | --- | --- |
| 2500000 | 1551.63 | 1563.25 | 11.62 |

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff |
| --- | --- | --- | --- |
| 100 | 0.6 | 0.6 | 0.01 |
| 1000 | 0.92 | 0.91 | -0.01 |
| 10000 | 12.98 | 10.9 | -2.08 |
| 100000 | 53.17 | 52.92 | -0.24 |
| 1000000 | 607.33 | 609.03 | 1.7 |
| 2500000 | 1551.63 | 1563.25 | 11.62 |


</details>

### benchmarks/DataPool-CSV-constructor.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff |
| --- | --- | --- | --- |
| 2500000 | 0.24 | 0.24 | 0 |

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff |
| --- | --- | --- | --- |
| 100 | 0.25 | 0.24 | -0.01 |
| 1000 | 0.24 | 0.24 | 0 |
| 10000 | 0.24 | 0.23 | -0.01 |
| 100000 | 0.24 | 0.24 | 0 |
| 1000000 | 0.25 | 0.26 | 0.01 |
| 2500000 | 0.24 | 0.24 | 0 |


</details>

### benchmarks/DataTable-loading-columns.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff |
| --- | --- | --- | --- |
| 2500000 | 53.78 | 56.8 | 3.03 |

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff |
| --- | --- | --- | --- |
| 100 | 0.36 | 0.36 | 0 |
| 1000 | 0.37 | 0.39 | 0.02 |
| 10000 | 0.49 | 0.48 | 0 |
| 100000 | 3.57 | 4.05 | 0.48 |
| 1000000 | 22.09 | 22.35 | 0.26 |
| 2500000 | 53.78 | 56.8 | 3.03 |


</details>

2023-09-20 11:20 UTC, marvin19 requested changes

2023-09-20 11:20 UTC, marvin19 commented on samples/dashboards/demo/minimal/demo.js
> +                chartContainerLabel: 'Iron',
- It looks like the Vitamin A and Iron is switched for the demos,
- chartContainerLabel belongs in `lang`

2023-09-20 11:20 UTC, marvin19 commented on samples/dashboards/demo/minimal/demo.js
> +                description: 'The iron amount in Foods',
It looks like the Vitamin A and Iron is switched for the demos

2023-09-20 11:20 UTC, marvin19 commented on samples/dashboards/demo/minimal/demo.js
> +                chartContainerLabel: 'Vitamin A',
- It looks like the Vitamin A and Iron is switched for the demos
- chartContainerLabel belongs in `lang`

2023-09-20 11:20 UTC, marvin19 commented on samples/dashboards/demo/minimal/demo.js
> +                description: 'The vitamin A amount in Foods',
It looks like the Vitamin A and Iron is switched for the demos

2023-09-20 11:20 UTC, marvin19 commented on samples/dashboards/demo/minimal/demo.js
> +                    description: 'Grocieries'
Typo --> Groceries

2023-09-21 06:29 UTC, marvin19 commented on samples/dashboards/demo/minimal/demo.js
> +                the daily Recommended Dietary Allowance (RDA)`,
Can you also put in the value of the RDA?

2023-09-21 06:30 UTC, marvin19 requested changes
Looks good!

2023-09-21 06:30 UTC, marvin19 commented on samples/dashboards/demo/minimal/demo.js
> +                the daily Recommended Dietary Allowance (RDA)`,
Can you also put in the value of the RDA?

2023-09-22 06:09 UTC, karolkolodziej reviewed
Can you please investigate if we can do sth about the tooltips:
![image](https://github.com/highcharts/highcharts/assets/57004120/f7a0b613-7912-45ed-b323-4ebee2e4c9e9)
It is visible when you load the page and start to hover over one of the charts.

2023-09-22 06:09 UTC, karolkolodziej commented on samples/dashboards/demo/minimal/demo.js
> +                        medium: {
IMO it looks too small in medium.

2023-09-22 06:09 UTC, karolkolodziej commented on ts/Dashboards/cypress/support/commands.js
> +// ***********************************************
Are these files related to the fix?

2023-09-22 10:48 UTC, closed without merging