dash/a11y-light-dark-demo
highcharts/highcharts pull request #19776
Opened 2023-09-18 13:36 UTC by karolkolodziej

Improved demos' accecibility.

2023-09-18 13:44 UTC, circleci-mu commented
## Lighthouse report
### dashboards-demo-minimal.json
|   | Reference | Proposed | Diff |
| :---- | ------ | ----- | ----- |
| performance – score | 0.6 | 0.66 | 0.06 |
| first-contentful-paint – score | 0.97 | 0.97 | 0.00 |
| first-contentful-paint – milliseconds | 703.59 | 707.91 | 4.32 |
| first-meaningful-paint – score | 0.97 | 0.97 | 0.00 |
| first-meaningful-paint – milliseconds | 703.59 | 707.91 | 4.32 |
| dom-size – score | 1 | 1 | 0.00 |
| dom-size – elements | 331 | 331 | 0.00 |

2023-09-18 13:46 UTC, circleci-mu commented
### File size comparison
No differences found

2023-09-18 13:49 UTC, circleci-mu commented
## Visual test results - No difference found

2023-10-18 11:03 UTC, sebastianbochan requested changes

2023-10-18 11:03 UTC, sebastianbochan commented on samples/dashboards/demo/light-dark-theme/demo.css
> +label {
Instead of overwriting global rules for labels, I would suggest to use `.inputs-wrapper label { }`

2023-10-18 11:22 UTC, marvin19 approved these changes

2023-10-20 08:22 UTC, sebastianbochan approved these changes

2023-10-20 08:30 UTC, merged