dash/a11y-sync-extremes-demo
highcharts/highcharts pull request #19797
Opened 2023-09-20 10:06 UTC by sebastianbochan

Applied a11y requests to sync-extremes dashboard demo.

2023-09-20 10:12 UTC, circleci-mu commented
## Lighthouse report
### dashboards-demo-minimal.json
|   | Reference | Proposed | Diff |
| :---- | ------ | ----- | ----- |
| performance – score | 0.66 | 0.67 | 0.01 |
| first-contentful-paint – score | 0.97 | 0.97 | 0.00 |
| first-contentful-paint – milliseconds | 697.54 | 696.7 | -0.84 |
| first-meaningful-paint – score | 0.97 | 0.97 | 0.00 |
| first-meaningful-paint – milliseconds | 697.54 | 696.7 | -0.84 |
| dom-size – score | 1 | 1 | 0.00 |
| dom-size – elements | 331 | 331 | 0.00 |

2023-09-20 10:20 UTC, circleci-mu commented
## Visual test results - No difference found

2023-09-21 06:45 UTC, marvin19 requested changes

2023-09-21 06:45 UTC, marvin19 commented on samples/dashboards/demo/sync-extremes/demo.js
> +                chartContainerLabel: 'Population',
Move `chartContainerLabel` to `lang`

2023-09-21 06:45 UTC, marvin19 commented on samples/dashboards/demo/sync-extremes/demo.js
> +                chartContainerLabel: 'Metropolitan Area',
Move `chartContainerLabel` to `lang`

2023-09-21 06:45 UTC, marvin19 commented on samples/dashboards/demo/sync-extremes/demo.js
> +                chartContainerLabel: 'Highest Elevation',
Move `chartContainerLabel` to `lang`

2023-09-22 11:04 UTC, karolkolodziej approved these changes

2023-10-13 07:30 UTC, Vazonik approved these changes

2023-10-13 07:50 UTC, marvin19 approved these changes

2023-10-13 08:01 UTC, merged