Fixed #19736, MouseWheelZoom preventing list scroll.
highcharts/highcharts pull request #19800
Opened 2023-09-20 10:27 UTC by DJTechnoo

Fixed #19736 , `mouseWheel` zooming prevented scrolling in Stock Tools popups.

2023-09-20 10:32 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highstock.js | **133.3 kB**<br>383.9 kB | **133.3 kB**<br>384.0 kB | **20 B**<br>75 B |

2023-09-20 10:37 UTC, circleci-mu commented
## Visual test results - No difference found

2023-09-20 13:39 UTC, pawelfus requested changes
Minor improvements, otherwise looks good!

2023-09-20 13:39 UTC, pawelfus commented on ts/Extensions/MouseWheelZoom/MouseWheelZoom.ts
> +import DOMElementType from '../../Core/Renderer/DOMElementType';
I believe you can simply import `DOMElementType` type 🤔

2023-09-20 14:28 UTC, kamil-musialowski requested changes
Looks good and works good! 

The original issue is resolved, however one still remains:
- add any label, line, annotation (whatever) to the chart,
- click on it, then click on the pencil icon to edit it,
- try to scroll the edit popup

I don't think it makes any sense to create a separate issue for that, so could you also look into that @DJTechnoo?

2023-09-21 07:17 UTC, TorsteinHonsi approved these changes
Thanks!

2023-09-21 11:54 UTC, pawelfus requested changes
Looks good now, but if you could check the suggestion by Kamil, that would be great. If it's a simple fix, let's include it in this PR

2023-09-21 11:56 UTC, DJTechnoo commented
I am adding a fix very soon

2023-09-22 06:48 UTC, pawellysy approved these changes

2023-09-22 07:49 UTC, pawelfus approved these changes
Thanks!

2023-09-22 08:25 UTC, merged