demo/navigator-set-maskinside-false
highcharts/highcharts pull request #19812
Opened 2023-09-21 10:29 UTC by kamil-musialowski

Moved `navigator.maskInside` sample to the main demo page.

Asana: https://app.asana.com/0/1203542399740129/1204308269116701/f

2023-09-21 10:34 UTC, circleci-mu commented
### File size comparison
No differences found

2023-09-21 10:40 UTC, circleci-mu commented
## Visual test results - Differences found
Found **1** diffing sample(s). [Please review the differences.](https://vrevs.highsoft.com/pr/19812/review)


---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  ? | samples/stock/navigator/maskinside-false/demo.js |

</p>
</details>

2023-09-21 12:26 UTC, pawelfus requested changes
Thanks, looks good!

Could we also change min-width to 310px? To match other demos. Sorry for missing this in the first review!

2023-09-22 07:16 UTC, TorsteinHonsi approved these changes
Thanks!

2023-09-22 08:27 UTC, merged