demo/relocate-rangeselector-datagrouping
highcharts/highcharts pull request #19822
Opened 2023-09-22 10:40 UTC by DJTechnoo

Moved the demo from `stock/rangeselector/datagrouping` to `stock/demo`.

2023-09-22 10:45 UTC, circleci-mu commented
### File size comparison
No differences found

2023-09-22 10:52 UTC, circleci-mu commented
## Visual test results - No difference found

---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  ? | samples/stock/rangeselector/datagrouping/demo.js |

</p>
</details>

2023-09-22 11:58 UTC, pawelfus approved these changes
Thanks!

2023-10-02 12:32 UTC, TorsteinHonsi requested changes
Thanks! Some small change requests.

2023-10-02 12:32 UTC, TorsteinHonsi commented on samples/stock/demo/rangeselector-datagrouping/demo.details
> +name: Rangeselector Datagrouping
Other demos have natural language title, so I think this should be:

"Range selector with data grouping"

2023-10-02 12:32 UTC, TorsteinHonsi commented on samples/stock/demo/rangeselector-datagrouping/demo.details
> +  - General
I think we should put this in the `Various features` category, otherwise it will be placed under "Chart types".

2023-10-02 12:32 UTC, TorsteinHonsi commented on samples/stock/demo/rangeselector-datagrouping/demo.js
Remove the `chart.height = 300` setting. Other demos are typically 400px.

2023-10-02 14:15 UTC, TorsteinHonsi approved these changes

2023-10-02 16:40 UTC, pawellysy approved these changes
LGTM

2023-10-02 16:40 UTC, merged