Migration: TilesProviders
highcharts/highcharts pull request #19834
Opened 2023-09-26 16:58 UTC by bre1470

2023-09-26 17:02 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highmaps.js | **126.1 kB**<br>361.1 kB | **126.1 kB**<br>361.1 kB | **29 B**<br>2 B |

2023-09-26 17:08 UTC, circleci-mu commented
## Visual test results - Differences found
Found **1** diffing sample(s). [Please review the differences.](https://vrevs.highsoft.com/pr/19834/review)


---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  Modified | samples/maps/demo/twm-providers/demo.js |
|  Modified | samples/maps/series-tiledwebmap/human-anatomy/demo.js |

</p>
</details>

2023-09-27 07:37 UTC, bre1470 commented
@TorsteinHonsi Please note that I corrected the name of the TilesProviderRegistry. Before it was TilesProvider__s__Registry which is inconsistent with the rest of registries and as it is not an official property only a few demos are affected.

2023-09-28 14:03 UTC, TorsteinHonsi requested changes
Thanks!

Now (probably after merging #19833) we have many conflicts.

Also, the visual diff reports two differences, but https://vrevs.highsoft.com/pr/19834/review reports some server side problem. Do we know what's causing that? I've seen it on other recent test runs too. I think it's a bit risky to merge before we can see the visual diff, it may come back to bite us later.

2023-09-28 16:37 UTC, TorsteinHonsi approved these changes

2023-09-28 16:39 UTC, merged