docs/19550-candlestick-documentation-improvement
highcharts/highcharts pull request #19830
Opened 2023-09-25 14:31 UTC by jedrzejruta

Enhanced candlestick documentation with information about candles wick and body colors altering.

2023-09-25 14:42 UTC, circleci-mu commented
### File size comparison
No differences found

2023-09-25 14:45 UTC, circleci-mu commented
## Visual test results - No difference found

2023-09-28 07:14 UTC, pawelfus requested changes
Minor improvements, overall great, thanks!

2023-09-28 07:14 UTC, pawelfus commented on docs/stock/candlestick-chart.md
> +![candlestick-color.png](candlestick-color.png)
Can we replace the image with an embedded live demo? I think [this one](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/plotoptions/candlestick-linecolor/) would be good. Feel free to update colors, to match the config above

2023-10-02 08:12 UTC, pawelfus approved these changes
Thanks!

2023-10-02 10:57 UTC, TorsteinHonsi approved these changes
Thanks!

2023-10-02 10:57 UTC, merged