Migration: Gantt/Pathfinder
highcharts/highcharts pull request #19837
Opened 2023-09-27 10:29 UTC by bre1470

2023-09-27 10:35 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts.js | **99.9 kB**<br>281.9 kB | **99.8 kB**<br>281.9 kB | **-24 B**<br>-27 B |
| highstock.js | **133.3 kB**<br>384.0 kB | **133.3 kB**<br>384.0 kB | **-81 B**<br>-27 B |
| highmaps.js | **126.1 kB**<br>361.1 kB | **126.1 kB**<br>361.0 kB | **3 B**<br>-27 B |
| highcharts-gantt.js | **135.2 kB**<br>388.6 kB | **135.5 kB**<br>388.7 kB | **371 B**<br>146 B |
| dashboards/datagrid.js | **9.3 kB**<br>26.4 kB | **8.6 kB**<br>24.4 kB | **-782 B**<br>-2031 B |
| dashboards/modules/dashboards-plugin.js | **16.1 kB**<br>51.8 kB | **15.2 kB**<br>49.9 kB | **-944 B**<br>-2033 B |

2023-09-27 10:39 UTC, circleci-mu commented
## Visual test results - No difference found

2023-09-28 14:06 UTC, TorsteinHonsi requested changes
Now there are conflicts since I merged https://github.com/highcharts/highcharts/pull/19837 . 

Actually this PR contains the changes from the other one, so the note that this _requires_ the other one is a bit confusing. Maybe in cases like this, when one PR builds upon another, it would be better to delete the first one? I mean, apparently merging this one would be enough to get the changes from both.

2023-09-28 14:11 UTC, bre1470 commented
I thought that this is easier for you to review. What puzzles me is that these conflicts occur at all. It should just continue at the same commits on master.

2023-09-28 16:41 UTC, TorsteinHonsi commented
> What puzzles me is that these conflicts occur at all. It should just continue at the same commits on master.

@bre1470 Yes that puzzles me too. If it behaved like that it would indeed be easier to review.

2023-09-28 16:41 UTC, TorsteinHonsi approved these changes

2023-09-28 16:41 UTC, merged