bugfix/18716-export-menu-redraw-a11y
highcharts/highcharts pull request #19856
Opened 2023-10-01 19:09 UTC by jedrzejruta

Fixed #18716, stop export menu proxy button reposition on data change.

2023-10-01 19:13 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| modules/accessibility.js | **45.8 kB**<br>157.0 kB | **45.8 kB**<br>157.0 kB | **13 B**<br>23 B |

2023-10-01 19:19 UTC, circleci-mu commented
## Visual test results - Differences found
Found **1** diffing sample(s). [Please review the differences.](https://vrevs.highsoft.com/pr/19856/review)

2023-10-12 10:00 UTC, oysteinmoseng requested changes
Hm, I wonder if this will cause issues if we e.g. add one more series, and the legend buttons then need to change positions?

Also in the MenuComponent we are redrawing the export button proxy anyway on every chart render: https://github.com/highcharts/highcharts/blob/master/ts/Accessibility/Components/MenuComponent.ts#L189

Could you investigate and see if there is another way of fixing this, where we still catch updates for other proxy elements, and where we still support for example calling `chart.update` and changing the position of the menu button?

2023-10-17 12:47 UTC, jedrzejruta commented
I'll investigate it further to find possible issues in this approach. 

I'm aware of MenuComponent redraw on each chart render, but from what I see it doesn't affect the mentioned issue (at least on master branch, since #19689 PR). Before this PR, actually preventing the redraw on MenuComponent seemed to solve the problem.

I'll try to find another way of fixing this and will keep you updated on the progress.

2023-12-15 13:35 UTC, jedrzejruta commented
@oysteinmoseng any thoughts on this PR?

2024-01-29 13:01 UTC, oysteinmoseng requested changes
Good! Minor change request only.

Now, the current solution will still cause issues if people do
```javascript
    chart.update({
        // some a11y options or menu placement options
    })
```
but I think that's an edge case, and we can ignore it for now.

Ideally we just want to skip handling the re-renders that are caused because of new data, and nothing else, but to my knowledge there is no easy way to detect that currently (@TorsteinHonsi any ideas?)

Maybe we could hook into the new data event, and also the update event, look at options and set flags accordingly, but it sounds a bit messy, so I am inclined to wait unless there is an easier way.

EDIT: Or maybe we should do the handling on update, and the handling on render separately 🤔 Doing the handling on update always, and on render if resized/first render. Perhaps investigate this a bit further, there might be a simple solution.

2024-01-29 14:57 UTC, TorsteinHonsi commented
> Ideally we just want to skip handling the re-renders that are caused because of new data, and nothing else, but to my knowledge there is no easy way to detect that currently (@TorsteinHonsi any ideas?)

We have the `updatedData` event. I see we have code already that [checks for the trigger](https://github.com/highcharts/highcharts/blob/312dd7dd9cf74c72bdadcb0ebe6ee31838f26e3d/ts/Stock/RangeSelector/RangeSelector.ts#L476). But I'm not sure if that is consistently implemented. If not, we could add an event listener for `updatedData` that sets some flag, then reset the flag when the redraw is gone.

2024-01-30 08:32 UTC, oysteinmoseng commented
Looking at it, I think the simplest solution is to recreate the proxies on chart update in addition to the current code, where we update on resize & initial load. There is already an inherited `onChartUpdate` function that can be overridden in the `MenuComponent` class. This function should not be called on new data, I think? But let's double check that..

2024-02-19 15:20 UTC, jedrzejruta commented
Thanks for all the insights regarding this issue. I must've missed your comments, getting back to this PR soon.

2026-04-20 13:28 UTC, closed without merging