dash/19707-hide-settings-button
highcharts/highcharts pull request #19875
Opened 2023-10-04 19:37 UTC by Vazonik

Added the `toolbars.settingsButtonEnabled` option. Closes #19707.

2023-10-04 19:43 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| dashboards/dashboards.js | **43.1 kB**<br>148.6 kB | **43.2 kB**<br>148.8 kB | **50 B**<br>200 B |

2023-10-04 19:44 UTC, circleci-mu commented
## Lighthouse report
### dashboards-demo-minimal.json
|   | Reference | Proposed | Diff |
| :---- | ------ | ----- | ----- |
| performance – score | 0.66 | 0.66 | 0.00 |
| first-contentful-paint – score | 0.97 | 0.97 | 0.00 |
| first-contentful-paint – milliseconds | 711.21 | 700.5 | -10.71 |
| first-meaningful-paint – score | 0.97 | 0.97 | 0.00 |
| first-meaningful-paint – milliseconds | 711.21 | 700.5 | -10.71 |
| dom-size – score | 1 | 1 | 0.00 |
| dom-size – elements | 331 | 331 | 0.00 |

2023-10-04 19:50 UTC, circleci-mu commented
## Visual test results - Differences found
Found **1** diffing sample(s). [Please review the differences.](https://vrevs.highsoft.com/pr/19875/review)

2023-10-04 20:02 UTC, circleci-mu commented
## Benchmark report
### benchmarks/DataTable-loading-rows.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff |
| --- | --- | --- | --- |
| 2500000 | 1351.41 | 1327.3 | -24.1 |

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff |
| --- | --- | --- | --- |
| 100 | 0.47 | 0.48 | 0.01 |
| 1000 | 0.73 | 0.74 | 0.01 |
| 10000 | 9.24 | 10.94 | 1.69 |
| 100000 | 44.04 | 44 | -0.04 |
| 1000000 | 518.82 | 513.55 | -5.27 |
| 2500000 | 1351.41 | 1327.3 | -24.1 |


</details>

### benchmarks/DataPool-CSV-constructor.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff |
| --- | --- | --- | --- |
| 2500000 | 0.2 | 0.2 | 0 |

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff |
| --- | --- | --- | --- |
| 100 | 0.19 | 0.19 | 0 |
| 1000 | 0.2 | 0.2 | 0 |
| 10000 | 0.2 | 0.2 | 0 |
| 100000 | 0.2 | 0.19 | 0 |
| 1000000 | 0.19 | 0.2 | 0 |
| 2500000 | 0.2 | 0.2 | 0 |


</details>

### benchmarks/DataTable-loading-columns.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff |
| --- | --- | --- | --- |
| 2500000 | 48.3 | 48.76 | 0.46 |

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff |
| --- | --- | --- | --- |
| 100 | 0.31 | 0.29 | -0.01 |
| 1000 | 0.31 | 0.31 | 0 |
| 10000 | 0.86 | 0.4 | -0.46 |
| 100000 | 3.21 | 3.22 | 0.01 |
| 1000000 | 19.82 | 20.07 | 0.25 |
| 2500000 | 48.3 | 48.76 | 0.46 |


</details>

2023-10-06 06:20 UTC, karolkolodziej requested changes

2023-10-06 06:20 UTC, karolkolodziej commented on ts/Dashboards/EditMode/Toolbar/CellEditToolbar.ts
> +        items.push({
At this point, we can implement in a similar fashion the `destroy` button 😉 
@oysteinmoseng do you think it makes sense?

2023-10-06 06:20 UTC, karolkolodziej commented on ts/Dashboards/EditMode/EditMode.ts
> +                    settingsButtonEnabled: true
I'm not convinced if this should be here...

IMO in the `toolbar` we have options for the toolbar itself.
The setting button, at least for me, is something like the `dragDrop` or `resize` and it should have a separate config object like:
```js
                dragDrop: {
                    enabled: true
                },
                resize: {
                    enabled: true
                },
                settings: {
                    enabled: true
                },
```

Altho I can imagine in the future someone would like to disable separately for the cell/row...
But let's not get too far 😅

2023-10-09 10:14 UTC, karolkolodziej approved these changes

2023-10-11 13:32 UTC, sebastianbochan approved these changes

2023-10-11 14:42 UTC, merged