bugfix/19917-arialabel-empty-series
highcharts/highcharts pull request #19918
Opened 2023-10-11 18:41 UTC by marvin19

Fixed #19917, removed aria-label for series without data. Added a check to see if `series.data` is empty and only describe if `series.data` has value. This makes styling with e.g `dashStyle` and nothing else in the series possible without describing the object.

2023-10-11 18:46 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| modules/accessibility.js | **45.8 kB**<br>157.1 kB | **45.8 kB**<br>157.1 kB | **10 B**<br>19 B |

2023-10-11 18:54 UTC, circleci-mu commented
## Visual test results - Differences found
Found **1** diffing sample(s). [Please review the differences.](https://vrevs.highsoft.com/pr/19918/review)

2023-10-12 08:27 UTC, oysteinmoseng requested changes
Nice and simple, I think that's fine (until we get complaints) - and if people want the series described it needs to have null points.

Would be nice to have this covered by a unit test, though. Probably an existing one you can add to.

2023-10-26 13:14 UTC, oysteinmoseng approved these changes
🎉

2023-10-31 09:20 UTC, TorsteinHonsi approved these changes
Thanks!

2023-10-31 09:20 UTC, merged