Enhancement/fix benchmarks
highcharts/highcharts pull request #19945
Opened 2023-10-17 06:00 UTC by pawellysy

Fixed the benchmark comparison scripts.

2023-10-17 06:21 UTC, kamil-musialowski approved these changes

2023-10-17 06:30 UTC, circleci-mu commented
## Benchmark report - Stock
### benchmarks/Stock/Stock-DataGrouping.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff |
| --- | --- | --- | --- |
| 1000000 | 3338.93 | 3381.96 | 43.03 |

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff |
| --- | --- | --- | --- |
| 1000 | 550.47 | 551.45 | 0.98 |
| 10000 | 633.56 | 623.44 | -10.11 |
| 100000 | 1090.01 | 1114.53 | 24.52 |
| 1000000 | 3338.93 | 3381.96 | 43.03 |


</details>

### benchmarks/Stock/Stock-Ordinal.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff |
| --- | --- | --- | --- |
| 1000000 | 4256.73 | 4256.25 | -0.49 |

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff |
| --- | --- | --- | --- |
| 1000 | 589.87 | 589.11 | -0.76 |
| 10000 | 739.26 | 754.13 | 14.87 |
| 100000 | 1550.99 | 1539.23 | -11.76 |
| 1000000 | 4256.73 | 4256.25 | -0.49 |


</details>

### benchmarks/Stock/Stock-DataGrouping-Ordinal.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff |
| --- | --- | --- | --- |
| 100000 | 1570.84 | 1551.66 | -19.18 |

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff |
| --- | --- | --- | --- |
| 1000 | 597.58 | 594.49 | -3.08 |
| 10000 | 745.94 | 742.08 | -3.86 |
| 100000 | 1570.84 | 1551.66 | -19.18 |


</details>

2023-10-17 07:41 UTC, pawelfus requested changes
While you are at this.. 😬

2023-10-17 07:41 UTC, pawelfus commented on .github/workflows/stock-benchmark.yml
> +      - 'ts/Extensions/Annotations/**'
+ `StockChart.ts` and `BrokenAxis.ts` please

2023-10-17 07:44 UTC, pawelfus commented
How hard would it be to add a column with %-change? Is 100ms too long? It depends if the test takes 500ms or 5000ms

2023-10-18 08:20 UTC, DJTechnoo approved these changes

2023-10-19 11:05 UTC, pawelfus approved these changes
Thanks!

2023-10-20 09:14 UTC, merged