Bugfix/19742 anchor pos moved twice
highcharts/highcharts pull request #19959
Opened 2023-10-18 11:28 UTC by pawellysy

Fixed #19742, the anchor position was applied twice if there was only 1 point in the series.

2023-10-18 11:35 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highstock.js | **133.3 kB**<br>383.0 kB | **133.3 kB**<br>383.0 kB | **8 B**<br>5 B |

2023-10-18 11:39 UTC, circleci-mu commented
## Visual test results - No difference found

2023-10-19 07:55 UTC, DJTechnoo approved these changes

2023-10-19 08:29 UTC, pawelfus requested changes
This doesn't fix the issue: https://jsfiddle.net/BlackLabel/tspwxfr5/1/ (and current: https://jsfiddle.net/BlackLabel/tspwxfr5/1/ ) - both double the offset

2023-11-07 11:59 UTC, pawelfus requested changes
Nice work!

Before accepting, I would like to see the perf results

2023-11-07 11:59 UTC, pawelfus commented on ts/Extensions/DataGrouping/DataGroupingSeriesComposition.ts
> +            dataGroupingOptions &&
indent

2023-11-07 11:59 UTC, pawelfus commented on ts/Extensions/DataGrouping/DataGroupingSeriesComposition.ts
> +        i--;
I suggested a more descriptive name for `i` variable. It is easy to miss it and it is not obvious why you decrease the iterator here. Previously `i` was used close to its assignment so it was more readable

2023-11-07 17:13 UTC, bm64 approved these changes
lgtm

2023-11-08 09:14 UTC, kamil-musialowski approved these changes

2023-11-10 10:06 UTC, pawelfus requested changes
Just a minor thingy, otherwise look good!

2023-11-10 10:06 UTC, pawelfus commented on ts/Extensions/DataGrouping/DataGroupingSeriesComposition.ts
> -        // Anchor points that are not extremes.
This comment was misplaced, it shouldn't be removed :)

2023-11-13 11:01 UTC, pawelfus approved these changes
Thanks!

2023-11-13 12:30 UTC, TorsteinHonsi requested changes
Thanks! Just a minor change request to save a few bytes of weight.

2023-11-13 12:30 UTC, TorsteinHonsi commented on ts/Extensions/DataGrouping/DataGrouping.ts
> +                    series.groupMap[point.index].groupStart,
Use optional chaining: 
`series?.groupMap?.[point.index].groupStart`

2023-11-15 07:25 UTC, circleci-mu commented
## Benchmark report - Stock
### benchmarks/Stock/Stock-DataGrouping-Ordinal.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 1000000 | 2238.2 | 2207.08 | -31.12 | -0.01%

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 1000 | 320.58 | 318.68 | -1.9 | -0.01%
| 10000 | 374.17 | 376.03 | 1.86 | 0%
| 100000 | 685.74 | 688.85 | 3.11 | 0%
| 1000000 | 2238.2 | 2207.08 | -31.12 | -0.01%


</details>

### benchmarks/Stock/Stock-DataGrouping.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 1000000 | 1796.1 | 1807.14 | 11.04 | 0.01%

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 1000 | 306.04 | 305.99 | -0.05 | 0%
| 10000 | 356.46 | 358.95 | 2.5 | 0.01%
| 100000 | 561.2 | 564.07 | 2.86 | 0.01%
| 1000000 | 1796.1 | 1807.14 | 11.04 | 0.01%


</details>

### benchmarks/Stock/Stock-Ordinal.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 1000000 | 2237.38 | 2249.43 | 12.05 | 0.01%

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 1000 | 315.96 | 321.05 | 5.08 | 0.02%
| 10000 | 372.75 | 381.19 | 8.44 | 0.02%
| 100000 | 674.64 | 702.2 | 27.57 | 0.04%
| 1000000 | 2237.38 | 2249.43 | 12.05 | 0.01%


</details>

### benchmarks/Stock/Stock-Base.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 1000000 | 7019.7 | 7039.02 | 19.32 | 0%

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 1000 | 318.69 | 319.07 | 0.38 | 0%
| 10000 | 465.93 | 472.32 | 6.39 | 0.01%
| 100000 | 1096.04 | 1098.07 | 2.03 | 0%
| 1000000 | 7019.7 | 7039.02 | 19.32 | 0%


</details>

2023-11-15 08:48 UTC, TorsteinHonsi approved these changes

2023-11-15 08:48 UTC, merged