dash/sidebar-outside-click
highcharts/highcharts pull request #19965
Opened 2023-10-19 10:56 UTC by sebastianbochan

Added closing sidebar, when clicking outside the box.

2023-10-19 11:02 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| modules/annotations.js | **17.6 kB**<br>58.9 kB | **17.6 kB**<br>59.0 kB | **41 B**<br>131 B |
| modules/annotations-advanced.js | **24.1 kB**<br>86.4 kB | **24.1 kB**<br>86.6 kB | **51 B**<br>130 B |
| dashboards/dashboards.js | **43.1 kB**<br>149.1 kB | **43.1 kB**<br>149.2 kB | **40 B**<br>130 B |

2023-10-19 11:06 UTC, circleci-mu commented
## Visual test results - No difference found

2023-10-19 12:32 UTC, karolkolodziej requested changes
A few things:
- The mask is missing when the 
- Test is missing 
- You are editing the `BaseFormat` so someone from the Stock team should also review it.

2023-10-20 13:05 UTC, sebastianbochan commented
I decided to move the clicking functionality from the main class to the sidebar in dashboards, it was too risky to change annotations popups, etc.

2023-10-20 13:14 UTC, circleci-mu commented
## Lighthouse report
### dashboards-demo-minimal.json
|   | Reference | Proposed | Diff |
| :---- | ------ | ----- | ----- |
| performance – score | 0.66 | 0.66 | 0.00 |
| first-contentful-paint – score | 0.97 | 0.97 | 0.00 |
| first-contentful-paint – milliseconds | 699.8 | 700.7 | 0.90 |
| first-meaningful-paint – score | 0.97 | 0.97 | 0.00 |
| first-meaningful-paint – milliseconds | 699.8 | 700.7 | 0.90 |
| dom-size – score | 1 | 1 | 0.00 |
| dom-size – elements | 334 | 334 | 0.00 |

2023-10-20 13:26 UTC, circleci-mu commented
## Benchmark report - Dashboards
### benchmarks/Dashboards/DataPool-CSV-constructor.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 2500000 | 0.2 | 0.2 | 0 | 0.01%

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 100 | 0.2 | 0.2 | 0 | 0.02%
| 1000 | 0.2 | 0.2 | 0 | -0.01%
| 10000 | 0.2 | 0.2 | 0 | 0.02%
| 100000 | 0.2 | 0.2 | 0 | 0.02%
| 1000000 | 0.23 | 0.2 | -0.03 | -0.15%
| 2500000 | 0.2 | 0.2 | 0 | 0.01%


</details>

### benchmarks/Dashboards/DataTable-loading-columns.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 2500000 | 48.25 | 47.68 | -0.57 | -0.01%

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 100 | 0.3 | 0.31 | 0.01 | 0.03%
| 1000 | 0.31 | 0.31 | 0 | 0%
| 10000 | 2.18 | 3.18 | 0.99 | 0.45%
| 100000 | 3.33 | 3.05 | -0.28 | -0.08%
| 1000000 | 20.05 | 19.53 | -0.51 | -0.03%
| 2500000 | 48.25 | 47.68 | -0.57 | -0.01%


</details>

2023-10-24 09:04 UTC, karolkolodziej requested changes
Works well but the grey overlay `highcharts-dashboards-edit-overlay` is missing.

2023-10-24 11:59 UTC, karolkolodziej approved these changes

2023-10-24 11:59 UTC, karolkolodziej commented on test/cypress/integration/Dashboards/component-add.cy.js
> +        // cy.get('#dashboard-col-1').first().trigger('click', {force: true});
Please remove

2023-10-24 11:59 UTC, karolkolodziej commented on test/cypress/integration/Dashboards/component-add.cy.js
> +
Please check if the overlay is visible at that point.

2023-10-24 12:08 UTC, sebastianbochan commented on test/cypress/integration/Dashboards/component-add.cy.js
> +        // cy.get('#dashboard-col-1').first().trigger('click', {force: true});
Nice catch!

2023-10-24 12:33 UTC, Vazonik approved these changes

2023-11-03 10:40 UTC, merged