Migration: GanttSeries
highcharts/highcharts pull request #19985
Opened 2023-10-23 14:44 UTC by bre1470

2023-10-23 14:49 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts-gantt.js | **130.7 kB**<br>382.2 kB | **130.7 kB**<br>382.5 kB | **20 B**<br>289 B |

2023-10-23 14:58 UTC, circleci-mu commented
## Visual test results - No difference found

2023-10-31 08:30 UTC, TorsteinHonsi approved these changes
Thanks!

2023-10-31 08:31 UTC, TorsteinHonsi requested changes
Please resolve conflicts

2023-11-01 11:30 UTC, MarkusBarstad approved these changes
Looks good!

2023-11-01 11:40 UTC, merged