Added scaling to patterns
highcharts/highcharts pull request #19980
Opened 2023-10-23 10:53 UTC by Xillez

- Made patterns scale inversely to used series' visual scale
- Linting issues with pattern-fill
- Scaled patterns to make it compatible with scaling solution

2023-10-23 10:57 UTC, circleci-mu commented
### File size comparison
No differences found

2023-10-23 11:05 UTC, circleci-mu commented
## Visual test results - Differences found
Found **19** diffing sample(s). [Please review the differences.](https://vrevs.highsoft.com/pr/19980/review)

2023-10-23 12:40 UTC, Xillez commented
@TorsteinHonsi There are some minor visual differences and I was hoping you could take a look to see if they're ok? (or maybe someone else if you don't have the time).
It comes from scaling of the built in pattern definitions to remove the patternTransform attribute, so it possibly won't interfere with the fix.

@hubertkozik Made some fiddles and it looks like patterns got inadvertently scaled up a bit somewhere since 9.0.0:
v9.0.0: https://jsfiddle.net/BlackLabel/gashvrzw/
current fix: https://jsfiddle.net/BlackLabel/ekbz4s75/

2023-10-25 09:07 UTC, hubertkozik requested changes
Let's discuss these 3 demos:
- TopoJSON from the actual branch: https://jsfiddle.net/BlackLabel/1b69aqdm/
- GeoJSON from the actual branch: https://jsfiddle.net/BlackLabel/bosm3h4a/
- GeoJSON with v9.2.2: https://jsfiddle.net/BlackLabel/bs3w7oue/

Actual TopoJSON and GeoJSON looks almost the same, minor differences in pattern position - I wouldn’t classify it as an issue. Just a small difference between topo and geo jsons.

Actual TopoJSON and actual GeoJSON are really similar to map with GeoJSON from v9.2.2 (the last working version before regression). To me, this fix looks good now. It applies only for Highcharts Maps and now we don't have any differences for normal series.

- [x] The last missing thing in the code is a unit-test. We've got tests for pattern fill in HC Maps, so I think checking the scale of the pattern in map series would be enough.

- [ ] Also, some notes about the description itself. See [Writing content for the changelog](https://github.com/highcharts/highcharts/tree/master/changelog#writing-content-for-the-changelog). We should follow the rules about assigning yourself to PR, correct labelling and linking the main issue to PR etc.

2023-10-25 09:47 UTC, KacperMadej requested changes
- [ ] change the PR to draft until it passes the internal review
- [ ] add test(s)
- [ ] the [pattern-fill-map](https://www.highcharts.com/demo/maps/pattern-fill-map) seems to be broken [now](http://utils.highcharts.local/samples/#view/maps/demo/pattern-fill-map). Maybe just that demo code needs to be adjusted - it should look like before the fix or better. Maybe the fix should be excluded from being applied to patterns that use images.
![image](https://github.com/highcharts/highcharts/assets/8960408/8881fefd-f67b-4ffe-aced-4584cdbc076d)

2023-10-25 09:47 UTC, KacperMadej commented on ts/Extensions/PatternFill.ts
> +        id = options.id;
It is recommended to keep variables sorted in the ascending order as long as this is not causing any initialization problems (if you have something like `let x = this, a = x.a;` then it is going to stay as is).

2023-11-08 16:03 UTC, KacperMadej requested changes
[The tests](http://utils.highcharts.local/samples/#test/unit-tests/color/pattern-fill) are not passing in a browser or this is happening only for me? I even merged the master branch locally to this branch to double-check (because there were 16 new commits there) but it still shows as 55/61 (or 58/61 sometimes).

2023-11-13 13:33 UTC, Xillez commented
> [The tests](http://utils.highcharts.local/samples/#test/unit-tests/color/pattern-fill) are not passing in a browser or this is happening only for me? I even merged the master branch locally to this branch to double-check (because there were 16 new commits there) but it still shows as 55/61 (or 58/61 sometimes).

Yeah I'm not sure. In firefox locally some tests are failing (none fail with chrome) but it's not the same tests that fail in the CI, and for the most part all the tests that do fail seems to be unrelated with pattern-fill as far as I can see. So not really sure what's going on. Should I try to rerun the tests to see if it's just a coincidence or something happened to not work at the time? @KacperMadej

2023-11-28 11:52 UTC, hubertkozik approved these changes

2023-11-28 14:26 UTC, TorsteinHonsi requested changes
Thanks, this looks really solid!

In addition to the inline comments:

**Zooming**. See this demo: https://jsfiddle.net/highcharts/fq0w7teL/ . 
* Click the plus button. Patterns don't scale.
* Then click the minus button. Patterns scale at the beginning of the animation, but are not corrected during or after the animation.
* Then click the minus button again. Patterns are now correctly scaled.

**Demo**. I realised the only demo we have for patterns on maps is the one with flags. Can we take this demo https://jsfiddle.net/highcharts/fq0w7teL/ and add it to `maps/accessibility/pattern-fills` ? It will also help us catch regressions in the future.

2023-11-28 14:26 UTC, TorsteinHonsi commented on ts/Extensions/PatternFill.ts
> +            (p as any).group?.scaleX &&
Can we avoid the `any` cast here by casting to the `MapPoint` type`
`(p as MapPoint).group?.scaleX`

2023-12-05 10:43 UTC, Xillez commented on ts/Extensions/PatternFill.ts
> +import Series from '../Core/Series/Series.js';
I did get an error related to it but not anymore 🤔

2023-12-05 17:47 UTC, TorsteinHonsi commented on ts/Extensions/PatternFill.ts
> +    element: SVGDOMElement,
Yes, I think that's fine! A few extra bytes of code in the core, but just a handful.

2023-12-07 14:45 UTC, Xillez commented
Managed to find a fix for the zoom animation thing but it sort of looks like the pattern shifts inside the shape:
https://github.com/highcharts/highcharts/assets/5503724/0bb58529-db89-46fe-a901-d8d19accbf8e

Is this a wanted result or should I try to get rid of the "sliding" of the pattern if possible?

2023-12-08 08:58 UTC, TorsteinHonsi commented
> Is this a wanted result or should I try to get rid of the "sliding" of the pattern if possible?

I fear this might cause some seizures out there 😬 . With the current solution, are you updating the pattern on every `step` of the animation? To avoid the flickering, maybe it would be better to only apply the transformation on animation `complete`?

2023-12-12 12:32 UTC, TorsteinHonsi requested changes
Awesome, works like a charm! Just some style guide related comments now and it's ready to merge.

2023-12-12 12:32 UTC, TorsteinHonsi commented on samples/unit-tests/color/pattern-fill/demo.js
> +    );
We have some unwritten conventions for assertion messages:
* Upper case first (real sentence)
* Always include the word "should" in some form. It ensures that we describe what whe _expect_ to see, not what we are actually looking at, which will be confusing depending on whether the test fails or passes, or if the assertion is `ok` or `notOk`.

2023-12-14 11:41 UTC, TorsteinHonsi approved these changes

2023-12-14 11:41 UTC, merged