bugfix/19816-ordinal-incorrect-zoom
highcharts/highcharts pull request #19989
Opened 2023-10-24 10:33 UTC by DJTechnoo

Fixed #19816, incorrect zooming with multiple series and ordinal axis

2023-10-24 10:47 UTC, circleci-mu commented
## Visual test results - No difference found

2023-10-24 11:11 UTC, circleci-mu commented
## Benchmark report - Stock
### benchmarks/Stock/Stock-Base.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 1000000 | 11609.05 | 11592.64 | -16.41 | 0%

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 1000 | 389.69 | 392.67 | 2.98 | 0.01%
| 10000 | 573.6 | 573.84 | 0.24 | 0%
| 100000 | 1540.81 | 1532.42 | -8.39 | -0.01%
| 1000000 | 11609.05 | 11592.64 | -16.41 | 0%


</details>

### benchmarks/Stock/Stock-Ordinal.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 1000000 | 3138.69 | 3152.35 | 13.66 | 0%

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 1000 | 401.76 | 402.5 | 0.75 | 0%
| 10000 | 530.9 | 520.46 | -10.44 | -0.02%
| 100000 | 1134.38 | 1144.6 | 10.22 | 0.01%
| 1000000 | 3138.69 | 3152.35 | 13.66 | 0%


</details>

### benchmarks/Stock/Stock-DataGrouping.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 1000000 | 2448.12 | 2440.36 | -7.76 | 0%

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 1000 | 376.19 | 376.32 | 0.13 | 0%
| 10000 | 444.4 | 445.24 | 0.83 | 0%
| 100000 | 794.17 | 805.44 | 11.27 | 0.01%
| 1000000 | 2448.12 | 2440.36 | -7.76 | 0%


</details>

### benchmarks/Stock/Stock-DataGrouping-Ordinal.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 1000000 | 3135.15 | 3135.96 | 0.81 | 0%

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 1000 | 397.97 | 396.83 | -1.15 | 0%
| 10000 | 529.92 | 533.18 | 3.26 | 0.01%
| 100000 | 1145.34 | 1132.34 | -13 | -0.01%
| 1000000 | 3135.15 | 3135.96 | 0.81 | 0%


</details>

2023-11-08 20:16 UTC, kamil-musialowski requested changes
Absolutely minor stuff to be changes, other than that I like the solution and decision about  always using the extended ordinal positions. Good job!

2023-11-08 20:16 UTC, kamil-musialowski commented on samples/unit-tests/axis/ordinal/demo.js
> +QUnit.test('Zooming in ordnial', assert => {
Typo in "ordnial" :D

2023-11-08 20:16 UTC, kamil-musialowski commented on samples/unit-tests/axis/ordinal/demo.js
> +    testController.pan(start, end, {}, true);
Unnecessary debug marker enabled

2023-11-09 12:57 UTC, kamil-musialowski approved these changes
That's it, thanks!

2023-11-10 09:42 UTC, pawellysy approved these changes
LGTM

2023-11-13 12:38 UTC, TorsteinHonsi commented
Pending resolution to Pawel's comment.

2023-11-14 10:01 UTC, pawelfus commented on ts/Core/Axis/OrdinalAxis.ts
> +        let positions = ordinal.getExtendedPositions();
Debugged together: Postponing this refactor, as it seems to be a longer process than a quick refactor

2023-11-14 10:02 UTC, pawelfus approved these changes
Thank you!

2023-11-15 08:50 UTC, TorsteinHonsi approved these changes

2023-11-15 08:50 UTC, merged