dash/docs-embedded-demos
highcharts/highcharts pull request #19982
Opened 2023-10-23 12:04 UTC by Vazonik

Added missing live demo iframes to docs.

2023-10-24 08:44 UTC, sebastianbochan requested changes

2023-10-24 08:44 UTC, sebastianbochan approved these changes

2023-10-24 08:45 UTC, sebastianbochan requested changes

2023-10-24 08:45 UTC, sebastianbochan commented on docs/dashboards/custom-component.md
> +<iframe style="width: 100%; height: 590px; border: none;" src="https://www.highcharts.com/samples/embed/dashboards/components/custom-component"></iframe>
Please add `allow="fullscreen"` attribute to the iframe.

2023-10-24 11:40 UTC, karolkolodziej approved these changes

2023-10-25 08:21 UTC, sebastianbochan approved these changes

2023-10-25 08:27 UTC, merged