bugix/19946-organization-series-node-alignment
highcharts/highcharts pull request #19995
Opened 2023-10-25 11:02 UTC by hubertkozik

Fixed #19446, nodes in the organization chart weren’t centred while using node width or height options.

2023-10-25 11:06 UTC, circleci-mu commented
### File size comparison
No differences found

2023-10-25 11:12 UTC, circleci-mu commented
## Visual test results - Differences found
Found **7** diffing sample(s). [Please review the differences.](https://vrevs.highsoft.com/pr/19995/review)

2023-10-25 11:15 UTC, hubertkozik commented
There are some visual differences, but to me, it is intended differences, due to improved positioning of nodes in Organization charts.

2023-10-26 11:58 UTC, marvin19 requested changes
In some of the visuals, the context is lost because the node is then overlapping the link between them. See for example [this demo](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/series-organization/datalabels-nodeformatter) and the nodes linked to CTO.

2023-10-27 11:00 UTC, marvin19 approved these changes

2023-10-31 09:29 UTC, TorsteinHonsi approved these changes
Thanks!

2023-10-31 09:30 UTC, merged