Tools: Product visual comparison
highcharts/highcharts pull request #19990
Opened 2023-10-24 11:39 UTC by bre1470

2023-11-01 14:11 UTC, goransle approved these changes
Looks good!

2023-11-02 07:47 UTC, TorsteinHonsi requested changes
Okay, let's try this 🤞 . But first, there is a conflict to resolve.

2023-11-02 09:33 UTC, circleci-mu commented
## Visual test results - No difference found

2023-11-06 12:03 UTC, goransle reviewed
Looks like the Cypress workflow needs the fetch-depth setting as well. Also the dashboards/script is gone from master section of the filesize job?

2023-11-06 13:01 UTC, bre1470 commented
I moved file size comparison into its own workflow, so that we can keep both, Highcharts and Dashboards, in that regard together while visuals are separate.

2023-11-06 13:06 UTC, circleci-mu commented
### File size comparison
No differences found

2023-11-10 12:09 UTC, goransle commented on tools/gulptasks/lib/test.js
> +                .execSync('git diff refs/heads/master HEAD --name-only --diff-filter=ACM')
Still see some git weirdness here.
![image](https://github.com/highcharts/highcharts/assets/7478772/0cee8ea2-e5d3-4049-a755-8465c484da36)

Locally this worked for me on a single-branch checkout:
```
➜  shallowcharts git:(tools/product-visual-ci) git remote set-branches origin 'master'
➜  shallowcharts git:(tools/product-visual-ci) git fetch -v --depth=1
➜  shallowcharts git:(tools/product-visual-ci) git diff HEAD origin/master
```

2023-11-13 08:35 UTC, closed without merging