bugfix/20048-newdataannouncer-not-announcing
highcharts/highcharts pull request #20050
Opened 2023-11-01 15:09 UTC by marvin19

Fixed #20048, `NewDataAnnouncer` was not announcing.

2023-11-01 15:12 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| modules/accessibility.js | **44.4 kB**<br>156.0 kB | **44.4 kB**<br>156.1 kB | **12 B**<br>60 B |

2023-11-01 15:18 UTC, circleci-mu commented
## Visual test results - No difference found

---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  Modified | samples/highcharts/accessibility/custom-dynamic/demo.js |

</p>
</details>

2023-11-02 06:41 UTC, goransle approved these changes
Looks good!

2023-11-09 08:07 UTC, oysteinmoseng requested changes
Nice 🎉 Could we find a way to unit test that something is added to the announce region `div`, though? Would be nice not to have to test this manually.

2023-12-08 09:34 UTC, TorsteinHonsi commented
Pending review by @oysteinmoseng

2024-01-10 11:21 UTC, oysteinmoseng requested changes
Nice, small question to the test only!

2024-01-10 11:21 UTC, oysteinmoseng commented on samples/unit-tests/accessibility/newdataannouncer/demo.js
> +        'The text in the announceRegion should be removed after a short while'
Should this check be moved into the 2nd setTimeout, so that it runs after the announcement text has first been added, and then removed again?

2024-01-17 13:50 UTC, oysteinmoseng approved these changes
🎉

2024-01-23 13:48 UTC, merged