dash/toggle-edit-mode-a11y
highcharts/highcharts pull request #20067
Opened 2023-11-03 09:27 UTC by karolkolodziej

Changed context menu toggle into a button.

2023-11-03 09:32 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| dashboards/dashboards.js | **39.8 kB**<br>142.0 kB | **39.8 kB**<br>142.1 kB | **23 B**<br>69 B |

2023-11-03 09:37 UTC, circleci-mu commented
## Visual test results - No difference found

2023-11-03 09:44 UTC, circleci-mu commented
## Benchmark report - Dashboards
### benchmarks/Dashboards/DataTable-loading-columns.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 2500000 | 0 | 0 | 0 | NaN%

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 100 | 0 | 0 | 0 | NaN%
| 1000 | 0 | 0 | 0 | NaN%
| 10000 | 0 | 0 | 0 | NaN%
| 100000 | 0 | 0 | 0 | NaN%
| 1000000 | 0 | 0 | 0 | NaN%
| 2500000 | 0 | 0 | 0 | NaN%


</details>

### benchmarks/Dashboards/DataPool-CSV-constructor.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 2500000 | 0 | 0 | 0 | NaN%

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 100 | 0 | 0 | 0 | NaN%
| 1000 | 0 | 0 | 0 | NaN%
| 10000 | 0 | 0 | 0 | NaN%
| 100000 | 0 | 0 | 0 | NaN%
| 1000000 | 0 | 0 | 0 | NaN%
| 2500000 | 0 | 0 | 0 | NaN%


</details>

2023-11-06 14:10 UTC, circleci-mu commented
## Lighthouse report
### dashboards-demo-minimal.json
|   | Reference | Proposed | Diff |
| :---- | ------ | ----- | ----- |
| performance – score | 0.57 | 0.57 | 0.00 |
| first-contentful-paint – score | 0.22 | 0.22 | 0.00 |
| first-contentful-paint – milliseconds | 2195.11 | 2191.14 | -3.97 |
| first-meaningful-paint – score | 0.22 | 0.22 | 0.00 |
| first-meaningful-paint – milliseconds | 2195.11 | 2191.14 | -3.97 |
| dom-size – score | 1 | 1 | 0.00 |
| dom-size – elements | 335 | 335 | 0.00 |

2023-11-07 11:24 UTC, sebastianbochan requested changes

2023-11-07 11:24 UTC, sebastianbochan commented on ts/Dashboards/EditMode/EditGlobals.ts
> +        [key: string]: any;
Do we need `any` here? Maybe the generic type would be useful?

2023-11-07 16:54 UTC, Vazonik approved these changes

2023-11-08 08:55 UTC, marvin19 approved these changes

2023-11-08 09:06 UTC, merged