bugfix/19926-annotations-incorrect-event-binding
highcharts/highcharts pull request #20072
Opened 2023-11-03 14:03 UTC by bm64

Fixed #19926, click event wasn't bound correctly for annotations with HTML labels.

2023-11-03 14:05 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| modules/annotations.js | **17.1 kB**<br>58.6 kB | **17.1 kB**<br>58.7 kB | **16 B**<br>71 B |
| modules/annotations-advanced.js | **23.3 kB**<br>86.0 kB | **23.3 kB**<br>86.0 kB | **14 B**<br>71 B |

2023-11-03 14:25 UTC, circleci-mu commented
## Benchmark report - Stock
### benchmarks/Stock/Stock-DataGrouping-Ordinal.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 1000000 | 0 | 0 | 0 | NaN%

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 1000 | 0 | 0 | 0 | NaN%
| 10000 | 0 | 0 | 0 | NaN%
| 100000 | 0 | 0 | 0 | NaN%
| 1000000 | 0 | 0 | 0 | NaN%


</details>

### benchmarks/Stock/Stock-DataGrouping.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 1000000 | 0 | 0 | 0 | NaN%

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 1000 | 0 | 0 | 0 | NaN%
| 10000 | 0 | 0 | 0 | NaN%
| 100000 | 0 | 0 | 0 | NaN%
| 1000000 | 0 | 0 | 0 | NaN%


</details>

### benchmarks/Stock/Stock-Ordinal.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 1000000 | 0 | 0 | 0 | NaN%

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 1000 | 0 | 0 | 0 | NaN%
| 10000 | 0 | 0 | 0 | NaN%
| 100000 | 0 | 0 | 0 | NaN%
| 1000000 | 0 | 0 | 0 | NaN%


</details>

### benchmarks/Stock/Stock-Base.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 1000000 | 0 | 0 | 0 | NaN%

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 1000 | 0 | 0 | 0 | NaN%
| 10000 | 0 | 0 | 0 | NaN%
| 100000 | 0 | 0 | 0 | NaN%
| 1000000 | 0 | 0 | 0 | NaN%


</details>

2023-11-05 11:27 UTC, kamil-musialowski approved these changes

2023-11-06 08:37 UTC, pawelfus requested changes

2023-11-06 08:37 UTC, pawelfus commented on samples/unit-tests/annotations/annotations-events/demo.js
> +    controller.click(chart.plotLeft + 200, chart.plotTop + 75);
Instead of hardcoded pixels, please translate x & y values to pixels

2023-11-06 10:16 UTC, pawelfus approved these changes
Thanks!

2023-11-06 10:16 UTC, pawelfus commented on samples/unit-tests/annotations/annotations-events/demo.js
> +    controller.click(chart.plotLeft + 200, chart.plotTop + 75);
Just realized annotation uses pixels position too, so it is fine

2023-11-06 12:51 UTC, pawellysy approved these changes

2023-11-06 14:06 UTC, DJTechnoo approved these changes
Looks great!

2023-11-07 08:43 UTC, TorsteinHonsi approved these changes

2023-11-07 08:44 UTC, merged