bugfix/19403-tooltip-touch-follow
highcharts/highcharts pull request #20083
Opened 2023-11-06 12:57 UTC by Xillez

Fixed #19403, tooltip didn't follow single finger touch on treemap.

---

Issue: https://github.com/highcharts/highcharts/issues/19403

During testing I found two things:
- I found that the tooltip options aren't applied for some reason, at least they're not visible in the tooltip options referenced at Pointer.ts:1347. 
- There's several demo's where touch follow isn't working and not explicitly disabled as far as I could see.

List of demos (not sure if all should have touch follow or not): 
- heatmap:
  - global-temp-heatmap
  - calendar-heatmap-month
  - highcharts/demo/heatmap
  - series-heatmap/periodic-table
  - stock/yaxis/heatmap-scrollbars
  - maps/demo/heatmap
  - maps/plotoptions/heatmap-*
- scatter:
  - 3d/scatter
  - All 3d-scatter-*
- bubble (bubble has a separate issue as far as I understood):
  - bubble-legend/color
  - packed-bubble-simple-demo
  - packed-bubble-basic

2023-11-06 13:01 UTC, circleci-mu commented
### File size comparison
No differences found

2023-11-06 13:04 UTC, circleci-mu commented
## Visual test results - No difference found

2023-11-07 12:30 UTC, KacperMadej requested changes

2023-11-07 12:30 UTC, KacperMadej commented on ts/Series/Treemap/TreemapSeries.ts
> +            // clientX --> plotX
Is there a nice way to make this work in TS @bre1470 ?

2023-11-07 14:14 UTC, bre1470 commented on ts/Series/Treemap/TreemapSeries.ts
> +            // clientX --> plotX
The typing looks good. If you think about redundancy, we could have a simpler interface extending from `PositionObject`, but that requires refactoring.

2023-11-07 15:30 UTC, KacperMadej commented
@Xillez 
Regarding the list of the other demos, it boils down to different series types and each one of them could be considered in a separate issue:
- `heatmap` --> it has `directTouch: true,` and the first step, at least so far, to make tooltip touch follow work is to change this to `true` and fill other missing gaps.
- `scatter3d` --> same as above. Additionally, there's a missing implementation for XYZ coordinate system in k-d-tree but it looks like something that could be added - from a brief, first look, it seems that the relevant code is extendable to accommodate the needed new feature.
- `packed-bubble-...` --> 'packedbubble` --> same as heatmap.
- bubble-legend/color --> `mapbubble` --> https://github.com/highcharts/highcharts/issues/20086 needs to be resolved first but after that there might be interference with `map` so this might not be that easy to resolve and there is no feature request pending from any user as far as I know, so maybe no need to address this at this time.

2023-11-08 14:07 UTC, KacperMadej approved these changes

2023-11-15 09:11 UTC, TorsteinHonsi reviewed
Thanks!

There are some issues with this approach.

* Consider a multi-level treemap like https://jsfiddle.net/pn7jwrqm/ with default options. On the desktop, the tooltip now points to items from the current level and higher levels in a mix. That's because we turned off `directTouch`. We either need to filter on the current level, or bring back `directTouch`.
* A k-d-tree search finds the closest point to the cursor. Since it only looks for one point of each rectangle in the treemap (center? corner?), we may have a situation where we hover one item and the center of another item is closer. That's why we had `directTouch` behaviour in the first place. We see this if we hover one of the elongated items in the demo.

Maybe using a k-d-tree is not the right solution in the first place to this issue. We have the touch event and a reference to the element it touches, so why look it up in a k-d-tree that is designed for finding points, not shapes?

2023-11-16 12:50 UTC, KacperMadej commented
[The current implementation](https://github.com/highcharts/highcharts/blob/9bd53fb798301ab81c25790599256f8596a39792/ts/Series/Column/ColumnSeries.ts#L879) seems to track hover point only touchstart and proceed to [find the relevant point from the event's target](https://github.com/highcharts/highcharts/blob/9bd53fb798301ab81c25790599256f8596a39792/ts/Core/Pointer.ts#L911-L920). `touchmove` event has no updated target, so it will show the `touchstart`'s original target on `touchmove` over different elements. [Here is a potential solution](https://stackoverflow.com/a/70737325/4046096), but it might require some heavier refactoring and testing.

2023-12-21 16:05 UTC, KacperMadej commented
If the alternative approach will work then it might be worth revisiting [this map bubble issue](https://github.com/highcharts/highcharts/issues/20086).

2024-01-12 08:45 UTC, TorsteinHonsi commented
Setting this back to draft while we're exploring the other approach.

2024-04-04 15:50 UTC, Xillez commented
Fixed in this PR => https://github.com/highcharts/highcharts/pull/20552, closing.

2024-04-04 15:51 UTC, closed without merging