bugfix/19976-jumpy-zoom
highcharts/highcharts pull request #20081
Opened 2023-11-06 12:04 UTC by DJTechnoo

Fixed #19976, sticking to either side when using mouse zoom.

2023-11-06 12:06 UTC, TorsteinHonsi requested changes
Thanks! Please add a unit test too.

2023-11-06 12:08 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highstock.js | **129.3 kB**<br>378.7 kB | **129.3 kB**<br>378.8 kB | **11 B**<br>40 B |

2023-11-06 12:10 UTC, circleci-mu commented
## Visual test results - No difference found

2023-11-09 13:29 UTC, DJTechnoo commented
When all is good, here is a [PR](https://github.com/highcharts/highcharts-utils/pull/77) ready to go for utils

2023-11-09 16:53 UTC, pawelfus requested changes

2023-11-09 16:53 UTC, pawelfus commented on samples/unit-tests/chart/mouse-wheel/demo.js
> +    controller.mouseWheel(200, 100, -1000, true);
Nitpicking: unnecessary debug=true

2023-11-10 08:13 UTC, TorsteinHonsi approved these changes
Thanks!

2023-11-10 08:14 UTC, merged