dash/project-demo
highcharts/highcharts pull request #20107
Opened 2023-11-09 11:57 UTC by karolkolodziej

Added the project management demo.

2023-11-09 11:59 UTC, circleci-mu commented
### File size comparison
No differences found

2023-11-09 12:06 UTC, circleci-mu commented
## Visual test results - No difference found

2023-11-09 15:33 UTC, sebastianbochan commented on samples/dashboards/demo/project-management/demo.css
> +    fill: black;
Please use hex instead.

2023-11-27 12:03 UTC, Vazonik approved these changes
Looks good! 🎉

2023-11-29 09:28 UTC, TorsteinHonsi commented on samples/dashboards/demo/project-management/demo.html
> +    management dashboard. <br>
Prefer using paragraphs, not single breaks. https://github.com/highcharts/highcharts/blob/master/repo-guidelines.md#1-avoid-line-breaks-without-paragraphs

2023-11-29 09:29 UTC, TorsteinHonsi commented on samples/dashboards/demo/project-management/demo.js
> +                categories: ['Done', 'To Do', 'In Progress', 'Blocked']
Pie series don't use `xAxis` 🤔

2023-11-29 09:53 UTC, TorsteinHonsi reviewed
Nice work! I have some comments inline, and some design related.

1. The dashboard title ("Current sprint") has its own card, which looks a bit weird. I think it would look better if it was either outside the cell structure, or the cell background and shadow was removed. I see we have solved this in different ways in the other demos.

2. The #current-sprint div has its own background color, making the background of the top row darker than the rest of the dashboard. Is that intended? It looks a bit unmotivated.

3. On the mobile, we use almost all the screen estate above the fold to show two numbers; completed tasks and incomplete tasks. Maybe it would be better to shrink the two cells to 50% and adjust the font sizes accordingly?

![Skjermbilde 2023-11-29 kl  10 51 19](https://github.com/highcharts/highcharts/assets/227836/eb406231-d1b0-4bb1-b7eb-b3f5bb01a25b)

2023-12-01 12:37 UTC, sebastianbochan requested changes

2023-12-01 12:43 UTC, TorsteinHonsi commented on samples/dashboards/demo/project-management/demo.js
> +                    day: '%e<br><span style="opacity: 0.5; font-size: 0.7em">%a</span>'
> use `<div>`

I don't think the SVG TextBuilder supports that

2023-12-01 13:40 UTC, TorsteinHonsi commented on samples/dashboards/demo/project-management/demo.js
> +                    day: '%e<br><span style="opacity: 0.5; font-size: 0.7em">%a</span>'
It doesn't: https://jsfiddle.net/highcharts/df0v6sn4/

2023-12-04 08:34 UTC, karolkolodziej commented on samples/dashboards/demo/project-management/demo.js
> +                categories: ['Done', 'To Do', 'In Progress', 'Blocked']
leftover 😅

2023-12-04 11:53 UTC, karolkolodziej commented
3. It Seems valid but responsive options don't support the height. I added that to the backlog and we will change the demo after it is implemented.

2023-12-05 18:23 UTC, TorsteinHonsi requested changes
Overall it looks great!

The contrast between the series types is too low (they are all very dark), but I know other team members are working on that. 

One thing that I think should be fixed is the tooltip for the Gantt chart. Both start and end date shows "Week from...", which is not very specific. I assume this happens because both dates are defined on the Monday midnight. There are two ways of resolving it; either set an explicit time format for the tooltip, or change the dates. Actually in this case I think it would make sense to reduce the length of the tasks. What about starting Monday 9:00 and ending them Friday at 17:00? That is a more realisting work week, and will probably resolve the tooltip.

2023-12-06 14:47 UTC, TorsteinHonsi commented
Thanks! Not a big deal, but wouldn't it be more realistic if the tasks end on Friday 17:00 instead of the next Monday 17:00? Like fill out the work week and keep the weekend off?

2023-12-07 14:07 UTC, sebastianbochan commented on samples/dashboards/demo/project-management/demo.css
> +}
So many duplicates in declarations, you can optimize it.

2023-12-08 14:04 UTC, nasin commented
Hi, I think it looks great. 
If possible, can you increase the margin a bit around the component header like in the screenshot?
<img width="919" alt="image" src="https://github.com/highcharts/highcharts/assets/1271445/c9bb24be-db04-4082-b5af-bd333bc9dd9e">

Also, I'm not sure if the "done" color (that darker green color) should be used for the timeline, unless all those tasks are "done." If the timeline is just a timeline, I would use the almost black color like you have in the column chart. And maybe make the "today" line a distinct color from everything else so it stands out more.
![image](https://github.com/highcharts/highcharts/assets/1271445/d294eadc-173a-4469-a78a-4fac3ab7d443)

2023-12-11 08:14 UTC, marvin19 approved these changes

2023-12-11 11:49 UTC, TorsteinHonsi requested changes
We need to do something with the colors of the area chart. I know we did this for a11y compliance, but according to common sense it is not really usable when the legend color is brown and the area color is yellow. Yes, the line color is brown, but that's barely distinguishable from the other lines.

As far as I know, the a11y aspect is covered since we have text directly on the area, so can we just use normal colors?

![Skjermbilde 2023-12-11 kl  12 46 32](https://github.com/highcharts/highcharts/assets/227836/ee429493-b851-4dfd-80a2-a7a521d419bf)

2023-12-13 12:16 UTC, karolkolodziej commented
@TorsteinHonsi I'm ok with that- it seems more logical 😉

2023-12-13 12:31 UTC, TorsteinHonsi approved these changes

2023-12-14 08:31 UTC, merged