Docs: TypeScript Guide
highcharts/highcharts pull request #20113
Opened 2023-11-10 12:28 UTC by bre1470

2023-11-16 08:42 UTC, Xillez requested changes
Just some typos as far as I can see 👍

2023-11-16 08:42 UTC, Xillez commented on docs/advanced-chart-features/highcharts-typescript-declarations.md
> +* User proper typing in your extensions
Typo: "User" => "Use"

2023-11-16 08:42 UTC, Xillez commented on docs/advanced-chart-features/highcharts-typescript-declarations.md
> +Note: If you like to replace existing functionallity of Highcharts, listen to
Typo: "functionallity" => "functionality"

2023-11-16 09:37 UTC, Xillez approved these changes
LGTM 👍

2023-11-17 08:05 UTC, TorsteinHonsi approved these changes
Thanks!

2023-11-22 15:59 UTC, KacperMadej approved these changes

2023-11-23 08:53 UTC, merged