bugfix/19845-gantt-axis-alignment
highcharts/highcharts pull request #20148
Opened 2023-11-16 12:28 UTC by hubertkozik

Fixed #19845, the unnatural shift of ticks in certain conditions.

2023-11-16 12:31 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts-gantt.js | **131.1 kB**<br>382.3 kB | **131.2 kB**<br>382.5 kB | **36 B**<br>144 B |

2023-11-16 12:35 UTC, circleci-mu commented
## Visual test results - Differences found
Found **11** diffing sample(s). [Please review the differences.](https://vrevs.highsoft.com/pr/20148/review)

2023-11-17 12:44 UTC, hubertkozik commented
After a few tries and code changes: there is only one visual difference, which is expected - there shouldn't be any shift of label cell in that demo.

2023-11-22 12:22 UTC, KacperMadej approved these changes

2023-11-22 14:47 UTC, TorsteinHonsi reviewed
Thanks!

Can you give a little explanation of what is going on?

In the [OP demo](https://jsfiddle.net/0kope62s/), the minimum of the x-axis is set to January 31, 00:00. Which means that by moving the tick two pixels to the left, we actually include the last day of January, making it look like it were part of February. 

In the one visual diff, at least on my machine (Central European Time), the situation appears to be similar. The `xAxis.min` is on the previous Sunday at 17:00 hours. So the two pixels on the left actually belong to the week before, and it's misleading to move the tick to the end of the axis.

In https://jsfiddle.net/highcharts/hp9xczn0/ I have added a slider to show what happens when we add or remove 6 hours from the min and max. In both ends we see the same issue - the final line doesn't show up if the first or last tick is very close to the end.

Judging from the comments in the code, I would suspect the problem lies somewhere in this function:

https://github.com/highcharts/highcharts/blob/fbee6f0acf7b2af5dc60390f105d631072f92b32/ts/Core/Axis/GridAxis.ts#L517-L524

2023-11-22 17:03 UTC, hubertkozik commented
I have overlooked some functions in the `GridAxis.ts` file, the previous fix was bad. I added new changes now, which look much better.

2023-11-22 19:52 UTC, TorsteinHonsi requested changes
Thanks! The visual diffs now resolve some of the cases that I always found strange, but weren't sure were a bug.

Since we've fixed this case for the low end of the axes, we should also apply the same logic to the high end. I consider those the same issue:

Check out https://jsfiddle.net/highcharts/hp9xczn0/1/
* For slider values 1 and 2, the last week box is open ended.
* For slider values from 13 up until 24, the January box is open ended.

2023-11-22 19:52 UTC, TorsteinHonsi commented on ts/Core/Axis/GridAxis.ts
> +            min &&
If `min` is 0, `endMoreThanMin` will end up as falsy. Not very likely that `min` is on January 1st 1970, but nonetheless. Use `isNumber(min)` instead.

2023-11-22 19:52 UTC, TorsteinHonsi commented on ts/Core/Axis/GridAxis.ts
> +            min &&
This also applies to the two more checks for `min` and `max` down below.

2023-11-23 09:12 UTC, TorsteinHonsi requested changes
Awesome! I found one more glitch that I think we should address before we leave this subject. In the `gantt/demo/inverted` sample, the week cells have open ends both at min and max.

2023-11-23 14:39 UTC, TorsteinHonsi approved these changes

2023-11-23 14:40 UTC, merged