bugfix/19857-disappearing-auto-rotation-labels
highcharts/highcharts pull request #20186
Opened 2023-11-23 13:14 UTC by jakubjanuchta

Fixed #19857, short labels disappeared when `labels.autoRotation` set.

**Demos to test:**
- User's demo: https://jsfiddle.net/BlackLabel/ht2b1fua/
- Adjustable width demo: https://jsfiddle.net/BlackLabel/dhpxj9q1/

2023-11-23 13:17 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts.js | **96.5 kB**<br>276.2 kB | **96.6 kB**<br>276.4 kB | **54 B**<br>220 B |
| highstock.js | **129.4 kB**<br>378.4 kB | **129.4 kB**<br>378.7 kB | **55 B**<br>220 B |
| highmaps.js | **122.1 kB**<br>355.0 kB | **122.1 kB**<br>355.3 kB | **54 B**<br>220 B |
| highcharts-gantt.js | **131.4 kB**<br>382.6 kB | **131.4 kB**<br>382.8 kB | **53 B**<br>220 B |

2023-11-23 13:21 UTC, circleci-mu commented
## Visual test results - Differences found
Found **1** diffing sample(s). [Please review the differences.](https://vrevs.highsoft.com/pr/20186/review)

2023-11-24 06:38 UTC, TorsteinHonsi requested changes
Thanks! 

This is a very marginal case that happens only when the label width is smaller than the line height. In practice as far as I can see only in a category axis when the categories consist of two characters.

I've proposed a cheaper solution at https://github.com/highcharts/highcharts/pull/20190, by just making sure the slot width never becomes smaller than the line height. Can you have a look at that? If you agree, you can bring those changes over to this PR and keep the unit test. 

There are a few visual differences, which I think are legit. There is now more space around the auto-rotated labels which makes them easier to read.

2023-11-24 08:17 UTC, jakubjanuchta commented
> Thanks!
> 
> This is a very marginal case that happens only when the label width is smaller than the line height. In practice as far as I can see only in a category axis when the categories consist of two characters.
> 
> I've proposed a cheaper solution at #20190, by just making sure the slot width never becomes smaller than the line height. Can you have a look at that? If you agree, you can bring those changes over to this PR and keep the unit test.
> 
> There are a few visual differences, which I think are legit. There is now more space around the auto-rotated labels which makes them easier to read.

Thanks for following up!

I definitely agree that your solution is much cheaper, I brought your changes to this PR.

2023-11-24 09:17 UTC, TorsteinHonsi approved these changes

2023-11-24 09:17 UTC, merged