Webpack bundling
highcharts/highcharts pull request #20210
Opened 2023-11-27 16:30 UTC by bre1470

2023-11-27 16:50 UTC, circleci-mu commented
## Visual test results - No difference found

2023-11-29 11:27 UTC, TorsteinHonsi commented
The CI doesn't run, and it doesn't run locally on a fresh system. It stops of "Generating code..." because the Webpack CLI is not installed. This is how it looks when running the task directly, but the yes/no prompt is not revealed when running `.exec` trough the gulp task.

![Skjermbilde 2023-11-29 kl  12 22 01](https://github.com/highcharts/highcharts/assets/227836/c23e8618-25ef-4b4c-9712-d30a7bee8756)

2023-11-29 11:38 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts.js | **96.5 kB**<br>276.2 kB | **95.7 kB**<br>268.8 kB | **-876 B**<br>-7543 B |
| highstock.js | **129.3 kB**<br>378.4 kB | **128.1 kB**<br>365.9 kB | **-1225 B**<br>-12832 B |
| highmaps.js | **122.0 kB**<br>355.0 kB | **120.7 kB**<br>342.7 kB | **-1321 B**<br>-12649 B |
| highcharts-gantt.js | **131.5 kB**<br>382.9 kB | **130.3 kB**<br>371.8 kB | **-1225 B**<br>-11357 B |
| indicators/indicators-all.js | **20.4 kB**<br>76.7 kB | **23.9 kB**<br>79.0 kB | **3593 B**<br>2382 B |
| modules/accessibility.js | **44.5 kB**<br>156.2 kB | **44.0 kB**<br>149.8 kB | **-472 B**<br>-6577 B |
| modules/annotations.js | **17.1 kB**<br>58.7 kB | **16.9 kB**<br>55.0 kB | **-108 B**<br>-3742 B |
| modules/annotations-advanced.js | **23.3 kB**<br>86.0 kB | **23.0 kB**<br>80.1 kB | **-352 B**<br>-6015 B |
| modules/boost.js | **13.3 kB**<br>38.6 kB | **13.2 kB**<br>37.7 kB | **-163 B**<br>-971 B |
| modules/data.js | **6.1 kB**<br>15.4 kB | **6.3 kB**<br>15.8 kB | **141 B**<br>431 B |
| modules/exporting.js | **7.1 kB**<br>18.9 kB | **7.0 kB**<br>18.4 kB | **-92 B**<br>-508 B |
| modules/heatmap.js | **7.2 kB**<br>19.4 kB | **7.7 kB**<br>20.2 kB | **466 B**<br>776 B |
| modules/offline-exporting.js | **4.0 kB**<br>9.4 kB | **9.9 kB**<br>26.5 kB | **6063 B**<br>17441 B |

2023-11-29 11:58 UTC, circleci-mu commented
## Benchmark report - Stock
### benchmarks/Stock/Stock-DataGrouping.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 1000000 | 0 | 1803.85 | 1803.85 | Infinity%

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 1000 | 0 | 319.06 | 319.06 | Infinity%
| 10000 | 0 | 365.79 | 365.79 | Infinity%
| 100000 | 0 | 570.63 | 570.63 | Infinity%
| 1000000 | 0 | 1803.85 | 1803.85 | Infinity%


</details>

### benchmarks/Stock/Stock-Ordinal.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 1000000 | 0 | 2236.39 | 2236.39 | Infinity%

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 1000 | 0 | 333.23 | 333.23 | Infinity%
| 10000 | 0 | 386.31 | 386.31 | Infinity%
| 100000 | 0 | 688.29 | 688.29 | Infinity%
| 1000000 | 0 | 2236.39 | 2236.39 | Infinity%


</details>

### benchmarks/Stock/Stock-DataGrouping-Ordinal.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 1000000 | 0 | 2216.45 | 2216.45 | Infinity%

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 1000 | 0 | 331.71 | 331.71 | Infinity%
| 10000 | 0 | 389.53 | 389.53 | Infinity%
| 100000 | 0 | 689.46 | 689.46 | Infinity%
| 1000000 | 0 | 2216.45 | 2216.45 | Infinity%


</details>

### benchmarks/Stock/Stock-Base.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 1000000 | 0 | 6945.54 | 6945.54 | Infinity%

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 1000 | 0 | 333 | 333 | Infinity%
| 10000 | 0 | 465.38 | 465.38 | Infinity%
| 100000 | 0 | 1097.69 | 1097.69 | Infinity%
| 1000000 | 0 | 6945.54 | 6945.54 | Infinity%


</details>

2024-02-16 11:43 UTC, goransle approved these changes
Besides those hiccups I don't see anything blocking a merge 👍

2024-02-20 09:35 UTC, KacperMadej commented
`npx gulp test --webpack` fails for me with error:
```console
Chrome Headless 121.0.6167.185 (Windows 10) ERROR
  Uncaught TypeError: Cannot read properties of undefined (reading 'prototype')
  at code/highcharts-more.src.js:19346:28

  TypeError: Cannot read properties of undefined (reading 'prototype')
      at code/highcharts-more.src.js:19346:28
      at code/highcharts-more.src.js:45013:12
      at webpackUniversalModuleDefinition (code/highcharts-more.src.js:9:24)
      at code/highcharts-more.src.js:10:3
```

that points to the first `prototype` in this line of code:
```
const { area: { prototype: { pointClass: AreaPoint, pointClass: { prototype: areaProto } } } } = Series_SeriesRegistry.seriesTypes;
```

2024-02-20 10:15 UTC, TorsteinHonsi commented
Before merging to master, shouldn't we
* Include Dashboard builds?
* Remove the flags (`npx gulp test --webpack` etc), as webpack becomes standard?

2024-02-20 10:31 UTC, bre1470 commented
This is not production ready.

2024-02-20 10:35 UTC, bre1470 commented
The point to merge this into master:
- Limit the already huge scope of review
- Avoid further merge conflicts
- Have more setups to test against
- Optimize webpack
- Prepare integration of webpack

2024-02-20 13:39 UTC, bre1470 commented
@KacperMadej I fixed the Windows-compatibility of the Webpack configuration. Please review ones more.

2024-02-20 16:21 UTC, circleci-mu commented
## Dashboard visual diffs
Visual differences found in: 
* /home/runner/work/highcharts/highcharts/cypress/snapshots/actual/test/cypress/dashboards/visual/dashboards-responsive-responsive-breakpoints-mobile-horizontal.png

 See artifacts in [the run summary](https://github.com/highcharts/highcharts/actions/runs/7976583777) for screenshots

2024-02-22 08:45 UTC, TorsteinHonsi requested changes
Thanks for the solid piece of work 💪 !

2024-02-22 08:45 UTC, TorsteinHonsi commented on tools/webpacks/highcharts.webpack.mjs
Is this file used anymore? Or just a remnant of the POC phase?

2024-02-22 12:26 UTC, bre1470 commented on tools/webpacks/highcharts.webpack.mjs
This is the configuration for webpack.

2024-02-22 12:43 UTC, TorsteinHonsi commented on tools/webpacks/highcharts.webpack.mjs
Okay! Should it be `/webpacks` though? Plural?

2024-02-22 12:47 UTC, bre1470 commented on tools/webpacks/highcharts.webpack.mjs
There is an old MVP-variant for Dashboards as well. Basically base products need their own webpack configuration, as internal and external reference together with the modules organisation differ.

2024-02-23 15:29 UTC, KacperMadej commented
> @KacperMadej I fixed the Windows-compatibility of the Webpack configuration. Please review ones more.

It works for me ✅

2024-02-26 11:37 UTC, TorsteinHonsi commented
Oh. There's a conflict...

2024-02-27 14:15 UTC, TorsteinHonsi approved these changes

2024-02-27 14:15 UTC, merged