dash/HighchartsTypes
highcharts/highcharts pull request #20218
Opened 2023-11-28 13:26 UTC by karolkolodziej

Fixed `d.ts` files for `HighchartsTypes`.

2023-11-28 13:28 UTC, circleci-mu commented
### File size comparison
No differences found

2023-11-28 13:30 UTC, circleci-mu commented
## Lighthouse report
### dashboards-demo-minimal.json
|   | Reference | Proposed | Diff |
| :---- | ------ | ----- | ----- |
| performance – score | 0.57 | 0.57 | 0.00 |
| first-contentful-paint – score | 0.22 | 0.22 | 0.00 |
| first-contentful-paint – milliseconds | 2191.68 | 2191.03 | -0.65 |
| first-meaningful-paint – score | 0 | 0 | 0.00 |
| first-meaningful-paint – milliseconds | 18545.56 | 18539.75 | -5.81 |
| dom-size – score | 1 | 1 | 0.00 |
| dom-size – elements | 348 | 348 | 0.00 |

2023-11-28 13:32 UTC, circleci-mu commented
## Visual test results - No difference found

2023-11-28 13:48 UTC, circleci-mu commented
## Benchmark report - Dashboards
### benchmarks/Dashboards/DataTable-loading-columns.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 2500000 | 15.23 | 16.1 | 0.87 | 0.06%

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 100 | 0.23 | 0.24 | 0.01 | 0.03%
| 1000 | 0.24 | 0.24 | 0 | 0.02%
| 10000 | 0.27 | 0.27 | -0.01 | -0.02%
| 100000 | 2.45 | 2.24 | -0.21 | -0.09%
| 1000000 | 8.48 | 8.61 | 0.13 | 0.02%
| 2500000 | 15.23 | 16.1 | 0.87 | 0.06%


</details>

### benchmarks/Dashboards/DataPool-CSV-constructor.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 2500000 | 0.16 | 0.16 | 0 | 0.02%

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 100 | 0.16 | 0.16 | 0 | 0%
| 1000 | 0.16 | 0.16 | 0 | 0.01%
| 10000 | 0.15 | 0.16 | 0 | 0.03%
| 100000 | 0.15 | 0.16 | 0 | 0.02%
| 1000000 | 0.15 | 0.16 | 0 | 0.02%
| 2500000 | 0.16 | 0.16 | 0 | 0.02%


</details>

### benchmarks/Dashboards/DataTable-loading-rows.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 2500000 | 796.79 | 794.31 | -2.48 | 0%

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 100 | 0.29 | 0.29 | 0.01 | 0.02%
| 1000 | 0.51 | 0.54 | 0.03 | 0.06%
| 10000 | 2.73 | 2.86 | 0.13 | 0.05%
| 100000 | 16.3 | 15.67 | -0.63 | -0.04%
| 1000000 | 307.51 | 305.82 | -1.69 | -0.01%
| 2500000 | 796.79 | 794.31 | -2.48 | 0%


</details>

2023-12-01 10:39 UTC, sebastianbochan approved these changes

2023-12-05 10:19 UTC, sebastianbochan approved these changes

2023-12-05 10:30 UTC, bre1470 requested changes
Looks good, except `any`s.

2023-12-05 10:30 UTC, bre1470 commented on ts/Dashboards/Plugins/HighchartsComponent.ts
> +        return this.chart as any;
I do not like the use of `any`. The previous one worked without it. Does it lack declarations in HighchartsTypes?

2023-12-05 10:30 UTC, bre1470 commented on ts/Dashboards/Plugins/KPIComponent.ts
> +        const charter = KPIComponent.charter as any;
This probably also looks like in need of a type fix.

2023-12-05 10:30 UTC, bre1470 commented on ts/Dashboards/Plugins/NavigatorComponent.ts
> +        ) as any;
Why?

2023-12-05 12:08 UTC, bre1470 approved these changes
Awesome! 👍

2023-12-05 12:29 UTC, merged