dash/first-dash-docs
highcharts/highcharts pull request #20223
Opened 2023-11-29 09:25 UTC by karolkolodziej

Attempt to fix the first dashboard docs.
Looks like the layout is broken: https://www.highcharts.com/docs/dashboards/your-first-dashboard

2023-12-01 10:38 UTC, sebastianbochan requested changes

2023-12-01 10:38 UTC, sebastianbochan commented on docs/dashboards/your-first-dashboard.md
> +To do so, you have to pass two arguments:
Remove extra spaces.

2023-12-01 15:45 UTC, Vazonik approved these changes
Looks ok, except the extra spaces.

2023-12-01 15:45 UTC, Vazonik approved these changes
Looks ok, except the extra spaces.

2023-12-04 08:25 UTC, karolkolodziej commented
With the double space, I'm trying to fix the issue visible here:
![image](https://github.com/highcharts/highcharts/assets/57004120/795c2e5f-2cf2-4e39-bd8a-d31ab0dbb65e)

I don't see this in VSCode, it is only visible in the released version thus I'm experimenting here slightly 😅

2023-12-06 11:39 UTC, sebastianbochan approved these changes

2023-12-06 11:51 UTC, merged