dash/sync-multiple-series
highcharts/highcharts pull request #20246
Opened 2023-12-04 15:09 UTC by sebastianbochan

Fixed syncs between different lengths of arrays of series.

2023-12-04 15:12 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| dashboards/modules/dashboards-plugin.js | **13.7 kB**<br>45.7 kB | **13.7 kB**<br>45.7 kB | **14 B**<br>30 B |

2023-12-04 15:14 UTC, circleci-mu commented
## Lighthouse report
### dashboards-demo-minimal.json
|   | Reference | Proposed | Diff |
| :---- | ------ | ----- | ----- |
| performance – score | 0.57 | 0.57 | 0.00 |
| first-contentful-paint – score | 0.22 | 0.22 | 0.00 |
| first-contentful-paint – milliseconds | 2190.95 | 2193.31 | 2.36 |
| first-meaningful-paint – score | 0 | 0 | 0.00 |
| first-meaningful-paint – milliseconds | 18539.01 | 18542.24 | 3.23 |
| dom-size – score | 1 | 1 | 0.00 |
| dom-size – elements | 348 | 348 | 0.00 |

2023-12-04 15:31 UTC, circleci-mu commented
## Benchmark report - Dashboards
### benchmarks/Dashboards/DataTable-loading-columns.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 2500000 | 16.2 | 16.33 | 0.13 | 0.01%

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 100 | 0.24 | 0.24 | 0 | 0%
| 1000 | 0.24 | 0.24 | 0 | -0.01%
| 10000 | 0.27 | 0.27 | 0 | 0%
| 100000 | 2.31 | 2.27 | -0.04 | -0.02%
| 1000000 | 9 | 8.98 | -0.02 | 0%
| 2500000 | 16.2 | 16.33 | 0.13 | 0.01%


</details>

### benchmarks/Dashboards/DataPool-CSV-constructor.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 2500000 | 0.17 | 0.17 | 0 | 0.01%

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 100 | 0.17 | 0.17 | 0 | 0.03%
| 1000 | 0.16 | 0.17 | 0.01 | 0.06%
| 10000 | 0.16 | 0.17 | 0.01 | 0.04%
| 100000 | 0.16 | 0.17 | 0.01 | 0.04%
| 1000000 | 0.16 | 0.17 | 0 | 0.03%
| 2500000 | 0.17 | 0.17 | 0 | 0.01%


</details>

### benchmarks/Dashboards/DataTable-loading-rows.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 2500000 | 789.53 | 791.77 | 2.24 | 0%

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 100 | 0.28 | 0.29 | 0.01 | 0.02%
| 1000 | 0.53 | 0.73 | 0.19 | 0.36%
| 10000 | 2.83 | 2.9 | 0.08 | 0.03%
| 100000 | 17.14 | 16.8 | -0.33 | -0.02%
| 1000000 | 308.32 | 309 | 0.68 | 0%
| 2500000 | 789.53 | 791.77 | 2.24 | 0%


</details>

2023-12-05 08:46 UTC, karolkolodziej requested changes
What in the case when the chart with multiple series has a shared tooltip- [demo](https://jsfiddle.net/BlackLabel/amjhu3s7/)?

Don't you think that also shared tooltip should be visible when hovering over the left chart?

2023-12-07 10:38 UTC, Vazonik commented on samples/dashboards/cypress/chart-interaction/demo.mjs
>  }, true);
Missing trailing line.

2023-12-07 10:38 UTC, Vazonik commented on ts/Dashboards/Plugins/HighchartsSyncHandlers.ts
> +                                series.visible &&
it can be `series?.visible` instead

2023-12-07 10:38 UTC, Vazonik commented on ts/Dashboards/Plugins/HighchartsSyncHandlers.ts
> +                                        hoverSeries = hoverPoint?.series || chart.hoverSeries,
Shouldn't we follow the accepted rules of linting in this project instead of circumventing it?

2023-12-07 10:38 UTC, Vazonik commented on ts/Dashboards/Plugins/HighchartsSyncHandlers.ts
> +                                        useSharedTooltip ? points.hoverPoints : point
As above.

2023-12-07 10:38 UTC, Vazonik commented on ts/Dashboards/Plugins/HighchartsSyncHandlers.ts
> +                                    (series): boolean => series.name === cursor.column
Is it acceptable to use `/* eslint-disable max-len */` in the src?

2023-12-07 11:07 UTC, karolkolodziej approved these changes

2023-12-07 11:58 UTC, merged