bugfix/19808-range-selector-states
highcharts/highcharts pull request #20300
Opened 2023-12-12 17:39 UTC by kamil-musialowski

Fixed #19808, week/month buttons state was incorrect.

- [ ] Add test once agreed on a final solution.

2023-12-12 17:39 UTC, kamil-musialowski commented
@pawelfus Pushing the solution draft, let me know what you think

2023-12-12 17:41 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highstock.js | **128.6 kB**<br>373.5 kB | **128.6 kB**<br>373.5 kB | **-16 B**<br>-47 B |
| highcharts-gantt.js | **130.7 kB**<br>378.1 kB | **130.7 kB**<br>378.1 kB | **-29 B**<br>-47 B |
| modules/accessibility.js | **44.3 kB**<br>155.0 kB | **44.3 kB**<br>155.0 kB | **-30 B**<br>-47 B |

2023-12-12 17:45 UTC, circleci-mu commented
## Visual test results - No difference found

2023-12-12 18:08 UTC, circleci-mu commented
## Benchmark report - Stock
### benchmarks/Stock/Stock-DataGrouping.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 1000000 | 1764.48 | 1769.9 | 5.42 | 0%

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 1000 | 277.54 | 275.71 | -1.83 | -0.01%
| 10000 | 307.04 | 312.5 | 5.45 | 0.02%
| 100000 | 514.93 | 532.64 | 17.72 | 0.03%
| 1000000 | 1764.48 | 1769.9 | 5.42 | 0%


</details>

### benchmarks/Stock/Stock-DataGrouping-Ordinal.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 1000000 | 2238.43 | 2202.55 | -35.88 | -0.02%

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 1000 | 286.34 | 284.2 | -2.14 | -0.01%
| 10000 | 342.75 | 338.28 | -4.47 | -0.01%
| 100000 | 644.01 | 648.95 | 4.94 | 0.01%
| 1000000 | 2238.43 | 2202.55 | -35.88 | -0.02%


</details>

### benchmarks/Stock/Stock-Base.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 1000000 | 10076.16 | 9891.76 | -184.4 | -0.02%

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 1000 | 291.87 | 287.94 | -3.92 | -0.01%
| 10000 | 447.06 | 442.73 | -4.33 | -0.01%
| 100000 | 1176.11 | 1173.5 | -2.61 | 0%
| 1000000 | 10076.16 | 9891.76 | -184.4 | -0.02%


</details>

### benchmarks/Stock/Stock-Ordinal.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 1000000 | 2231.74 | 2178.88 | -52.86 | -0.02%

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 1000 | 279.36 | 289.51 | 10.15 | 0.04%
| 10000 | 331.88 | 333.75 | 1.87 | 0.01%
| 100000 | 646.42 | 635.44 | -10.98 | -0.02%
| 1000000 | 2231.74 | 2178.88 | -52.86 | -0.02%


</details>

2023-12-13 14:05 UTC, pawelfus requested changes
The solution looks fine, but I'm not convinced about the numbers (0.99, 1.01 etc). I think it will be better to keep the strict number of days (5, 28, 365 etc) instead of the percentage of the range.

2023-12-13 16:04 UTC, kamil-musialowski commented
@pawelfus Agreed, thank you!

I didn't go with the approach i.e `range > 28 && range < 34` since I wanted this solution to work with buttons that have a `count > 1`, i.e 3M  (months) rangeSelector button.

2023-12-15 08:44 UTC, pawelfus requested changes
Looks promising!
Missing test + api info

2023-12-15 08:44 UTC, pawelfus commented on ts/Stock/RangeSelector/RangeSelector.ts
> +                day = 864e5,
Variable already defined in the outer scope

2023-12-19 16:06 UTC, kamil-musialowski commented
@pawelfus I've changed the logic a bit - my mistake. Previously I was checking if `range is < > than actualRange +/- few days`, while it should go, `is actualRange < > than a range +/- few days.`

2023-12-20 11:48 UTC, pawellysy approved these changes
Great job! thanks!

2023-12-29 13:29 UTC, bm64 approved these changes
Looks good!

2024-01-02 11:44 UTC, pawelfus approved these changes
Thanks!

2024-01-03 13:25 UTC, TorsteinHonsi commented
Are we sure we want the button matching to be sloppier? As noted in the issue, this is a regression after a commit dealing with `fixedRange` on an ordinal axis. Could it be that the solution should be related to the ordinal axis rather than the range selector? Maybe what we need is a more granular fix for 8ec07aca85f67a48c0023da2214f927b961dc4b2 that retains the button state?

2024-01-29 10:59 UTC, kamil-musialowski commented
New PR with a new solution can be found here: https://github.com/highcharts/highcharts/pull/20522

2024-01-29 10:59 UTC, closed without merging