bugfix/20307-rotation-align-verticalalign
highcharts/highcharts pull request #20345
Opened 2023-12-22 11:21 UTC by hubertkozik

Data labels rotation alignment - work in progress.

2023-12-22 11:24 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts.js | **96.0 kB**<br>272.1 kB | **96.0 kB**<br>272.0 kB | **-13 B**<br>-22 B |
| highstock.js | **128.7 kB**<br>373.2 kB | **128.6 kB**<br>373.2 kB | **-15 B**<br>-22 B |
| highmaps.js | **121.4 kB**<br>350.0 kB | **121.4 kB**<br>350.0 kB | **-21 B**<br>-22 B |
| highcharts-gantt.js | **130.8 kB**<br>377.9 kB | **130.8 kB**<br>377.9 kB | **-15 B**<br>-22 B |

2023-12-22 11:28 UTC, circleci-mu commented
## Visual test results - Differences found
Found **20** diffing sample(s). [Please review the differences.](https://vrevs.highsoft.com/pr/20345/review)

2023-12-27 15:59 UTC, KacperMadej commented
Existing changes are resolving https://github.com/highcharts/highcharts/issues/20301 because for dataLabels with rotation placed is set to true and alignAttr is set for dataLabels (in dataLabel.align). As long as those, or equivalent, changes will be done we should mark this PR as resolving https://github.com/highcharts/highcharts/issues/20301.

2024-01-08 14:46 UTC, hubertkozik commented
Current visual differences sound ok to me, due to many changes in the alignment of data labels.

2024-01-09 08:50 UTC, MarkusBarstad approved these changes
🚀

2024-01-11 15:29 UTC, TorsteinHonsi reviewed
Very nice piece of work! I set up this demo to see how why the labels moved in the diff, it turns out the new logic greatly improved on the current: https://jsfiddle.net/highcharts/u8bot6mp/1/

Will do a proper review tomorrow.

2024-01-12 08:20 UTC, TorsteinHonsi requested changes
Rock solid 💪 .

While working on overlapping detection of rotated labels, maybe you can take a look at an issue that has been bugging me for a while?

In the x-axis of variwide charts, we simply skipped overlapping detection because we lacked support for rotation. See https://www.highcharts.com/demo/highcharts/variwide, where the first few and especially the last few labels overlap.

![Skjermbilde 2024-01-12 kl  09 16 18](https://github.com/highcharts/highcharts/assets/227836/38fde3ee-157d-43d8-90af-6ceae8cc8936)

Peeking at the source code, I was expecting everything to fall into place when I removed the exception for `this.horiz` at this line:

https://github.com/highcharts/highcharts/blob/4ad22a6fc5109fc5e562097f45b5a7f64e655cd8/ts/Series/Variwide/VariwideComposition.ts#L116

But it doesn't work well. The overlapping detection becomes too aggressive and removes more labels than it needs to. Can you look into that? Maybe [bring the commented box preview code](https://github.com/highcharts/highcharts/blob/4ad22a6fc5109fc5e562097f45b5a7f64e655cd8/ts/Core/Series/DataLabel.ts#L362-L381) over to OverlappingDataLabels to see what's going on.

2024-01-12 08:24 UTC, hubertkozik commented
Sure! I will take a look and try to fix.

2024-01-16 11:38 UTC, TorsteinHonsi approved these changes

2024-01-16 11:39 UTC, merged