dash/unify-tools
highcharts/highcharts pull request #20364
Opened 2024-01-02 12:15 UTC by karolkolodziej

Unified tooling between `Dashboards` and `Highcharts`.

To do:

- [ ] scripts
- [ ] api
- [ ] test
- [ ] dist

2024-01-03 13:25 UTC, TorsteinHonsi commented
Should this PR be marked Draft?

2024-01-08 13:45 UTC, jomar-honsi approved these changes

2024-01-08 14:28 UTC, sebastianbochan requested changes

2024-01-08 14:28 UTC, sebastianbochan commented on tools/gulptasks/dist-productsjs.js
> +            ].join('-'),
`new Date().toISOString().split('T')[0]` seems to be simpler

2024-01-08 14:28 UTC, sebastianbochan commented on tools/gulptasks/dist-verify.js
> +        pathsToVerify = HIGHCHARTS_PATHS;
I would simplify it and use `pathsToVerify = argv.dashboards ? DASHBOARDS_PATHS : HIGHCHARTS_PATHS;`

2024-01-08 14:28 UTC, sebastianbochan commented on tools/gulptasks/lint-dts.js
> +            directories = directories.filter(folder => !folder.includes('dashboards'));
One line condition seems to be more optimized.

2024-01-10 11:26 UTC, sebastianbochan approved these changes

2024-01-10 11:37 UTC, Vazonik approved these changes

2024-01-11 13:48 UTC, TorsteinHonsi approved these changes
Awesome, thanks!

2024-01-11 13:48 UTC, merged