bugfix/17320-markers-in-boost
highcharts/highcharts pull request #20387
Opened 2024-01-08 07:51 UTC by marvin19

Fixed #17320, disabled markers for boosted series that had forced marker.

2024-01-08 07:54 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| modules/accessibility.js | **44.3 kB**<br>155.0 kB | **44.4 kB**<br>155.2 kB | **40 B**<br>143 B |
| modules/boost.js | **13.4 kB**<br>38.6 kB | **13.4 kB**<br>38.6 kB | **4 B**<br>23 B |

2024-01-08 07:58 UTC, circleci-mu commented
## Visual test results - No difference found

2024-01-08 08:26 UTC, bre1470 reviewed
Looks good. Some form of test would be nice.

2024-01-08 12:27 UTC, oysteinmoseng requested changes
Thanks, minor thing only!
+ tests as discussed

2024-01-08 12:27 UTC, oysteinmoseng commented on ts/Accessibility/Components/SeriesComponent/ForcedMarkers.ts
> +                function (): void {
Would suggest adding as a `seriesOnRenderCanvas` function, for consistency

2024-01-08 12:27 UTC, oysteinmoseng commented on ts/Accessibility/Components/SeriesComponent/ForcedMarkers.ts
> +                function (): void {
Also perhaps add a comment on why this is necessary (incl. issue #)

2024-01-11 15:01 UTC, TorsteinHonsi approved these changes
Thanks!

2024-01-17 13:53 UTC, oysteinmoseng approved these changes
🎉

2024-01-22 13:46 UTC, merged