demo/dark-themed-stock-chart
highcharts/highcharts pull request #20488
Opened 2024-01-22 10:32 UTC by bm64

Added dark themed stock chart demo.

2024-01-22 10:35 UTC, circleci-mu commented
### File size comparison
No differences found

2024-01-22 10:35 UTC, circleci-mu commented
## Visual test results - No difference found

2024-01-22 11:14 UTC, pawellysy approved these changes
LGTM!

2024-01-22 13:44 UTC, TorsteinHonsi reviewed
Thanks! Did you consider separating out the theming into a `setOptions` call? Otherwise it will be cumbersome for users to modify this for their own charts, since the theming and the general chart setup is intermixed.

2024-01-22 14:46 UTC, DJTechnoo approved these changes
Looking nice!

2024-01-23 09:49 UTC, kamil-musialowski approved these changes
Great!

2024-01-26 15:44 UTC, pawelfus requested changes
Just one minor thing

2024-01-26 15:44 UTC, pawelfus commented on samples/stock/demo/stock-design-dark-theme/demo.details
> +  - General:
Change category

2024-01-29 13:05 UTC, pawelfus approved these changes
Thanks!

2024-01-30 09:35 UTC, TorsteinHonsi commented on samples/stock/demo/responsive/scrollbar-disabled/demo.css
This demo is one level too deep in the file structure... Was it intended to be part of the demo pages?

2024-01-30 09:35 UTC, TorsteinHonsi commented on samples/stock/demo/stock-design-dark-theme/demo.css
Do we need to repeat the word "stock" in the file path `stock-design-dark-theme`? All demos are stock...

2024-02-05 14:22 UTC, bm64 commented on samples/stock/demo/responsive/scrollbar-disabled/demo.css
Must have moved it by mistake, sorry!

2024-02-06 13:16 UTC, TorsteinHonsi requested changes
Thanks! There are still some elements that differ from the design sketch we are targeting at. We should comply with the sketch, to demonstrate how flexible the Highcharts design is.

* The range selector buttons. The sketch has a simple dropdown. If we choose to use buttons, they must follow the dark theme.
* The scrollbar. The sketch doesn't have one.
* The range selector. The navigator handles look different. 
* The border color of the candles
* The sketch uses a candlestick series in the navigator too. Don't know if that's possible in Highcharts, but I think so.

2024-02-12 15:35 UTC, TorsteinHonsi requested changes
Thanks! Still some details I think we should work on to make it match the sketch
* Drop the 1px borders on the range selector buttons and the context button. The sketch has borderless icons at the top, it looks cleaner.
* Drop (or dim) the vertical grid lines inside the navigator
* Drop the scrollbar. It doesn't really fit in.

2024-02-16 08:30 UTC, marvin19 requested changes
- Remove white border from candlestick (replace with red/green border for red/green points)
- Add `lang.accessibility.defaultChartTitle`
- Add `accessibility.typeDescription`: ‘Combination chart with 2 data series. ‘
- Add title to yAxis
- linkedDescription

For title and description, use original text from dataset if it exists in some other demo. Also when RangeSelector is a dropdown, there seems to be a keyboard navigation issue. Will report it as separate issue.

2024-02-20 13:20 UTC, bm64 commented
@marvin19 Thanks! I've made the requested changes. Regarding the candlestick border, chaning it would also change the colors of the high and low shapes since it's currently impossible to change the color of the candle separately. In that case is it okay to leave it as is?

2024-02-20 14:25 UTC, marvin19 approved these changes
Keep as it is!

2024-02-21 08:25 UTC, TorsteinHonsi reviewed
Thanks! One final question before approving - the demo currently opens with the navigator zoomed all out. In the inspiration sketch, only the right part of the navigator is pre-selected (through `rangeSelector.selected`. Should we extend the example data so that we get to show off more of the navigator's value? Right now it shows a series that exactly reflects the main series, plus the two handles at the end, that kind of just hang there. If we set `rangeSelector.selected` to 3 initially, we get the result I want, but I'm not sure if we want 0.5 hours granularity initially. Maybe it's better to use a longer time series.

2024-02-22 16:04 UTC, pawelfus commented
Good point. To me, with our dataset 5min looks the best. Good visible-available data ratio, candles are not too crowded, not too few and far between, right in the spot.

2024-02-23 10:31 UTC, bm64 commented
@TorsteinHonsi I decided to change the initial timeframe to 5m, as this is an interval frequently used by traders and people who analyze stock charts. The navigator looks decent in this configuration. Let me know what you think 😃

2024-02-23 13:14 UTC, TorsteinHonsi approved these changes
I think that looks very good!

2024-02-23 13:14 UTC, TorsteinHonsi approved these changes
I think that looks very good!

2024-02-23 13:14 UTC, merged