dash/organize-karma-tests
highcharts/highcharts pull request #20497
Opened 2024-01-22 20:29 UTC by Vazonik

Reorganized Dashboards Karma tests.

2024-01-22 20:32 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| dashboards/dashboards.js | **40.0 kB**<br>142.5 kB | **39.4 kB**<br>140.2 kB | **-604 B**<br>-2375 B |
| dashboards/modules/dashboards-plugin.js | **14.3 kB**<br>47.3 kB | **14.5 kB**<br>48.1 kB | **275 B**<br>767 B |

2024-01-22 20:32 UTC, circleci-mu commented
## Visual test results - No difference found

2024-01-22 20:33 UTC, circleci-mu commented
## Lighthouse report
### dashboards-demo-minimal.json
|   | Reference | Proposed | Diff |
| :---- | ------ | ----- | ----- |
| performance – score | 1 | 1 | 0.00 |
| first-contentful-paint – score | 1 | 1 | 0.00 |
| first-contentful-paint – milliseconds | 188.72 | 187.57 | -1.15 |
| first-meaningful-paint – score | 1 | 1 | 0.00 |
| first-meaningful-paint – milliseconds | 512.34 | 515.91 | 3.57 |
| dom-size – score | 1 | 1 | 0.00 |
| dom-size – elements | 349 | 346 | -3.00 |

2024-01-22 20:52 UTC, circleci-mu commented
## Benchmark report - Dashboards
### benchmarks/Dashboards/DataPool-CSV-constructor.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 2500000 | 0.17 | 0.16 | 0 | -0.01%

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 100 | 0.17 | 0.16 | -0.01 | -0.06%
| 1000 | 0.16 | 0.16 | 0 | 0.01%
| 10000 | 0.16 | 0.17 | 0.01 | 0.06%
| 100000 | 0.17 | 0.17 | 0 | -0.01%
| 1000000 | 0.16 | 0.16 | 0 | -0.01%
| 2500000 | 0.17 | 0.16 | 0 | -0.01%


</details>

### benchmarks/Dashboards/DataTable-loading-columns.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 2500000 | 16.99 | 15.95 | -1.04 | -0.06%

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 100 | 0.24 | 0.23 | 0 | -0.02%
| 1000 | 0.24 | 0.24 | 0 | 0%
| 10000 | 0.27 | 0.27 | 0 | 0.01%
| 100000 | 2.29 | 2.52 | 0.24 | 0.1%
| 1000000 | 9.43 | 8.96 | -0.47 | -0.05%
| 2500000 | 16.99 | 15.95 | -1.04 | -0.06%


</details>

### benchmarks/Dashboards/DataTable-loading-rows.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 2500000 | 797.65 | 795.43 | -2.22 | 0%

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 100 | 0.28 | 0.28 | 0 | -0.01%
| 1000 | 0.53 | 0.53 | 0 | 0%
| 10000 | 2.77 | 2.9 | 0.13 | 0.05%
| 100000 | 16.39 | 15.99 | -0.39 | -0.02%
| 1000000 | 304.24 | 304.61 | 0.38 | 0%
| 2500000 | 797.65 | 795.43 | -2.22 | 0%


</details>

2024-01-23 07:19 UTC, karolkolodziej requested changes

2024-01-23 07:19 UTC, karolkolodziej commented on test/typescript-karma/Dashboards/Component/html.js
> +    // parentElement.style.width = '1000px';
If we are here lets clean up the commented tests.

2024-01-23 07:20 UTC, karolkolodziej commented
Also, I think we can merge it to the master 😉

2024-01-23 08:25 UTC, sebastianbochan approved these changes

2024-01-23 09:06 UTC, Vazonik commented
> Also, I think we can merge it to the master 😉

The changes after changing the respo to CSS-handled are included there, so I'm not sure it's a good idea, @karolkolodziej.

2024-01-23 17:57 UTC, karolkolodziej approved these changes

2024-01-24 09:45 UTC, merged