dash/new-packages
highcharts/highcharts pull request #20490
Opened 2024-01-22 13:24 UTC by karolkolodziej

WIP

2024-01-30 09:31 UTC, circleci-mu commented
## Lighthouse report
### dashboards-demo-minimal.json
|   | Reference | Proposed | Diff |
| :---- | ------ | ----- | ----- |
| performance – score | 1 | 1 | 0.00 |
| first-contentful-paint – score | 1 | 1 | 0.00 |
| first-contentful-paint – milliseconds | 189.56 | 189.27 | -0.29 |
| first-meaningful-paint – score | 1 | 1 | 0.00 |
| first-meaningful-paint – milliseconds | 511.01 | 423.88 | -87.13 |
| dom-size – score | 1 | 1 | 0.00 |
| dom-size – elements | 349 | 338 | -11.00 |

2024-01-30 09:35 UTC, circleci-mu commented
## Visual test results - No difference found

---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  Modified | samples/highcharts/website/static-editor/demo.js |
|  Modified | samples/highcharts/data-tools/csv-modifiers/demo.js |
|  Modified | samples/highcharts/data-tools/datapool-json-connector-dataurl/demo.js |
|  Modified | samples/highcharts/data-tools/datapool-json-connector-enable-polling/demo.js |
|  Modified | samples/highcharts/data-tools/datapool-json-connector-orientation/demo.js |
|  Modified | samples/highcharts/data-tools/datapool-json-connector/demo.js |
|  Modified | samples/highcharts/website/small-demos-dashboards/demo.js |
|  Modified | samples/highcharts/website/static-dashboard/demo.js |
|  Modified | samples/highcharts/website/static-editor/demo.js |

</p>
</details>

2024-01-30 09:50 UTC, circleci-mu commented
## Benchmark report - Dashboards
### benchmarks/Dashboards/DataTable-loading-rows.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 2500000 | 796.63 | 805.61 | 8.98 | 0.01%

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 100 | 0.29 | 0.29 | 0 | 0.01%
| 1000 | 0.52 | 0.53 | 0.02 | 0.03%
| 10000 | 3.01 | 2.63 | -0.38 | -0.13%
| 100000 | 15.58 | 16.86 | 1.28 | 0.08%
| 1000000 | 313.01 | 311.73 | -1.28 | 0%
| 2500000 | 796.63 | 805.61 | 8.98 | 0.01%


</details>

### benchmarks/Dashboards/DataTable-loading-columns.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 2500000 | 15.86 | 15.84 | -0.02 | 0%

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 100 | 0.24 | 0.24 | 0 | 0.01%
| 1000 | 0.24 | 0.24 | 0 | -0.01%
| 10000 | 0.27 | 0.28 | 0.01 | 0.03%
| 100000 | 2.25 | 2.24 | -0.01 | 0%
| 1000000 | 8.51 | 8.87 | 0.36 | 0.04%
| 2500000 | 15.86 | 15.84 | -0.02 | 0%


</details>

### benchmarks/Dashboards/DataPool-CSV-constructor.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 2500000 | 0.16 | 0.17 | 0 | 0.03%

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 100 | 0.17 | 0.16 | 0 | -0.01%
| 1000 | 0.16 | 0.17 | 0 | 0.02%
| 10000 | 0.17 | 0.17 | 0 | -0.02%
| 100000 | 0.17 | 0.17 | 0 | -0.02%
| 1000000 | 0.16 | 0.16 | 0 | 0%
| 2500000 | 0.16 | 0.17 | 0 | 0.03%


</details>

2024-01-30 11:05 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| dashboards/dashboards.js | **40.0 kB**<br>142.5 kB | **52.8 kB**<br>188.8 kB | **13092 B**<br>47379 B |

2024-01-30 12:50 UTC, circleci-mu commented
## Dashboard visual diffs
Visual differences found in: 
* /home/runner/work/highcharts/highcharts/cypress/snapshots/actual/test/cypress/dashboards/visual/dashboard-climate-edit-mode.png
* /home/runner/work/highcharts/highcharts/cypress/snapshots/actual/test/cypress/dashboards/visual/dashboard-climate-loaded.png
* /home/runner/work/highcharts/highcharts/cypress/snapshots/actual/test/cypress/dashboards/visual/dashboard-climate-mobile-horizontal.png
* /home/runner/work/highcharts/highcharts/cypress/snapshots/actual/test/cypress/dashboards/visual/dashboard-climate-mobile-vertical.png
* /home/runner/work/highcharts/highcharts/cypress/snapshots/actual/test/cypress/dashboards/visual/dashboards-demo-minimal-loaded.png
* /home/runner/work/highcharts/highcharts/cypress/snapshots/actual/test/cypress/dashboards/visual/dashboards-demo-minimal-mobile-horizontal.png
* /home/runner/work/highcharts/highcharts/cypress/snapshots/actual/test/cypress/dashboards/visual/dashboards-demo-minimal-mobile-vertical.png

 See artifacts in [the run summary](https://github.com/highcharts/highcharts/actions/runs/7711345352) for screenshots

2024-02-08 11:03 UTC, sebastianbochan approved these changes

2024-02-08 14:15 UTC, Vazonik approved these changes

2024-02-14 07:56 UTC, bre1470 approved these changes
Setup looks good. 👍 Just one thing to consider.

2024-02-14 07:56 UTC, bre1470 commented on tools/gulptasks/dashboards/_config.json
> +    "bundleSourceFolderDataGrid": "code/datagrid/es-modules/masters-datagrid/",
This should be `code/datagrid/es-modules/masters/` for consistency. Only in the `ts/` folder we have to distinguish more.

2024-02-14 08:09 UTC, bre1470 requested changes
One thing is missing though. You have to adjust `tools/gulptasks/lint-ts.js` and its calls after excluding data grid with `ts/.eslintingore`.

2024-02-15 08:02 UTC, bre1470 approved these changes
Thank you! Looks good. 👍

2024-02-15 09:29 UTC, merged