feature/17240-orgchart-rtl-hanging-lines
highcharts/highcharts pull request #20504
Opened 2024-01-23 12:30 UTC by Xillez

Added #17240, option `hangingRight` which allows nodes to hang from the right side in inverted organization charts.

---

Asana task: https://app.asana.com/0/1204848917817812/1206243178116085/f

Also, added tests for both:
- Hanging lines (Shrink + Left side, Cumulative + Left side, Shrink + Right side, Cumulative + Right side).
- Bug where nodes don't drop in non-inverted organization chart (both "shrink" and "cumulative").

However, I wanted to mention this seems to add another issue with nodes being cut off by the plot area:
https://github.com/highcharts/highcharts/assets/5503724/68da3dea-3816-4e14-938c-6f12d29a7128
I'm unsure of whether this is within the scope of the task to fix?
It can be avoided by switching to "shrink".

2024-01-23 12:33 UTC, circleci-mu commented
### File size comparison
No differences found

2024-01-23 12:33 UTC, circleci-mu commented
## Visual test results - No difference found

2024-01-23 14:35 UTC, bre1470 commented
For me one of the unit tests is failing in Firefox because of a slightly different SVG path than expected.

Regarding the similar issue, it might be better to have this in a separate PR, just to be safe in case it evolves into something different of a solution.

2024-01-24 07:38 UTC, Xillez commented
I'll check out the unit test!

The fix is very very simple, but for sure, I can separate them 👍

2024-01-24 12:50 UTC, Xillez commented
I did a test and found that the node [clipping issue](https://github.com/highcharts/highcharts/assets/5503724/68da3dea-3816-4e14-938c-6f12d29a7128) mentioned is also present in master branch. I'll make an issue so it can be fixed separately if that is fine.

2024-01-26 10:43 UTC, TorsteinHonsi requested changes
Thanks!

The code looks great, nothing to add there.

* When it comes to the name of the new option, I think `hangingRight` as a boolean is a bit out of place. Usually when it comes to alignment we have enum-like string options like `align: 'left'|'center'|'right'`. So in this case I think we should rename (and refactor) the option to `hangingSide: 'left'|'right'`, with default value `left`. 
* Sample. We should have a visual sample, linked from the API doclet. Maybe using a real rtl is a bit hard for us, but a simple way to do it would be just to copy the `hanging-shrink` demo and do some minor changes to it to display the new feature. It will double as an educational sample and a visual test.

2024-01-29 11:23 UTC, TorsteinHonsi requested changes
Thanks! Just a minor change now and it's a green light from me 👍

2024-01-29 11:23 UTC, TorsteinHonsi commented on samples/highcharts/series-organization/hanging-right/demo.css
The sample should also be renamed to `hanging-side`

2024-01-29 11:23 UTC, TorsteinHonsi commented on ts/Series/Organization/OrganizationSeriesDefaults.ts
> +     * @sample highcharts/series-organization/hanging-right
Remember to change the @sample link here too

2024-01-30 09:43 UTC, merged