Docs: Comprehensive renderer tutorial
highcharts/highcharts pull request #20527
Opened 2024-01-26 07:47 UTC by TorsteinHonsi

2024-01-26 07:50 UTC, circleci-mu commented
### File size comparison
No differences found

2024-01-26 07:54 UTC, circleci-mu commented
## Visual test results - Differences found
Found **2** diffing sample(s). [Please review the differences.](https://vrevs.highsoft.com/pr/20527/review)


---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  Added | samples/highcharts/members/addevent/demo.js |
|  Modified | samples/highcharts/members/renderer-basic/demo.js |
|  Modified | samples/highcharts/members/renderer-on-chart/demo.js |

</p>
</details>

2024-01-29 13:42 UTC, raf18seb approved these changes
Nice and clean! Nothing to add 👏

2024-01-30 10:16 UTC, KacperMadej requested changes
The new doc page looks easy to understand 👍

2024-01-30 10:16 UTC, KacperMadej commented on docs/advanced-chart-features/renderer.md
> +```
Why this code block is not marked as JS with **```js** ?

2024-01-30 10:16 UTC, KacperMadej commented on ts/Core/Renderer/SVG/SVGElement.ts
> + * https://www.highcharts.com/docs/advanced-chart-features/boost-module) for a
Shouldn't this be linked to the renderer docs?

2024-01-30 10:16 UTC, KacperMadej commented on ts/Core/Renderer/SVG/SVGRenderer.ts
> + * https://www.highcharts.com/docs/advanced-chart-features/boost-module) for a
Shouldn't this be linked to the renderer docs?

2024-01-30 12:13 UTC, merged