bugfix/19808-ordinal-rangeselector-states
highcharts/highcharts pull request #20522
Opened 2024-01-25 12:47 UTC by kamil-musialowski

_work in progress_

2024-01-25 12:50 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highstock.js | **128.3 kB**<br>371.4 kB | **128.4 kB**<br>371.6 kB | **66 B**<br>215 B |
| highcharts-gantt.js | **130.5 kB**<br>376.2 kB | **130.6 kB**<br>376.4 kB | **74 B**<br>215 B |
| modules/accessibility.js | **44.2 kB**<br>154.8 kB | **44.3 kB**<br>155.0 kB | **82 B**<br>215 B |

2024-01-25 12:54 UTC, circleci-mu commented
## Visual test results - Differences found
Found **29** diffing sample(s). [Please review the differences.](https://vrevs.highsoft.com/pr/20522/review)

2024-01-25 13:14 UTC, circleci-mu commented
## Benchmark report - Stock
### benchmarks/Stock/Stock-Base.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 1000000 | 6850.85 | 6809.36 | -41.49 | -0.01%

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 1000 | 287.08 | 282.55 | -4.54 | -0.02%
| 10000 | 394.95 | 390.65 | -4.29 | -0.01%
| 100000 | 1027.89 | 1035.38 | 7.48 | 0.01%
| 1000000 | 6850.85 | 6809.36 | -41.49 | -0.01%


</details>

### benchmarks/Stock/Stock-DataGrouping.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 1000000 | 1779.74 | 1791.08 | 11.35 | 0.01%

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 1000 | 276.11 | 278.03 | 1.92 | 0.01%
| 10000 | 317.36 | 314.09 | -3.27 | -0.01%
| 100000 | 529.22 | 533.52 | 4.3 | 0.01%
| 1000000 | 1779.74 | 1791.08 | 11.35 | 0.01%


</details>

### benchmarks/Stock/Stock-Ordinal.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 1000000 | 2198.18 | 2187.05 | -11.13 | -0.01%

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 1000 | 287.75 | 287.33 | -0.42 | 0%
| 10000 | 332.44 | 333.3 | 0.86 | 0%
| 100000 | 641.49 | 641.74 | 0.25 | 0%
| 1000000 | 2198.18 | 2187.05 | -11.13 | -0.01%


</details>

### benchmarks/Stock/Stock-DataGrouping-Ordinal.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 1000000 | 2207.01 | 2188.86 | -18.15 | -0.01%

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 1000 | 282.69 | 284.6 | 1.91 | 0.01%
| 10000 | 330.27 | 336.64 | 6.36 | 0.02%
| 100000 | 643.14 | 651.41 | 8.28 | 0.01%
| 1000000 | 2207.01 | 2188.86 | -18.15 | -0.01%


</details>

2024-01-29 11:55 UTC, TorsteinHonsi approved these changes
Awesome, thanks!

PS: @kamil-musialowski Should this PR be marked Ready to review?

2024-01-29 11:56 UTC, pawelfus requested changes

2024-01-29 11:56 UTC, pawelfus commented on samples/unit-tests/rangeselector/buttons-range-state/demo.js
> +        [1706505600000, 1],    // 29.01
Unsorted data?

2024-01-29 13:17 UTC, bm64 approved these changes

2024-01-29 14:29 UTC, pawelfus approved these changes
Thanks!

2024-02-01 07:19 UTC, pawellysy approved these changes
LGTM

2024-02-01 09:51 UTC, merged