dash/20557-hidden-caption-bug
highcharts/highcharts pull request #20565
Opened 2024-01-31 21:01 UTC by Vazonik

Fixed #20557, incorrect calculation of component content height when caption is defined.

2024-01-31 21:04 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| dashboards/dashboards.js | **40.0 kB**<br>142.3 kB | **40.0 kB**<br>142.3 kB | **4 B**<br>2 B |

2024-01-31 21:05 UTC, circleci-mu commented
## Dashboard visual diffs
No differences found

2024-01-31 21:05 UTC, circleci-mu commented
## Lighthouse report
### dashboards-demo-minimal.json
|   | Reference | Proposed | Diff |
| :---- | ------ | ----- | ----- |
| performance – score | 1 | 1 | 0.00 |
| first-contentful-paint – score | 1 | 1 | 0.00 |
| first-contentful-paint – milliseconds | 190.22 | 188.45 | -1.77 |
| first-meaningful-paint – score | 1 | 1 | 0.00 |
| first-meaningful-paint – milliseconds | 516.58 | 518.56 | 1.98 |
| dom-size – score | 1 | 1 | 0.00 |
| dom-size – elements | 349 | 349 | 0.00 |

2024-01-31 21:08 UTC, circleci-mu commented
## Visual test results - No difference found

2024-01-31 21:23 UTC, circleci-mu commented
## Benchmark report - Dashboards
### benchmarks/Dashboards/DataTable-loading-rows.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 2500000 | 793.96 | 798.54 | 4.58 | 0.01%

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 100 | 0.28 | 0.28 | 0.01 | 0.03%
| 1000 | 0.53 | 0.51 | -0.02 | -0.04%
| 10000 | 2.78 | 2.91 | 0.13 | 0.05%
| 100000 | 16.08 | 16.28 | 0.19 | 0.01%
| 1000000 | 310.85 | 309.05 | -1.8 | -0.01%
| 2500000 | 793.96 | 798.54 | 4.58 | 0.01%


</details>

### benchmarks/Dashboards/DataTable-loading-columns.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 2500000 | 16.6 | 16.71 | 0.12 | 0.01%

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 100 | 0.23 | 0.23 | 0 | -0.01%
| 1000 | 0.24 | 0.24 | 0 | -0.02%
| 10000 | 0.27 | 0.27 | -0.01 | -0.02%
| 100000 | 2.31 | 2.27 | -0.04 | -0.02%
| 1000000 | 8.79 | 8.73 | -0.06 | -0.01%
| 2500000 | 16.6 | 16.71 | 0.12 | 0.01%


</details>

### benchmarks/Dashboards/DataPool-CSV-constructor.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 2500000 | 0.16 | 0.16 | 0 | 0.01%

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 100 | 0.16 | 0.16 | 0 | 0.01%
| 1000 | 0.16 | 0.16 | 0 | 0.01%
| 10000 | 0.16 | 0.16 | 0 | -0.01%
| 100000 | 0.16 | 0.16 | 0 | 0%
| 1000000 | 0.16 | 0.16 | 0 | 0%
| 2500000 | 0.16 | 0.16 | 0 | 0.01%


</details>

2024-02-01 07:11 UTC, karolkolodziej requested changes
Are we able to test somehow if the elements are visible? 
I know that they exist but it will be good to test if they are visible 🤔

2024-02-01 12:07 UTC, karolkolodziej approved these changes

2024-02-01 13:39 UTC, jomar-honsi approved these changes

2024-02-02 09:15 UTC, sebastianbochan approved these changes

2024-02-02 09:16 UTC, sebastianbochan requested changes
The cypress test is broken

2024-02-05 09:17 UTC, sebastianbochan approved these changes

2024-02-05 09:17 UTC, merged