bugfix/rangeselector-unnecessary-redraw
highcharts/highcharts pull request #20601
Opened 2024-02-07 13:52 UTC by pawellysy

Fixed #20214, `RangeSelector#render` was unnecessarily called 3 times on each chart render.

2024-02-07 13:57 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highstock.js | **127.3 kB**<br>368.1 kB | **127.2 kB**<br>367.8 kB | **-85 B**<br>-275 B |
| highcharts-gantt.js | **129.8 kB**<br>374.1 kB | **129.7 kB**<br>373.8 kB | **-89 B**<br>-275 B |

2024-02-07 14:00 UTC, circleci-mu commented
## Visual test results - No difference found

2024-02-15 13:18 UTC, bm64 approved these changes
Just one thing, otherwise looks good.

2024-02-15 13:18 UTC, bm64 commented on ts/Stock/RangeSelector/RangeSelector.ts
> +    public dupa!: string;
I don't think it's meant to be here 😅

2024-02-16 11:42 UTC, kamil-musialowski approved these changes
🚀

2024-02-16 12:10 UTC, pawelfus requested changes
See visual issues + perf (current one is slower by ~50%?)

2024-02-29 09:59 UTC, DJTechnoo commented on samples/unit-tests/chart/stockchart-update/demo.js
>              '6 range selector buttons'
Maybe rephrase it like "Range selector should have 6 buttons."

2024-02-29 10:17 UTC, DJTechnoo approved these changes
Just a thing of small significance, looks good!

2024-03-11 11:58 UTC, circleci-mu commented
## Webpack monitoring
LGTM :+1:

2024-04-25 14:16 UTC, pawelfus approved these changes
That's a big ✅!

Regarding visual diffs:
- I'm okay with black-and-white demo and arrow placements changes, unless Torstein says otherwise
- Not sure about the timezone one. Looks unrelated, can't recreate locally. But somehow it looks familiar..

2024-04-26 07:46 UTC, TorsteinHonsi requested changes
Thanks, great work 👏 

The timezone visual diff is real though. If you open http://localhost:3030/samples/#view/stock/time/individual, you'll see an Error 34 in the console. This doesn't happen on the master.

It can be debugged by putting a debugger statement inside the catch here:

https://github.com/highcharts/highcharts/blob/3c6838c543cb52974f1c6ff5518148ceafd62bd1/ts/Core/Time.ts#L439-L441

I traced it back to `getYTDExtremes` and `updateButtonStates`, where `dataMin` and `dataMax` are undefined, ultimately causing the error when trying to compute timezones for undefined.

2024-05-07 06:57 UTC, TorsteinHonsi approved these changes

2024-05-07 08:30 UTC, pawelfus approved these changes
Thanks!

2024-05-07 10:19 UTC, merged