demo/non-geo-map
highcharts/highcharts pull request #20639
Opened 2024-02-16 17:13 UTC by KacperMadej

Added a cinema seat plan demo.

2024-02-16 17:16 UTC, circleci-mu commented
### File size comparison
No differences found

2024-02-16 17:20 UTC, circleci-mu commented
## Visual test results - No difference found

---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  Added | samples/maps/demo/cinema-seat-plan/demo.js |

</p>
</details>

2024-02-19 11:58 UTC, hubertkozik reviewed
Some inline comments are below and some are here.

- [ ] For a few themes, e.g. BrandDark 'Click to select' label is touching the 'Stage':

<img width="973" alt="image" src="https://github.com/highcharts/highcharts/assets/62724907/99317055-3477-4b70-a749-49aef6196868">

- [ ] Mobile view is a little bit broken: 
<img width="488" alt="image" src="https://github.com/highcharts/highcharts/assets/62724907/0b0217ac-f978-4205-9c41-a9efb87524d1">

- [ ] Exporting to jpg etc. doesn't respect the rotated HTML data labels. I think it can be fixed by using non-HTML data labels with built-in rotation.

2024-02-20 14:12 UTC, KacperMadej commented on samples/maps/demo/cinema-seat-plan/demo.details
> +js_wrap: b
I will add this, although most demos don't have it.

2024-02-21 07:00 UTC, marvin19 requested changes

2024-02-21 07:00 UTC, marvin19 commented on samples/maps/demo/cinema-seat-plan/demo.js
> +        type: 'mappoint',
add `series.accessibility.enabled.false = true` to hide series for row & screen labels from screen readers. Modify `accessibility.point.descriptionFormat` instead

2024-02-21 07:05 UTC, marvin19 reviewed
Can you also add:
`accessibility.typeDescription: 'Map of cinema seat plan.'`

2024-02-23 11:49 UTC, marvin19 approved these changes
Looks good!

2024-02-26 13:01 UTC, TorsteinHonsi approved these changes
Thanks, looks good!

2024-02-26 13:01 UTC, merged

2024-02-28 13:59 UTC, TorsteinHonsi commented on samples/maps/demo/cinema-seat-plan/demo.js
> +        }
We should be able to express this as a string format.

2024-02-28 13:59 UTC, TorsteinHonsi commented on samples/maps/demo/cinema-seat-plan/demo.js
> +        }()),
This code is quite complex and intimidating. Bearing in mind that the purpose of the demos are to show the public how easy it is to create cool visualizations with Highcharts, I think it is better that we simplify it. Maybe a loop for the rotation is needed, but the array for taken seats I think should be just defined static in the data set.

2024-02-29 10:47 UTC, KacperMadej commented
Addressed in https://github.com/highcharts/highcharts/pull/20745