demo/org-hanging-lines
highcharts/highcharts pull request #20633
Opened 2024-02-15 07:57 UTC by Xillez

Added Germanic language tree organization chart demo feat. hanging lines.

---

Asana task: https://app.asana.com/0/1204848917817812/1206408652981595/f

2024-02-15 08:00 UTC, circleci-mu commented
### File size comparison
No differences found

2024-02-15 08:00 UTC, circleci-mu commented
## Visual test results - No difference found

2024-02-15 08:37 UTC, MarkusBarstad approved these changes
Good job!

2024-02-15 15:39 UTC, MarkusBarstad commented
Just 2 things I forgot to check and tell you during the review @Xillez but they are no biggies:

- it would be good to assign yourself to this PR, 
- and add the label `Changelog: Feature` so the changelog will list this new feature

2024-02-19 15:17 UTC, KacperMadej requested changes
- [x] By default dataLabels have `useHTML:true1` so tooltip will be under them. Fixable by e.g. `tooltip.outside:true`.
![image](https://github.com/highcharts/highcharts/assets/8960408/3f006b99-1f20-4ec4-bb35-1b07733012f7)

- [ ] The series name in the tooltip could be improved (set the series name or edit the tooltip header format to display nothing/something instead of "Series 1")

2024-02-20 11:53 UTC, Xillez commented on samples/highcharts/demo/organization-hanging/demo.css
> +    border: 1px solid silver;
Sorry, kinda forgot to check the css 😅

2024-02-23 10:48 UTC, KacperMadej approved these changes

2024-02-26 12:58 UTC, TorsteinHonsi reviewed
Thanks!

But, where's the German language? In other trees it is positioned close to Dutch, then there's the Frisian language close to English. Seems a bit skewed when we list 6 variations of Dutch but no German at all 🇩🇪 

Other than that, the demo is perfect, fitting on mobile and all.

2024-03-06 08:13 UTC, TorsteinHonsi approved these changes
Thanks! Pending review from @marvin19

2024-03-11 07:19 UTC, marvin19 approved these changes
Looks good!

2024-03-11 08:08 UTC, merged