dash/v2-fixed-tests
highcharts/highcharts pull request #20670
Opened 2024-02-20 13:10 UTC by sebastianbochan

2024-02-20 13:14 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| dashboards/dashboards.js | **40.0 kB**<br>142.6 kB | **42.4 kB**<br>144.8 kB | **2495 B**<br>2287 B |

2024-02-20 13:14 UTC, circleci-mu commented
## Lighthouse report
### dashboards-demo-minimal.json
|   | Reference | Proposed | Diff |
| :---- | ------ | ----- | ----- |
| performance – score | 1 | 1 | 0.00 |
| first-contentful-paint – score | 1 | 1 | 0.00 |
| first-contentful-paint – milliseconds | 189.74 | 188.05 | -1.69 |
| first-meaningful-paint – score | 1 | 1 | 0.00 |
| first-meaningful-paint – milliseconds | 513.99 | 441.09 | -72.90 |
| dom-size – score | 1 | 1 | 0.00 |
| dom-size – elements | 350 | 340 | -10.00 |

2024-02-20 13:15 UTC, circleci-mu commented
## Dashboard visual diffs
Visual differences found in: 
* /home/runner/work/highcharts/highcharts/cypress/snapshots/actual/test/cypress/dashboards/visual/dashboard-climate-edit-mode.png
* /home/runner/work/highcharts/highcharts/cypress/snapshots/actual/test/cypress/dashboards/visual/dashboard-climate-loaded.png
* /home/runner/work/highcharts/highcharts/cypress/snapshots/actual/test/cypress/dashboards/visual/dashboard-climate-mobile-horizontal.png
* /home/runner/work/highcharts/highcharts/cypress/snapshots/actual/test/cypress/dashboards/visual/dashboard-climate-mobile-vertical.png
* /home/runner/work/highcharts/highcharts/cypress/snapshots/actual/test/cypress/dashboards/visual/dashboards-demo-minimal-loaded.png
* /home/runner/work/highcharts/highcharts/cypress/snapshots/actual/test/cypress/dashboards/visual/dashboards-demo-minimal-mobile-horizontal.png
* /home/runner/work/highcharts/highcharts/cypress/snapshots/actual/test/cypress/dashboards/visual/dashboards-demo-minimal-mobile-vertical.png

 See artifacts in [the run summary](https://github.com/highcharts/highcharts/actions/runs/7974028378) for screenshots

2024-02-20 13:17 UTC, circleci-mu commented
## Visual test results - No difference found

---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  Modified | samples/stock/demo/black-and-white/demo.js |
|  Modified | samples/stock/demo/black-and-white/demo.js |
|  Modified | samples/stock/demo/black-and-white/demo.js |
|  Modified | samples/stock/demo/black-and-white/demo.js |
|  ? | samples/stock/demo/stock-design-black-and-white/demo.js |
|  Modified | samples/stock/demo/stock-design-black-and-white/demo.js |
|  Modified | samples/stock/demo/stock-design-black-and-white/demo.js |
|  Added | samples/stock/demo/stock-design-black-and-white/demo.js |
|  Modified | samples/highcharts/website/static-editor/demo.js |
|  Modified | samples/highcharts/data-tools/csv-modifiers/demo.js |
|  Modified | samples/highcharts/data-tools/datapool-json-connector-dataurl/demo.js |
|  Modified | samples/highcharts/data-tools/datapool-json-connector-enable-polling/demo.js |
|  Modified | samples/highcharts/data-tools/datapool-json-connector-orientation/demo.js |
|  Modified | samples/highcharts/data-tools/datapool-json-connector/demo.js |
|  Modified | samples/highcharts/website/small-demos-dashboards/demo.js |
|  Modified | samples/highcharts/website/static-dashboard/demo.js |
|  Modified | samples/highcharts/website/static-editor/demo.js |

</p>
</details>

2024-02-20 13:33 UTC, circleci-mu commented
## Benchmark report - Dashboards
### benchmarks/Dashboards/DataTable-loading-rows.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 2500000 | 817.79 | 817.02 | -0.77 | 0%

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 100 | 0.29 | 0.29 | 0 | 0%
| 1000 | 0.52 | 0.51 | -0.01 | -0.0002%
| 10000 | 2.87 | 2.99 | 0.11 | 0.0004%
| 100000 | 16.89 | 16.12 | -0.77 | -0.0005%
| 1000000 | 316.12 | 315.97 | -0.15 | 0%
| 2500000 | 817.79 | 817.02 | -0.77 | 0%


</details>

### benchmarks/Dashboards/DataTable-loading-columns.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 2500000 | 16.67 | 17.15 | 0.48 | 0.0003%

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 100 | 0.24 | 0.24 | 0 | 0.0001%
| 1000 | 0.24 | 0.25 | 0.01 | 0.0004%
| 10000 | 0.28 | 0.29 | 0.01 | 0.0002%
| 100000 | 2.3 | 2.26 | -0.03 | -0.0001%
| 1000000 | 9.19 | 9.07 | -0.12 | -0.0001%
| 2500000 | 16.67 | 17.15 | 0.48 | 0.0003%


</details>

### benchmarks/Dashboards/DataPool-CSV-constructor.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 2500000 | 0.17 | 0.17 | 0 | 0.0002%

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 100 | 0.17 | 0.16 | 0 | -0.0002%
| 1000 | 0.17 | 0.17 | 0 | 0.0003%
| 10000 | 0.17 | 0.17 | 0 | 0.0001%
| 100000 | 0.17 | 0.17 | 0 | -0.0001%
| 1000000 | 0.18 | 0.17 | -0.01 | -0.0005%
| 2500000 | 0.17 | 0.17 | 0 | 0.0002%


</details>

2024-02-20 13:39 UTC, Vazonik approved these changes

2024-02-20 13:54 UTC, karolkolodziej requested changes

2024-02-20 13:54 UTC, karolkolodziej commented on ts/Dashboards/Actions/Bindings.ts
> +        const currentBoard = board || cell?.row?.layout.board;
Wouldn't it be easier to have a `board` as a required argument? We will get rid of a lot of question marks and checks.

2024-02-21 06:40 UTC, karolkolodziej approved these changes

2024-02-21 08:52 UTC, jomar-honsi approved these changes

2024-02-21 09:10 UTC, merged