Samples/area stacked inverted
highcharts/highcharts pull request #20696
Opened 2024-02-22 12:11 UTC by AndersHonsi

Created new sample for stacked inverted area.

2024-02-22 12:13 UTC, TorsteinHonsi commented
This PR is part of a school project under my guidance. Internal [Asana reference](https://app.asana.com/0/1203542399740129/1203770998738599).

2024-02-22 12:13 UTC, circleci-mu commented
### File size comparison
No differences found

2024-02-22 12:18 UTC, circleci-mu commented
## Visual test results - No difference found

---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  Modified | samples/highcharts/demo/area-stacked-inverted/demo.js |
|  Added | samples/highcharts/demo/area-stacked-inverted/demo.js |

</p>
</details>

2024-02-27 10:28 UTC, marvin19 requested changes
Great job! A few comments:
- I think the `dataLabels` are not in the place where they are supposed to be. The O2 should e.g be inside of the purple series.
![Screenshot 2024-02-27 at 11 10 30](https://github.com/highcharts/highcharts/assets/14174575/330de8e0-80ce-4523-a8da-4319e3099986)
- The `marker` on hover disappears a bit in the lighter series. I would change it to a darker color. What are your thoughts on this @TorsteinHonsi . Can the marker be the same color or should it have different colors then?
- The same goes for the text in the `tooltip`. The lightest colors are not very readable. I would aim for a 4.5:1 contrast for text in the `tooltip`.

2024-02-27 11:44 UTC, marvin19 commented
> It was fixed in another PR prior to creating this - did you remember to gulp?

Works after `gulp`👌🏻

2024-02-27 12:27 UTC, marvin19 approved these changes

2024-02-27 13:56 UTC, merged