dash/fixed-height-htmlcomponent
highcharts/highcharts pull request #20705
Opened 2024-02-23 10:38 UTC by sebastianbochan

Fixed bug in height of html component.

2024-02-23 10:41 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| dashboards/dashboards.js | **40.0 kB**<br>142.6 kB | **42.7 kB**<br>146.1 kB | **2801 B**<br>3534 B |

2024-02-23 10:43 UTC, circleci-mu commented
## Dashboard visual diffs
Visual differences found in: 
* /home/runner/work/highcharts/highcharts/cypress/snapshots/actual/test/cypress/dashboards/visual/dashboard-climate-edit-mode.png
* /home/runner/work/highcharts/highcharts/cypress/snapshots/actual/test/cypress/dashboards/visual/dashboard-climate-loaded.png
* /home/runner/work/highcharts/highcharts/cypress/snapshots/actual/test/cypress/dashboards/visual/dashboard-climate-mobile-horizontal.png
* /home/runner/work/highcharts/highcharts/cypress/snapshots/actual/test/cypress/dashboards/visual/dashboard-climate-mobile-vertical.png
* /home/runner/work/highcharts/highcharts/cypress/snapshots/actual/test/cypress/dashboards/visual/dashboards-demo-minimal-loaded.png
* /home/runner/work/highcharts/highcharts/cypress/snapshots/actual/test/cypress/dashboards/visual/dashboards-demo-minimal-mobile-horizontal.png
* /home/runner/work/highcharts/highcharts/cypress/snapshots/actual/test/cypress/dashboards/visual/dashboards-demo-minimal-mobile-vertical.png

 See artifacts in [the run summary](https://github.com/highcharts/highcharts/actions/runs/8017996475) for screenshots

2024-02-23 10:43 UTC, circleci-mu commented
## Lighthouse report
### dashboards-demo-minimal.json
|   | Reference | Proposed | Diff |
| :---- | ------ | ----- | ----- |
| performance – score | 1 | 1 | 0.00 |
| first-contentful-paint – score | 1 | 1 | 0.00 |
| first-contentful-paint – milliseconds | 215.76 | 188.92 | -26.84 |
| first-meaningful-paint – score | 1 | 1 | 0.00 |
| first-meaningful-paint – milliseconds | 512.64 | 432.69 | -79.95 |
| dom-size – score | 1 | 1 | 0.00 |
| dom-size – elements | 350 | 340 | -10.00 |

2024-02-23 10:52 UTC, Vazonik requested changes
It seems that now the height of html elements is defined solely by its content. We should either set a fixed height in the demos or fix it here.

Bofore:
![image](https://github.com/highcharts/highcharts/assets/46498046/9b7e8712-0d3f-4622-8bf4-6172e67b2e10)

After:
![image](https://github.com/highcharts/highcharts/assets/46498046/dccdc506-b23a-4f66-bab7-34248e240e60)

2024-02-23 11:01 UTC, circleci-mu commented
## Benchmark report - Dashboards
### benchmarks/Dashboards/DataTable-loading-rows.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 2500000 | 805.86 | 813.8 | 7.94 | 0.0001%

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 100 | 0.29 | 0.28 | -0.01 | -0.0004%
| 1000 | 0.52 | 0.51 | 0 | -0.0001%
| 10000 | 2.87 | 3.22 | 0.34 | 0.0012%
| 100000 | 16.29 | 18.97 | 2.68 | 0.0016%
| 1000000 | 313.47 | 317.36 | 3.88 | 0.0001%
| 2500000 | 805.86 | 813.8 | 7.94 | 0.0001%


</details>

### benchmarks/Dashboards/DataTable-loading-columns.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 2500000 | 16.43 | 16.65 | 0.22 | 0.0001%

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 100 | 0.24 | 0.24 | 0 | -0.0001%
| 1000 | 0.24 | 0.24 | 0 | -0.0002%
| 10000 | 0.28 | 0.28 | -0.01 | -0.0002%
| 100000 | 2.3 | 2.48 | 0.19 | 0.0008%
| 1000000 | 9.13 | 9.03 | -0.09 | -0.0001%
| 2500000 | 16.43 | 16.65 | 0.22 | 0.0001%


</details>

### benchmarks/Dashboards/DataPool-CSV-constructor.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 2500000 | 0.17 | 0.17 | 0 | -0.0002%

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 100 | 0.17 | 0.17 | 0 | 0%
| 1000 | 0.17 | 0.17 | 0 | -0.0001%
| 10000 | 0.17 | 0.17 | 0 | 0%
| 100000 | 0.17 | 0.16 | -0.01 | -0.0006%
| 1000000 | 0.17 | 0.16 | 0 | -0.0003%
| 2500000 | 0.17 | 0.17 | 0 | -0.0002%


</details>

2024-02-23 12:04 UTC, sebastianbochan commented
In case when default height is 'auto', we should declare the `min-height` or `height` for the content of component too.

Good hint, thanks!

2024-02-23 17:34 UTC, jomar-honsi approved these changes

2024-02-26 10:14 UTC, Vazonik requested changes
I see that there is a problem, e.g. in demo `dashboards/components/component-html`:
![image](https://github.com/highcharts/highcharts/assets/46498046/b8368962-eccf-4caf-92ee-b20b4c4c4733)

2024-03-01 08:42 UTC, jomar-honsi approved these changes

2024-03-04 10:53 UTC, closed without merging