Fixed #20586 no spacing between css classes
highcharts/highcharts pull request #20708
Opened 2024-02-23 13:35 UTC by MarkusBarstad

Fixed #20586, there was no spacing between css classes.

2024-02-23 13:38 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| highcharts.js | **94.9 kB**<br>267.5 kB | **94.9 kB**<br>267.5 kB | **2 B**<br>1 B |
| highstock.js | **127.4 kB**<br>368.3 kB | **127.4 kB**<br>368.3 kB | **1 B**<br>1 B |
| highmaps.js | **120.6 kB**<br>346.5 kB | **120.6 kB**<br>346.5 kB | **2 B**<br>1 B |
| highcharts-gantt.js | **129.9 kB**<br>374.3 kB | **129.9 kB**<br>374.3 kB | **1 B**<br>1 B |

2024-02-23 13:42 UTC, circleci-mu commented
## Visual test results - No difference found

2024-03-11 07:25 UTC, marvin19 approved these changes

2024-03-15 12:37 UTC, TorsteinHonsi requested changes
Thanks! The fix is simple and spot on, but some work is needed on the PR description. See [Writing content for the changelog](https://github.com/highcharts/highcharts/tree/master/changelog#writing-content-for-the-changelog). Specificly rule no 7. In the current description the technical fix is described, but there is nothing in the description that indicates how it manifested. We should describe the symptoms we fix, not the technical details of the cure. In this case, the symptom was (am I right?) that plot line and plot band class names did not work.

Also, please set up a unit test for the issue. For a minor thing like this, it's sufficient to just reuse some other test. Add a class name then check the `element.classList` in the produced chart.

2024-03-15 14:32 UTC, TorsteinHonsi approved these changes

2024-03-15 14:32 UTC, merged