feature/17243 treemap parent header
highcharts/highcharts pull request #20714
Opened 2024-02-26 07:49 UTC by TorsteinHonsi

- Treemap headers: First commit, no area correction
- WIP Treemap headers: Area correction POC

2024-02-26 07:51 UTC, circleci-mu commented
### File size comparison
No differences found

2024-02-26 07:56 UTC, circleci-mu commented
## Visual test results - No difference found

---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  Modified | samples/highcharts/studies/treemap-headers/demo.js |
|  Added | samples/highcharts/studies/treemap-headers/demo.js |

</p>
</details>

2024-03-05 09:07 UTC, nishikantparmariam commented
Hi, adding some comments based on conversation with Henrik.

Reproducer: https://jsfiddle.net/6hqdna1y/8/

- Headers are overlapping with one another.
 
   ![image](https://github.com/highcharts/highcharts/assets/7736252/5e3356fc-ebca-44c7-8284-b7f2c507e883)

- The header is not occupying the entire space when there are multiple levels. Have we added multi-level support or addressed drilldown with header. This seems to happen when I drill down once and then drill up - 

  ![image](https://github.com/highcharts/highcharts/assets/7736252/fc6120c0-dca1-4849-b080-0af9fac9262c)
  ![image](https://github.com/highcharts/highcharts/assets/7736252/f9ddb545-578e-4ea5-b2cf-0aef71a69e28)

 


 
- Can a border also be added such that the header covers the child nodes:
  ![image](https://github.com/highcharts/highcharts/assets/7736252/73fe9ff0-6a22-42ac-96bf-b842de290836)
  Example - 
  ![image](https://github.com/highcharts/highcharts/assets/7736252/6da5a5a0-b3fe-4efe-9791-ba88f35c3fbd)

2024-03-05 09:42 UTC, TorsteinHonsi commented
Thanks @nishikantparmariam , I'll be sure to test those cases when we get that far. Right now I'm working on getting the adjusted area right when the area is too small for the header in the first place.

2024-03-06 18:01 UTC, circleci-mu commented
## Webpack monitoring
LGTM :+1:

2025-01-30 06:56 UTC, TorsteinHonsi commented
Hi again @nishikantparmariam, I've made some progress with this feature. Can you check out https://jsfiddle.net/highcharts/w5716nm2/ and test the updated library against your use case?

2025-02-07 13:28 UTC, TorsteinHonsi commented
@hubertkozik Review note: The Cypress test is failing, I think that's just a coincidence.

2025-02-14 10:28 UTC, hubertkozik reviewed
Something is wrong with the Visual Test of `treemap-grouping-advanced` demo. I think it's acceptable @TorsteinHonsi?

2025-02-14 10:51 UTC, hubertkozik requested changes
Bug: https://jsfiddle.net/BlackLabel/n0rak2v8/ First, the headers are shown correctly, but after traversing into (drill) and traversing up (drill up) the headers are lost.

2025-02-14 10:51 UTC, hubertkozik commented on ts/Series/Treemap/TreemapSeriesDefaults.ts
`headers`, `groupPadding`, `nodeSizeBy` are also showing in the docs for Treegraph series due to inheritance.

2025-02-14 10:51 UTC, hubertkozik commented on ts/Series/Treemap/TreemapSeries.ts
> +                if (width > 32 && height > 16 && point.shouldDraw()) {
Should those static numbers be configurable, or should they depend on font size?

2025-02-25 16:59 UTC, merged