demo/polar-btc-chart
highcharts/highcharts pull request #20733
Opened 2024-02-28 11:57 UTC by bm64

Added polar bitcoin demo.

2024-02-28 12:01 UTC, circleci-mu commented
## Visual test results - No difference found

2024-02-28 14:52 UTC, DJTechnoo reviewed
Looks great!

2024-02-28 14:53 UTC, DJTechnoo approved these changes

2024-02-29 09:06 UTC, pawellysy approved these changes
Nothing to add

2024-02-29 10:15 UTC, pawelfus approved these changes
Remaining questions:
- this demo could also be available under Highcharts categories, are you okay @TorsteinHonsi with placing it in the Stock-related category?
- reported two bugs, related to the background: https://github.com/highcharts/highcharts/issues/20743 and https://github.com/highcharts/highcharts/issues/20744 - I think plotBand workaround works better. Perhaps we should set a fixed max?

2024-02-29 12:17 UTC, kamil-musialowski approved these changes
Demo and code are great, just one hint.

If we hide the 2021 series (by legend click), then the dark blue background is hidden and the white labels are not visible. Can we make this background visible on both series?

2024-03-04 07:55 UTC, marvin19 requested changes
Really cool demo! 🤩 A few requests:
- Add `xAxis.accessibility.description` to a suitable name for the xAxis
- Add `yAxis.accessibility.description `to a suitable name for the yAxis
- Change the 0 to black font color or another color with more than 4.5:1 contrast to the yellow. It is good enough for 25k and 50k 👌🏻

2024-03-11 07:29 UTC, marvin19 approved these changes
Looks good!

2024-03-19 14:07 UTC, circleci-mu commented
## Webpack monitoring
LGTM :+1:

2024-03-19 15:04 UTC, pawelfus requested changes
Just one tiny thing

2024-03-19 15:04 UTC, pawelfus commented on samples/highcharts/blog/polar-btc/demo.html
> +<script src="https://code.highcharts.com/stock/modules/exporting.js"></script>
Sorry for the late nitpicking, but could you keep all modules to be loaded for HC? I mean, remove `stock` from URL

2024-03-20 08:29 UTC, TorsteinHonsi requested changes
Thanks! There are some lint errors now with the stricter lint rules.

2024-03-20 13:16 UTC, TorsteinHonsi approved these changes

2024-03-22 08:08 UTC, merged