dash/datagrid-improvements
highcharts/highcharts pull request #20732
Opened 2024-02-28 11:29 UTC by karolkolodziej

Made `datagrid` part of the dashboards.

2024-02-29 09:51 UTC, bre1470 requested changes
If there will be no NPM package for DataGrid, every reference to it can be removed and the existing `@highcharts/dashboards` reference used instead.

2024-02-29 09:51 UTC, bre1470 commented on ts/Dashboards/Plugins/DataGridTypes.ts
> +import type * as D from 'datagrid';
This has to be changed accordingly to the NPM distribution.

2024-02-29 09:51 UTC, bre1470 commented on test/typescript-dts/dashboards/tsconfig.json
> +            "datagrid/*": ["code/datagrid/*"],
Same here.

2024-02-29 12:36 UTC, bre1470 approved these changes
Thanks! LGTM 👍

2024-03-01 08:26 UTC, sebastianbochan approved these changes

2024-03-01 08:30 UTC, merged