Tools: Added CI workflow for webpack monitoring.
highcharts/highcharts pull request #20751
Opened 2024-02-29 13:29 UTC by bre1470

2024-02-29 14:04 UTC, circleci-mu commented
## Webpack monitoring
:rotating_light: Webpack tests failed. Check demos and masters!

2024-02-29 14:12 UTC, goransle approved these changes
LGTM 👍

2024-03-05 09:43 UTC, TorsteinHonsi approved these changes
Thanks!

2024-03-05 09:44 UTC, TorsteinHonsi requested changes
Please resolve conflicts, otherwise good to go.

2024-03-05 17:16 UTC, TorsteinHonsi approved these changes

2024-03-05 17:16 UTC, merged