Dash/election demo
highcharts/highcharts pull request #20772
Opened 2024-03-04 12:22 UTC by jomar-honsi

- PoC functionality
- Without React and Grid editing
- Responsiveness issues remain

2024-03-05 08:09 UTC, karolkolodziej requested changes
It doesn't look good on mobile/ipad:
![image](https://github.com/highcharts/highcharts/assets/57004120/cc3fc525-8c2f-4cfc-8716-4b5f9313f67f)

2024-03-05 08:48 UTC, sebastianbochan commented
1. Add some padding-bottom space
![Screenshot 2024-03-05 at 09 40 52](https://github.com/highcharts/highcharts/assets/2115686/510536fd-48cd-4f51-b65a-0654a9149b46)

2. Images are not good, I suggest using square images and applying `border-radius` to achieve a circle. 
![Screenshot 2024-03-05 at 09 40 41](https://github.com/highcharts/highcharts/assets/2115686/67f4efbb-d267-4e92-898b-eb311ae72ad4)

3. Datagrid is cut at the right edge
![Screenshot 2024-03-05 at 09 40 31](https://github.com/highcharts/highcharts/assets/2115686/ffe80b1c-8e54-47ce-95f3-d268964acf08)

I suggest applying a mobile style for 992px as well. The squeezed map and the column chart do not look good on the tablet.

2024-03-05 08:50 UTC, sebastianbochan requested changes

2024-03-06 08:32 UTC, jomar-honsi commented on samples/dashboards/demo/election/demo.css
> +    min-width: 40%;
> Can we replace min-width with `flex: 1`? It is better to apply margin on `.cell > .highcharts-dashboards-component`
> 
> I suggest taking a look at the rest of demos, which are updated to the newest v2.

Done

2024-03-06 08:34 UTC, jomar-honsi commented
> 1. Add some padding-bottom space
>    ![Screenshot 2024-03-05 at 09 40 52](https://private-user-images.githubusercontent.com/2115686/310043907-510536fd-48cd-4f51-b65a-0654a9149b46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MTQyMzksIm5iZiI6MTcwOTcxMzkzOSwicGF0aCI6Ii8yMTE1Njg2LzMxMDA0MzkwNy01MTA1MzZmZC00OGNkLTRmNTEtYjY1YS0wNjU0YTkxNDliNDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDZUMDgzMjE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTJhYjdkZjZiYjgyMWI0NmZmOGExZDY1ZTJkNjY4ZjdjMTFhMzAzNmRlZWRhNzkwMTdjN2QyM2RlMTkzZTg3MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._ygQ2aDOtVZg7QgEUxMS4LcJPq-nXGg1wOlQRu2Qw-Q)
> 2. Images are not good, I suggest using square images and applying `border-radius` to achieve a circle.
>    ![Screenshot 2024-03-05 at 09 40 41](https://private-user-images.githubusercontent.com/2115686/310043915-67f4efbb-d267-4e92-898b-eb311ae72ad4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MTQyMzksIm5iZiI6MTcwOTcxMzkzOSwicGF0aCI6Ii8yMTE1Njg2LzMxMDA0MzkxNS02N2Y0ZWZiYi1kMjY3LTRlOTItODk4Yi1lYjMxMWFlNzJhZDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDZUMDgzMjE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2ZiZGEzNDhlNzk4NjFiYTA0OTI1OTBhNjBlZGJhODI1M2M2YTBhNWVjZGU2NTVmMzQ2NGRkODExNzBmYzFiYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.UggU2T9yTIqlEFICUEw7hnhqFaYtZ0fITfdQLA4uGMg)
> 3. Datagrid is cut at the right edge
>    ![Screenshot 2024-03-05 at 09 40 31](https://private-user-images.githubusercontent.com/2115686/310043919-ffe80b1c-8e54-47ce-95f3-d268964acf08.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MTQyMzksIm5iZiI6MTcwOTcxMzkzOSwicGF0aCI6Ii8yMTE1Njg2LzMxMDA0MzkxOS1mZmU4MGIxYy04ZTU0LTQ3Y2UtOTVmMy1kMjY4OTY0YWNmMDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDZUMDgzMjE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjM5OGI3YzRjNWI1Nzk5MjlkNDNjNGZkNjJmZGI3YTQzZjM2ODljNjRmNTc4MzlmNmYyNzI2M2NlOGJjMDlhZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Ly_yIE9YkZItnGmTsXEmRBsRzbom0C1aBgJFjtlKreg)
> 
> I suggest applying a mobile style for 992px as well. The squeezed map and the column chart do not look good on the tablet.

Issue 1 and 3 fixed. Images changed to use 1:1, still working on scaling issue.

2024-03-06 08:34 UTC, jomar-honsi commented on samples/dashboards/demo/election/demo.css
> +        --highcharts-color-0: rgb(74, 131, 240);
Done

2024-03-06 08:35 UTC, jomar-honsi commented on samples/dashboards/demo/election/demo.js
> +/* eslint-disable max-len */
Removed

2024-03-06 08:39 UTC, jomar-honsi commented on samples/dashboards/demo/election/demo.css
> +#election-map .map-tooltip caption {
To be discussed, awaiting feedback from @nasin

2024-03-06 08:40 UTC, jomar-honsi commented
> It doesn't look good on mobile/ipad: ![image](https://private-user-images.githubusercontent.com/57004120/310026122-cc3fc525-8c2f-4cfc-8716-4b5f9313f67f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MTQyMzksIm5iZiI6MTcwOTcxMzkzOSwicGF0aCI6Ii81NzAwNDEyMC8zMTAwMjYxMjItY2MzZmM1MjUtOGMyZi00Y2ZjLTg3MTYtNGI1ZjkzMTNmNjdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDA4MzIxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhNWNiNjRlNzg4MDllN2IzNmU0NmY0YjJkOWM2NzgxMDhhNTVkZjljMjE5NWU1ZWI4NTkxNTkxZDY1NmUyNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZrlczVMBK4b42sad3o-ZN_cMjvMpdPcmVkhr7kPqezg)

Resolved (apart from image scaling issue).

2024-03-06 09:28 UTC, jomar-honsi commented on samples/dashboards/demo/election/demo.html
> +<xml id="xml-data-island">
I'm unable to reproduce the scroll issue. Could you provide some more details?

2024-03-06 10:09 UTC, karolkolodziej commented on samples/dashboards/demo/election/demo.html
> +<xml id="xml-data-island">
see:
![image](https://github.com/highcharts/highcharts/assets/57004120/4371771a-2753-4ce4-964c-74ce5fd45d7a)

2024-03-06 19:52 UTC, Vazonik reviewed
Looks promising! A few comments from me for now.

2024-03-06 19:52 UTC, Vazonik commented on samples/dashboards/demo/election/demo.html
> +</xml>
Missing trailing line.

2024-03-06 19:52 UTC, Vazonik commented on samples/dashboards/demo/election/demo.css
> +@media (max-width: 1200px) {
I wonder if it wouldn't be better to switch `@media` queries to `@container` in future demos. In this case, responsiveness would result from the width of the board, not the entire page. https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_containment/Container_queries

See others' input from the accounting demo: https://github.com/highcharts/highcharts/pull/20220#issuecomment-1958909467

And then mobile view in utils will also work.

2024-03-07 12:48 UTC, sebastianbochan commented
1. Spacings are not the same (mobile view)
![Screenshot 2024-03-07 at 13 45 53](https://github.com/highcharts/highcharts/assets/2115686/1bcddf83-ed12-463e-b575-a1240df4b645)

2. Missing padding below the text
![Screenshot 2024-03-07 at 13 45 36](https://github.com/highcharts/highcharts/assets/2115686/0779a42a-b531-4f33-9ec0-8b2b374bac9d)

3. How about this kind of style avatars? I suggest adding some more space (around central chart), increase border radius in avatars and remove the border around them.
![Screenshot 2024-03-07 at 13 44 52](https://github.com/highcharts/highcharts/assets/2115686/0fcc0c07-9db7-4aa6-a230-5432926998df)

2024-03-08 11:57 UTC, karolkolodziej requested changes
Candidates are not visible on mobile:
![image](https://github.com/highcharts/highcharts/assets/57004120/0217e5b0-e775-470e-a224-1294a1a7e691)

2024-03-12 16:21 UTC, circleci-mu commented
## Webpack monitoring
LGTM :+1:

2024-03-12 16:21 UTC, circleci-mu commented
### File size comparison
No differences found

2024-03-12 16:22 UTC, circleci-mu commented
## Lighthouse report
### dashboards-demo-minimal.json
|   | Reference | Proposed | Diff |
| :---- | ------ | ----- | ----- |
| performance – score | 1 | 1 | 0.00 |
| first-contentful-paint – score | 1 | 1 | 0.00 |
| first-contentful-paint – milliseconds | 187.93 | 188.06 | 0.13 |
| first-meaningful-paint – score | 1 | 1 | 0.00 |
| first-meaningful-paint – milliseconds | 454.7 | 447.52 | -7.18 |
| dom-size – score | 1 | 1 | 0.00 |
| dom-size – elements | 346 | 346 | 0.00 |

2024-03-12 16:22 UTC, circleci-mu commented
## Dashboard visual diffs
No differences found

2024-03-12 16:25 UTC, circleci-mu commented
## Visual test results - No difference found

2024-03-13 07:54 UTC, karolkolodziej requested changes
With a wider screen, the result bar is not visible:
![image](https://github.com/highcharts/highcharts/assets/57004120/35e4c0cd-1727-4966-82d6-cb6957f2256e)

2024-03-13 08:50 UTC, jomar-honsi commented
Fixed.

2024-03-13 08:51 UTC, jomar-honsi commented
Good catch!

2024-03-13 13:27 UTC, karolkolodziej approved these changes
Please check the alerts. Other than that looks good!

2024-03-18 10:41 UTC, sebastianbochan approved these changes
Should we have bolded the first row when scrolling?

![bold](https://github.com/highcharts/highcharts/assets/2115686/5f186c0e-0f6a-47db-96b9-f861b3751860)

Otherwise looks good 👍

2024-03-18 19:35 UTC, jomar-honsi commented
> Should we have bolded the first row when scrolling?
> 
> ![bold](https://private-user-images.githubusercontent.com/2115686/313642414-5f186c0e-0f6a-47db-96b9-f861b3751860.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3OTA3NTcsIm5iZiI6MTcxMDc5MDQ1NywicGF0aCI6Ii8yMTE1Njg2LzMxMzY0MjQxNC01ZjE4NmMwZS0wZjZhLTQ3ZGItOTZiOS1mODYxYjM3NTE4NjAuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMThUMTkzNDE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTQzN2E1OThjZjkyMzA1MWY5Mzc0MGEyOTU3YTM0M2U2NTI5YjM0ZDc2MmNhODY0OTY4OGM4NTdjMDY3YmEyMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.cuP84e2v20WJNrhhp4vN53RheP9MP17xi-bLfR-_lTc) [ ![bold](https://private-user-images.githubusercontent.com/2115686/313642414-5f186c0e-0f6a-47db-96b9-f861b3751860.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3OTA3NTcsIm5iZiI6MTcxMDc5MDQ1NywicGF0aCI6Ii8yMTE1Njg2LzMxMzY0MjQxNC01ZjE4NmMwZS0wZjZhLTQ3ZGItOTZiOS1mODYxYjM3NTE4NjAuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMThUMTkzNDE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTQzN2E1OThjZjkyMzA1MWY5Mzc0MGEyOTU3YTM0M2U2NTI5YjM0ZDc2MmNhODY0OTY4OGM4NTdjMDY3YmEyMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.cuP84e2v20WJNrhhp4vN53RheP9MP17xi-bLfR-_lTc) ](https://private-user-images.githubusercontent.com/2115686/313642414-5f186c0e-0f6a-47db-96b9-f861b3751860.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3OTA3NTcsIm5iZiI6MTcxMDc5MDQ1NywicGF0aCI6Ii8yMTE1Njg2LzMxMzY0MjQxNC01ZjE4NmMwZS0wZjZhLTQ3ZGItOTZiOS1mODYxYjM3NTE4NjAuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMThUMTkzNDE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTQzN2E1OThjZjkyMzA1MWY5Mzc0MGEyOTU3YTM0M2U2NTI5YjM0ZDc2MmNhODY0OTY4OGM4NTdjMDY3YmEyMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.cuP84e2v20WJNrhhp4vN53RheP9MP17xi-bLfR-_lTc) [ ](https://private-user-images.githubusercontent.com/2115686/313642414-5f186c0e-0f6a-47db-96b9-f861b3751860.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3OTA3NTcsIm5iZiI6MTcxMDc5MDQ1NywicGF0aCI6Ii8yMTE1Njg2LzMxMzY0MjQxNC01ZjE4NmMwZS0wZjZhLTQ3ZGItOTZiOS1mODYxYjM3NTE4NjAuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMThUMTkzNDE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTQzN2E1OThjZjkyMzA1MWY5Mzc0MGEyOTU3YTM0M2U2NTI5YjM0ZDc2MmNhODY0OTY4OGM4NTdjMDY3YmEyMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.cuP84e2v20WJNrhhp4vN53RheP9MP17xi-bLfR-_lTc)
> 
> Otherwise looks good 👍

Hmm., that was not the intention. The first row should only be bold when it shows the U.S. federal results. Any idea how to achieve this?

2024-03-19 08:55 UTC, sebastianbochan commented
@jomar-honsi you can use the data field.

I just committed it.

2024-03-19 09:21 UTC, jomar-honsi reviewed
Nice!

2024-03-25 15:42 UTC, Vazonik approved these changes
Great!

2024-04-16 13:56 UTC, stitot approved these changes

2024-04-16 13:59 UTC, merged