Created chart for stock point pushing comparison
highcharts/highcharts pull request #20794
Opened 2024-03-06 17:35 UTC by nasin

Hi
I made this point pushing comparison chart based on tests Black Label ran. It's for a new competitor comparison page.
<img width="1137" alt="stock-speed" src="https://github.com/highcharts/highcharts/assets/1271445/dd04ea04-4e73-45ac-9307-22c311240d42">

2024-03-06 17:36 UTC, circleci-mu commented
## Webpack monitoring
LGTM :+1:

2024-03-06 17:37 UTC, circleci-mu commented
### File size comparison
No differences found

2024-03-06 17:42 UTC, circleci-mu commented
## Visual test results - No difference found

---
<details>
<summary>Samples changed</summary><p>

| Change type | Sample |
| --- | --- |
|  Added | samples/highcharts/website/stock-speed-comparison/demo.js |

</p>
</details>

2024-03-07 08:09 UTC, TorsteinHonsi requested changes
Thanks, looks good!

Just a comment on the layout - we now have a plot area with a big blank space in the upper left. One way to exploit the screen real estate to the max would be to add the title (and maybe the legend) inside.

Just a suggestion, but something like this:
![Skjermbilde 2024-03-07 kl  09 08 38](https://github.com/highcharts/highcharts/assets/227836/bc2ae344-75f2-4ba6-98cf-eb6f09fd49fc)

```js
legend: {
        align: 'left',
        verticalAlign: 'top',
        floating: true,
        x: 20,
        y: 100,
        width: '50%'
    },
    title: {
        text: 'Point Pushing Comparison',
        align: 'left',
        floating: true,
        x: 30,
        y: 60
    },
    xAxis: {
        title: {
            text: 'Number of Points Pushed'
        },
        categories: ['10', '1000', '10000', '100000', '500000']
    },
    yAxis: {
        tickInterval: 5000,
        endOnTick: false,
        startOnTick: false,
        title: {
            text: 'Time (ms)'
        },
        opposite: true


    },
    ```

2024-06-10 17:39 UTC, nasin commented
Hi, I made the suggested edits (sorry for the long delay...other projects got in the way.)

2024-06-13 09:45 UTC, TorsteinHonsi approved these changes
Thanks!

2024-06-13 09:46 UTC, merged