dash/kpi-chart-height-decreasing
highcharts/highcharts pull request #20798
Opened 2024-03-07 10:58 UTC by ddragula

Fixed KPI chart height decreasing on displays with pixel ratio greater than 1.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1206783846736312

2024-03-07 14:56 UTC, karolkolodziej approved these changes

2024-03-08 08:56 UTC, sebastianbochan requested changes
![Screenshot 2024-03-07 at 15 56 53](https://github.com/highcharts/highcharts/assets/2115686/47952963-5643-42b4-b060-ed16d991aa45)

Demo: http://utils.highcharts.local/samples/#view/dashboards/components/component-html

2024-03-08 09:27 UTC, jomar-honsi approved these changes

2024-03-08 12:05 UTC, jomar-honsi approved these changes

2024-03-08 12:40 UTC, sebastianbochan approved these changes

2024-03-08 12:53 UTC, merged