dash/sync-docs-improvements
highcharts/highcharts pull request #20878
Opened 2024-03-18 18:10 UTC by Vazonik

Improved synchronization docs.

2024-03-18 18:13 UTC, circleci-mu commented
## Webpack monitoring
LGTM :+1:

2024-03-19 07:34 UTC, jomar-honsi requested changes

2024-03-19 07:34 UTC, jomar-honsi commented on docs/dashboards/html-component.md
>  If some of the HTML elements are used frequently or requires to be more customable, it is possible to create a custom component that will simplify the configuration. The custom component can be creat
requires -> require

2024-03-19 07:34 UTC, jomar-honsi commented on docs/dashboards/html-component.md
> +HTML Component is the only component that does not have predefined synchronization types for itself (mainly because it cannot be connected to data pool). However, you can define your own sync types a
Suggested rewrite: The HTML Component is the only component that does not support synchronization types.

2024-03-19 07:34 UTC, jomar-honsi commented on docs/dashboards/kpi-component.md
> +The KPI Component allows user to sync the component with other components in dashboards. You can find more information about it in the [sync chapter](https://www.highcharts.com/docs/dashboards/synchr
allows user -> _allows the user_ OR _allows users_

2024-03-19 07:34 UTC, jomar-honsi commented on docs/dashboards/navigator-component.md
> +The Navigator Component can be synced with other components in dashboards. Two synchronization types are predefined for the Navigator Component: [`crossfilter`](https://api.highcharts.com/dashboards/
... components in _dashboards_ ... Dashboards is a trade mark, so should arguably be written Dashboards.

2024-03-19 07:34 UTC, jomar-honsi commented on docs/dashboards/synchronize-components.md
> +To synchronize components you have to specify which event you want to synchronize between each component, as well as they have to use the same connector defined in the [dataPool](https://www.highchar
Long and cumbersome sentence, consider splitting it up.

2024-03-19 07:36 UTC, karolkolodziej requested changes

2024-03-19 07:36 UTC, karolkolodziej commented on docs/dashboards/html-component.md
> +HTML Component is the only component that does not have predefined synchronization types for itself (mainly because it cannot be connected to data pool). However, you can define your own sync types a
Technically `HTMLComponent extends Component ` which means that the connector can exist. 
So I'm not sure if the statement in the parentheses is true-[ see demo.](https://jsfiddle.net/BlackLabel/k9w5yoms/)

2024-03-19 08:32 UTC, karolkolodziej approved these changes

2024-03-19 08:50 UTC, sebastianbochan approved these changes

2024-03-19 09:19 UTC, jomar-honsi approved these changes

2024-03-20 11:07 UTC, stitot commented on docs/dashboards/html-component.md
> +If some of the HTML elements are used frequently or require to be more customable, it is possible to create a custom component that will simplify the configuration. The custom component can be create
customable = customizable

2024-03-20 11:07 UTC, stitot commented on docs/dashboards/kpi-component.md
> +The KPI Component allows users to sync the component with other components in dashboards. You can find more information about it in the [sync chapter](https://www.highcharts.com/docs/dashboards/synch
chapter = article

2024-03-20 11:07 UTC, stitot commented on docs/dashboards/navigator-component.md
> +The Navigator Component can be synced with other components in Dashboards. Two synchronization types are predefined for the Navigator Component: [`crossfilter`](https://api.highcharts.com/dashboards/
chapter = article

2024-03-20 11:07 UTC, stitot commented on docs/dashboards/datagrid-component.md
> +One of the many available options for the DataGrid Component is the [`sync` option](https://api.highcharts.com/dashboards/#interfaces/Dashboards_Components_DataGridComponent_DataGridComponentOptions.
chapter = article

2024-03-20 11:07 UTC, stitot commented on docs/dashboards/highcharts-component.md
> +One of the many available options for the Highcharts Component is the [`sync` option](https://api.highcharts.com/dashboards/#interfaces/Dashboards_Components_HighchartsComponent_HighchartsComponentOp
chapter = article

2024-03-21 06:05 UTC, stitot approved these changes

2024-03-21 09:10 UTC, jomar-honsi commented on docs/dashboards/kpi-component.md
> +The KPI Component allows users to sync the component with other components in dashboards. You can find more information about it in the [sync article](https://www.highcharts.com/docs/dashboards/synch
Knitpicking: Conistently write Dashboards with the first letter capitalised.

2024-03-21 09:11 UTC, jomar-honsi approved these changes

2024-03-21 09:38 UTC, merged