dash/unique-cell-id-warning
highcharts/highcharts pull request #20898
Opened 2024-03-20 13:43 UTC by sebastianbochan

Touch #20661, added warning when ids is duplicated.

2024-03-20 13:44 UTC, circleci-mu commented
## Visual test results - No difference found

2024-03-20 13:46 UTC, circleci-mu commented
## Webpack monitoring
LGTM :+1:

2024-03-20 13:46 UTC, circleci-mu commented
### File size comparison
Sizes for compiled+gzipped (bold) and compiled files.
| | master | candidate | difference |
|-------------|-------------:|-------------:|-------------:|
| dashboards/dashboards.js | **42.9 kB**<br>146.5 kB | **43.0 kB**<br>146.7 kB | **80 B**<br>140 B |

2024-03-20 13:47 UTC, circleci-mu commented
## Lighthouse report
### dashboards-demo-minimal.json
|   | Reference | Proposed | Diff |
| :---- | ------ | ----- | ----- |
| performance – score | 1 | 1 | 0.00 |
| first-contentful-paint – score | 1 | 1 | 0.00 |
| first-contentful-paint – milliseconds | 188 | 187.96 | -0.04 |
| first-meaningful-paint – score | 1 | 1 | 0.00 |
| first-meaningful-paint – milliseconds | 451.66 | 457.39 | 5.73 |
| dom-size – score | 1 | 1 | 0.00 |
| dom-size – elements | 346 | 346 | 0.00 |

2024-03-20 13:48 UTC, circleci-mu commented
## Dashboard visual diffs
Visual differences found in: 
* /home/runner/work/highcharts/highcharts/cypress/snapshots/actual/test/cypress/dashboards/visual/dashboards-demo-minimal-loaded.png

 See artifacts in [the run summary](https://github.com/highcharts/highcharts/actions/runs/8359975133) for screenshots

2024-03-20 14:06 UTC, circleci-mu commented
## Benchmark report - Dashboards
### benchmarks/Dashboards/DataTable-loading-rows.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 2500000 | 762.42 | 762.67 | 0.25 | 0%

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 100 | 0.3 | 0.3 | 0 | 0%
| 1000 | 0.52 | 0.53 | 0.01 | 0.0002%
| 10000 | 3.24 | 3.2 | -0.04 | -0.0001%
| 100000 | 16.18 | 16.17 | -0.01 | 0%
| 1000000 | 294.48 | 296.29 | 1.81 | 0.0001%
| 2500000 | 762.42 | 762.67 | 0.25 | 0%


</details>

### benchmarks/Dashboards/DataPool-CSV-constructor.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 2500000 | 0.17 | 0.17 | 0 | 0.0001%

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 100 | 0.17 | 0.17 | 0 | -0.0001%
| 1000 | 0.17 | 0.17 | 0 | 0.0001%
| 10000 | 0.17 | 0.17 | 0 | 0.0001%
| 100000 | 0.17 | 0.17 | 0 | 0%
| 1000000 | 0.17 | 0.17 | 0 | 0.0002%
| 2500000 | 0.17 | 0.17 | 0 | 0.0001%


</details>

### benchmarks/Dashboards/DataTable-loading-columns.bench.ts
| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 2500000 | 16.66 | 16.26 | -0.39 | -0.0002%

<details><summary>See all</summary>


| Sample size | Base avg (ms) | Actual avg (ms) | Diff | Percent diff |
| --- | --- | --- | --- | --- |
| 100 | 0.24 | 0.24 | 0 | 0.0001%
| 1000 | 0.25 | 0.25 | 0 | -0.0001%
| 10000 | 0.28 | 0.29 | 0.01 | 0.0002%
| 100000 | 2.33 | 2.32 | -0.01 | 0%
| 1000000 | 9.29 | 9.15 | -0.14 | -0.0002%
| 2500000 | 16.66 | 16.26 | -0.39 | -0.0002%


</details>

2024-03-20 15:05 UTC, jomar-honsi approved these changes

2024-03-21 07:37 UTC, karolkolodziej requested changes
- [x] See linter errors

2024-03-21 07:37 UTC, karolkolodziej commented on ts/Dashboards/Actions/Bindings.ts
> +                    'A few cells have the same id: `' + idOrElement +
I disagree, with this implementation, the components are going to be rendered. 

I would phrase it like this:
`Multiple cells have identical ID ("' + idOrElement + '"), potentially leading to unexpected behaviour. Ensure that each cell has a unique ID on the page.`

2024-03-21 08:09 UTC, stitot commented on ts/Dashboards/Actions/Bindings.ts
> +                    'A few cells have the same id: `' + idOrElement +
According to @sebastianbochan not all components will be rendered if there are identical ids in the same dashboard. All will be rendered only if identical ids across multiple dashboards. Anyways, your proposal is more general and catches any unidentified edge cases, so I like it better! Thanks!

2024-03-21 08:24 UTC, sebastianbochan commented on ts/Dashboards/Actions/Bindings.ts
> +                    'A few cells have the same id: `' + idOrElement +
I agree, so we have a solution! :) 

Thank you for suggestions!

2024-03-21 09:00 UTC, karolkolodziej approved these changes

2024-03-21 09:58 UTC, Vazonik approved these changes

2024-03-22 07:19 UTC, merged