dash/datagrid-docs-clarify
highcharts/highcharts pull request #20915
Opened 2024-03-25 11:40 UTC by karolkolodziej

Clarified the `DataGrid` in the documentation and improved demos.'

2024-03-25 11:43 UTC, circleci-mu commented
## Webpack monitoring
LGTM :+1:

2024-03-25 11:44 UTC, circleci-mu commented
### File size comparison
No differences found

2024-03-25 11:44 UTC, circleci-mu commented
## Lighthouse report
### dashboards-demo-minimal.json
|   | Reference | Proposed | Diff |
| :---- | ------ | ----- | ----- |
| performance – score | 1 | 1 | 0.00 |
| first-contentful-paint – score | 1 | 1 | 0.00 |
| first-contentful-paint – milliseconds | 187.57 | 188.55 | 0.98 |
| first-meaningful-paint – score | 1 | 1 | 0.00 |
| first-meaningful-paint – milliseconds | 444.07 | 454.46 | 10.39 |
| dom-size – score | 1 | 1 | 0.00 |
| dom-size – elements | 346 | 346 | 0.00 |

2024-03-25 11:45 UTC, circleci-mu commented
## Dashboard visual diffs
No differences found

2024-03-25 11:48 UTC, circleci-mu commented
## Visual test results - No difference found

2024-03-25 13:12 UTC, sebastianbochan approved these changes

2024-03-25 13:24 UTC, jomar-honsi commented on docs/datagrid/general.md
> +It can be a part of a dashboard or used as a standalone component.
There are several lint warnings, mainly regarding unused variables.

2024-03-25 13:25 UTC, jomar-honsi requested changes
There are several lint warnings, mainly regarding unused variables.

2024-03-25 15:37 UTC, Vazonik approved these changes

2024-03-26 07:42 UTC, jomar-honsi approved these changes

2024-03-26 08:41 UTC, stitot approved these changes

2024-03-26 08:41 UTC, stitot commented on docs/datagrid/general.md
> +It can be a part of a dashboard or used as a standalone component.
Change to "It can be a part of a dashboard or used as a standalone component, but requires a Dashboards license."

2024-03-26 09:16 UTC, jomar-honsi approved these changes

2024-03-26 09:23 UTC, merged