Added bitcoin historical sample data
highcharts/highcharts pull request #20980
Opened 2024-04-09 19:36 UTC by bm64

Added bitcoin sentiment analysis chart.

2024-04-17 17:11 UTC, kamil-musialowski approved these changes
Look and works really well 👏 
Does that mean, we should delete [this PR](https://github.com/highcharts/highcharts/pull/19511 )? @pawelfus

2024-04-18 09:20 UTC, DJTechnoo commented on samples/stock/demo/flags-general/demo.js
> +                    {series.name}: <b>{point.y:.2f}$</b><br/>`
For the dollar sign, it should be to the left of the value

2024-04-18 09:21 UTC, DJTechnoo approved these changes
Looking good! Approving, but could you see my small comment?

2024-04-23 14:13 UTC, pawelfus commented
> Look and works really well 👏 Does that mean, we should delete [this PR](https://github.com/highcharts/highcharts/pull/19511)? @pawelfus

Yes, we should. Nice catch!

2024-04-26 07:33 UTC, pawelfus approved these changes
Nice!

One suggestion: What do you think about adding simplified flags to the navigator (like 2nd, 3rd and 4th) and decreasing the initial range to 1y?

2024-04-26 07:33 UTC, pawelfus commented on samples/stock/demo/flags-general/demo.js
> +            overscroll: 31536000000 // 1 year
It seems you added extra space for flag? However, this makes RS buttons a bit useless on initial extremes. What do you think about changing this to one month, then removing 1M button from RS and setting `shape: 'squarepin'` for flags? So the connector is rendered in the middle of flag, not on the left edge

2024-04-26 07:33 UTC, pawelfus requested changes

2024-04-26 07:33 UTC, pawelfus commented on samples/stock/demo/flags-general/demo.js
> +                    {series.name}: <b>$${'{point.y:.2f}'}</b><br/>`
Please restore thousands separator ;)

2024-05-13 09:28 UTC, TorsteinHonsi approved these changes
Thanks!

2024-05-13 09:29 UTC, merged