bugfix/20560-arearange-hover-destroy
highcharts/highcharts pull request #20994
Opened 2024-04-11 12:53 UTC by hubertkozik

Fixed #20560, destroyed points in the area range series were wrongly used during mouse hover.

2024-04-12 05:36 UTC, goransle approved these changes
Looks good!

2024-04-12 11:05 UTC, TorsteinHonsi commented on ts/Core/Series/Point.ts
> +            halo.point.haloPath &&
```suggestion
            halo?.point?.haloPath &&
```

2024-04-12 11:05 UTC, TorsteinHonsi requested changes
Suggesting optional chaining, otherwise fine 👍

2024-04-16 08:23 UTC, TorsteinHonsi approved these changes

2024-04-16 08:23 UTC, merged