bugfix/20998-axis-left-dataLabels-overflow
highcharts/highcharts pull request #20993
Opened 2024-04-11 12:22 UTC by kamil-musialowski

Fixed #20998, data labels overflowed the plot area when the axis position was different from default.

2024-04-11 13:45 UTC, TorsteinHonsi requested changes
Thanks for the PR!

Please create an issue so that in the future we can see a description and replication of the bug. Here's a demo: https://jsfiddle.net/highcharts/as6xgo3b/

Also, we need to look at the broader picture. We are now fixing the overflow on the right side of the chart. But we need to look at related configs:
* Left side: https://jsfiddle.net/highcharts/as6xgo3b/1/
* Top and left sides: https://jsfiddle.net/highcharts/as6xgo3b/2/ 
* Wider and higher axes seem to be handled correctly: https://jsfiddle.net/highcharts/as6xgo3b/3/

2024-04-11 13:45 UTC, TorsteinHonsi commented on ts/Core/Series/DataLabel.ts
> +                this.yAxis?.horiz ? this.yAxis : void 0;
```suggestion
            horizontalAxis = chart.inverted ? this.yAxis : this.xAxis;
```
Simpler check

2024-04-12 07:31 UTC, pawelfus reviewed
Will that be a big problem to fix also overflow for bottom labels in a non-inverted chart? Like here: https://jsfiddle.net/BlackLabel/bsmxz2n3/3/ (orange labels are misplaced)

2024-04-12 09:33 UTC, kamil-musialowski commented
I'll also have a look into that @pawelfus , thanks for reporting 😄

2024-04-16 14:57 UTC, kamil-musialowski commented
@pawelfus Fixed 👍

2024-04-17 09:17 UTC, TorsteinHonsi commented
Pending approval by @pawelfus

2024-04-22 07:57 UTC, merged