Bugfix/missing padding auto rotation defaults
highcharts/highcharts pull request #21005
Opened 2024-04-12 14:04 UTC by pawelfus

Improved the default padding of axis labels, and fixed their collision calculations. 

Closes #20889

2024-04-12 14:26 UTC, pawelfus commented
Some of the demos now look better, other present the same issue:

1. http://utils.highcharts.local/samples/#test/highcharts/plotoptions/column-pointrange - crowded ticks provide more info, current build looks better
2. http://utils.highcharts.local/samples/#test/highcharts/legend/align - unnecessary rotation, candidate IMHO looks better (applies to all charts with JAN-DEC categories)
3. http://utils.highcharts.local/samples/#test/highcharts/css/error-bar - unable to compare, local build looks the same..

2024-04-22 07:25 UTC, TorsteinHonsi requested changes
Thanks, this looks good to me! I think all the diff cases now look better with the candidate. Once the docs comment is fixed, are we ready to merge?

2024-04-22 07:25 UTC, TorsteinHonsi commented on ts/Core/Axis/AxisDefaults.ts
> +             * them. Defaults to 5 for horizontal axes, 0 for vertical.
```suggestion
             * them. Defaults to 4 for horizontal axes, 1 for vertical.
```

2024-04-22 07:51 UTC, TorsteinHonsi commented
If this replaces #20889 then we need a proper description and tagging too.

2024-04-23 13:19 UTC, TorsteinHonsi approved these changes

2024-04-23 13:20 UTC, merged