Dashboards/mqtt demo
highcharts/highcharts pull request #21027
Opened 2024-04-17 17:43 UTC by jomar-honsi

MQTT data -> Data pool -> Dash components.

2024-08-30 07:00 UTC, karolkolodziej requested changes
The layout is off:
![image](https://github.com/user-attachments/assets/b7bd4941-d38e-448a-9dfd-e196ec24361b)

2024-08-30 07:00 UTC, karolkolodziej commented on samples/dashboards/demo/mqtt/demo.html
> +                <input id="connect-toggle" type="checkbox"></input>
I would add a label explaining what the toggle does- without reading the text is difficult to understand.
Label above the toggle saying `Connect to mqtt` should be enough.

2024-08-31 10:37 UTC, jomar-honsi commented on samples/dashboards/demo/mqtt/demo.details
> +requiresManualTesting: true
Remove the entire file?

2024-09-03 14:19 UTC, sebastianbochan commented
<img width="832" alt="Screenshot 2024-09-03 at 16 19 03" src="https://github.com/user-attachments/assets/c1b265c4-c61c-4829-ac88-5ae361a3eb1f">
Is it intentional for this location?

2024-09-03 14:19 UTC, sebastianbochan commented on samples/dashboards/demo/mqtt/demo.details
> +requiresManualTesting: true
Only the line about manual testing

2024-09-04 06:19 UTC, jomar-honsi commented
> <img alt="Screenshot 2024-09-03 at 16 19 03" width="832" src="https://private-user-images.githubusercontent.com/2115686/364020599-c1b265c4-c61c-4829-ac88-5ae361a3eb1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MzA4NjcsIm5iZiI6MTcyNTQzMDU2NywicGF0aCI6Ii8yMTE1Njg2LzM2NDAyMDU5OS1jMWIyNjVjNC1jNjFjLTQ4MjktYWM4OC01YWUzNjFhM2ViMWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDRUMDYxNjA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjdhOGVjYTBmNWQ3ODU0MWVhMmYxYjE3ODY4YmY0N2ZjNmUwNzFkYjEwMWZhNTBhOWNmMDQ4MmRkMzBjYWI0OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-FS5Ltr6b0NYA-cFtcuqVr83d8m6CA3i5SOORswviBA"> Is it intentional for this location?

At the moment there is no production at this plant (high summer low, demand).

2024-09-04 06:21 UTC, jomar-honsi commented on samples/dashboards/demo/mqtt/demo.details
> +requiresManualTesting: true
Done

2024-09-05 12:45 UTC, sebastianbochan approved these changes

2024-09-19 07:17 UTC, karolkolodziej approved these changes

2024-10-10 10:51 UTC, stitot approved these changes

2024-10-15 04:25 UTC, TorsteinHonsi requested changes
Thanks, great work!

In addition to the inline comments:

* The most critical issue is the bad animation on the spline chart for Kråkeelvi. I'm not sure what happens, but it is supposed to slide gracefully to the left like the [dynamic-update](http://localhost:3030/samples/#view/highcharts/demo/dynamic-update) demo.
* Do we want the dashboard to be hidden behind two clicks? The end user first needs to connect, then select the river. Can we streamline this? I appreciate that we may want to demonstrate that connecting is a user action, but maybe we can put this button (or a shortcut) in a more prominent place on the screen? And maybe consider auto-connecting to the first of the rivers?
* The name of the demo is now MQTT. But it does so much more. So in order to send the right message to the reader, maybe we should name it something like "MQTT advanced dashboard"? Then somewhere in the text below we could point to the simpler MQTT custom connector demo?

2024-10-15 04:25 UTC, TorsteinHonsi commented on samples/dashboards/demo/mqtt/demo.js
> +            animation: true
Probably redundant, animation should be true by default

2024-10-15 04:25 UTC, TorsteinHonsi commented on samples/dashboards/demo/mqtt/demo.js
> +}
It would be better practice to toggle a class name in the top container (one line of JS), then use CSS to apply cell visibility.

2024-10-15 04:25 UTC, TorsteinHonsi commented on samples/dashboards/demo/mqtt/demo.js
> +        return colHtml;
Combine into a single operation with Array.map?

2024-10-15 04:25 UTC, TorsteinHonsi commented on samples/dashboards/demo/mqtt/demo.js
> +        return colHtml;
`return getInfoRecord(item, fields).map(col => [...])`

2024-10-15 04:25 UTC, TorsteinHonsi commented on samples/graphics/dashboards/mqtt/sognekraft_logo.png
Not a biggie, but do they have an SVG available? Renders better on modern screens.

2024-10-15 08:12 UTC, jomar-honsi commented on samples/dashboards/demo/mqtt/demo.js
> +            animation: false
There was an issue early on where the map points being misplaced (offset) after selecting a new power station. I worked around it by turning off animation (don't remember of I filed a bug). However, we can try it again, perhaps the issue has been fixed in the meantime.

2024-10-15 08:12 UTC, jomar-honsi commented on samples/dashboards/demo/mqtt/demo.js
> +                theme: 'Standard'
Good point!

2024-10-15 11:26 UTC, jomar-honsi commented on samples/dashboards/demo/mqtt/demo.js
> +            animation: false
Shifting the map now seems to work also with animation turned on.

2024-10-25 06:51 UTC, jomar-honsi commented on samples/graphics/dashboards/mqtt/sognekraft_logo.png
I will check.

2024-11-08 08:57 UTC, jomar-honsi commented
@TorsteinHonsi Workarounds have been provided for two issues in the incoming MQTT data, so from a visual perspective this PR can be reviewed again.

2024-11-08 14:13 UTC, TorsteinHonsi requested changes
Animation is running smooth as silk now 👍 

Finally, we need some responsive CSS for the mobile view
<img width="392" alt="Skjermbilde 2024-11-08 kl  15 13 08" src="https://github.com/user-attachments/assets/dd4870c5-6f43-440d-8eb3-dc736087e934">

2024-11-08 14:16 UTC, TorsteinHonsi commented on samples/dashboards/demo/mqtt/demo.js
> +            styledMode: false
Tiled web maps look better when they fill the space

```suggestion
            styledMode: false,
            margin: 0
```

2024-11-22 12:57 UTC, merged