Fixed #14067, click event handlers didn't work on boosted charts
highcharts/highcharts pull request #21067
Opened 2024-04-25 09:07 UTC by TorsteinHonsi

Fixed #14067, click event handlers didn't work on boosted charts

2024-04-25 10:06 UTC, karolkolodziej requested changes
I can see two things:
1. When clicking directly on the halo, the point click isn't triggered- [better visible in this demo.](https://jsfiddle.net/BlackLabel/tamd1q4b/)
2. Remove or clarify in [docs](https://www.highcharts.com/docs/advanced-chart-features/boost-module)
> Point click handlers are not supported in boost mode.

2024-04-25 12:35 UTC, kamil-musialowski reviewed
Everything seems to be fine, aside from one thing - but I'm not sure if it's on my side only or not.

Whenever I trigger the click event, the chart gets veeery laggy, tooltip dosen't move, everything freezes for a few seconds.

2024-04-25 12:35 UTC, karolkolodziej approved these changes

2024-05-02 11:15 UTC, TorsteinHonsi commented
@kamil-musialowski As far as I can see, it is jsFiddle that freezes on clicking. It doesn't happen every time, but when it does, I am able to pause the execution inside som `defaultClickHandler` function that is not ours. I'll take the chance on merging this as is.

2024-05-02 11:15 UTC, merged

2024-05-02 17:25 UTC, kamil-musialowski commented
In that case, that's good for me!