Removed dashboards animation
highcharts/highcharts pull request #21082
Opened 2024-04-29 11:09 UTC by nasin

Hi, I removed the dashboard animation from the chart rotation

2024-04-30 07:10 UTC, TorsteinHonsi requested changes
Thanks! 

There's a lint error on [line 2028](https://github.com/highcharts/highcharts/pull/21082/files#diff-9587a641a1435286cb613a43cfb6d058e13412aa6149974e3ed216ed690a150cR2028). Can you either remove or comment out the `db` constant?

2024-05-02 08:15 UTC, TorsteinHonsi requested changes
Thanks! More lint errors now...

See https://github.com/highcharts/highcharts/pull/21082/files

2024-06-12 14:29 UTC, nasin commented
Hi, I fixed the linting errors...sorry for the long delay

2024-06-13 09:38 UTC, TorsteinHonsi approved these changes

2024-06-13 09:38 UTC, merged