Demo/bar force
highcharts/highcharts pull request #21094
Opened 2024-04-30 11:10 UTC by Xillez

Added Pawel's bar force PoC as demo.

Asana task: https://app.asana.com/0/1204848917817812/1206574774352158/f

2024-04-30 11:38 UTC, Xillez commented
Still looking into accessibility and a possibly better dataset, will poke when properly ready 😅

2024-05-15 07:11 UTC, Xillez commented
@bre1470 @marvin19 Ready for review 👍

2024-05-15 17:26 UTC, bre1470 requested changes
Great use case!

When it comes to screen reader navigation, it jumps between slowing and accelerating values. I am not sure if this is by design, but it might help to pre-sort data in ascending order, so that it is easier to follow.

And I get the screen reader description only on entering the series with the first point (initial entry speed), not during navigation. This makes it hard to understand the different forces.

In addition it would be nice to have two sums of all slowing and accelerating forces, or at least y-axis labels.

2024-05-15 17:26 UTC, bre1470 commented on samples/highcharts/demo/bar-force/demo.details
> +  This demo shows a horizontally stacked bar chart styled to show how
> This demo shows a horizontally stacked bar chart styled to show...
This demo is a horizontally stacked bar chart and shows...

2024-05-22 09:30 UTC, Xillez commented
Thanks!

> When it comes to screen reader navigation, it jumps between slowing and accelerating values. I am not sure if this is by design, but it might help to pre-sort data in ascending order, so that it is easier to follow.
The jumping is kind of by design and kind of not, I placed the data in chronological order to how a EDL sequence goes, so it would be easy to follow the steps when they use keyboard navigation. Also another thing is that if it's placed with the other accelerating forces it might be confused with something else as it'll be read out of order. I could include some statement of the order if that's alright? That or mention the next point somehow or something similar?

Bit more info:
Including the freefall (backshell seperation) is a bit difficult as it happens late and is technically part of the slowdown sequence but given the spacecraft is accelerating as this brief moment it gets visualized as a positive value, and so the navigation jumps a bit. I could bundle them based or remove the step but I also kinda wanted it to be as close as possible to the actual sequence that's performed

> And I get the screen reader description only on entering the series with the first point (initial entry speed), not during navigation. This makes it hard to understand the different forces.
I'll take a closer look 👍

> In addition it would be nice to have two sums of all slowing and accelerating forces, or at least y-axis labels.
I was told to remove the axis labels in the task but I can try and minimize them or as you say, add some sum labels for either side 👍

2024-06-10 10:11 UTC, bre1470 reviewed
I struggle to come out of the series points. I get a level up with ⌘⌥⇧↑, but as soon as try to got on, I fall back to the series points. Otherwise it looks good.

2024-06-11 09:40 UTC, Xillez commented
@marvin19 Do you get the same issue?
When I test with NVDA on Windows I don't really get stuck on the points so its somewhat difficult to debug 🤔

2024-06-11 12:16 UTC, bre1470 approved these changes
Nice work! 👍

2024-06-11 12:23 UTC, marvin19 commented
> @marvin19 Do you get the same issue? When I test with NVDA on Windows I don't really get stuck on the points so its somewhat difficult to debug 🤔

I've tested with MacOS in Safari + VoiceOver and on Windows on Edge + NVDA. No problems on my end.

2024-06-11 12:23 UTC, marvin19 approved these changes

2024-06-12 11:59 UTC, TorsteinHonsi requested changes
Thanks, that's a good start!

In addition to the comments, it needs some TLC in mobile view:
![Skjermbilde 2024-06-12 kl  13 55 42](https://github.com/highcharts/highcharts/assets/227836/a528aea5-bc03-4d1e-a6fb-a5df5a96ac05)
* I propose setting `startOnTick` and `endOnTick` to false so that we get to use the whole width.
* The title must be reduced or the height adjusted to make room for the labels

2024-06-12 11:59 UTC, TorsteinHonsi commented on samples/highcharts/demo/bar-force/demo.html
> +        <br/>
Use nested paragraphs instead of double breaks.

2024-06-12 11:59 UTC, TorsteinHonsi commented on samples/highcharts/demo/bar-force/demo.html
> +        <br/>
Oh wait a minute; that's not valid HTML. Instead, make the `.highcharts-description` a div, then paragraphs inside.

2024-06-12 11:59 UTC, TorsteinHonsi commented on samples/highcharts/demo/bar-force/demo.js
> +                    var len = options.headSize; // in pixels
```suggestion
                    let len = options.headSize; // in pixels
```

2024-06-12 11:59 UTC, TorsteinHonsi commented on samples/highcharts/demo/bar-force/demo.js
> +            render: function () {
I think we can just use stack labels instead of the custom render function: https://jsfiddle.net/highcharts/pzevxsb9/

2024-06-12 11:59 UTC, TorsteinHonsi commented on samples/highcharts/demo/bar-force/demo.js
> +        stickOnContact: true
I think we should remove this. The tooltip gets in the way of hovering to read the values.

2024-06-14 11:05 UTC, Xillez commented
Thanks for the feedback! Kinda forgot about mobile view :sweat_smile:
Will take a closer look on Monday :+1:

2024-06-17 08:46 UTC, TorsteinHonsi requested changes
Thanks, the only remaining issue I can see now is that the tooltip is gone. In my comment when I said "I think we can remove this", I was referring to the `stickOnContact` setting only.

2024-06-17 11:58 UTC, TorsteinHonsi approved these changes

2024-06-17 11:58 UTC, merged