dash/20756-edit-mode-change-event
highcharts/highcharts pull request #21100
Opened 2024-04-30 23:05 UTC by vazonik

Closing #20756.

---

TO DO:
- [x] Change the moment of component update in the edit mode accordion.
- [ ] Add edit-mode events called when updating component options.
- [ ] Add edit-mode events called when editing the layout.
- [ ] Add a modal popup confirming whether to cancel component editing when clicked out of the accordion (?).
- [ ] Add regression tests.
- [ ] Update docs.

2024-05-13 08:11 UTC, jomar-honsi approved these changes

2024-05-13 12:02 UTC, karolkolodziej requested changes
1. Maskiis missing steps: edit component -> click outside of the sidebar -> click cancel 
2. IMO clicking outside of the dashboard's container should not trigger the popup

2024-05-13 12:02 UTC, karolkolodziej commented on ts/Dashboards/EditMode/AccordionMenu.ts
> +            await component.update({
This is only true for the Highcharts component right? Wouldn't it be possible to improve the typing?

2024-05-14 13:26 UTC, karolkolodziej approved these changes

2024-05-14 13:26 UTC, karolkolodziej commented on test/cypress/dashboards/integration/EditMode/sidebar.cy.js
> +    it('Should be able to confirm or cancel changes, #20756.', () => {
Can you please add test coverage for the visibility of the mask throughout the whole process?

2024-05-14 18:19 UTC, jomar-honsi approved these changes

2024-05-15 13:31 UTC, jomar-honsi approved these changes

2024-05-22 10:20 UTC, sebastianbochan approved these changes

2024-05-27 11:28 UTC, stitot reviewed
Nice work! Are docs unclear on the fact that not all changes will trigger events, such as component (not chart) options such as title? Possible to add support for these as well?

PS. Really nice(!) that components are updated when fields are unfocused!

2024-06-03 09:15 UTC, vazonik commented
> Are docs unclear on the fact that not all changes will trigger events, such as component (not chart) options such as title? Possible to add support for these as well?

In what case did you observe this, @stitot? My point was that events are always emitted when confirming or cancelling changes, regardless of the option type. I can't reproduce this, it seems to work here too.
![image](https://github.com/highcharts/highcharts/assets/46498046/796c8abc-c259-4671-ae1a-64d9aa6ad60d)

2024-06-03 09:57 UTC, stitot commented
Hm, it work fine now, @vazonik . When I tried last time only chart options, not component, triggered the event. All good!

2024-06-03 11:16 UTC, merged