docs/improving-chart-height-docs
highcharts/highcharts pull request #21116
Opened 2024-05-03 12:43 UTC by MarkusBarstad

Fixed chart height docs, updated `500px`-sample title, and added new demo showing height inherited from container

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1207087393075554

2024-05-06 17:07 UTC, bre1470 requested changes
Looks good. 👍 Demo height should be changed though.

2024-05-06 17:07 UTC, bre1470 commented on samples/highcharts/chart/height-inherited/demo.css
> +    height: 400px;
[600 x 400 is default](https://github.com/highcharts/highcharts/blob/master/ts/Core/Chart/Chart.ts#L1397), so something different than 400 (600?) would be good to make sure, inheritance is always demonstrated and tested.

2024-05-07 07:47 UTC, bre1470 approved these changes

2024-05-14 13:57 UTC, KacperMadej approved these changes

2024-05-15 10:40 UTC, TorsteinHonsi approved these changes
Thanks!

2024-05-15 10:41 UTC, merged