Fixed #20877, one-finger panning with Ordinal xAxis.
highcharts/highcharts pull request #21195
Opened 2024-05-21 13:09 UTC by pawelfus

2024-05-23 05:39 UTC, pawellysy approved these changes

2024-05-23 07:07 UTC, kamil-musialowski requested changes
All good! I would just suggest changing the [deprecated `zoomType`](https://api.highcharts.com/highstock/chart.zoomType) to [`zooming.type`](https://api.highcharts.com/highstock/chart.zooming.type)

2024-05-23 07:07 UTC, kamil-musialowski commented on samples/unit-tests/axis/extremes/demo.js
> +            zoomType: '',
```suggestion
            zooming: {
               type: ''
            }
```

2024-05-23 08:26 UTC, bm64 approved these changes

2024-05-30 13:17 UTC, DJTechnoo approved these changes

2024-06-03 09:17 UTC, TorsteinHonsi approved these changes
Thanks!

2024-06-03 09:17 UTC, merged