bugfix/crooked-navigator-outline
highcharts/highcharts pull request #21208
Opened 2024-05-22 16:09 UTC by bm64

Corrected crooked line in the navigator outline.

2024-05-23 10:33 UTC, pawelfus approved these changes

2024-05-27 08:49 UTC, TorsteinHonsi commented
Looks good, but the visual diff preview is down now so I can't verify.

2024-05-27 08:51 UTC, TorsteinHonsi requested changes

2024-05-27 08:51 UTC, TorsteinHonsi commented on samples/unit-tests/navigator/navigator/demo.js
> +            outlinePathArray[0][2], //Upper left of navigator outline
Lint error
```suggestion
            outlinePathArray[0][2], // Upper left of navigator outline
```

2024-05-29 08:04 UTC, TorsteinHonsi requested changes
Thanks!

Our test suite takes some time to run, mainly because of the time it takes to generate the charts for each test. Therefore we have a policy to try to reuse existing charts for new regression tests. Can you find a similar test and apply the assertion there instead of creating a whole new test with a stock chart?

2024-06-19 11:30 UTC, TorsteinHonsi commented
Thanks! Can you take a look at the conflicts too?

2024-06-21 09:38 UTC, pawelfus approved these changes

2024-06-25 10:06 UTC, TorsteinHonsi approved these changes

2024-07-02 06:30 UTC, merged