demo/order-book-a11y
highcharts/highcharts pull request #21221
Opened 2024-05-27 07:31 UTC by kamil-musialowski

Added a11y improvements to order book demo.

2024-05-27 08:34 UTC, marvin19 requested changes
Great improvements! 🎉  Some requests

- Make button text correspond with the state of the chart. If chart is paused, label button "Start Animation", if chart is animating label button "Stop animation" 
- Button can be a <button> element outside of the chart. The way it is rendered right now gives it a aria-hidden="true" which means it is never exposed to a screen reader.
- Add xAxis.accessibility.description to xAxis. Currently the default says "value".
-  Add dollar sign to dataLabels 
-  Use accessibility.point.descriptionFormat to modify the aria-label of the points. Use what you are showing in the tooltip as a guideline.

2024-07-08 11:57 UTC, marvin19 approved these changes

2024-08-19 10:23 UTC, pawelfus commented
bump @TorsteinHonsi

2024-08-19 10:32 UTC, TorsteinHonsi approved these changes
Thanks!

2024-08-19 10:32 UTC, merged