Dash/edit mode context
highcharts/highcharts pull request #21231
Opened 2024-05-28 12:45 UTC by karolkolodziej

Added context detection for custom HTML.

2024-06-08 11:32 UTC, stitot commented
Looking good! Some issues:

**Toogle is deactivated**
When editMode is enabled by default (like in demo) the toggle button is inactive. Activating it turn editMode off. 

**Context menu jumps down**
1. Click hamburger menu
2. Enable editMode
3. Disable editMode

Observe that the context menu jumps down (tested in chrome)

**Fields miss label** (see attachment)

<img width="330" alt="Skjermbilde 2024-06-08 kl  13 24 51" src="https://github.com/highcharts/highcharts/assets/1061862/fd6b919e-6422-44b1-a1e6-d8f985890bf4">

**Icon on mouseover**
I want us to consider that the edit icon (the cogwheel) should also appears on mouseover, together with the blue border. The extra click needed doesn't seem necessary?

**Edit pane always to the left**
The edit pane is never triggered to the right, even when it covers the chart I want to edit to the left.

2024-06-10 13:21 UTC, karolkolodziej commented
> Fields miss label (see attachment)

Unrelated to the changes, I reported this separately. 

> Icon on mouseover

It behaves the same as the layout version- IMO we shouldn't change that now. At least not within the PR.

2024-06-12 16:52 UTC, vazonik approved these changes

2024-06-17 14:02 UTC, sebastianbochan commented on ts/Dashboards/EditMode/SidebarPopup.ts
> +            editMode.editCellContext.row
`editMode.editCellContext instanceof Cell &&
            editMode.editCellContext.row` it should be enough.

2024-06-17 14:02 UTC, sebastianbochan commented on ts/Dashboards/EditMode/SidebarPopup.ts
> +            editCellContext.row
The same as above

2024-06-19 16:57 UTC, jomar-honsi commented on docs/dashboards/edit-mode.md
> +When dashboard is declared with custom HTML structure, the edit mode is limited to the component settings only.
the dashboard

2024-06-19 16:58 UTC, jomar-honsi approved these changes

2024-06-20 16:19 UTC, jomar-honsi approved these changes

2024-06-24 06:44 UTC, stitot requested changes
I meant it when I said "1000000000" ;-)

For this to actually reduce cases of overlap due to high z-index in customers layout I believe it must be much higher than 100.

2024-06-27 07:08 UTC, sebastianbochan commented
The zIndex like `1000000000` does not make sense, because the maximum value is limited. I suggest setting the value 9999.

2024-06-27 08:02 UTC, stitot commented
> The zIndex like `1000000000` does not make sense, because the maximum value is limited. I suggest setting the value 9999.

@karolkolodziej mentioned there was maybe a more elegant solution than this "brute force" one.

2024-06-27 09:18 UTC, stitot commented
Have a look at e.g. http://localhost:3030/samples/#view/data-grid/v2/fixed-distribution

If I remove `width: 100% `from `table` it's still 100%, I guess because of the inline width we set on `thead`?

Possible to have default table behavior in these cases? That table is never wider than needed if no explicit width for the table is set via CSS?

2024-06-28 07:51 UTC, sebastianbochan approved these changes
Looks good to me.

2024-06-28 12:06 UTC, stitot reviewed
I would like to understand your reluctance to set this higher. Value for z-index is an integer, so can be −2147483648 to +2147483647 without breaking the rules. Could we at least add some 9's, so that the value is 9999999? The higher the better, as it will cover more cases. Your call.

2024-07-01 07:03 UTC, merged