demo/improve-a11y-btc
highcharts/highcharts pull request #21327
Opened 2024-06-14 11:18 UTC by DJTechnoo

2024-06-18 12:34 UTC, marvin19 requested changes

2024-06-21 14:58 UTC, kamil-musialowski requested changes
Everything looks good imo! Just one tiny leftover :)

2024-06-21 14:58 UTC, kamil-musialowski commented on samples/stock/demo/area/demo.js
> +const chart = Highcharts.stockChart('container', {
I believe we don't need the chart object in this demo 🤔

2024-06-21 15:06 UTC, kamil-musialowski approved these changes

2024-06-24 06:42 UTC, pawellysy reviewed
LGTM!

2024-06-24 06:42 UTC, pawellysy approved these changes

2024-06-24 07:14 UTC, pawelfus approved these changes
Thanks!

2024-06-24 09:02 UTC, bm64 approved these changes

2024-06-25 13:11 UTC, TorsteinHonsi approved these changes
Thanks!

2024-06-25 13:12 UTC, merged