20968 synchronization of connector values
highcharts/highcharts pull request #21426
Opened 2024-06-28 14:44 UTC by jomar-honsi

2024-06-28 14:53 UTC, jomar-honsi commented
This is a renaming of PR and branch as requested by @vazonik . Original [PR](https://github.com/highcharts/highcharts/pull/21242#issue-2322853579).

2024-06-28 14:54 UTC, jomar-honsi commented
Renaming of PR and branch as requestet by @vazonik.
Original [PR](https://github.com/highcharts/highcharts/pull/21242#issue-2322853579).

2024-06-28 14:55 UTC, jomar-honsi commented
Test.

2024-06-28 15:55 UTC, vazonik requested changes
I also noticed that there are problems with Highlight Sync. Some rows are skipped and the next ones highlight incorrect points, if there is a shift equal to the number of previously skipped points. Could you investigate it? It seems that the original row index should be used somewhere in the syncs.

2024-06-28 15:55 UTC, vazonik commented on ts/Data/DataTable.ts
>              thisColumns = this.columns;
Use consistently
```ts
const a = ...,
   b = ...,
   c = ...;
```
or
```ts
const a = ...;
const b = ...;
const c = ...;
```

2024-06-28 16:04 UTC, jomar-honsi commented
> I also noticed that there are problems with Highlight Sync. Some rows are skipped and the next ones highlight incorrect points, if there is a shift equal to the number of previously skipped points. Could you investigate it? It seems that the original row index should be used somewhere in the syncs.

This issue is reported, I'd prefer to deal with it separately: #21296.

2024-06-28 16:26 UTC, vazonik approved these changes
> This issue is reported, I'd prefer to deal with it separately: https://github.com/highcharts/highcharts/issues/21296.

Okay, that makes sense!

2024-07-01 11:49 UTC, sebastianbochan approved these changes

2024-07-01 11:49 UTC, merged