feature/20692-treemap-small-nodes-grouping
highcharts/highcharts pull request #21499
Opened 2024-07-09 13:13 UTC by hubertkozik

Added new logic, a grouping of small leaf nodes in Treemap configured by the `groupAreaThreshold` option, closes #20692.

2024-08-12 10:17 UTC, KacperMadej requested changes
- [x] Click on the grouped after drilling down to the top left category in highcharts/plotoptions/treemap-grouping-advanced is causing an error in the console.
- [ ] Both bottom right groups only partially fill the available space (like 50%) after a drilldown.
![image](https://github.com/user-attachments/assets/1aafc90c-fd21-467c-b35e-607cdc6ac0e5)
![image](https://github.com/user-attachments/assets/b2ef6831-fb93-42b2-9be5-38a8d7e174b7)
- [x] drawing `dataLabels` in the advanced demo takes over 8 seconds
![image](https://github.com/user-attachments/assets/0fb86560-2033-496c-8dd8-b6cf243a2787)

2024-08-19 10:07 UTC, hubertkozik commented on ts/Series/Treemap/TreemapSeries.ts
> +                    )
Right, I didn't simplify it! Fixed.

2024-08-19 11:21 UTC, bre1470 requested changes

2024-08-19 11:21 UTC, bre1470 commented on ts/Series/Treemap/TreemapNode.ts
> +    isGroup: boolean = false;
You can make it optional and skip the initial assignment.

2024-08-19 11:21 UTC, bre1470 commented on ts/Series/Treemap/TreemapSeriesDefaults.ts
> +         * @default   + {point.groupedPointsAmount} more...
C&P problem with `+` and `more...`. This should probably be a string.

2024-08-19 11:21 UTC, bre1470 commented on ts/Series/Treemap/TreemapSeriesOptions.d.ts
> +     *
Unnecessary spacing as in others as well. Keep it compact for one-liners.

2024-08-19 11:21 UTC, bre1470 commented on ts/Series/Treemap/TreemapSeriesOptions.d.ts
> +     * @default   + {point.groupedPointsAmount} more...
The plus-more-thing ones more.

2024-08-19 11:21 UTC, bre1470 commented on ts/Series/Treemap/TreemapSeriesDefaults.ts
> +         *
Unnecessary spacing

2024-08-21 14:09 UTC, KacperMadej approved these changes
Looks good to me.
Isn't the format "+ X more..." a bit misleading? I would expect to the group to contain **over** X and not exactly X.

2024-08-22 12:49 UTC, MarkusBarstad approved these changes
Very well done! 🚀

2024-08-23 10:56 UTC, bre1470 approved these changes
In the grouping demo the rest tooltip says "New tooltip content", which is a bit strange.
And I agree with what Kacper wrote.

Otherwise it looks good. 👍

2024-09-04 10:40 UTC, TorsteinHonsi requested changes
Thanks, great work! I added some comments inline. 

- [x] Also, I think this feature deserves a mention in the `docs/chart-and-series-types/treemap.md` article.

- [x] I addition, did you consider adding a feature to click the grouped item to expand it? I am not sure how that would work, if it should expand to the parent level or only the grouped items. But this would be equivalent to clicking a [marker cluster in scatter charts](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/marker-clusters/basic/), where the cluster dissolves into the individual points.

2024-09-04 10:40 UTC, TorsteinHonsi commented on samples/highcharts/plotoptions/treemap-grouping-advanced/demo.js
> +    const lightenDarkenColor = (col, amt) =>
We have the [Highcharts.Color.brighten](https://api.highcharts.com/class-reference/Highcharts.Color#brighten) function that we use in some demos that looks a bit friendlier...

2024-09-11 13:45 UTC, hubertkozik commented on ts/Series/Treemap/TreemapSeriesDefaults.ts
> +        name: 'Grouped nodes'
Agree, removed default name and added info in API description.

2024-09-30 10:09 UTC, TorsteinHonsi reviewed
Thanks so far! I've been fiddling a bit with the traversing and have some comments/questions:

1. Consider highcharts/plotoptions/treemap-grouping-advanced. If you click the "All machinery" group, the nested nodes expand, but they seem to do so without animation. As far as I can see, this is contrary to the `treemap-large` demo, where animation occurs. 
2. Next, click the +168 tile. Also no animation.
3. The breadcrumbs now say +112. But I clicked +168...
4. Click Machinery again in the breadcrumbs. Now the +168 tile takes up som 30-40% of the plot area, unlike in step 1 where it was much smaller. 
5. Click +168 again. Now the breadcrumbs say +153.

All in all we may have to work a bit on animation. For comparison, see the highcharts/marker-clusters/basic demo, where all animations flow nicely, all points originating in the cluster. But this may not be unique to this PR or the new feature, but maybe a treemap issue by itself.

2024-10-09 12:53 UTC, hubertkozik commented
@TorsteinHonsi I fixed the animation problem, turns out it was the `animationLimit` for this series in this demo.

Also, I fixed the problem of grouped node wrong sizing - it was much more complicated and I figured out, that the previous implementation of grouping was done in the wrong place, I refactored it one more time.

Sadly, now after traversing into grouped nodes their children sometimes look strange, but it's a correct layout behaviour - not sure if we should improve that. For example, after traversing into a grouped node in "Machinery" group there are some empty points, due to layout change/re-calculation, but only good points are shown on the chart.

2024-10-26 11:00 UTC, TorsteinHonsi commented
> To be honest I am not sure if we should provide the possibility to traverse into grouped points, due to algorithm calculations it gets very complicated.

@hubertkozik Could you make a team decision on this in the core group? The client probably has a preference. If we can't decide clearly for one solution or the other, we could introduce an option.

2024-11-29 12:21 UTC, bre1470 approved these changes
Great job! Looks good. 👍

2024-11-29 12:21 UTC, bre1470 commented on ts/Series/Treemap/TreemapSeriesDefaults.ts
> +     * @apioption plotOptions.treemap.groupAreaThreshold
You could skip `@apioption` as it is part of an `@optionparent`-tree.

2024-12-02 08:56 UTC, KacperMadej approved these changes

2024-12-10 09:31 UTC, TorsteinHonsi requested changes
Great work! Just some minor details/questions.

2024-12-10 09:31 UTC, TorsteinHonsi commented on samples/highcharts/plotoptions/treemap-grouping-advanced/demo.js
> +    const dataJson = await fetch(
Just `data`, it is no longer JSON after the JSON string has been parsed.
```suggestion
    const dataJson = await fetch(
```

2024-12-10 09:31 UTC, TorsteinHonsi commented on ts/Series/Treemap/TreemapSeriesDefaults.ts
> +        clusterFormat: '<span>+ {point.groupedPointsAmount} more...' +
Why the span?

2024-12-10 09:31 UTC, TorsteinHonsi commented on ts/Series/Treemap/TreemapSeriesDefaults.ts
> +     * into group point per series.
Did you mean into _one_ group point?
```suggestion
     * into one group point per series.
```

2024-12-11 16:54 UTC, hubertkozik commented on ts/Series/Treemap/TreemapSeriesDefaults.ts
> +        clusterFormat: '<span>+ {point.groupedPointsAmount} more...' +
Right, span not needed.

2024-12-12 06:09 UTC, TorsteinHonsi approved these changes

2024-12-12 06:09 UTC, merged