docs/faq-stock-tools-icons
highcharts/highcharts pull request #21509
Opened 2024-07-10 09:30 UTC by DJTechnoo

Added new point for external file references in the FAQ.

2024-07-10 12:48 UTC, pawelfus requested changes

2024-07-10 12:48 UTC, pawelfus commented on docs/getting-started/frequently-asked-questions.md
> +* Stock Tools icons. By default the icons are loaded dynamically from https://code.highcharts.com. To change where icons should be loaded from see the [iconsURL](https://api.highcharts.com/highstock/
wrong URL, this one leads to deprecated option, please use: https://api.highcharts.com/highstock/navigation.iconsURL

2024-07-10 16:07 UTC, kamil-musialowski approved these changes
Apart from Pawel's comment - all good!

2024-07-11 22:35 UTC, bm64 approved these changes

2024-07-12 08:28 UTC, pawelfus approved these changes
Thanks!

2024-07-16 08:33 UTC, pawellysy approved these changes

2024-08-05 09:30 UTC, TorsteinHonsi approved these changes
Thanks!

2024-08-05 09:31 UTC, merged