dash/sidebar-layout
highcharts/highcharts pull request #21528
Opened 2024-07-11 12:34 UTC by karolkolodziej

Changed the `layout` element in the Add component sidebar to a `row` and improved the look when added.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1207420047763497

2024-07-12 09:09 UTC, sebastianbochan requested changes

2024-07-12 09:09 UTC, sebastianbochan commented on ts/Dashboards/EditMode/SidebarPopup.ts
> +                html: '<h2> Placeholder </h2><p> This placeholder can be deleted when you add extra components to this row. </p>'
You can multiline string and linter will not have to be disabled.

2024-07-15 07:28 UTC, sebastianbochan approved these changes

2024-07-15 08:28 UTC, jomar-honsi approved these changes

2024-07-15 14:34 UTC, ddragula approved these changes

2024-07-19 08:20 UTC, merged