docs/getting-started-stock-update
highcharts/highcharts pull request #21523
Opened 2024-07-11 08:31 UTC by kamil-musialowski

Improved [Getting started with Stock docs](https://www.highcharts.com/docs/stock/getting-started-stock).

2024-07-11 11:26 UTC, DJTechnoo requested changes
This looks much better! Just some small nit-picking from my side

2024-07-11 11:26 UTC, DJTechnoo commented on docs/stock/getting-started-stock.md
> +Run the `stockChart` constructor for initializing a Stock chart visualization. The constructor takes two required parameters (container ID and a config object) and a third optional parameter, which i
```suggestion
Run the `stockChart` constructor for initializing a Stock chart visualization. The constructor takes two required parameters (container ID and a config object) and a third optional parameter, which is the callback function run after the chart has loaded.
```

2024-07-11 11:26 UTC, DJTechnoo commented on docs/stock/getting-started-stock.md
> +To create your first simple stock chart, all you need to do is to define the dataset appropriate for the [series type](https://api.highcharts.com/highstock/series) that you choose. The default series
"Simple" should maybe also be changed to "basic" here as well

2024-07-12 08:37 UTC, pawelfus requested changes

2024-07-12 08:37 UTC, pawelfus commented on docs/stock/getting-started-stock.md
> +Highcharts.stockChart('container ID', {
According to the HTML 4/5 spec ID's must not contain empty spaces

2024-07-12 10:53 UTC, kamil-musialowski commented on docs/stock/getting-started-stock.md
> +Run the `stockChart` constructor for initializing a Stock chart visualization. The constructor takes two required parameters (container ID and a config object) and a third optional parameter, which i
Nice catch, thanks!

2024-07-12 11:26 UTC, DJTechnoo approved these changes

2024-07-15 20:40 UTC, bm64 approved these changes

2024-07-16 08:59 UTC, pawellysy requested changes
minor polishing

2024-07-16 08:59 UTC, pawellysy commented on docs/stock/getting-started-stock.md
> +1.  `containerID:` The `id` of the HTML element used for rendering the chart.
or the element itself?

2024-07-16 08:59 UTC, pawellysy commented on docs/stock/getting-started-stock.md
> +Highcharts.stockChart('containerID', {
```suggestion
Highcharts.stockChart(containerID' {
```

2024-07-24 14:47 UTC, pawelfus commented on docs/stock/getting-started-stock.md
> +Highcharts.stockChart('containerID', {
Hm.. something strange happened here :D

2024-07-24 14:47 UTC, pawelfus commented on docs/stock/getting-started-stock.md
> +Highcharts.stockChart('container ID', {
Yes, that sounds good.

2024-07-26 07:43 UTC, pawelfus approved these changes
Thanks!

2024-07-31 08:53 UTC, pawellysy approved these changes

2024-08-05 08:44 UTC, TorsteinHonsi approved these changes
Thanks!

2024-08-05 08:44 UTC, merged