docs/annotations-gui
highcharts/highcharts pull request #21561
Opened 2024-07-21 12:06 UTC by bm64

Extracted build custom UI section from stock tools docs and created annotations GUI docs.

2024-07-23 14:59 UTC, pawellysy approved these changes

2024-07-24 11:17 UTC, kamil-musialowski requested changes

2024-07-24 11:17 UTC, kamil-musialowski commented on docs/advanced-chart-features/annotations-gui.md
> +              var chart = this.chart;
```suggestion
              const chart = this.chart;
```

2024-07-24 11:17 UTC, kamil-musialowski commented on docs/advanced-chart-features/annotations-gui.md
> +        ....
```suggestion
        ...
```

2024-07-24 11:17 UTC, kamil-musialowski commented on docs/advanced-chart-features/annotations-gui.md
> +        bindingsClassName: 'custom-gui-container' // informs Annotations module where to look for HTML elements for adding annotations etc.
```suggestion
        bindingsClassName: 'custom-gui-container' // Informs Annotations module where to look for HTML elements for adding annotations etc.
```

2024-07-24 11:17 UTC, kamil-musialowski commented on docs/advanced-chart-features/annotations-gui.md
> +HTML elements are bound to annotations events through reverse lookup of HTML elements with a classname in the form of: `highcharts-BINDINGNAME`. For example a HTML button with `highcharts-circle-anno
```suggestion
HTML elements are bound to annotations events through reverse lookup of HTML elements with a classname in the form of: `highcharts-BINDINGNAME`. For example a HTML button with `highcharts-circle-annotation` will bind the [`navigation.bindings.circleAnnotation`](https://api.highcharts.com/highcharts/navigation.bindings.circleAnnotation) events. Classname can be changed by setting `navigation.bindings.circleAnnotation.className`. The actual binding takes place on chart initialization, but only for HTML elements that are wrapped within another HTML element with the classname correlating the chart configuration for [`navigation.bindingsClassName`](https://api.highcharts.com/highcharts/navigation.bindingsClassName). The wrapping classname defaults to `highcharts-bindings-wrapper`. Wrapping the GUI elements is made required for specifying which GUI elements need to be bound and events are delegated to the correct chart.
```

2024-07-24 11:17 UTC, kamil-musialowski commented on docs/advanced-chart-features/annotations-gui.md
> +                  var chart = this;
```suggestion
                  const chart = this;
```

2024-07-24 11:17 UTC, kamil-musialowski commented on docs/advanced-chart-features/annotations-gui.md
> +                          var color = document.querySelectorAll(
```suggestion
                          const color = document.querySelectorAll(
```

2024-07-24 11:17 UTC, kamil-musialowski commented on samples/highcharts/annotations/basic-gui/demo.js
> +        // informs Annotations module where to look for HTML elements for adding
```suggestion
        // Informs Annotations module where to look for HTML elements for adding
```

2024-07-29 10:08 UTC, kamil-musialowski approved these changes
lgtm!

2024-08-05 13:02 UTC, DJTechnoo approved these changes
Great job!

2024-08-06 07:06 UTC, TorsteinHonsi requested changes
Thanks, looks good! Suggested correcting "classname" to "class name".

2024-08-06 07:06 UTC, TorsteinHonsi commented on docs/advanced-chart-features/annotations-gui.md
> +HTML elements are bound to annotations events through reverse lookup of HTML elements with a classname in the form of: `highcharts-BINDINGNAME`. For example a HTML button with `highcharts-circle-anno
```suggestion
HTML elements are bound to annotations events through reverse lookup of HTML elements with a class name in the form of: `highcharts-BINDINGNAME`. For example a HTML button with `highcharts-circle-annotation` will bind the [`navigation.bindings.circleAnnotation`](https://api.highcharts.com/highcharts/navigation.bindings.circleAnnotation) events. Class name can be changed by setting `navigation.bindings.circleAnnotation.className`. The actual binding takes place on chart initialization, but only for HTML elements that are wrapped within another HTML element with the class name correlating the chart configuration for [`navigation.bindingsClassName`](https://api.highcharts.com/highcharts/navigation.bindingsClassName). The wrapping class name defaults to `highcharts-bindings-wrapper`. Wrapping the GUI elements is made required for specifying which GUI elements need to be bound and events are delegated to the correct chart.
```

2024-08-06 07:06 UTC, TorsteinHonsi commented on docs/advanced-chart-features/annotations-gui.md
> +_The button below is now bound to the `circleAnnotation` events, after it's found through the above specified classname `custom-gui-container`._
```suggestion
_The button below is now bound to the `circleAnnotation` events, after it's found through the above specified class name `custom-gui-container`._
```

2024-08-06 07:06 UTC, TorsteinHonsi commented on docs/advanced-chart-features/annotations-gui.md
> +1. First we define a dialog window in HTML. Notice the classname `highcharts-popup-annotations` of the outer `div` element. We need this classname in the [`navigation.events.showPopup`](https://api.h
```suggestion
1. First we define a dialog window in HTML. Notice the class name `highcharts-popup-annotations` of the outer `div` element. We need this class name in the [`navigation.events.showPopup`](https://api.highcharts.com/highcharts/navigation.events.showPopup) event later on.
```

2024-09-18 10:18 UTC, TorsteinHonsi approved these changes
Thanks!

2024-09-18 10:18 UTC, merged