dash/21280-setActiveState
highcharts/highcharts pull request #21577
Opened 2024-07-26 08:12 UTC by karolkolodziej

Fixed #21280, it was impossible to set the component active state, so added `isAcitve` flag.

2024-07-26 08:18 UTC, sebastianbochan requested changes

2024-07-29 14:42 UTC, jomar-honsi approved these changes

2024-07-30 09:59 UTC, jomar-honsi approved these changes

2024-07-31 07:02 UTC, ddragula approved these changes

2024-07-31 07:02 UTC, ddragula commented on ts/Dashboards/Components/Component.ts
> +
Are we decided on this name? It sounds a bit odd because it's a verb (suggests a callback?) when all the options are usually adjectives.

2024-08-01 07:50 UTC, ddragula approved these changes

2024-08-01 07:51 UTC, jomar-honsi approved these changes

2024-08-02 11:35 UTC, sebastianbochan requested changes

2024-08-02 11:35 UTC, sebastianbochan commented on samples/dashboards/demo/live-weather/demo.js
> +                        activated: true
I would replace it with one of them: "initialized", "visible", "isActive", "isActiveState"

`active.activated` does not sound intuitive to me.

2024-08-05 10:24 UTC, jomar-honsi approved these changes

2024-08-07 07:17 UTC, sebastianbochan approved these changes

2024-08-07 07:17 UTC, merged