demo/navigator-interactive-docs
highcharts/highcharts pull request #21602
Opened 2024-07-30 15:54 UTC by kamil-musialowski

Added interactive docs to be used on navigator page.

2024-07-31 16:37 UTC, DJTechnoo approved these changes
Great demos! Approving, with one small remark though: Should the titles of the demos be more descriptive?

2024-08-01 08:06 UTC, bm64 approved these changes

2024-08-05 13:27 UTC, pawelfus requested changes
Looks great! Minor polishing

2024-08-05 13:27 UTC, pawelfus commented on samples/stock/interactive-docs/navigator-styling/demo.js
> +        }]
Could you set initial range to be eg 1 year? The first thing I clicked was to change the mask from inner to outer and even though I knew the expected result, it was confusing.

2024-08-05 13:27 UTC, pawelfus commented on samples/stock/interactive-docs/navigator-styling/demo.html
> +    <input type="text" id="navigator-mask-fill"><br><br>
How about we change the input to a color picker? With a hardcoded opacity (0.3)? I mean, users can change the color, but not the opacity.

2024-08-08 09:25 UTC, pawelfus approved these changes
Thanks!

2024-08-12 09:10 UTC, pawellysy approved these changes

2024-08-15 06:21 UTC, TorsteinHonsi approved these changes
Thanks!

2024-08-15 06:21 UTC, merged