bugfix/21530-numbers-padding-categories
highcharts/highcharts pull request #21672
Opened 2024-08-16 08:47 UTC by MarkusBarstad

Fixed #21530, numbers show up as axisLabels when user has defined categories.

2024-08-27 10:24 UTC, TorsteinHonsi requested changes
Thanks, the fix looks good! 

A little spice should be added to the PR:
* A unit test.
* Some comment(s) within the actual code explaining why we are doing this, and with a reference to the issue. Will save our futures selves from some head scratching.

2024-09-04 08:18 UTC, TorsteinHonsi requested changes
Thanks, it works well!

2024-09-04 08:18 UTC, TorsteinHonsi commented on ts/Series/Bubble/BubbleSeries.ts
> +        if ((categories && categories.length) || type === 'category') {
These two if's can be combined into one. Run the `categories?.length` check first because it is cheaper than `find`.

2024-09-04 08:18 UTC, TorsteinHonsi commented on ts/Series/Bubble/BubbleSeries.ts
> +        type = options.type;
Doens't really need a constant since it's only used once.

2024-09-04 08:18 UTC, TorsteinHonsi commented on ts/Series/Bubble/BubbleSeries.ts
> +                    tick.label.hide();
Slightly terser:

```suggestion
                if (pos > dataMax || pos < dataMin) {
                    tick.label?.hide();
```

2024-09-06 13:40 UTC, TorsteinHonsi requested changes
Another two possibilities for squeezing out bytes

2024-09-06 13:40 UTC, TorsteinHonsi commented on ts/Series/Bubble/BubbleSeries.ts
> +        ((categories && categories.length) || type === 'category') &&
```suggestion
        (categories?.length || type === 'category') &&
```

2024-09-06 13:40 UTC, TorsteinHonsi commented on ts/Series/Bubble/BubbleSeries.ts
> +        this.series.find((s): boolean => s.bubblePadding === true)
```suggestion
        this.series.find((s): boolean|undefined => s.bubblePadding)
```

2024-09-09 12:40 UTC, MarkusBarstad commented
@TorsteinHonsi Good catches!

2024-09-09 13:55 UTC, TorsteinHonsi approved these changes

2024-09-09 13:55 UTC, merged