dash/dataGrid-editableOptions
highcharts/highcharts pull request #21670
Opened 2024-08-15 10:34 UTC by karolkolodziej

Added `editableOptions` for the DataGrid component.

- [ ] Styling
- [ ] Tests

2024-08-15 15:14 UTC, sebastianbochan approved these changes

2024-08-15 15:14 UTC, sebastianbochan commented on test/cypress/dashboards/integration/Components/DataGrid/DataGridComponent.cy.js
> +        //Assert
space

2024-08-16 07:24 UTC, jomar-honsi approved these changes

2024-08-16 08:21 UTC, ddragula requested changes
It looks great! But I found one issue: not all changed options are reverted after editing cancel. Could you investigate it?

2024-08-16 11:38 UTC, stitot requested changes
Looks really good!!

In addition to inline comments: Spec probably says otherwise, but when looking at it now I believe all DataGrid related options should be moved into a separate "panel" called DataGrid options".  Sorry about that...

2024-08-16 11:38 UTC, stitot commented on ts/Dashboards/Components/DataGridComponent/DataGridComponentDefaults.ts
> +            name: 'Grid caption',
```suggestion
            name: 'DataGrid caption/title',
```

2024-08-16 11:38 UTC, stitot commented on ts/Dashboards/Components/DataGridComponent/DataGridComponentDefaults.ts
> +            name: 'Editable table',
```suggestion
            name: 'Editable DataGrid',
```

2024-08-16 11:38 UTC, stitot commented on ts/Dashboards/Components/DataGridComponent/DataGridComponentDefaults.ts
> +            name: 'Text truncation',
```suggestion
            name: 'Cell text truncation',
```

2024-08-19 08:32 UTC, karolkolodziej commented
@stitot Please check if the nested options are fine for you. Don't look at the styling for now.
The current implementation doesn't allow to have standalone options in the first parent...

2024-08-20 08:31 UTC, stitot commented
> @stitot Please check if the nested options are fine for you. Don't look at the styling for now. The current implementation doesn't allow to have standalone options in the first parent...

Looks good (if not looking at styling ;-), but some changes:

1. DataGrid options -> General -> Caption is caption for the component, so belongs in the root after Title
2. With this grouping you can rename DataGrid options -> General -> "DataGrid Caption/Title" to just "Caption/title"
3. Place DataGrid options -> General -> Columns distribution as the third item, so that all radios are at the bottom.

2024-08-20 08:59 UTC, stitot commented
One more:

To be consistent with options we have for charts we should also add "DataGrid class name" and "DataGrid ID" to the root here. If not users will not be able to add DataGrid with different styling, if needed.

2024-08-22 10:53 UTC, karolkolodziej commented
@ddragula I haven't found this issue. Do you have any steps on how to recreate it?

2024-08-23 08:05 UTC, stitot requested changes
Looks good! Just one comment.

2024-08-23 08:05 UTC, stitot commented on ts/Dashboards/Components/DataGridComponent/DataGridComponentDefaults.ts
> +            type: 'input'
These are not updated on unfocus and save, when checking /cypress/component-datagrid.

I my previous review I wrote "we should also add "DataGrid class name" and "DataGrid ID" to the root here". The placement is to be consistent with other components, but I've added a separate task (https://app.asana.com/0/1203234853779898/1208086790358623) for a cleanup here. Let's look at all components together later on.

2024-08-26 08:51 UTC, stitot approved these changes
Nice!

2024-08-26 09:27 UTC, ddragula approved these changes

2024-08-26 11:01 UTC, merged