bugfix/21524-column-ordinal-panning
highcharts/highcharts pull request #21705
Opened 2024-08-22 16:01 UTC by bm64

Fixed #21524, in some cases panning to axis minimum was impossible in data grouped ordinal column chart.

2024-08-26 07:13 UTC, kamil-musialowski approved these changes
Looking good!

2024-08-26 07:23 UTC, pawellysy approved these changes

2024-08-28 12:13 UTC, pawelfus requested changes
Thanks! Just some minor errands, see below

2024-08-28 12:13 UTC, pawelfus commented on samples/unit-tests/chart/panning/demo.js
> +QUnit.test('Column chart panning.', function (assert) {
Could you move the test to `Ordinal axis panning`? It seems to be almost exactly the same with some minor changes.

2024-09-18 08:58 UTC, DJTechnoo approved these changes
looks great!

2024-09-24 14:09 UTC, pawelfus requested changes
See my comment below

2024-09-24 14:09 UTC, pawelfus commented on samples/unit-tests/chart/panning/demo.js
> +            ordinal column chart, #21524.`
When testing grouped data, please set `forced=true`. And keep the old test. What I meant in the previous review is: to move new test to the old test, so we will reuse the chart (it takes most of the time in our tests). Something like this:

```ts
const chart = new chart(..);
controller.pan(..);
assert.notEqual(..);

chart.series[0].update({ data, dataGrouping });
controller.pan(..);
assert.equal(..);
```

2024-11-19 12:57 UTC, pawelfus approved these changes

2024-11-20 06:45 UTC, TorsteinHonsi approved these changes
Thanks!

2024-11-20 06:46 UTC, merged