demos/morning-star-areaspline
highcharts/highcharts pull request #21713
Opened 2024-08-23 16:05 UTC by DJTechnoo

Replaced data of Areaspline demo with financial data of Netflix

2024-09-12 14:05 UTC, bm64 approved these changes

2024-09-13 09:43 UTC, kamil-musialowski commented on samples/highcharts/demo/areaspline/demo.html
> +<script src="http://code.highcharts.com/connectors/morningstar/connectors-morningstar.js"></script>
Https still not working on my side, even after clearing cache in chrome.

2024-09-13 10:41 UTC, pawelfus approved these changes
Thanks!

2024-09-13 11:07 UTC, pawellysy approved these changes

2024-09-18 14:26 UTC, pawelfus approved these changes
Thanks!

2025-01-10 13:58 UTC, kamil-musialowski requested changes
Very minor stuff!

2025-01-10 13:58 UTC, kamil-musialowski commented on samples/highcharts/demo/areaspline/demo.js
> +]).then(() => {
Based on recent changes, shouldn't we change it to async/await?

2025-01-10 13:58 UTC, kamil-musialowski commented on samples/highcharts/demo/areaspline/demo.js
> +                color: 'rgba(68, 170, 213, .4)'
Just a suggestion, how about a different color of the plotBand? Right now it looks like an error in the data 😅

2025-03-19 12:52 UTC, kamil-musialowski approved these changes

2025-04-09 06:46 UTC, TorsteinHonsi commented
@pawelfus I'm a bit confused here... The area-chart demo currently uses nuclear power, while the areaspline demo previously used hunting data, right?

I think the area-chart perhaps should continue to use the nuclear power data, as its setup is simpler than using the Morningstar connector. 

I have another concern though. In the new areaspline demo, the data is so dense that we can't actually see that it is a spline. It might as well have been a regular area. So the dataset kind of defeats the purpose of the demo. If we slice the data to show only, say, 100 points, we can see the smooth spline. But the question is - is this a suitable dataset for a spline area? A spline indicates that the values change gradually over time (no sudden jumps).

2025-04-09 08:08 UTC, pawelfus commented
> @pawelfus I'm a bit confused here... The area-chart demo currently uses nuclear power, while the areaspline demo previously used hunting data, right?
>
> I think the area-chart perhaps should continue to use the nuclear power data, as its setup is simpler than using the Morningstar connector.
> 
> I have another concern though. In the new areaspline demo, the data is so dense that we can't actually see that it is a spline. It might as well have been a regular area. So the dataset kind of defeats the purpose of the demo. If we slice the data to show only, say, 100 points, we can see the smooth spline. But the question is - is this a suitable dataset for a spline area? A spline indicates that the values change gradually over time (no sudden jumps).

Oh, good point. I made a mistake, and thought it's area chart (because of the reasons you just posted). I would rather avoid displaying just 100 points, unless followed by Navigator (or other way to change the date-window). As for the spline vs line, we are focused more on the trend-spotting or peaks and throughs.

2025-04-09 09:14 UTC, pawelfus commented
After internal discussion, we skip it for now.

2025-04-09 09:14 UTC, closed without merging