dash/datagrid2-css-refactor
highcharts/highcharts pull request #21721
Opened 2024-08-27 13:05 UTC by sebastianbochan

2024-08-27 15:07 UTC, stitot commented
Nice work, but some comments below. 

This should be placed further down with the theme CSS, and AFTER the selector where top-border is specified, for readability. It's an override, and should be positioned after the selector it overrides.
https://github.com/highcharts/highcharts/blob/8b1a8378b8de73ddbec3217389c2c967ad0a4b64/css/datagrid/datagrid.css#L106-L109

Is this needed?
https://github.com/highcharts/highcharts/blob/8b1a8378b8de73ddbec3217389c2c967ad0a4b64/css/datagrid/datagrid.css#L111-L113

IMO we are somewhat inconsistent here. We use a class name to target the `tr`, but not the `td`. Yes, the class name has "row" in it, but it's not clear that this CSS selector applies to `tr`s in `tbody` only, and not `thead`.

To be more educational and clearer in our default CSS I would prefer:
`.highcharts-datagrid-table tbody tr` and `.highcharts-datagrid-table tbody td` as selectors here. This also paves the way for `.highcharts-datagrid-table tfoot td` when we get there, so that we are absolutely clear on what applies to what.

We should not be afraid to be a little verbose on selectors if that makes things clearer and easier to understand.
https://github.com/highcharts/highcharts/blob/8b1a8378b8de73ddbec3217389c2c967ad0a4b64/css/datagrid/datagrid.css#L145-L156

I don't like this hardcoded height, but that's another issue than this CSS refactoring I guess.
https://github.com/highcharts/highcharts/blob/8b1a8378b8de73ddbec3217389c2c967ad0a4b64/css/datagrid/datagrid.css#L147

I believe this should go down with the theme CSS
https://github.com/highcharts/highcharts/blob/8b1a8378b8de73ddbec3217389c2c967ad0a4b64/css/datagrid/datagrid.css#L154

This should be moved down to the theme CSS, and  after the selector it is overriding. In addition: we are mixing `thead` and `tbody` stuff here. Should split those so that they are located together with other thead and tbody stuff. Better to repeat stuff, again for "educational" purposes.
https://github.com/highcharts/highcharts/blob/8b1a8378b8de73ddbec3217389c2c967ad0a4b64/css/datagrid/datagrid.css#L158-L162

All resizer stuff should be moved up, together with other header stuff.
https://github.com/highcharts/highcharts/blob/8b1a8378b8de73ddbec3217389c2c967ad0a4b64/css/datagrid/datagrid.css#L164

Is this still in use?
https://github.com/highcharts/highcharts/blob/8b1a8378b8de73ddbec3217389c2c967ad0a4b64/css/datagrid/datagrid.css#L200

IMO we don't need this. If people want to they can fix styling themselves.
https://github.com/highcharts/highcharts/blob/8b1a8378b8de73ddbec3217389c2c967ad0a4b64/css/datagrid/datagrid.css#L212-L216

Sorting stuff should be moved up together with other header stuff:
https://github.com/highcharts/highcharts/blob/8b1a8378b8de73ddbec3217389c2c967ad0a4b64/css/datagrid/datagrid.css#L230

Correct here would be "Default theme", since it covers both light and dark.
https://github.com/highcharts/highcharts/blob/8b1a8378b8de73ddbec3217389c2c967ad0a4b64/css/datagrid/datagrid.css#L255

Again, I don't like these hardcoded heights, but maybe a separate issue. If this height is needed for proper rendering/functionality then it should not be down here.
https://github.com/highcharts/highcharts/blob/8b1a8378b8de73ddbec3217389c2c967ad0a4b64/css/datagrid/datagrid.css#L276-L279

2024-08-28 13:20 UTC, sebastianbochan commented on css/datagrid/datagrid.css
> +    height: 32px;
Currently it is needed, in the closes future we can replace it with dynamic calculation in a separate ticket.

2024-08-28 13:23 UTC, stitot commented on css/datagrid/datagrid.css
> +    height: 32px;
OK, then it should be moved up to the Core CSS.

2024-08-28 13:30 UTC, stitot approved these changes
But please consider moving that 32px thing up to Core

2024-08-28 13:30 UTC, ddragula commented on css/datagrid/datagrid.css
> +/* End Default Theme */
Isn't the CSS linter blocking your commit? 😄 It seems there should be an empty newline at the end of the file.

2024-08-29 06:41 UTC, karolkolodziej requested changes
Please check `data-grid/basic/cell-formatting`. Sth if off
![image](https://github.com/user-attachments/assets/6b483dbd-3dee-4e1c-a3a2-2e68f7c624d8)

2024-08-29 06:54 UTC, karolkolodziej approved these changes

2024-08-29 08:22 UTC, ddragula requested changes
`data-grid/basic/strict-row-heights` does not work correctly
<img width="469" alt="image" src="https://github.com/user-attachments/assets/69ca9695-ac93-4b63-a44a-86ebe43a37ff">

2024-08-29 09:06 UTC, ddragula approved these changes

2024-08-29 09:06 UTC, merged