demo/donut-race-morningstar
highcharts/highcharts pull request #21732
Opened 2024-08-28 11:13 UTC by kamil-musialowski

Added experimental dataset from Morningstar.

2024-08-28 11:23 UTC, pawellysy reviewed
Demo itself looks fine. The one thing I'd suggest is maybe to extend the datarange to include data from 2020 to today, because e.g. nvidia price went up 6 times, which can be nicely displayed on the chart.

2024-08-28 11:27 UTC, kamil-musialowski commented
Thanks! I thought about the same thing regarding NVDA, however since I'm not sure if we're even going to use this type of dataset for this demo I skipped that for now.

2024-08-28 12:06 UTC, pawelfus requested changes
I'm afraid this is not exactly what was expected. From ticket:

> 
![image](https://github.com/user-attachments/assets/a3fd7aae-b708-475a-acd7-84813838ce88)

So this should present the split of the fund asset allocation across time (days/months/years), not the share price. For example direct stocks, real estate, cash, equities, etc. Is this data available?

2024-08-28 12:06 UTC, pawelfus commented on samples/highcharts/demo/donut-race/demo.js
> +const data = TimeSeries.Security
Add a comment explaining what is happening here and why

2024-08-28 12:14 UTC, kamil-musialowski commented
@pawelfus I've tried tu pull different dataset than Price, but failed - so I'm not sure if I'm doing something wrong or it's not available.

2024-08-31 19:32 UTC, bm64 approved these changes

2024-09-11 13:30 UTC, pawelfus requested changes

2024-09-11 13:30 UTC, pawelfus commented on samples/highcharts/demo/donut-race/demo.js
> +        format: '<b>{key}</b>: {point.y:.2f} USD'
EUR*

2024-09-12 12:31 UTC, kamil-musialowski commented
Task on hold till we find more suitable dataset.

2025-03-19 09:06 UTC, closed without merging