demo/morningstar-custom-entrance-animation
highcharts/highcharts pull request #21746
Opened 2024-08-29 14:21 UTC by bm64

Added custom entrance animation demo with FANG morningstar data.

2024-08-29 20:10 UTC, kamil-musialowski requested changes
Demo looks good! Just a few questions before accepting:

- is this an already parsed dataset (via GPT or anything like that), or you got it in this format straight from Morningstar? If you had to parse it, then we need to write parsing logic in the demo itself - see other PRs.

- The dataset seems to be corrupted after 25th of April, could you check if that's something on our side or it came in like that from Morningstar?

- Every time you click on legend all axes redraw. I know it's not your fault, since the original demo also has this issue, but it's something worth investigating imo.

2024-08-30 09:20 UTC, bm64 commented
@kamil-musialowski

- The data before was returned by the connector's getRows() method. I assumed it made more sense to use the tool instead of manual parsing. However, after discussing with @pawelfus, I've replaced it with the raw data.
- The data appears corrupted, but that's how Morningstar returns it. I've double-checked this.

2024-08-30 14:25 UTC, pawellysy approved these changes
As a placeholder for future data it seems alright. If data won't change, I'd put all series into the same axis. Apart from that, looks good!

2024-09-02 08:11 UTC, kamil-musialowski approved these changes
Thanks!

2024-09-02 12:00 UTC, pawelfus requested changes
Replace data in the old demo

2024-09-10 13:37 UTC, pawelfus requested changes
Nice! Just a minor thing: missing units in tooltip and y-axes, or in legend.

2024-09-10 13:59 UTC, pawelfus approved these changes
Thanks!

2024-09-10 17:24 UTC, TorsteinHonsi requested changes
Thanks, this is a nice dataset for the demo.

I talked to the other managers and apparently we want to use our Morningstar connector in the demos (but pointing to our mock server), instead of fetching the data directly and convert it to Highcharts format. 

I don't know the state of the connector - if it is not yet ready we should probably set this PR back to Draft while waiting.

2024-09-12 06:27 UTC, pawellysy commented on samples/highcharts/demo/line-custom-entrance-animation/demo.html
> +<script src="http://code.highcharts.com/connectors/morningstar/connectors-morningstar.js"></script>
```suggestion
<script src="https://code.highcharts.com/connectors/morningstar/connectors-morningstar.js"></script>
```

2024-09-13 15:00 UTC, pawelfus requested changes

2024-09-13 15:00 UTC, pawelfus commented on samples/highcharts/demo/line-custom-entrance-animation/demo.js
> +};
Remove unnecessary ISINs

2024-09-13 15:00 UTC, pawelfus commented on samples/highcharts/demo/line-custom-entrance-animation/demo.js
> +    console.log(processedData);
Remove console.log

2024-09-18 11:20 UTC, DJTechnoo approved these changes
Well done!

2024-09-24 13:59 UTC, pawelfus approved these changes
Thanks!

2026-07-29 09:58 UTC, TorsteinHonsi requested changes
Please reply to the EURO/Dollar concern in the last comment. There is now a conflict too.

2026-08-20 08:40 UTC, closed without merging

2026-08-20 08:40 UTC, pawelfus commented
This PR is no longer relevant, the demo https://www.highcharts.com/demo/highcharts/line-custom-entrance-animation uses now a different dataset. Closing PR