docs/improve-dg-docs
highcharts/highcharts pull request #21758
Opened 2024-09-02 10:40 UTC by pawellysy

Added demo of performance comparison of a chart with and without dataGrouping.

2024-09-02 12:27 UTC, pawelfus requested changes
List of improvements:
- wrong unit on the yAxis scale (s vs ms)
- missing unit in tooltip
- x-value in the tooltip does not match the format on xAxis (in general, x-value needs info what that number presents)
- add more details:
  - lower = better
  - the machine you used to test it

2024-09-02 12:57 UTC, bm64 approved these changes

2024-09-03 09:27 UTC, DJTechnoo approved these changes

2024-09-04 13:35 UTC, kamil-musialowski approved these changes
Looks good!

2024-09-05 06:44 UTC, pawelfus approved these changes
Thanks!

2024-09-05 07:17 UTC, TorsteinHonsi requested changes
Thanks! Just a couple of inline change request on sentence case.

In addition to that, I think it would look better with text and subtitle aligned to the left. Especially on the mobile, long titles don't look so good when centered.

2024-09-05 07:17 UTC, TorsteinHonsi commented on samples/highcharts/blog/dg-performance-comparison/demo.js
> +        text: 'chart initial rendering time (lower is better)'
```suggestion
        text: 'Chart initial rendering time (lower is better)'
```

2024-09-05 07:17 UTC, TorsteinHonsi commented on samples/highcharts/blog/dg-performance-comparison/demo.js
> +                        chart loading time for {point.x} points:
```suggestion
                        Chart loading time for {point.x} points: 
```

2024-09-05 13:01 UTC, marvin19 requested changes
Just two minor suggestions from me:
1. `accessibility.point.valueDescriptionFormat` to give a bit more context to Assitive Technology. Something like this would be good:
`valueDescriptionFormat: '{index}. {xDescription} points, {value} milliseconds.'`
2. The blue text color in the tooltip does not have enough contrast. Consider making the text color a darker blue or make all text black color.A blue color like this: #0179C1 would have sufficient contrast.

2024-09-06 12:02 UTC, pawellysy commented
@marvin19 Maybe I'll just skip over to more contrasting colors :D

2024-09-06 13:08 UTC, TorsteinHonsi approved these changes

2024-09-10 15:22 UTC, merged