bugfix/20470-nested-props-exporting-data
highcharts/highcharts pull request #21769
Opened 2024-09-02 16:53 UTC by jedrzejruta

Fixed #20470, allow values from nested properties in exported data.

2024-09-03 08:12 UTC, hubertkozik requested changes

2024-09-03 08:12 UTC, hubertkozik commented on ts/Extensions/ExportData/ExportData.ts
> +                        mockPoint as any,
I don't like this `as any` - let's remove it 😁

2024-09-04 07:10 UTC, TorsteinHonsi approved these changes
Thanks!

2024-09-04 07:45 UTC, hubertkozik approved these changes

2024-09-04 08:13 UTC, merged