dash/dg2-credits
highcharts/highcharts pull request #21763
Opened 2024-09-02 12:32 UTC by ddragula

WiP...

2024-09-03 12:01 UTC, sebastianbochan requested changes

2024-09-03 12:01 UTC, sebastianbochan commented on ts/DataGrid/DataGrid.ts
> +                this.options = { dataTable: options.dataTable };
```
this.userOptions.dataTable = this.options?.dataTable || {};
this.options = { dataTable: options.dataTable };
```

Moreover, the `this.userOptions.dataTable` is not used anywhere, so what is the reason of this assignment?

2024-09-03 12:01 UTC, sebastianbochan commented on ts/DataGrid/Options.ts
> +    enabled?: boolean;
Why its optional, if its enabled by default?

2024-09-03 12:10 UTC, sebastianbochan commented on ts/DataGrid/DataGrid.ts
> +                this.options = { dataTable: options.dataTable };
Suggestion: `(this.options || {}).dataTable = options.dataTable`

2024-09-04 12:04 UTC, stitot requested changes
Nice, but can we add target=_top to this link? Quite often datagrid will be in iframe, e.g. our own demos.

2024-09-05 07:02 UTC, stitot approved these changes

2024-09-05 07:16 UTC, sebastianbochan requested changes
IMO, credits should be disabled in Dashboards (DatagridComponent).
![Uploading Screenshot 2024-09-05 at 09.17.03.png…]()

2024-09-05 07:23 UTC, ddragula commented
> IMO, credits should be disabled in Dashboards (DatagridComponent) like it is in HC.

They are not disabled by default, they just have the credits manually disabled in the demos you are watching. Let's discuss this on daily.

2024-09-05 13:44 UTC, sebastianbochan approved these changes

2024-09-05 14:45 UTC, merged