Tools: Fixed Dashboards modification with Highcharts changelog.
highcharts/highcharts pull request #21779
Opened 2024-09-03 15:11 UTC by bre1470

2024-09-04 08:20 UTC, sebastianbochan commented
Initially `node changelog/generate --dashboards --release 2.4.0` returned the changelog for DB, however, currently it does not return anything.
All changes are applied to HC, with or without `--dashboards` flag.

2024-09-05 08:50 UTC, sebastianbochan requested changes
Can you edit the `changelog/readme.md` file as well. There is a different flag for dashboards.

2024-09-05 09:10 UTC, sebastianbochan approved these changes

2024-09-06 13:15 UTC, TorsteinHonsi approved these changes

2024-09-06 13:15 UTC, merged