dash/classList-editing-hc-component
highcharts/highcharts pull request #21774
Opened 2024-09-03 11:49 UTC by sebastianbochan

Fixed infinite classes when editing.

2024-09-03 15:41 UTC, ddragula commented on ts/Dashboards/Components/HighchartsComponent/HighchartsComponent.ts
> +            this.chartContainer.classList.value = this.options.chartClassName;
Won't this remove any other class names that should remain and not be replaced completely?

2024-09-04 09:40 UTC, ddragula approved these changes
👍 but let's wait for Karol

2024-09-09 05:55 UTC, karolkolodziej requested changes
Please do it similarly for DataGrid component in the dg2 branch: 
https://github.com/highcharts/highcharts/blob/294f677904ddbb2ac01c5d3a704cc81209a37ad7/ts/Dashboards/Components/DataGridComponent/DataGridComponent.ts#L283

2024-10-04 13:18 UTC, karolkolodziej approved these changes

2024-10-04 14:15 UTC, merged