feature/19780-non-cartesian-zooming
highcharts/highcharts pull request #21822
Opened 2024-09-11 15:14 UTC by hubertkozik

Non-cartesian zooming feature.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1207724993752890

2024-11-14 16:21 UTC, bre1470 reviewed
Supercool! But I only get the reset zoom button for arcdiagram, organization, sankey, and treegraph.

2024-12-09 13:21 UTC, KacperMadej reviewed
Looks really nice 🎉 Some points and questions:

- [ ] treegraph: mouse wheel seems to be working a bit off target - while zooming the point under the cursor is not preserved - although, this is also visible for other series types e.g. sankey (or even more visible for zoom out with mouse scroll for pie)
- [ ] treegraph: zoom mask is resizing correctly only for x and y seems to be using a fixed ratio for zooming type `'xy'` (also visible for other series types e.g. wordcloud)
- [ ] every other zoom selection after the 1st zoom-in is still based on the initial chart zoom level (drawing multiple rectangles for zooming-in leads to a mixed zoom-in - zoom-out result)
- [ ] Steps: zoom with selection > there is the zoom-out button > don't click it > zoom-in with mouse-scroll > the button is gone. Expected: the button stays.
- why no the timeline series type?
- axes have `zoomEnabled` that can be used to disable some. Could there be an option to disable zoom for a non-cartesian series? Might be useful for a combo charts.

2024-12-24 11:27 UTC, hubertkozik commented
@KacperMadej Thank you for the great feedback. I checked the fixed/added things from your list.

> Steps: zoom with selection > there is the zoom-out button > don't click it > zoom-in with mouse-scroll > the button is gone. Expected: the button stays.

The same behaviour can be seen for normal cartesian zooming: https://jsfiddle.net/BlackLabel/y6xgoj9e/ I am not sure if that is a bug though. If a bug, it should be handled in a different place.

> why no the timeline series type?

Timeline series is built on axes: https://jsfiddle.net/BlackLabel/r189f2dk/

2024-12-27 13:26 UTC, KacperMadej requested changes
- [ ] highcharts/series-treegraph/link-types - zoom selection works as expected horizontally but vertically the zoom doesn't match the selection.
Steps: 1. select a rectangle that clips 3 labels (e.g. like in the image here:
![image](https://github.com/user-attachments/assets/0085cf22-9416-4b87-8445-a38d192a4421)
2. the zoomed chart doesn't match the selection (e.g. the result from the previous step:
![image](https://github.com/user-attachments/assets/bd88b03a-7039-42d5-9153-3034d3924c31)
This is also visible with other series types, like pie.

- [ ] resize after zoom can lead to the chart jumping into a different part of the chart
![pieResizeAfterZoom](https://github.com/user-attachments/assets/cedc9a68-ac90-4cc1-9e02-86ebb061f02c)

2025-03-07 11:44 UTC, bre1470 approved these changes
Nice jobs. Works for me! 👍

I am just not sure about UX, might be better to have selection free and zoom based on top left corner or bottom right corner.

2025-03-07 11:44 UTC, bre1470 commented on samples/highcharts/demo/pie-chart/demo.js
> +        panKey: 'shift'
Zoom select rectangle has weird sizing effect along y-axis. Not sure, if this is by design, but it makes UX strange when first moving downwards than to the right side.

2025-03-07 11:44 UTC, bre1470 commented on samples/highcharts/demo/pie-chart/demo.js
> +        panKey: 'shift'
Maybe it is also because the tooltip covers the little rectangle. Can we disable tooltip while setting zoom range?

2025-03-27 10:00 UTC, KacperMadej approved these changes

2025-04-09 09:10 UTC, TorsteinHonsi requested changes
Thanks, great work! In addition to the inline comments:

* In the pie-chart demo, the clip is locked after zooming out. a) In the utils, click Mobile for the chart to be narrow. b) Zoom in, then out. c) Click Mobile again to revert do desktop. The clipping is now wrong.
* In demo/wordcloud, animation looks good when animating into the zoom, but not when animating back after clicking "Reset zoom".
* Discussion point: I find it a but cumbersome that the selection area's aspect ratio is locked to that of the plot area. I think it would be more comfortable if the size were free, and the aspect ratio be handled after releasing the zoom. So that all of the selected area would be part of the zoomed area, but with added padding on either sides. I think this was how Maps _used to_ work, but apparently [now it doesn't include the full area](https://jsfiddle.net/highcharts/jqcu5yb1/). With [Highcharts Maps v8](https://jsfiddle.net/highcharts/jqcu5yb1/1/) we can see how I think this should work. When zooming in on the extents of Africa, we get the full continent inside the plot area, plus some more land to the east and west to fill out the area.

2025-04-24 09:18 UTC, TorsteinHonsi approved these changes

2025-04-24 09:18 UTC, merged