dash/dg2-docs
highcharts/highcharts pull request #21835
Opened 2024-09-13 11:13 UTC by karolkolodziej

Added docs improvements.

2024-09-16 10:16 UTC, ddragula requested changes

2024-09-16 10:16 UTC, ddragula commented on docs/datagrid/datagrid-v2-migration.md
> +Since DataGrid v3.0.0 we removed the option:
I think it is more accurate:
```suggestion
Since Dashboards v3.0, we have removed the following option from the DataGrid:
```

2024-09-16 10:16 UTC, ddragula commented on docs/datagrid/datagrid-v2-migration.md
> +We recommend reading our [article about styling the DataGrid v3.0.0 and higher](https://www.highcharts.com/docs/datagrid/style-by-css).
```suggestion
We recommend reading our [article about styling the DataGrid in Dashboards v3.0 and higher](https://www.highcharts.com/docs/datagrid/style-by-css).
```

2024-09-16 12:07 UTC, stitot approved these changes
Nice!

2024-09-17 08:03 UTC, ddragula approved these changes
Thanks!

2024-09-17 10:56 UTC, sebastianbochan approved these changes

2024-09-17 10:56 UTC, merged