dash/dg2-cell-focus-state
highcharts/highcharts pull request #21842
Opened 2024-09-15 21:07 UTC by ddragula

- [x] Refactored cell events.
- [ ] Change cell edit trigger to double click.
- [ ] Implement cell focusing (single click).
- [ ] Add tests.

2024-09-16 13:24 UTC, ddragula commented
Thanks for the comment! On the one hand, I want to prepare the basis for accessibility, on the other, I don't want to do too much so as not to introduce changes that will have to be rolled back due to bad implementation that breaks a11y more than it fixes - I am not an expert on this topic, but I think it's important to do it soon.

I would also like to make sure that some sort of navigation etc. is actually possible before we conduct external a11y testing. I'll contact @marvin19 about this task, and I'll leave just the double-click edit with the focus off 'until Wednesday' if I can't discuss navigation and a11y in more detail by then.

2024-09-17 06:19 UTC, karolkolodziej requested changes
Looks like a solid foundation for future a11y work! 
I get a few failing cypress tests locally- could you please check?

2024-09-17 06:19 UTC, karolkolodziej commented on ts/DataGrid/Globals.ts
>          focusedCell: classNamePrefix + 'focused-cell',
this can be removed

2024-09-17 09:48 UTC, ddragula commented
I temporarily removed the features related to focusing because we want to merge this today (and several valuable changes have been made). This way, we avoid introducing an incomplete focus state without keyboard navigation. I'll move this to the next PR, which will go directly to the `master` branch if needed.

2024-09-17 10:09 UTC, stitot approved these changes
Looking good!

2024-09-17 10:50 UTC, sebastianbochan requested changes
DoubleClick is really tricky on touch devices (in many cases it does not work and some workarounds are needed).

Please test it on:
- native iPad (Safari + FF)
- desktop Firefox

2024-09-17 10:52 UTC, karolkolodziej approved these changes

2024-09-17 11:20 UTC, ddragula commented
@sebastianbochan Tested, works well on FF, Safari, iPhone.

2024-09-17 11:30 UTC, sebastianbochan approved these changes

2024-09-17 11:32 UTC, merged