bugfix/21220-multiple-axis-resize
highcharts/highcharts pull request #21857
Opened 2024-09-17 15:10 UTC by bm64

Fixed #21220, resizing panes with multiple axes was resulting in incorrect axis height.

2024-09-18 05:35 UTC, pawellysy requested changes
Would you consider adding a test :D?

2024-09-18 08:00 UTC, pawelfus approved these changes
Thanks!
I'm fine without the test for this one liner 👍

2024-09-18 09:25 UTC, kamil-musialowski approved these changes

2024-09-18 10:38 UTC, pawellysy approved these changes

2024-09-18 11:29 UTC, DJTechnoo approved these changes

2024-12-09 06:51 UTC, TorsteinHonsi approved these changes
Thanks!

2024-12-09 06:52 UTC, merged