dash/sticky-sidebar
highcharts/highcharts pull request #21870
Opened 2024-09-19 07:53 UTC by sebastianbochan

Added a sticky sidebar to the Dashboard.

2024-09-19 09:25 UTC, karolkolodziej requested changes
Looks and works good, but the position is off:
![image](https://github.com/user-attachments/assets/fe99eedb-5ca9-498d-bbf1-9216e0d4aba3)

2024-09-19 12:01 UTC, sebastianbochan commented
@karolkolodziej the issue is in the main branch, that I forked. It's caused by max-width and missing position relative in the demo container.

So it's not a part of this task.

2024-09-19 14:53 UTC, ddragula requested changes
Nice! Two comments:

1. When not needed, the scrollbar should not be displayed.
![image](https://github.com/user-attachments/assets/9af74e3f-a4d3-47a1-871f-9846f4e87319)

2. Do we want such a big margin here?
![image](https://github.com/user-attachments/assets/a5d09ee7-f3c9-4489-8e44-1453fc032e5b)

2024-09-20 07:38 UTC, karolkolodziej approved these changes

2024-09-20 07:38 UTC, karolkolodziej commented on ts/Dashboards/EditMode/EditMode.ts
> +        sticky?: boolean;
Please add a vertical demo as an example here.

2024-09-20 09:29 UTC, ddragula approved these changes
Good job!

2024-09-20 09:35 UTC, stitot requested changes
Really nice, and IMO a big improvement that form elements in sidebar are now visible in the viewport when you click charts further down the page, and that they stay visible on scroll! Some further tweaking is needed, though.

If you decrease height of browser window and/or expand multiple accordions in the sidebar the save/cancel button disappears below the fold. That's why I believe the sidebar should consist of 3 parts:

1. Header at top
2. Form with overflow:auto and 100% height
3. Footer with buttons that is absolute positioned at the bottom of sidebar.

Please have a look at the description and illustration at https://app.asana.com/0/1203234853779882/1208043991339536/f that shows this.

**In addition (most likely not stated to clear in dialog/Asana):**
The sidebar is now sticky in relation to `#container`, but I believe we need an option where it's sticky in relation to `body`. I assum it's a bigger refactoring job involved here, so in that case we should perhaps postpone until we start looking at the complete overhaul of editmode.

Otherwise: great job!

2024-09-30 13:54 UTC, stitot reviewed
Wow, really like this! 

Perhaps just add something like `box-shadow: rgb(0, 0, 0) 0px 0px 10px 0px` to it so it doesn't bleed into the background?

Nice work!

2024-09-30 13:55 UTC, stitot commented
And I see it's sticky in relation to `body` as well? Sweet!

2024-10-01 07:45 UTC, stitot commented
I would like background with rounded corners to be on the entire container, so that chart title is inside.

![Skjermbilde 2024-10-01 kl  09 44 05](https://github.com/user-attachments/assets/c957b2a7-5d2f-4172-b5e5-809d531e3743)

2024-10-01 13:14 UTC, stitot reviewed
Nice, but sadly I need the same background/padding on .highcharts-dashboards-component-caption

2024-10-02 08:22 UTC, stitot approved these changes

2024-10-02 08:29 UTC, merged