Fixed setting pie plot options with multiple data labels renders incorrectly
highcharts/highcharts pull request #21952
Opened 2024-10-03 11:24 UTC by Eskils

Fixed #21928, Setting plot options for pie-chart with multiple data labels does not work.

- Issue was resolved by merging data label options in pie plot options with the defaults. 
   + This was not already happening because the `merge` function does not merge arrays.
- Updated pie demos with multiple data labels to use pie plot options instead of series plot options. 
   + This seems more correct since the demos will not compile in TypeScript.

2024-10-04 05:54 UTC, goransle requested changes

2024-10-04 05:54 UTC, goransle commented on ts/Core/Chart/Chart.ts
> +            }
This should likely happen in `PieSeries.ts`. This seems to work:

```ts
addEvent(PieSeries, 'afterInit', (e): void => {
    const chart = e.target.chart;
    if (chart.options.plotOptions.pie) {
        PieSeries.mergePieDataLabelPlotOptions(chart.options.plotOptions.pie);
    }
});
```

Possibly the `update` or `setOptions` events can be used for processing when changing options.

2024-10-04 05:54 UTC, goransle commented on samples/unit-tests/series-pie/datalabel/demo.js
> +        assert.ok(
I would slightly prefer `assert.strictEqual` for test failure reporting

2024-10-04 08:21 UTC, Eskils commented
Thank you for your feedback! The `setOptions` event was what I needed.

2024-10-04 08:35 UTC, goransle approved these changes
Nice, looks good!

2024-10-07 07:54 UTC, hubertkozik commented
I think this problem is deeper than only for `PieSeries`. I tried to use the same config for the line series: https://jsfiddle.net/BlackLabel/a8grfdvc/ and sadly the error came up. That would mean, that your fix is not enough and we should fix it somewhere deeper in the code 😕

2024-10-07 07:54 UTC, hubertkozik requested changes
I think this problem is deeper than only for `PieSeries`. I tried to use the same config for the line series: https://jsfiddle.net/BlackLabel/a8grfdvc/ and sadly the error came up. That would mean, that your fix is not enough and we should fix it somewhere deeper in the code 😕

2024-10-08 18:01 UTC, Eskils commented
> I think this problem is deeper than only for `PieSeries`. I tried to use the same config for the line series: https://jsfiddle.net/BlackLabel/a8grfdvc/ and sadly the error came up. That would mean, that your fix is not enough and we should fix it somewhere deeper in the code 😕

Thank you for testing more broadly—good find! I added a unit-test for line-series and moved my patch to Series.ts.

2024-11-06 14:33 UTC, hubertkozik reviewed
Sorry for the long wait for review! The notification got lost somehow :(

2024-11-06 14:33 UTC, hubertkozik commented on samples/unit-tests/series-line/datalabel/demo.js
Do we need this new file and this QUnit test instance? Those instances are quite heavy, it is better and we are trying to add some code to the existing test because updates are lighter than creating new tests and new chart instances. Can you put it somewhere in existing test?

2024-11-06 14:33 UTC, hubertkozik commented on ts/Core/Series/Series.ts
> +        if (dataLabelOptions instanceof Array) {
I'm thinking about using `splat` function to simplify logic a little bit. Did you consider using `splat` and operating always on the array?

2024-11-11 17:00 UTC, Eskils commented on samples/unit-tests/series-line/datalabel/demo.js
Good point. I integrated the _series-line/datalabel_ test in the existing _series-line/linewidth_ test. This greatly reduced the test run duration.

The new tests in _series-pie/datalabel_ are already quite swift, and integrating them into existing tests had little to no effect so they are left unchanged (See attached image).

<img width="836" alt="Screenshot 2024-11-11 at 17 37 10" src="https://github.com/user-attachments/assets/5918509d-9785-403f-a1e6-8e0e8d86dd57">

2024-11-12 08:56 UTC, hubertkozik commented on ts/Core/Series/Series.ts
> +        if (dataLabelOptions instanceof Array) {
Right, got it!

2024-11-12 08:56 UTC, hubertkozik commented on samples/unit-tests/series-line/datalabel/demo.js
Nice! Thank you.

2024-11-13 09:45 UTC, TorsteinHonsi requested changes
Thanks!

Since we already have logic for this array-merging somewhere else, I think we should refactor to avoid repeating ourselves. There's two reasons for that - both lower code weight, and maintenance benefits if there are bugs in either place.

So I tried this approach that passes the tests:
```diff
diff --git a/ts/Core/Series/DataLabel.ts b/ts/Core/Series/DataLabel.ts
index ffef2466ff..653f40af27 100644
--- a/ts/Core/Series/DataLabel.ts
+++ b/ts/Core/Series/DataLabel.ts
@@ -110,6 +110,10 @@ declare module './SeriesLike' {
             alignTo?: BBoxObject,
             isNew?: boolean
         ): (boolean|undefined);
+        mergeArrays(
+            one: (DataLabelOptions|Array<DataLabelOptions>|undefined),
+            two: (DataLabelOptions|Array<DataLabelOptions>|undefined)
+        ) : (DataLabelOptions|Array<DataLabelOptions>);
         placeDataLabels?(): void;
         setDataLabelStartPos(
             point: ColumnPoint,
@@ -482,6 +486,7 @@ namespace DataLabel {
             seriesProto.alignDataLabel = alignDataLabel;
             seriesProto.drawDataLabels = drawDataLabels;
             seriesProto.justifyDataLabel = justifyDataLabel;
+            seriesProto.mergeArrays = mergeArrays;
             seriesProto.setDataLabelStartPos = setDataLabelStartPos;
             seriesProto.hasDataLabels = hasDataLabels;
         }
diff --git a/ts/Core/Series/Series.ts b/ts/Core/Series/Series.ts
index a63eb55eb2..955c07c6a2 100644
--- a/ts/Core/Series/Series.ts
+++ b/ts/Core/Series/Series.ts
@@ -818,16 +818,10 @@ class Series {
 
         // When plot options have multiple data labels, the default data label
         // plot options are not merged (#21928).
-        const dataLabelOptions = typeOptions.dataLabels;
-        if (dataLabelOptions instanceof Array) {
-            const dataLabelDefaults = defaultPlotOptionsType.dataLabels || {};
-            for (let i = 0; i < dataLabelOptions.length; i++) {
-                dataLabelOptions[i] = merge(
-                    dataLabelDefaults,
-                    dataLabelOptions[i]
-                );
-            }
-        }
+        typeOptions.dataLabels = this.mergeArrays?.(
+            defaultPlotOptionsType.dataLabels,
+            typeOptions.dataLabels
+        );
 
         // Use copy to prevent undetected changes (#9762)
         /**
```

The only thing that doesn't quite sit right here is that `mergeArrays` is a general utility function, but it is attached to the Series prototype for convenience. I think that is okay for now, since it is only used by the data label logic.

2024-11-13 09:45 UTC, TorsteinHonsi commented on ts/Core/Series/Series.ts
> +        // plot options are not merged (#21928).
This comment describes a situation that is no longer true. Instead, describe what the code actually does, and add a reference to the issue.
```suggestion
        // Merge in multiple data label options from the plot option (#21928).
```

2024-11-20 18:07 UTC, Eskils commented
Thank you for pointing this out. I’ve changed my code to your approach.

2025-01-08 15:32 UTC, TorsteinHonsi approved these changes

2025-01-08 15:32 UTC, merged