demo/temperature-range-color-axis
highcharts/highcharts pull request #21961
Opened 2024-10-07 08:55 UTC by bm64

Added color axis to column range stock demo.

2024-10-07 09:02 UTC, kamil-musialowski approved these changes

2024-10-07 13:45 UTC, pawelfus requested changes

2024-10-07 13:45 UTC, pawelfus commented on samples/stock/demo/columnrange/demo.html
> +<script src="https://code.highcharts.com/modules/coloraxis.js"></script>
Not a bug, but somehow I feel we should use `stock/modules/coloraxis.js` path (the file is the same)

2024-10-08 12:36 UTC, pawelfus approved these changes

2024-10-10 14:06 UTC, DJTechnoo approved these changes

2024-10-15 05:14 UTC, pawellysy approved these changes

2024-10-16 10:58 UTC, TorsteinHonsi approved these changes
Thanks!

2024-10-16 10:59 UTC, merged