feature/renko-series-type
highcharts/highcharts pull request #21966
Opened 2024-10-08 10:08 UTC by pawellysy

Created new series type: `Renko`. Closes #12524

2024-10-08 12:59 UTC, pawelfus requested changes

2024-10-08 12:59 UTC, pawelfus commented on ts/Series/Renko/RenkoSeriesDefaults.ts
> + * data point.
I think Renko focuses only on close prices.

2024-10-08 12:59 UTC, pawelfus commented on ts/Series/Renko/RenkoSeriesDefaults.ts
> + *    ]
Let's go with x+y values only.

2024-10-08 12:59 UTC, pawelfus commented on ts/Series/Renko/RenkoSeriesOptions.d.ts
> +     *        close: 7,
Let's rename to `y`, so we follow other cartesian series

2024-10-08 12:59 UTC, pawelfus commented on ts/Series/Renko/RenkoSeries.ts
> +        if (U.pushUnique(composed, 'pointandfigure')) {
Renko*

2024-10-10 14:05 UTC, DJTechnoo requested changes
Looks very good! Found a few typos

2024-10-10 14:05 UTC, DJTechnoo commented on ts/Series/Renko/RenkoSeriesDefaults.ts
> + * An Renko series is a style of financial chart used to describe price
```suggestion
 * A Renko series is a style of financial chart used to describe price
```

2024-10-10 14:05 UTC, DJTechnoo commented on ts/Series/Renko/RenkoSeriesOptions.d.ts
> + * An Renko series is a style of financial chart used to describe price
```suggestion
 * A Renko series is a style of financial chart used to describe price
```

2024-10-10 22:56 UTC, bm64 requested changes

2024-10-10 22:56 UTC, bm64 commented on docs/stock/renko.md
> +    pointFormat: ' style="color:{point.color}">\u25CF</span> {series.name}: <b>{point.y}<br/>'
Missing starting `span` tag

2024-10-11 11:27 UTC, pawelfus requested changes
In addition to the comments below:

1. It seems the API ref is missing: 
![image](https://github.com/user-attachments/assets/67e2110f-0290-450a-bc95-f932030f24f4)

2024-10-11 11:27 UTC, pawelfus commented on docs/stock/renko.md
> +Highcharts optimizes viewer experience with large datasets by providing data grouping options. However, the dataGrouping is disabled for renko series, because it does not make sense to group those po
dataGrouping -> `dataGrouping`

2024-10-11 11:27 UTC, pawelfus commented on docs/stock/renko.md
> +STEP 3: Applying tone of voice rules.
Nice

2024-10-11 11:27 UTC, pawelfus commented on docs/stock/renko.md
> +FINAL_RESULT:# Highcharts: Introducing Renko Series
Nice

2024-10-11 11:27 UTC, pawelfus commented on docs/stock/renko.md
> +The Renko series that Highcharts provides is a valuable way of visualizing price data. By focusing on significant price changes and omitting time and minor swings, it becomes a handy resource for tra
It seems we have two articles in one :)

2024-10-11 11:27 UTC, pawelfus commented on samples/stock/demo/renko-vs-heikinashi-vs-candlestick/demo.details
> +  - Karol Kolodziej
Who?

2024-10-11 11:27 UTC, pawelfus commented on samples/stock/demo/renko-vs-heikinashi-vs-candlestick/demo.details
> +name: Heikin Ashi
Name

2024-10-11 11:27 UTC, pawelfus commented on samples/stock/demo/renko-vs-heikinashi-vs-candlestick/demo.html
This should be in samples, not demos

2024-10-11 11:27 UTC, pawelfus commented on samples/stock/demo/stock-tools-gui/demo.js
Unexpected changes?

2024-10-11 11:27 UTC, pawelfus commented on ts/Series/Renko/RenkoSeriesOptions.d.ts
> +     *        close: 7,
Still incorrect.

2024-10-11 11:27 UTC, pawelfus commented on ts/Series/Renko/RenkoSeriesOptions.d.ts
> +     * @excluding y
Why excluding `y`?

2024-10-14 19:03 UTC, pawellysy commented on docs/stock/renko.md
> +Renko, a Japanese term that signifies "brick", is a charting method commonly used for technical securities trading. The unique aspect of [Renko charts](https://www.investopedia.com/terms/r/renkochart
we do not, but skald suggested that 😓

2024-10-14 19:11 UTC, pawellysy commented on docs/stock/renko.md
> +FINAL_RESULT:# Highcharts: Introducing Renko Series
😓

2024-10-14 19:13 UTC, pawellysy commented on samples/stock/demo/renko-vs-heikinashi-vs-candlestick/demo.html
any particular dir it should be in?

2024-10-15 07:50 UTC, DJTechnoo approved these changes
LGTM! Great job

2024-10-16 11:41 UTC, bm64 approved these changes
lgtm

2024-10-17 11:02 UTC, pawelfus requested changes
A few API requests:

- [ ] Options from API ref to remove:
- boost (and all derivatives)
- cumulative (and all derivatives)
- dataSorting
- dragDrop

- [x] Some of the options are removed from `plotOptions.renko` but still available under `series.renko` (eg http://localhost:9005/highstock/series.renko.dataGrouping).

- [x] A narrow chart is missing the navigator series - could it be an issue with DG? Demo: https://jsfiddle.net/Ln2gs69z/

- [x] Colors (up/down) are missing in styledMode: https://jsfiddle.net/Ln2gs69z/1/ 

- [x] `setData` seems to be broken: https://jsfiddle.net/Ln2gs69z/3/

2024-10-18 11:41 UTC, kamil-musialowski requested changes
Minor typos, other than that looks really well 👏

2024-10-18 11:41 UTC, kamil-musialowski commented on samples/stock/demo/renko-vs-heikinashi-vs-candlestick/demo.details
> +  - Pawel lysy
```suggestion
name: Renko vs Heikin Ashi vs Candlestick
authors:
  - Pawel Lysy
```

2024-10-18 11:41 UTC, kamil-musialowski commented on samples/stock/plotoptions/renko-boxsize/demo.details
> +  - Pawel lysy
```suggestion
name: Renko series
authors:
  - Pawel Lysy
```

2024-10-18 11:41 UTC, kamil-musialowski commented on ts/Series/Renko/RenkoSeriesOptions.d.ts
> + * An Renko series is a style of financial chart used to describe price
```suggestion
 * A Renko series is a style of financial chart used to describe price
```

2024-10-18 11:44 UTC, kamil-musialowski commented
Switching the series type via Stock Tools also doesn't work for this series, so I'd suggest adding a new issue like this one: https://github.com/highcharts/highcharts/issues/22021

2024-10-27 13:28 UTC, TorsteinHonsi reviewed
Hey, thanks for the PR! I'm commenting early here - like the P&F series we need to refactor this to work with the v12 DataTable architecture. See the other PR for details.

2024-10-31 12:59 UTC, kamil-musialowski requested changes

2024-10-31 12:59 UTC, kamil-musialowski commented on samples/stock/demo/renko-vs-heikinashi-vs-candlestick/demo.js
> +            data: data
```suggestion
            data
```

2024-10-31 12:59 UTC, kamil-musialowski commented on samples/stock/demo/renko-vs-heikinashi-vs-candlestick/demo.js
> +            data: data
```suggestion
            data
```

2024-10-31 12:59 UTC, kamil-musialowski commented on samples/stock/demo/renko-vs-heikinashi-vs-candlestick/demo.js
> +            data: data,
```suggestion
            data
```

2024-10-31 12:59 UTC, kamil-musialowski commented on samples/stock/plotoptions/renko-boxsize/demo.js
> +                yAxis: 0,
Do we need this `yAxis`? 🤔

2024-10-31 12:59 UTC, kamil-musialowski commented on ts/Series/Renko/RenkoSeries.ts
> +                modified: this.dataTable.modified,
```suggestion
                modified,
```

2024-10-31 12:59 UTC, kamil-musialowski commented on ts/Series/Renko/RenkoSeries.ts
> +            modified: modified,
```suggestion
            modified,
```

2024-10-31 12:59 UTC, kamil-musialowski commented on ts/Series/Renko/RenkoSeriesDefaults.ts
> + * An Renko series is a style of financial chart used to describe price
```suggestion
 * A Renko series is a style of financial chart used to describe price
```

2024-11-04 09:48 UTC, TorsteinHonsi requested changes
Thanks, nice work! Only one minor grammatical issue from my end.

2024-11-04 09:48 UTC, TorsteinHonsi commented on docs/stock/renko.md
> +By default, for a brief overview of the price data, smaller Renko chart is beneath the main chart using the `navigator` feature:
```suggestion
By default, for a brief overview of the price data, a smaller Renko chart is beneath the main chart using the `navigator` feature:
```

2024-11-04 11:37 UTC, pawelfus requested changes
I don't see `series.data` anymore in API ref. The other options are displayed properly:
![Zrzut ekranu 2024-11-4 o 12 36 17](https://github.com/user-attachments/assets/097e5e90-e47b-45bc-8a6e-69f2166d5aa6)

2024-11-04 13:09 UTC, kamil-musialowski approved these changes

2024-11-07 12:49 UTC, DJTechnoo approved these changes
👏

2024-11-08 14:22 UTC, pawelfus approved these changes
Thanks!!

2024-11-11 08:06 UTC, TorsteinHonsi approved these changes

2024-11-11 08:06 UTC, merged