bugfix/range-selector-dropdown-alignment
highcharts/highcharts pull request #21989
Opened 2024-10-10 11:17 UTC by bm64

wip

2024-10-17 08:06 UTC, pawellysy requested changes
Please invastigate the visual diff

2024-10-21 07:19 UTC, pawellysy approved these changes
Looks good to me! @pawelfus Should we consider adding some tests?

2024-10-21 09:32 UTC, pawelfus requested changes
Missing test. I know we have plenty of visual tests, but somehow this regression got through. 

Could you create a generic test, which will check different positions and overlapping? I mean something like all left, all right, combinations.

The code looks good. Visual changes too.

2024-10-24 11:25 UTC, pawelfus requested changes
Minor change, see below

2024-10-24 11:25 UTC, pawelfus commented on ts/Stock/RangeSelector/RangeSelectorDefaults.ts
> +         * @sample {highstock} stock/rangeselector/input-button-opposite-alignment/
Use both demos here (and below)

2024-10-25 12:35 UTC, pawelfus approved these changes
Thanks!

2024-10-25 15:40 UTC, kamil-musialowski approved these changes
nice!

2024-11-01 14:48 UTC, DJTechnoo approved these changes

2024-12-09 06:49 UTC, TorsteinHonsi approved these changes
Thanks!

2024-12-09 06:49 UTC, merged