Fixed missing points in scatter series with boost
highcharts/highcharts pull request #22000
Opened 2024-10-14 08:03 UTC by Eskils

Fixed #21897 missing points in scatter series with boost

This fix changes the behavior for scatter and bubble series (where sorted is false).  The optimization attempts made in `pushSeriesData` does not work for these series and so are bypassed. 

Two new samples are added to test and make sure no regressions occur:
- samples/issues/boost/19701-points-outside-zoom-range-visible-in-scatter
- samples/issues/boost/21897-missing-points-in-scatter-series

2024-10-16 07:40 UTC, bre1470 requested changes
Fix seems to work! 👍
The visual tests should be merged into `samples/highcharts/boost/scatter/` to save overhead, just expand there the setup to cover you second test. `samples/issues` is legacy.

2024-10-16 18:21 UTC, Eskils commented
Thank you for pointing this out. 

I moved the samples to `samples/highcharts/boost`. Not sure what you mean with expanding the tests in `samples/highcharts/boost/scatter`—can there be multiple visual tests in one sample? 

Maybe I misunderstand?

2024-10-18 10:19 UTC, goransle approved these changes
I agree with the points above☝️, but otherwise LGTM

2024-10-23 08:35 UTC, Eskils commented
I converted the visual test into a unit test.

2024-11-21 10:24 UTC, bre1470 approved these changes
Sorry for the delay. Looks good! 👍

2024-11-25 06:34 UTC, TorsteinHonsi requested changes
Thanks, nice work! Just nitpicking on the language of the comments.

2024-11-25 06:34 UTC, TorsteinHonsi commented on ts/Extensions/Boost/WGLRenderer.ts
> +            // Boost fails to render scatter series with a single point (#21897)
"Boost fails..." describes a situation that is no longer true, so this comment would be confusing to the future us. This is more precise:
```suggestion
            // Make sure series with a single point are rendered (#21897)
```

2024-11-25 06:34 UTC, TorsteinHonsi commented on ts/Extensions/Boost/WGLRenderer.ts
> +            // Scatter points outside zoomed range were visible (#19701)
Describe how the code actually works, not how it used to fail at some point:
```suggestion
            // Do not render points outside the zoomed range (#19701)
```

2024-11-27 13:25 UTC, Eskils commented
Thank you for your insight. I will change my other PRs if I have made the same mistake there. 😅

2024-12-03 07:35 UTC, TorsteinHonsi approved these changes

2024-12-03 07:35 UTC, merged