dash/grouped-samples-demopage
highcharts/highcharts pull request #22001
Opened 2024-10-14 12:12 UTC by sebastianbochan

Assigned demos into two categories.

2024-10-14 13:00 UTC, ddragula approved these changes

2024-10-14 19:30 UTC, karolkolodziej approved these changes
Looks good, I would only check the priorities with someone from the demo pages 😉

2024-10-14 19:30 UTC, karolkolodziej commented on samples/dashboards/demo/cloud-monitoring/demo.details
>          priority: 1
Accounting already has the same priority. Won't it be an issue?

2024-10-14 20:12 UTC, stitot requested changes
Looks good, but a cleanup suggestion: let's add `priority` in each `demo.details` in both categories, in increments of 10. That way we have full control on order of demos, and we can add new ones were we want.

2024-10-15 07:12 UTC, stitot reviewed
IMO we should use increments of 10 in `priority`, meaning 10,20,30 etc. instead of 1,2,3 etc. That way we can inject new demos where we want without adjusting every single `priority` each time. Your call.

2024-10-15 10:19 UTC, sebastianbochan commented
I'm not convinced, because of requests to add more categories, set different orders, etc. For me, it's only artificially flexibly.

2024-10-15 11:34 UTC, stitot requested changes
Aaaaaaalmost there

2024-10-15 11:34 UTC, stitot commented on samples/dashboards/demo/accounting/demo.details
>         priority: 1
```suggestion
       priority: 10
```

2024-10-15 11:34 UTC, stitot commented on samples/dashboards/demo/minimal/demo.details
>          priority: 1
```suggestion
        priority: 10
```

2024-10-15 11:50 UTC, stitot approved these changes

2024-10-15 11:54 UTC, merged