feat/21975-4-and-8-digit-color
highcharts/highcharts pull request #22074
Opened 2024-10-28 14:27 UTC by Xillez

Fixed #21975, Added support for 4 & 8 digit hex colors

2024-10-29 08:43 UTC, bre1470 requested changes
There are opportunities to save much more space.
- [x] Just extend the 3 digit and 6 digit RegExps with an addition optional group and change the `1` as a fallback, if the optional group is empty.
- [x] Make use of the `i` flag in RegExp, so that you do not have to write down both letter cases.

2024-10-29 09:00 UTC, KacperMadej approved these changes
Readability and the tests are great. LGTM 👍

2024-10-29 13:40 UTC, Xillez commented
@bre1470 I find this way much more readable and simpler than the bit masking method below. Usually I tend to avoid bit-wise operations at all cost because they are very hard to understand and non-intuitive (although very fast). Could it be a middle ground if I re-wrote the 3 and 6 and merged them into the 4 and 8 versions above if possible or?

2024-10-29 14:07 UTC, bre1470 commented
@Xillez Yes, sounds good! 👍 Just merge the functionality as all cases are very similar.

2024-10-30 11:57 UTC, bre1470 approved these changes
Thank you! Looks good. 👍

2024-11-06 08:46 UTC, KacperMadej approved these changes

2024-11-06 09:03 UTC, TorsteinHonsi approved these changes
Awesome, thanks!

2024-11-06 09:03 UTC, merged