bugfix/21955-dash-nested-toggle
highcharts/highcharts pull request #22089
Opened 2024-10-30 15:21 UTC by sebastianbochan

Fixed #21955, nested group was rendered when empty options.

2024-10-31 17:55 UTC, ddragula requested changes
The checkbox has moved to a new line. Can you fix it?
<img width="291" alt="image" src="https://github.com/user-attachments/assets/79faed69-1477-4546-878c-8e4173c17aee">

2024-11-01 08:29 UTC, sebastianbochan commented
> The checkbox has moved to a new line. Can you fix it? <img alt="image" width="291" src="https://private-user-images.githubusercontent.com/46498046/382062980-79faed69-1477-4546-878c-8e4173c17aee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzOTc3MzEsIm5iZiI6MTczMDM5NzQzMSwicGF0aCI6Ii80NjQ5ODA0Ni8zODIwNjI5ODAtNzlmYWVkNjktMTQ3Ny00NTQ2LTg3OGMtOGU0MTczYzE3YWVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDE3NTcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1NmU0ODg5NDY1ZmEzM2E5ODdkZDNlMGM5Yjg3N2I1MzkyNTY4MWNkZjZkODYzODhiMmQyYThiMGY5MTEyZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RcWvxOgNqlwe-vZ4lM0hihBO9sbsfJ6jjtPYlBwqGxA">

Please double-check if everything is up-to-date.

<img width="781" alt="Screenshot 2024-11-01 at 09 28 48" src="https://github.com/user-attachments/assets/25435326-6599-44fd-b8c7-548b01a63458">

2024-11-04 08:46 UTC, ddragula approved these changes
Forgot to update CSS in the fiddle. All works now!

Approved, apart from what Karol has already brought up.

2024-11-04 12:38 UTC, karolkolodziej approved these changes

2024-11-04 13:46 UTC, merged