dash/dg-perf
highcharts/highcharts pull request #22139
Opened 2024-11-12 12:26 UTC by karolkolodziej

Improved performance when scrolling.

PS. I haven't found any easy way to test it.

2024-11-12 14:08 UTC, sebastianbochan requested changes

2024-11-12 14:08 UTC, sebastianbochan commented on ts/DataGrid/Table/Actions/RowsVirtualizer.ts
> +            }
In both (IF and ELSE) all lines (except the last one) are the same. So I think that we can optimize it.

2024-11-12 15:25 UTC, ddragula requested changes
Nice! This seems to work fine for `rows.strictHeights: true`, but not when rows heights are set automatically. (See the `data-grid/basic/scroll-to-row` sample). I will test some more cases.

2024-11-20 13:36 UTC, sebastianbochan commented
I found another bug.
1. Run the demo and scroll to the bottom (by handle)
2. use a trackpad to scroll up.
3. Rows disappear.

![scrolling](https://github.com/user-attachments/assets/c9784734-ba56-44c0-a346-a985873032b7)

2024-11-26 08:23 UTC, closed without merging