Fixed disappearing circle marker on scrollable scatter
highcharts/highcharts pull request #22163
Opened 2024-11-15 13:45 UTC by Eskils

Fixed #21701, Disappearing circle marker on scrollable scatter charts

## Cause
This issue is caused by a floating point accuracy error.

Highcharts creates the arc at offset like so: 
```
M 4884.5 137
A 4 4 0 1 1 4884.5001999999995 136.999999995
Z
```

The end x-value for the arc, 4884.5001999999995 is represented in 32-bit floating point (IEEE 754) as 4884.5. Same story with the y-value.

Since the end point of the arc is effectively the same as the start point, the arc command is simply ignored by the user-agents.

## Resolution

Changed arc renderer to use relative coordinates.

2024-11-25 12:43 UTC, hubertkozik requested changes
The fix works and looks really good to me, but the test needs some adjustments 😁

2024-11-25 12:43 UTC, hubertkozik commented on samples/unit-tests/svgrenderer/symbol/demo.js
This test is passing even on the master branch, tested here: https://jsfiddle.net/BlackLabel/nfa4bdyv/

2024-12-04 12:29 UTC, Eskils commented
Ready for review @MarkusBarstad @hubertkozik

2024-12-17 09:40 UTC, hubertkozik commented on samples/unit-tests/svgrenderer/symbol/demo.js
Not beneficial, thanks!

2024-12-17 09:42 UTC, hubertkozik approved these changes
LGTM!

2025-01-08 12:05 UTC, MarkusBarstad approved these changes
LGTM!

2025-01-09 07:50 UTC, TorsteinHonsi reviewed
Thanks, this is a nice approach!

This fixes a regression that was introduced by changing the `proximity`, which is itself a patch for issues with rounding. Then we have https://github.com/highcharts/highcharts/pull/22465 that deals with the same problem. So we are basically just adding patches for the same fundamental problem. 

I think we should take a step back and look again at these patches. Could your approach with relative coordinates resolve all the issues? Why not always use relative coordinates?

Or as a completely different approach - maybe we should split the fill-circle arc into two half-circle arcs to avoid the rounding issues altogether? 

@KacperMadej FYI

2025-01-10 07:57 UTC, Eskils commented
Thank you for taking a look, and for your insights.

I tested my patch (with relative coordinates for all circles) on https://github.com/highcharts/highcharts/pull/22465 (Kacper’s issue) and Kacpers patch on https://github.com/highcharts/highcharts/pull/21701 (This issue). And we _don’t_ solve each other's issues.

### Why not use relative coordinates all the time

When testing this patch, many of the visual tests were failing with major flaws (For example `highcharts/demo/polar-advanced`, see image).  I determined that it was better to use relative coordinates only for the failing edge cases, since the absolute coordinates work well for most purposes, and because I worried such a change might invoke many regressions.

<img width="431" alt="Screenshot 2025-01-10 at 08 52 10" src="https://github.com/user-attachments/assets/0e172eb6-0cb7-49bc-9fec-6ffa2e242f75" />

### Using two half arcs

Like Kacper has pointed out, two arc commands would be twice as many draw commands and might impact performance. This change might also cause regressions. 

### Conclusion

I also tested applying both mine and Kacper’s patch and that would solve both issues. I therefore believe applying both my patch and Kacper’s patch is the safest approach.

2025-01-10 12:55 UTC, TorsteinHonsi commented
Okay, thanks for the explanation! I agree that two halves, at least theoretically, may affect performance. In my experience added segments like that has very little impact, but if we can avoid it it would probably be better.

I still think we're patching a patch though. The proximity hack and this new hack deals with the same problem, and we want to keep the complexity down. Issue #22163 is simply fixed by changing the constant used for calculating the proximity to 0.0003 instead of 0.0002.

`proximity = 0.0003 / (options.borderRadius ? 1 : Math.max(rx, 1)),`

And still the cases in #20586 are good. So unless there are other flaws with that approach, I think we should stick with it.

2025-01-13 18:36 UTC, Eskils commented
We can keep changing the proximity value, but that does not actually solve the problem. To illustrate my point, you can just increase the position of the test circle from `5_000.5` to `10_000.5` to make the test fail with your suggested proximity. (See image)

<img width="1320" alt="Changing the circle position to 1000.5 makes the test fail" src="https://github.com/user-attachments/assets/59830ca9-6308-43e2-ad8b-abeee8938d51" />

I understand the desire to keep the code as simple as possible, but this might just be shoving the problem under a rug until someone makes a larger chart than #21701.

2025-09-26 10:31 UTC, closed without merging