bugfix/21994-ally-legend-button-offset
highcharts/highcharts pull request #22217
Opened 2024-11-25 12:51 UTC by Xillez

Fixed #21994, legend a11y proxy elements not tracking legend items correctly

---

I couldn't manage to make it as a normal unit test nor cypress test due to not being able to programmatically scroll down through the nested iframe structures.

2024-12-06 12:23 UTC, KacperMadej requested changes

2024-12-06 12:23 UTC, KacperMadej commented on ts/Accessibility/ProxyElement.ts
> +            const scrollTop = window.scrollY ||
Use `H.win` instead of `window` and `H.doc` instead of `document`.

2024-12-16 14:48 UTC, KacperMadej approved these changes

2025-01-10 07:01 UTC, bre1470 approved these changes
Looks good! 👍

2025-01-10 12:34 UTC, merged