dash/dg-perf-with-nonvirtual
highcharts/highcharts pull request #22222
Opened 2024-11-26 08:23 UTC by karolkolodziej

Improved performance when scrolling.

2024-11-27 09:40 UTC, sebastianbochan approved these changes

2024-11-27 11:18 UTC, ddragula requested changes
Unfortunately, it doesn't work with sorting. Need to be investigated more.

2024-12-03 09:02 UTC, ddragula approved these changes
It seems to work! 🎉

2024-12-03 09:10 UTC, sebastianbochan approved these changes

2024-12-03 09:11 UTC, merged