Fixed #21299, amended scrollbar and navigator margin settings
highcharts/highcharts pull request #22323
Opened 2024-12-09 12:45 UTC by AndrzejBuleczka

Fixed #21299, amended scrollbar and navigator margin settings

2024-12-09 14:03 UTC, kamil-musialowski requested changes
One small comment for start 🤔 

@pawelfus Are we cool with such visual diff?

2024-12-09 14:03 UTC, kamil-musialowski commented on ts/Stock/Navigator/Navigator.ts
> +                }
Can we do it that way?

```suggestion
            if (navigator.navigatorEnabled && !isNumber(options.margin)) {
                  options.margin = chart.inverted ? -3 : 3;
```

2024-12-09 14:19 UTC, AndrzejBuleczka commented on ts/Stock/Navigator/Navigator.ts
> +                }
pewnie!

2024-12-09 14:30 UTC, kamil-musialowski requested changes
Lint error :)

2024-12-09 15:28 UTC, kamil-musialowski commented
@AndrzejBuleczka also have a look at the contribution guide https://github.com/highcharts/highcharts/blob/master/CONTRIBUTING.md and change the title to something more descriptive, as it will be visible in the [changelog](https://www.highcharts.com/blog/changelog/) later.

I.e the message in the PR should look like this:
Fixed https://github.com/highcharts/highcharts/issues/21299, scrollbar and navigator margin settings were incorrect.

2024-12-09 15:31 UTC, kamil-musialowski requested changes
See comment above

2024-12-11 11:26 UTC, pawelfus requested changes
That's a lot of visual changes - we should avoid that, as described in https://github.com/highcharts/highcharts/issues/21299#issuecomment-2382918264

2024-12-13 13:46 UTC, AndrzejBuleczka commented
Thanks @pawelfus for the comments, I added tests, and as for the visual changes, I don't see how this can be fixed without it, and am more than open for suggestions in this respect. The core issue was that the scrollbar margin was not counted into spacing calculation for the navigator group, so the fix causes the minimal shift of the whole navigator group.

2025-01-21 11:00 UTC, AndrzejBuleczka commented
Setting default margin to 22 does the trick, thanks @pawelfus!

2025-01-23 13:21 UTC, pawelfus requested changes
Thanks! How about the margin when the navigator is disabled, but scrollbar enabled? Please take a look at the remainder of the visual differences.

2025-02-06 12:00 UTC, AndrzejBuleczka commented
With the kind help of @kamil-musialowski I've spotted one inconsistent bit about standalone scrollbar margin and we fixed it, the remaining visual differences seem to be expected and are caused by the changes introduced.

2025-02-06 13:20 UTC, kamil-musialowski approved these changes
I think we have it, nice!

2025-02-06 13:20 UTC, kamil-musialowski commented on ts/Stock/Navigator/Navigator.ts
> +        if (chart.options.scrollbar?.enabled) {
You've even managed to find another one - good job! 🎊

2025-02-06 20:36 UTC, AndrzejBuleczka commented on ts/Stock/Navigator/Navigator.ts
> +        if (chart.options.scrollbar?.enabled) {
Learning from the best 😄

2025-02-11 06:57 UTC, TorsteinHonsi approved these changes
Thanks!

2025-02-11 06:58 UTC, merged