demo/improve-stock-step-line
highcharts/highcharts pull request #22340
Opened 2024-12-10 19:49 UTC by kamil-musialowski

Added last price label to the stock step line demo.

Based on https://github.com/highcharts/highcharts/pull/22214

2024-12-11 06:28 UTC, pawellysy approved these changes

2024-12-11 09:37 UTC, pawelfus requested changes
Dataset update missing

2024-12-13 12:37 UTC, pawelfus requested changes
Thanks! Looks good a few minor things though:


1. Series ends in 2025, but should in 2024 :) 
2. I'm not convinced to use a dotted line. I would rather avoid that.
3. How about we improve the demo's description with more details about what demo presents?
4. Legend for mobile screen looks good, but for wider, let's use proximate on the right side:
<img width="895" alt="image" src="https://github.com/user-attachments/assets/2976455e-0439-4ac7-84e9-ddd5ac74fccb" />

2024-12-13 12:37 UTC, pawelfus commented on samples/stock/demo/step-line/demo.js
> +            text: 'Recurring stock investment simulator'
Q: How about simply an `Investment simulator`? It doesn't have to be stock, might be cash, or other asset, right?

2024-12-15 11:56 UTC, bm64 approved these changes

2024-12-30 13:46 UTC, pawelfus approved these changes
Thanks!

2025-01-03 07:59 UTC, TorsteinHonsi commented
Thanks!

It looks good, but there is some behavior on scrolling that may be unwanted, at least it feels a bit strange:


https://github.com/user-attachments/assets/a5d78b1c-b57a-4679-b68d-c68e597d05e6

1. The last price label sticks even when we scroll so that the last point is outside the viewable area. Is that wanted? It is kind of orphaned and not intuitive what it is.
2. As we scroll, and the length of the tick labels vary, the plot are jumps right and left. Maybe this is a case for a fixed `chart.marginRight`?

2025-01-03 09:27 UTC, pawelfus commented
> The last price label sticks even when we scroll so that the last point is outside the viewable area. Is that wanted? It is kind of orphaned and not intuitive what it is.

Well, this is kind of standard in Stock, to display the last value on the yAxis for each series, using corresponding colors, even when you don't see that last point (or especially then). But it doesn't mean we can't improve it. Alternatively, we could use the legend, and display value there. Quite common usage too. I tried to use `labelFormat`, but it's not obvious how to best use format there. A helper to get the last value? 

> As we scroll, and the length of the tick labels vary, the plot are jumps right and left. Maybe this is a case for a fixed chart.marginRight? Or maybe better, render the axis labels inside the plot area so that their size don't affect the plot area.

Tried fixed margin right, but it's quite big one (~300px) for wide screens and looks strange. Labels inside the plotting area decreases the readability of the last points on the chart, during zooming. I think we should resign from dynamic numeric symbols in this demo, and just use full numbers. 

I suggest results like this: https://jsfiddle.net/grqtudjb/3/

<img width="734" alt="image" src="https://github.com/user-attachments/assets/306704f6-1349-45a1-ba66-e6b3efe985c0" />


Note: I don't see thousands separator. It should default to locale, right? So there should be a space 🤔

2025-04-22 13:45 UTC, pawelfus approved these changes
Thanks!

With this config, it could be linked to both, Responsive options and Templating. Not sure if we need overscroll options here though.

2025-04-23 08:33 UTC, TorsteinHonsi requested changes
Thanks!

In addition to the inline comments:

> Tried fixed margin right, but it's quite big one (~300px) for wide screens and looks strange. Labels inside the plotting area decreases the readability of the last points on the chart, during zooming. I think we should resign from dynamic numeric symbols in this demo, and just use full numbers.

With the current design, full numbers outside the plot area, I think it is too much clutter going on. The axis labels come in between the lines and their legend items, making it less clear. Besides, two full decimals can be considered overkill when the scale is by the thousands. 

**Two many labels floating around:**
![Skjermbilde 2025-04-23 kl  10 23 37](https://github.com/user-attachments/assets/a717fc3a-7852-435f-8799-bca6f93a2b00)

What about we just [left-align the y-axis instead](https://jsfiddle.net/zp6dcn5e/)? We already have the numbers inside the legend, and now the whole right side looks cleaner.

2025-04-23 08:33 UTC, TorsteinHonsi commented on samples/stock/demo/step-line/demo.html
> +        investment over time. Blue step line represents the invested amount, in
```suggestion
        investment over time. The blue step line represents the invested amount, in
```

2025-04-23 08:33 UTC, TorsteinHonsi commented on samples/stock/demo/step-line/demo.html
> +        this case 200EUR each 30 days. Purple line represents the actual
```suggestion
        this case 200EUR each 30 days. The purple line represents the actual
```

2025-04-23 08:33 UTC, TorsteinHonsi commented on samples/stock/demo/step-line/demo.js
> +        return points[points.length - 1].y.toFixed(2);
This causes a crash when toggling between desktop and mobile views in the utils. 

`Cannot read properties of undefined (reading 'y')`

2025-04-23 08:33 UTC, TorsteinHonsi commented on samples/stock/demo/step-line/demo.js
> +                pointInterval: 86400000 // One day
Using `pointIntervalUnit` is generally safer/better practice, as it will adjust to DST in local time zones.
```suggestion
                pointIntervalUnit: 'day'
```

2025-04-23 10:28 UTC, TorsteinHonsi requested changes

2025-04-29 10:14 UTC, TorsteinHonsi approved these changes

2025-04-29 10:14 UTC, merged