Fixed syntax in Your First Dashboard
highcharts/highcharts pull request #22351
Opened 2024-12-11 13:20 UTC by jomar-honsi

Removed ordered lists, fixed minor issues.

2024-12-12 07:59 UTC, karolkolodziej approved these changes

2024-12-12 15:53 UTC, sebastianbochan approved these changes

2024-12-12 15:54 UTC, ddragula approved these changes
Thanks!

2024-12-13 14:06 UTC, stitot requested changes
I was probably unclear on what I wanted to achieve here. My bad. I would like to keep the step by step thing, but with headers, not as a list. Se https://www.highcharts.com/docs/datagrid/general for inspiration.

Short and to the point` ## Headers`, that will provide the outline of the process in the right navigation menu.

2024-12-13 14:06 UTC, stitot commented on docs/dashboards/types-of-components.md
> +### **Abstract Syntax Tree (AST) style**
On a general basis we shouldn't use ** in #. Let the CSS handle formatting of headers.

2024-12-13 14:06 UTC, stitot commented on docs/dashboards/types-of-components.md
> +### **HTML string**
Remove **

2024-12-17 09:38 UTC, stitot requested changes
Great work! Small details, but big impact on clarity.

2024-12-17 13:40 UTC, stitot approved these changes
Thanks!

2024-12-17 14:06 UTC, merged