demo/stock-area-improvements
highcharts/highcharts pull request #22374
Opened 2024-12-14 17:24 UTC by kamil-musialowski

Added lastPrice module to stock area demos.

2024-12-15 11:55 UTC, bm64 approved these changes

2024-12-16 09:04 UTC, pawellysy approved these changes

2025-01-02 12:12 UTC, pawelfus approved these changes
Thanks!

2025-01-02 15:02 UTC, DJTechnoo approved these changes

2025-01-03 11:11 UTC, TorsteinHonsi commented
Thanks!

I'm wondering what's the deal with the alignment though. In these two demos, apparently you set a `spacingRight` value, and moved the y-axis label outside the pane. Nevertheless, the `lastPrice` label actually covers the last point. If the axis labels were shorter and the last-price label longer, we would get more overlap.

If I set a large `chart.marginRight`, I would expect the last-price label to use the empty space, but instead it aligns to the plot area, covering up the point is is supposed to highlight: https://jsfiddle.net/d8b10yk3/

Maybe we should fix this and allow the label to be placed within the whole spacing box or even chart box? A similar option for data labels is [overflow](https://api.highcharts.com/highcharts/series.line.dataLabels.overflow).

2025-01-03 13:45 UTC, kamil-musialowski commented
Hmm, I see your point and it's valid. I'm open for discussion about it. 

Although right now, from the charting perspective it kind of makes sense that lastPrice label is placed on the yAxis, and I don't recall any issues outside standard support questions about it from the community 🤔 

@pawelfus Do you have any thoughts about it?

2025-01-20 13:06 UTC, TorsteinHonsi commented
@pawelfus I think it looks a bit messy with the overflowing axis labels and grid lines... Also plugins in simple demos is suboptimal.

2025-02-17 12:40 UTC, pawelfus commented
Extended plotlines are pretty much the same as maxPadding/overscroll option. Quite often used, but the request might seem different. The only difference is behavior upon viewing historical data: overscroll is ignored, while extended plotlines always reserve space, making the chart look disconnected. Which is good for columns & candles, but not so good for line series.

I think we should simply use `overscroll` option, how does it sound? After all, we have fixed it: https://github.com/highcharts/highcharts/pull/22389
![Zrzut ekranu 2025-02-17 o 13 39 06](https://github.com/user-attachments/assets/493d03ba-2721-4c45-b396-e879e26a07df)

2025-02-17 12:55 UTC, kamil-musialowski commented
Overscroll could be the best idea, however it doesn't work together with `xAxis.breaks` https://jsfiddle.net/BlackLabel/zs05rtpm/

2025-02-18 10:03 UTC, pawelfus commented
Not sure then.. Perhaps the best would be to resign from using price indication in this demo, unless fixed. @TorsteinHonsi do you think we should keep the demos as similar as possible?

2025-02-19 09:06 UTC, TorsteinHonsi commented
> do you think we should keep the demos as similar as possible?

@pawelfus You mean this and the ordinal demo? Not necessarily. If it doesn't work optimally then I think we should leave it out.

2025-02-19 10:32 UTC, pawelfus commented
Agreed, let's leave the breaks in axis demo as is (without the price label), and use overscoll in the other one, @kamil-musialowski

2025-02-20 13:09 UTC, pawelfus approved these changes
Thanks!

2025-02-20 13:11 UTC, pawelfus requested changes

2025-02-20 13:11 UTC, pawelfus commented on samples/stock/demo/intraday-area/demo.js
> +            overscroll: 60000 * 30
How about pixels? For narrow screens it still overlaps

2025-04-22 09:55 UTC, pawelfus approved these changes
Thanks!

2025-04-23 07:49 UTC, TorsteinHonsi approved these changes
Approving, but there are still some quirks with the overscroll. Not sure if it belongs here though, maybe it should be raised as a separate issue.

https://github.com/user-attachments/assets/fbdcb69a-1691-4437-b4e6-063bfb8f069b

2025-04-29 11:07 UTC, pawelfus commented
Nice catch!
Let's treat this as a separate issue and fix first, before publishing the demo.

2026-09-01 08:40 UTC, pawelfus requested changes
Tested with current branch - the issue with overscroll is fixed, however, the way it works (https://jsfiddle.net/24efmwbv/ - the overscroll and RangeSelector interpret extremes in a different way) is still not what I would expect. For now, let's close that PR.

2026-09-01 08:40 UTC, closed without merging