demo/plotline-annotation
highcharts/highcharts pull request #22377
Opened 2024-12-15 15:09 UTC by bm64

Added plot line annotations demo.

2024-12-18 13:08 UTC, kamil-musialowski approved these changes

2024-12-31 15:31 UTC, pawelfus requested changes
A few other changes are needed:

- from the code, it seems you use EUR currency, but it's not clear on the chart
- in fact, it seems to be USD in use (according to annotations)
- missing `new_uintil` info in details. Let's make it new until 2025.04.30

Question:
Did you consider using just one annotation, instead of three different ones? It would reduce amount of unnecessary code (duplicated properties)

2025-01-02 15:21 UTC, DJTechnoo requested changes
Looks good!  Let's also keep only two decimals in the tooltip

2025-04-04 15:00 UTC, pawelfus requested changes
Let's put on hold this PR, we already have one, a bit more advanced: https://github.com/highcharts/highcharts/pull/21729

2025-04-04 15:00 UTC, pawelfus commented on samples/highcharts/demo/plotline-annotation/demo.details
> +new_until: 2024-04-01
Needs to be updated, 2024 happened a year ago ;) Let's put 2025-08-01

2025-04-04 15:00 UTC, pawelfus commented on samples/highcharts/demo/plotline-annotation/demo.details
> +      priority: 1
add `is_morningstar: true`

2025-04-04 15:00 UTC, closed without merging