dash/data-layer-typed-arrays
highcharts/highcharts pull request #22376
Opened 2024-12-15 12:09 UTC by ddragula

Added support for column typed arrays and arrays in cells.

2024-12-20 07:53 UTC, karolkolodziej approved these changes
Good job!

2024-12-20 07:53 UTC, karolkolodziej commented on ts/Data/DataTableCore.ts
> +     * unlike the `setColumn` method.
This description is a bit vague. In order to get it you need to understand how the `setColumn` works.

2024-12-20 10:08 UTC, jomar-honsi commented on test/typescript-karma/Data/DataTable.test.js
Typo on line 643.

2024-12-20 11:26 UTC, jomar-honsi commented on ts/Core/Series/Series.ts
Type line 781: asscendingly

2024-12-20 11:43 UTC, jomar-honsi commented on ts/Data/DataTable.ts
Typos:
- 239: informations -> information
- 351: fiven -> given
- 782: Watchs -> Watches (consider changing the argument name also?)
- 841: Usefull -> Useful

2024-12-20 11:46 UTC, jomar-honsi commented on ts/Data/DataTableCore.ts
Typos:
- 88: indentification -> identification
- 321: undefind -> undefined

2024-12-20 11:50 UTC, jomar-honsi commented on ts/Data/Formula/FormulaProcessor.ts
Typo, line 128, 175: convertable -> convertible

2024-12-20 11:53 UTC, jomar-honsi approved these changes
Nice work!

There are however some typos that already existed already before this PR but you might just as well fix them.

2024-12-20 12:20 UTC, ddragula commented
> There are however some typos that already existed already before this PR but you might just as well fix them.

Thanks! Fixed some of them that were in the files I edited in this PR, but left the rest to be done in a separate PR so as not to put too much stuff here unrelated to introducing support for typed arrays in DataTable.

2024-12-20 13:19 UTC, sebastianbochan approved these changes

2025-01-03 09:42 UTC, TorsteinHonsi requested changes
Thanks, it looks good! Just a couple of comments. Also, I added a commit adding the `deleteRows` function in DataTableCore. It cleans up Series.ts, and we'll need it soon when we add two-way event binding between the data table and the series.

2025-01-03 09:42 UTC, TorsteinHonsi commented on ts/Data/DataTable.ts
> +            } else if (defined(cellValue) && Number.isFinite(cellValue)) {
This condition as far as I can see can be replaced with `if (isNumber(cellValue)) {`, where `isNumber` is from Utilities.ts. When I do that, there is also no need for typecasting the `cellValue` with +.

2025-01-03 09:42 UTC, TorsteinHonsi commented on ts/Data/DataTableCore.ts
> +    public replaceColumnRef(
Can we just call it `replaceColumn`? Because that's what it does...

2025-01-06 11:45 UTC, ddragula commented on ts/Data/DataTableCore.ts
> +    public replaceColumnRef(
I'll delete it since it's not needed anymore - all column array reference overrides are inside the `DataTableCore` class, so in this case encapsulation no longer forces the use of this method anywhere.

2025-01-06 12:09 UTC, ddragula commented on ts/Data/DataTable.ts
>              }
The code should theoretically work with this simplification:

```ts
if (Array.isArray(column) || isNumber(cellValue)) {
    rowIndex = column.indexOf(cellValue, rowIndexOffset);
}
```

but unfortunately, TypeScript doesn’t allow `cellValue` in this case:

![image](https://github.com/user-attachments/assets/87985590-9e4d-4ef9-8a08-f351a295853f)

2025-01-28 11:18 UTC, TorsteinHonsi requested changes

2025-01-28 11:18 UTC, TorsteinHonsi commented on ts/Data/DataTableCore.ts
> +import ColumnUtils from './ColumnUtils.js';
I think we should use local constants for these properties. We don't use the `setLength` function in this module, so when we rewrite to named imports we should be able to tree-shake off some bytes.
```suggestion
import ColumnUtils from './ColumnUtils.js';
const { shift, splice } = ColumnUtils;
```

2025-01-30 09:31 UTC, TorsteinHonsi approved these changes

2025-01-31 12:12 UTC, bre1470 commented on ts/Data/ColumnUtils.ts
> +    }
This is just a special splice and nowhere in use. I suggest to remove it.

2025-01-31 12:15 UTC, bre1470 commented on ts/Data/DataTableCore.ts
> + * @typedef {Array<boolean|null|number|string|undefined>|TypedArray} Highcharts.DataTableColumn
Why does this not contain the Array like our internal typing?

2025-01-31 12:22 UTC, bre1470 commented on ts/Data/DataTableOptions.ts
> +export type DataTableValue = DataTablePrimitiveValue|DataTablePrimitiveValue[];
Same question here. We have
```ts
CellType = BasicCellType|Array<BasicCellType>
```
in DataTable, but it does not get exposed further. I suggest to remove array as a cell type until we have a practical use case for it. It is not good for performance and produces management overhead. It is also a significant breaking change, independently whether we be consistent with typing or not. Every conditional check of types where last possible type is in the `else` section will not work anymore, when we introduce array.

2025-01-31 12:49 UTC, bre1470 commented on ts/Data/ColumnUtils.ts
> +    }
```ts
    export type TypedArrayConstructor = (
        Int8ArrayConstructor|Uint8ArrayConstructor|Uint8ClampedArrayConstructor|Int16ArrayConstructor|Uint16ArrayConstructor|
        Int32ArrayConstructor|Uint32ArrayConstructor|Float32ArrayConstructor|Float64ArrayConstructor
    );
```

2025-02-03 13:09 UTC, ddragula commented on ts/Data/DataTable.ts
> +                        }
I think I missed this during development process, we should be able to support it with Utils I wrote. Will fix it, thanks for the vigilance!

2025-02-03 13:21 UTC, ddragula commented on ts/Data/DataTable.ts
> +    export type CellType = BasicCellType|Array<BasicCellType>;
This is a very important change for us because we want to support sparklines in the Grid on these arrays. But in the case of Highcharts Core, I don't see any use for it.

2025-02-03 14:07 UTC, ddragula commented on ts/Data/DataTableCore.ts
> + * @typedef {Array<boolean|null|number|string|undefined>|TypedArray} Highcharts.DataTableColumn
Because this doclet is about `DataTableCore` which is only used in Highcharts Core where Array as a cell type has no use case. Do you have any suggestions on how this could be handled better way? Extension of `column` field's type only in the `DataTable` class?

2025-02-03 14:11 UTC, ddragula commented on ts/Data/DataTableOptions.ts
> +export type DataTableValue = DataTablePrimitiveValue|DataTablePrimitiveValue[];
The only practical use for now is sparklines in Grid, but it's quite important. Do you have any suggestions for another way we can define data in cells for them?

2025-02-06 11:28 UTC, ddragula commented on ts/Data/DataTableOptions.ts
> +export type DataTableValue = DataTablePrimitiveValue|DataTablePrimitiveValue[];
If this is a definite no-go, we can alternatively store the data as JSON string in cells and validate & parse it at the DataGrid level, on sparkline render.

2025-02-06 12:14 UTC, bre1470 commented on ts/Data/DataTableOptions.ts
> +export type DataTableValue = DataTablePrimitiveValue|DataTablePrimitiveValue[];
Yes, in the beginning we said that we go with JSON string, because otherwise you will always have to add new types for new cell content, if some structure has to be supported or extended.

2025-02-10 14:15 UTC, bre1470 requested changes
Thank you! Some clean-up is needed.

2025-02-10 14:15 UTC, bre1470 commented on ts/Data/DataTable.ts
> +                } else {
This needs an extra check for performance reasons as a basic column is faster sliced.

Ref: https://www.measurethat.net/Benchmarks/Show/30839/0/slice-vs-array-from#latest_results_block

2025-02-10 14:15 UTC, bre1470 commented on ts/Dashboards/Components/NavigatorComponent/NavigatorSyncs/NavigatorExtremesSync.ts
> +                    defined(min) && !Array.isArray(min)
This can also simplified, as an array is not possible anymore.

2025-02-10 15:29 UTC, ddragula commented on ts/Data/DataTable.ts
> +                } else {
From what I can see, for a typed array `Array.from(typed)` works a bit faster than `[].slice.call(typed)`: [benchmark](https://www.measurethat.net/Benchmarks/Show/33528/0/array-from-vs-slice). I added a condition to the if to execute it only if it's a typed array, otherwise, do `slice`.

2025-02-11 08:17 UTC, bre1470 commented on ts/Data/DataTable.ts
> +                } else {
In Safari and Firefox basic slice is twice and more faster, while Chrome has a slight advantage for Array.from. This needs improvements.

2025-02-11 09:14 UTC, bre1470 approved these changes
Thank you! Looks good. 👍

2025-02-11 09:14 UTC, bre1470 commented on ts/Data/DataTable.ts
> +                }
I looked at the wrong commit. This looks better. Thanks!

2025-02-14 09:13 UTC, merged