demo/areaspline-last-price-indicator
highcharts/highcharts pull request #22408
Opened 2024-12-18 21:56 UTC by bm64

Add last price indicator to areaspline demo.

2024-12-19 14:18 UTC, kamil-musialowski approved these changes

2024-12-31 09:37 UTC, pawellysy approved these changes

2025-01-02 12:17 UTC, pawelfus approved these changes
Thanks!

2025-01-03 09:05 UTC, DJTechnoo approved these changes

2025-01-03 11:13 UTC, TorsteinHonsi requested changes

2025-03-14 12:24 UTC, bm64 commented on samples/stock/demo/areaspline/demo.js
> +            overscroll: '8px'
@TorsteinHonsi I've adjusted the overscroll value to look good on a 3M range, but it behaves the same way as before when the range changes. I believe this is how the last price indicator currently works, and I’m not sure if we can change it. Could you share your thoughts? Is there anything else we could improve?

2025-03-19 06:54 UTC, TorsteinHonsi commented on samples/stock/demo/areaspline/demo.js
> +            overscroll: '8px'
Okay, thanks! It's better now, and works when we start out with different ranges.

2025-03-19 06:55 UTC, TorsteinHonsi approved these changes

2025-03-19 06:55 UTC, merged