docs/missing-lastprice-options
highcharts/highcharts pull request #22418
Opened 2024-12-19 14:45 UTC by kamil-musialowski

Added width and dashStyle options to lastprice docs.

2024-12-26 00:28 UTC, bm64 approved these changes

2024-12-30 13:25 UTC, pawelfus requested changes
Could you also add this info to `lastVisiblePrice`? It works too: https://jsfiddle.net/1wgce645/ (requires setting color first though, which also is missing)

2024-12-31 09:38 UTC, pawellysy approved these changes

2025-01-09 14:53 UTC, pawelfus approved these changes
Thanks!

2025-01-10 13:41 UTC, DJTechnoo approved these changes

2025-01-10 14:33 UTC, TorsteinHonsi approved these changes
Thanks!

2025-01-10 14:34 UTC, merged