bugfix/21217-navigator-disabled-in-setOptions
highcharts/highcharts pull request #22429
Opened 2024-12-23 13:00 UTC by kamil-musialowski

Fixed #21217, navigator was still rendered after disabling it in `setOptions`.

2024-12-31 09:38 UTC, pawellysy approved these changes

2025-01-02 11:59 UTC, pawelfus approved these changes
Thanks!

2025-01-02 18:24 UTC, bm64 approved these changes

2025-01-03 11:43 UTC, DJTechnoo approved these changes

2025-02-21 12:33 UTC, pawelfus requested changes

2025-02-21 12:33 UTC, pawelfus commented on samples/unit-tests/navigator/navigator/demo.js
> +});
It seems tests are failing because of that (default is undefined, not `true`. `true` is only for Stock`).

2025-05-05 12:38 UTC, kamil-musialowski commented
@pawelfus @TorsteinHonsi The solution is finally fixed, tests are improved and everything seems to be working both locally, in Utils and in Karma. Two tests are failing, but that is unrelated to the PR (they are failing in other PRs as well).

2025-05-05 13:08 UTC, pawelfus approved these changes
This looks good, thanks!

2025-05-06 06:09 UTC, TorsteinHonsi approved these changes

2025-05-06 06:09 UTC, merged