bugfix/21879-measure-annotation-control-point
highcharts/highcharts pull request #22435
Opened 2024-12-25 10:55 UTC by kamil-musialowski

Fixed #21879, control point option was not working for measure annotation.

2024-12-26 00:24 UTC, bm64 approved these changes

2024-12-30 13:29 UTC, pawelfus requested changes
Looks good, just one (or two) minor thing

2024-12-30 13:29 UTC, pawelfus commented on ts/Extensions/Annotations/Types/Measure.ts
> +                    point.y &&
what if `point.y === 0`?

2024-12-30 13:29 UTC, pawelfus commented on ts/Extensions/Annotations/Types/Measure.ts
> +                    point.y &&
What if `point.y === 0`?

2024-12-30 13:29 UTC, pawelfus commented on ts/Extensions/Annotations/Types/Measure.ts
> +                    point.y &&
What if.. 
Is this something we could refactor? Instead of using the same code three times?

2025-01-02 12:11 UTC, pawelfus requested changes
One last thing :)

2025-01-02 12:11 UTC, pawelfus commented on ts/Extensions/Annotations/Types/Measure.ts
> +                    isNumber(point.y) &&
already checked in `isPointWithinExtremes`

2025-01-02 12:11 UTC, pawelfus commented on ts/Extensions/Annotations/Types/Measure.ts
> +                    isNumber(point.y) &&
already checked in `isPointWithinExtremes`

2025-01-03 12:46 UTC, DJTechnoo approved these changes
Amazing job!

2025-01-03 13:59 UTC, kamil-musialowski commented on ts/Extensions/Annotations/Types/Measure.ts
> +                    isNumber(point.y) &&
Yeah, I've tried that but then it complains that `point.y > max` could be null or undefined
![image](https://github.com/user-attachments/assets/5de2c039-0e34-42a7-ad81-021e128f9d3e)

2025-01-03 15:07 UTC, pawelfus commented on ts/Extensions/Annotations/Types/Measure.ts
> +                    isNumber(point.y) &&
Oh, I see. Thanks for checking!

2025-01-03 15:08 UTC, pawelfus approved these changes
Thanks!

2025-02-24 13:54 UTC, TorsteinHonsi approved these changes
Thanks!

2025-02-24 13:54 UTC, merged